### PR TITLE
feat: change pachage name: autoware_msgs -> tier4_msgs

### PR DESCRIPTION
**Pull request by tkimura4**
## Related Issue(required)
https://github.com/autowarefoundation/autoware.universe/issues/1
https://github.com/autowarefoundation/autoware.universe/issues/2

## Description(required)

rename autoware_*_msg to tier4_*_msg

## Review Procedure(required)
- build check
- check that autoware_*_msg are no longer used.

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by tkimura4** [comment]
cc. @isamu-takagi

**Comment by isamu-takagi** [comment]
@tkimura4 
Are there any plans to change the package name of external_api_msgs?

**Comment by tkimura4** [comment]
@isamu-takagi 
I forgot it!

**Review by 1222-takeshi — APPROVED** [review]
LGTM

**Comment by 1222-takeshi** [comment]
@taikitanaka3 
Could check test error of behavior_velocity_planner ?

**Comment by tkimura4** [comment]
> --- stderr: behavior_velocity_planner
1: [ RUN      ] state_machine.set_state_stop
Errors while running CTest
1: [       OK ] state_machine.set_state_stop (0 ms)
---
1: [ RUN      ] state_machine.set_state_stop_with_margin_time
1: [       OK ] state_machine.set_state_stop_with_margin_time (0 ms)
1: [ RUN      ] state_machine.set_state_go_with_margin_time
1: /__w/autoware.universe/autoware.universe/planning/behavior_velocity_planner/test/src/test_state_machine.cpp:73: Failure
1: Value of: state_machine.getDuration() < margin_time
1:   Actual: false
1: Expected: true
1: [  FAILED  ] state_machine.set_state_go_with_margin_time (201 ms)

**Comment by tkimura4** [comment]
The test error may be fixed by https://github.com/autowarefoundation/autoware.universe/pull/156

**Comment by taikitanaka3** [comment]
@tkimura4 
I might miss equal case for unit test
```
    // be sure that duration is less equal to margin_time
    EXPECT_FALSE(state_machine.getDuration() > margin_time);
```

**Pull request merged**
