### PR TITLE
refactor: traffic light arbiter/autoware prefix

### PR DESCRIPTION
**Pull request by manato**
## Description
This PR introduces `autoware` namespace into the `traffic_light_arbiter` package

## Related links

**Parent Issue:**

- Part of: https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by knzo25** [comment]
Thank you for addressing this package :bow: 

Some parts that may still need to be updates:
https://github.com/manato/autoware.universe/blob/298d3573878fe350c76998bbe58bbb456530b5a3/perception/autoware_traffic_light_arbiter/README.md?plain=1#L1

https://github.com/manato/autoware.universe/blob/298d3573878fe350c76998bbe58bbb456530b5a3/perception/autoware_traffic_light_arbiter/package.xml#L6

**Comment by knzo25** [comment]
@manato 
Other than that checked the runtime and it looks Ok

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by technolojin — APPROVED** [review]
LGTM

It worked in my local environment.
Screenshot from 2024-07-26 17-54-50

**Review by miursh — APPROVED** [review]

**Pull request merged**
