### PR TITLE
fix(autoware_image_projection_based_fusion): fix unreadVariable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unreadVariable warnings.

```
perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp:352:14: style: Variable 'data' is assigned a value that is never used. [unreadVariable]
        data = &painted_pointcloud_msg.data[0];
             ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
Currently the warning is suppressed with a comment, but if the variable is not going to be used in the future, it can be removed.

**Review by kminoda — APPROVED** [review]

**Comment by kobayu858** [comment]
@kminoda 

Thanks for the approval.

I would like to ask one question about this code.
Is the intention of reassigning in [this line](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp#L352) to ensure that the variables used in the OpenMP parallel loop are correctly initialized for each thread?

**Review by yukkysaito — APPROVED** [review]

**Comment by kminoda** [comment]
@kobayu858 Sorry for the late response. Although being one of the maintainers, I am not the one who implemented this code, and not sure the real intention of the line you've pointed out.

@tzhong518 Hi, can you answer the above comment?

**Comment by kobayu858** [comment]
@tzhong518 

I await your reply to my comments.
Best regards.

**Comment by kminoda** [comment]
@kobayu858 Thank you for your patience. I am internally contacting @tzhong518 for the answer.

**Comment by tzhong518** [comment]
Sorry for the late reply. I'm afraid it's just a miss.

**Comment by Shin-kyoto** [comment]
> Sorry for the late reply. I'm afraid it's just a miss.

@tzhong518 

Oh, is it just a miss?
It means that we can remove this line?

https://github.com/autowarefoundation/autoware.universe/blob/1a1ab21693c9ecf9967ce7f82d1cdb188faf6360/perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp#L353

**Comment by kminoda** [comment]
@tzhong518 Friendly ping

**Comment by tzhong518** [comment]
> It means that we can remove this line?
Yes, I confirmed that it could be removed. 
should I make a PR for this?

**Comment by Shin-kyoto** [comment]
> > It means that we can remove this line?
> 
> Yes, I confirmed that it could be removed. should I make a PR for this?

Thank you for your comment!!

@veqcc 
How about proceeding as follows?

- Close this PR
- @tzhong518 will make the PR to remove this line.

**Comment by Shin-kyoto** [comment]
> > It means that we can remove this line?
> 
> Yes, I confirmed that it could be removed. should I make a PR for this?

Thanks!

@tzhong518
Yes, can you make a PR for this?

**Comment by veqcc** [comment]
@Shin-kyoto 
Thank you for leading the conversations!

@tzhong518 
If you have finished removing the cppcheck warning through the new PR, please let me know!

@kobayu858 
Could you close this PR?

**Comment by YoshiRi** [comment]
This issue will fixed in https://github.com/autowarefoundation/autoware.universe/pull/8634.

**Pull request closed without merging**
