### PR TITLE
fix(obstacle_stop_planner): fix debug topic name

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Related Issue(required)

The plotJuggler config can not be loaded correctly.

## Description(required)

Fix topic names used there.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by tkimura4** [comment]
Could you also rename `/control/trajectory_follower/velocity_controller/debug_values/data.N` to `/planning/scenario_planning/lane_driving/motion_planning/adaptive_cruise_controller/debug/debug_values/data.N`

**Comment by TakaHoribe** [comment]
>Could you also rename ...

Roger. And I've added its module name on the topic namespace.
image

image

**Review by tkimura4 — DISMISSED** [review]
LGTM
image

**Comment by tkimura4** [comment]
@TakaHoribe 
Could you fix clang-format?

**Comment by kenji-miyake** [comment]
pre-commit.ci run

**Comment by TakaHoribe** [comment]
SORRY

**Review by tkimura4 — APPROVED** [review]

**Pull request merged**
