### PR TITLE
feat(autodrive_autoware): autodrive-autoware integration

### PR DESCRIPTION
**Pull request by Tinker-Twins**
## Description

The core deliverable of this project was integrating [Autoware stack](https://autoware.org) with [AutoDRIVE Ecosystem](https://autodrive-ecosystem.github.io) to demonstrate the end-to-end task of mapping an unknown environment, recording a trajectory within the mapped environment, and autonomously tracking the pre-recorded trajectory to achieve the desired objective. Particularly, we demonstrate sim2real Autoware deployments using [Nigel](https://youtu.be/UVIShZuZmpg?si=eoiXwAD77mauHJdf) and [F1TENTH](https://f1tenth.org), two small-scale autonomous vehicle platforms with unique qualities and capabilities. Additionally we demonstrate simulated Autoware deployments using mid-scale [Hunter SE](https://global.agilex.ai/chassis/9) and full-scale [OpenCAV](https://sites.google.com/view/opencav) within simplified as well as realistic scenarios. It is worth mentioning that this work encapsulates the [first-ever off-road deployment of the Autoware stack](https://youtu.be/j5w_mH0ygUY?si=Adp2Do6CWUhot0po) using the mid-scale vehicle platform, thereby expanding the operational design domain (ODD) of Autoware beyond on-road autonomous navigation.

## Related links

- **Installation Documentation:** Autoware stack installation using different options depending upon the required system hardware/software configuration.
  - [Local Installation Documentation](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/install_local.md)
  - [Docker Installation Documentation](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/install_docker.md)
  - [Jetson Installation Documentation](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/install_jetson.md)
- **Deployment Documentation:** Autoware stack deployment on different vehicles of [AutoDRIVE Ecosystem](https://autodrive-ecosystem.github.io/) across scales and [ODDs](https://en.wikipedia.org/wiki/Operational_design_domain).
  - [Nigel (Small-Scale Vehicle - On-Road Navigation)](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/vehicles/nigel/readme.md)
  - [F1TENTH (Small-Scale Vehicle - Autonomous Racing)](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/vehicles/f1tenth/readme.md)
  - [Hunter SE (Mid-Scale Vehicle - On-Road & Off-Road Navigation)](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/vehicles/hunter/readme.md)
  - [OpenCAV (Full-Scale Vehicle - On-Road Navigation)](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/blob/main/autodrive_autoware/vehicles/opencav/readme.md)
- **Deployment Videos:** Deployment videos pertaining to [AutoDRIVE-Autoware Integration](https://github.com/Tinker-Twins/AutoDRIVE-Autoware) are available within the [Autoware Playlist](https://youtube.com/playlist?list=PL5Hd4DIMOmEJgpsPYCoLBGNb_91PZVxgA&si=UCN1iTwrKbx51Jry) on [AutoDRIVE Ecosystem's YouTube Channel](https://www.youtube.com/@AutoDRIVE-Ecosystem).

## Tests performed

We have tested sim2real Autoware deployments using [Nigel](https://youtu.be/i0-Nca-EkNQ?si=WgC2ULp9nPsOsFmT) and [F1TENTH](https://youtu.be/I-tEjVMtans?si=LcIetfsfDmK-8t8h), two small-scale autonomous vehicle platforms with unique qualities and capabilities. Additionally we have also extensively validated simulated Autoware deployments using mid-scale [Hunter SE](https://youtu.be/j5w_mH0ygUY?si=7Ggl60xR98ng8S4N) and full-scale [OpenCAV](https://youtu.be/v6CHTDdzbbw?si=aaZvmX8QXb3UClpO) within simplified as well as realistic scenarios.

Deployment videos pertaining to [AutoDRIVE-Autoware Integration](https://github.com/Tinker-Twins/AutoDRIVE-Autoware) are available within the [Autoware Playlist](https://youtube.com/playlist?list=PL5Hd4DIMOmEJgpsPYCoLBGNb_91PZVxgA&si=UCN1iTwrKbx51Jry) on [AutoDRIVE Ecosystem's YouTube Channel](https://www.youtube.com/@AutoDRIVE-Ecosystem).

## Notes for reviewers

Not applicable.

## Interface changes

The existing interfaces remain unchanged. New interfaces pertaining to [AutoDRIVE-Autoware integration](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware) have been added.

## Effects on system behavior

The existing system behavior remains unaffected. New demonstrations pertaining to [AutoDRIVE-Autoware integration](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware) have been added.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
Thank you.

Regarding this PR, it has a very large amount of changes, making it impossible for us to review. Would it be possible for you to divide the PR into component-level changes such as Sensing/Localization/Perception/Planning/Control? We place great importance on the [MicroAutonomy](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-concepts) architecture, and [the interfaces for each component](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/planning/) are defined in Autoware. Please also check if it conforms to these interfaces.

If it's difficult to comply with this request, please let us know. In the autoware universe, we would like to allow the free incorporation of research-level projects.

**Comment by yukkysaito** [comment]
Also, CI has not passed and conflicts are occurring. I will change it to Draft and you can change it to Ready when you are ready to review.

**Comment by Tinker-Twins** [comment]
Dear @yukkysaito,

Thank you for your feedback and for reviewing the pull request.

We understand your concerns regarding the size of the changes and the importance of maintaining clarity by dividing the PR into component-level changes. However, it would be difficult for us to divide the PR since it involves a large number of changes. In case it helps, following is a summary of the PR along with the most prominent updates:

**PR Summary:** The core crux of this PR was to integrate [Autoware](https://autoware.org) with [AutoDRIVE Ecosystem](https://autodrive-ecosystem.github.io). AutoDRIVE is an integrated digital twin ecosystem for modeling and simulating (real2sim) as well as deploying and validating (sim2real) autonomous vehicles across different scales, configurations, and operational design domains (ODDs). This PR contributes Autoware API for the AutoDRIVE Ecosystem along with detailed documentation and canned demos for deploying Autoware stack on small-scale ([Nigel](https://youtu.be/UVIShZuZmpg?si=eoiXwAD77mauHJdf), [F1TENTH](https://f1tenth.org)), mid-scale ([Hunter SE](https://global.agilex.ai/chassis/9)) as well as full-scale ([OpenCAV](https://sites.google.com/view/opencav)) autonomous vehicles in simulation as well as real-world settings.

**PR Updates:** This PR does not change any of the existing functions of the Autoware stack. It contributes [`autodrive_autoware`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware) including the following:
- [`perception`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/perception) packages [`lidar_slam`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/perception/lidar_slam), [`lio_sam_slam`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/perception/lio_sam_slam) and [`pf_localization`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/perception/pf_localization).
- [`planning`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/planning) package to store recorded [`paths`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/planning/paths) of different vehicles, which can be later modified to have additional functionality.
- [`control`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/control) package to perform path tracking using feedback-control by generating and publishing compatible vehicle control commands.
- [`vehicles`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/vehicles) packages to define and handle interfaces to the different vehicles of AutoDRIVE Ecosystem viz. [Nigel](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/vehicles/nigel), [F1TENTH](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/vehicles/f1tenth), [Hunter SE](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/vehicles/hunter) and [OpenCAV](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware/vehicles/opencav).

Regarding the CI failing, we have resolved most of these conflicts and have now marked this PR as `Ready`. We kindly request you to review it at your convenience.

Thank you and have a nice day!

Best regards,
Chinmay and Tanmay
(a.k.a. Tinker Twins)

**Comment by idorobotics** [comment]
@Tinker-Twins thank you very much for this draft PR. We'd love to learn more about your project. Are you available on Tuesday next week to join the Software WG Meeting to present your work? Check the [meeting calendar](https://calendar.google.com/calendar/u/0/embed?src=autoware.org_6lol0ho5ft0217h8c60pi1fm30@group.calendar.google.com) for the times (import the calendar to see your local time).

**Comment by Tinker-Twins** [comment]
@idorobotics Thank you for inviting us to the upcoming Software WG Meeting. We would love to present the AutoDRIVE-Autoware integration to the Autoware community! See you on Tuesday!

**Comment by mitsudome-r** [comment]
@Tinker-Twins As discussed in the Software WG, could you create a discussion thread with some diagrams explaining the changes that you would like to make (addition of packages, change in interface, etc.) just like [this example](https://github.com/orgs/autowarefoundation/discussions/3484) ?

**Comment by xmfcx** [comment]
@Tinker-Twins @mitsudome-r I've moved the `autodrive_ecosystem` 
from where it was (it was in somewhere along the main branch)
to the [f1tenth_galactic](https://github.com/autowarefoundation/autoware.universe/tree/f1tenth_galactic) branch.

Just this change reduced the files changed tab here from 4k~ to 1k~.

@Tinker-Twins could you check your updates again and revise this PR?

Also I highly recommend you to use https://www.gitkraken.com/ to visually see what is going on and how branches are playing along with each other.
It is free to use for public repositories like ours.

It makes actions like rebasing and switching between branches so easy and visual.

**Comment by Tinker-Twins** [comment]
@xmfcx and @mitsudome-r Many thanks for rebasing the [`autodrive_ecosystem`](https://github.com/autowarefoundation/autoware.universe/tree/autodrive_ecosystem) branch. We have updated the PR by moving all our changes to the [`autodrive_autoware`](https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main/autodrive_autoware) directory. This way, the other `autoware.universe` components are still how they were earlier.

I kindly request you review and merge this PR to the `autodrive_ecosystem` branch. In the meantime, we will continue to work on testing our changes with the [`main`](https://github.com/autowarefoundation/autoware.universe/tree/main) branch of `autoware.universe` using ROS 2 Humble. In the near future, we plan to create a discussion with exhaustive documentation of our changes (with some diagrams explaining the input-output architectures) as well as a separate PR with our code ported to and tested with ROS 2 Humble.

**Comment by xmfcx** [comment]
It would be better to keep having https://github.com/Tinker-Twins/AutoDRIVE-Autoware/tree/main as a fork rather than a branch because it is not integrated well.

Please branch out from the latest main and re-integrate it with the AutoDRIVE systems with the latest Autoware, using `humble` and Ubuntu 22.04.

**Pull request closed without merging**
