### PR TITLE
feat(behavior_path_planner): output stop reasons

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

- Output stop reason from `behavior_path_planner` modules.
- This PR should be merged after https://github.com/tier4/tier4_autoware_msgs/pull/89

Screenshot from 2023-05-24 10-53-29

[TIER IV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT1-2465)

## Tests performed

- [x] [PASS TIER IV INTERNAL SCENARIOS (NEW MANAGER)](https://evaluation.tier4.jp/evaluation/reports/d3a5abe2-1149-557e-9879-6135d69892a8?project_id=prd_jt)
- [x] [PASS TIER IV INTERNAL SCENARIOS (OLD MANAGER)](https://evaluation.tier4.jp/evaluation/reports/42758e1c-3d12-58e8-bce1-869c6d3cc152?project_id=prd_jt)

## Effects on system behavior

Show stop reason & distance (only `avoidance`)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
TODO: remove https://github.com/autowarefoundation/autoware.universe/pull/3807/commits/e452e8c2b7bc9ef95544d3f6317690769ec8efb1

**Review by shmpwk — APPROVED** [review]
LGTM!

**Comment by satoshi-ota** [comment]
> TODO: remove [e452e8c](https://github.com/autowarefoundation/autoware.universe/commit/e452e8c2b7bc9ef95544d3f6317690769ec8efb1)

DONE

**Comment by shmpwk** [comment]
Approved but required CI failed?

**Comment by satoshi-ota** [comment]
@shmpwk Could you check not only this PR but also https://github.com/tier4/tier4_autoware_msgs/pull/89 ?

**Comment by satoshi-ota** [comment]
> Approved but required CI fails?

Yes. I added some reasons in `tier4_planning_msgs` and this PR uses it.

**Pull request merged**
