### PR TITLE
fix(lidar_centerpoint): fix class

### PR DESCRIPTION
**Pull request by Shin-kyoto**
## Description

- Setting [`centerpoint_model_name` in `perception.launch.xml`](https://github.com/autowarefoundation/autoware.universe/blob/e9f2f4fb4bd1b1dc105d5fd3964565028d426c1b/launch/tier4_perception_launch/launch/perception.launch.xml#L14) to `centerpoint`, the following error occurs. 

```bash
[lidar_centerpoint_node-41] [I] [TRT] [MemUsageSnapshot] End constructing builder kernel library: CPU 1114 MiB, GPU 3407 MiB
[lidar_centerpoint_node-41] [INFO 1686388968.441690278] [lidar_centerpoint]: Using TensorRT FP16 Inference
[lidar_centerpoint_node-41] [I] [TRT] ----------------------------------------------------------------
[lidar_centerpoint_node-41] [I] [TRT] Input filename:   /home/shintarotomie/work/2023/0610-centerpoint-check/autoware/install/lidar_centerpoint/share/lidar_centerpoint/data/pts_backbone_neck_head_centerpoint.onnx
[lidar_centerpoint_node-41] [I] [TRT] ONNX IR version:  0.0.6
[lidar_centerpoint_node-41] [I] [TRT] Opset version:    11
[lidar_centerpoint_node-41] [I] [TRT] Producer name:    pytorch
[lidar_centerpoint_node-41] [I] [TRT] Producer version: 1.9
[lidar_centerpoint_node-41] [I] [TRT] Domain:           
[lidar_centerpoint_node-41] [I] [TRT] Model version:    0
[lidar_centerpoint_node-41] [I] [TRT] Doc string:       
[lidar_centerpoint_node-41] [I] [TRT] ----------------------------------------------------------------
[lidar_centerpoint_node-41] [ERROR 1686388968.464914941] [lidar_centerpoint]: Expected and actual number of classes do not match
[lidar_centerpoint_node-41] [ERROR 1686388968.464930734] [lidar_centerpoint]: Failed to set profile
[lidar_centerpoint_node-41] [ERROR 1686388968.475244790] [lidar_centerpoint]: Failed to create context: Engine was not created
```

- This is caused by `centerpoint.param.yaml`. So I fixed it. After PR, .engine file is generated correctly

- after PR
```bash
[lidar_centerpoint_node-41] [I] [TRT] [MemUsageSnapshot] End constructing builder kernel library: CPU 1111 MiB, GPU 3235 MiB
[lidar_centerpoint_node-41] [INFO 1686389563.949640600] [lidar_centerpoint]: Using TensorRT FP16 Inference
[lidar_centerpoint_node-41] [I] [TRT] ----------------------------------------------------------------
[lidar_centerpoint_node-41] [I] [TRT] Input filename:   /home/shintarotomie/work/2023/0610-centerpoint-check/autoware/install/lidar_centerpoint/share/lidar_centerpoint/data/pts_backbone_neck_head_centerpoint.onnx
[lidar_centerpoint_node-41] [I] [TRT] ONNX IR version:  0.0.6
[lidar_centerpoint_node-41] [I] [TRT] Opset version:    11
[lidar_centerpoint_node-41] [I] [TRT] Producer name:    pytorch
[lidar_centerpoint_node-41] [I] [TRT] Producer version: 1.9
[lidar_centerpoint_node-41] [I] [TRT] Domain:           
[lidar_centerpoint_node-41] [I] [TRT] Model version:    0
[lidar_centerpoint_node-41] [I] [TRT] Doc string:       
[lidar_centerpoint_node-41] [I] [TRT] ----------------------------------------------------------------
[lidar_centerpoint_node-41] [INFO 1686389563.995972870] [lidar_centerpoint]: Applying optimizations and building TRT CUDA engine (/home/shintarotomie/work/2023/0610-centerpoint-check/autoware/install/lidar_centerpoint/share/lidar_centerpoint/data/pts_backbone_neck_head_centerpoint.onnx) ...
[lidar_centerpoint_node-41] [INFO 1686389588.065159729] [lidar_centerpoint]: Writing to /home/shintarotomie/work/2023/0610-centerpoint-check/autoware/install/lidar_centerpoint/share/lidar_centerpoint/data/pts_backbone_neck_head_centerpoint.engine

```

## Tests performed

I tested on logging_simulator.

## Effects on system behavior

.engine file of centerpoint will be generated correctly.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@Shin-kyoto 
Actually for those models the ranges also changed. Could you update those?
(like in https://github.com/autowarefoundation/autoware.universe/blob/main/perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml)

**Review by knzo25 — CHANGES_REQUESTED** [review]
↑

**Comment by Shin-kyoto** [comment]
> @Shin-kyoto Actually for those models the ranges also changed. Could you update those? (like in https://github.com/autowarefoundation/autoware.universe/blob/main/perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml) Evidence: [TIER IV INTERNAL LINK](https://drive.google.com/drive/u/0/folders/19lB5X7WkEgIvbbEe-CfpVvqiZHhm1OSU)

Added it in https://github.com/autowarefoundation/autoware.universe/pull/3934/commits/37cf9a07122f7b5413c4b918d59bc28788e7c674

**Comment by knzo25** [comment]
Sorry, but can you fix it so that the ranges/voxel size matches? (both centerpoint and tiny)
If not possible I'll make a PR later

```
point_cloud_range = [-76.8, -76.8, -4, 76.8, 76.8, 6]
voxel_size = [0.32, 0.32, 10]
```

**Comment by Shin-kyoto** [comment]
> Sorry, but can you fix it so that the ranges/voxel size matches? (both centerpoint and tiny) If not possible I'll make a PR later
> 
> ```
> point_cloud_range = [-76.8, -76.8, -4, 76.8, 76.8, 6]
> voxel_size = [0.32, 0.32, 10]
> ```

Thanks!
I fixed them in https://github.com/autowarefoundation/autoware.universe/pull/3934/commits/47e7f8a7a2143b9ea810b9211ab8e0688558d1df and checked if autoware launches correctly.

**Review by knzo25 — APPROVED** [review]
Thanks !
LGTM

**Pull request merged**
