### PR TITLE
feat(behavior_path_planner): add debug marker to side shift module

### PR DESCRIPTION
**Pull request by zulfaqar-azmi-t4**
Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>

## Description

This PR adds debug marker to visualize shift points in side shift module.
Screenshot from 2022-06-13 12-38-54

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by zulfaqar-azmi-t4** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/1101 is required now.

**Comment by mitsudome-r** [comment]
@zulfaqar-azmi-t4 
Could you share the status of this PR?
It seems this was left as draft for quite a long time. Please consider closing the PR if you don't plan to merge this anymore.

**Comment by zulfaqar-azmi-t4** [comment]
@mitsudome-r 
My apologies. Yes, the marker is still being used.
I will rebase this PR and inform the related person in charge for review.

**Comment by zulfaqar-azmi-t4** [comment]
@kyoichi-sugahara 
I look forward for your review!
Launcher is needed https://github.com/autowarefoundation/autoware_launch/pull/298

**Comment by kyoichi-sugahara** [comment]
process has died by publishing topic with
`ros2 topic pub -1 /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/input/lateral_offset tier4_planning_msgs/msg/LateralOffset "lateral_offset: 1.0"`
I will investigate the issue.

**Comment by kyoichi-sugahara** [comment]
looks good!
image

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM
sorry for late review

**Pull request merged**
