### PR TITLE
fix(tensorrt classifier wrapper): fix unreadVariable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unreadVariable warnings.

```
perception/autoware_tensorrt_classifier/src/tensorrt_classifier.cpp:126:27: style: Variable 'calibName' is assigned a value that is never used. [unreadVariable]
    std::string calibName = "";
                          ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
Currently the warning is suppressed with a comment, but if the variable is not going to be used in the future, it can be removed.

**Comment by kobayu858** [comment]
This variable was removed because it was clearly not being used.

**Review by ktro2828 — APPROVED** [review]
Thank you for PR! LGTM.

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
