### PR TITLE
refactor(polar_grid): add autoware prefix to polar_grid

### PR DESCRIPTION
**Pull request by esteve**
## Description

Added `autoware` prefix to `polar_grid`

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by esteve** [comment]
@xmfcx @mitsudome-r @yukkysaito I couldn't find any packages in universe that depend on this package, so I wasn't sure if it'd be best to remove it. But perhaps it has downstream dependencies in other repositories?

**Comment by xmfcx** [comment]
This is used in the default Autoware configuration. Shows the polar grid and the periodic growing circles around the vehicle.

**Comment by esteve** [comment]
@yukkysaito can you please have a look at this PR? Thanks.

**Comment by xmfcx** [comment]
@esteve 

https://github.com/autowarefoundation/autoware_launch/blob/565568d2ea47ad2a0d92d2cb544f27d3b0efc93e/autoware_launch/rviz/autoware.rviz#L233-L246

It is referenced through the plugin class name: `rviz_plugins/PolarGridDisplay`.

So you probably don't need to update it on the RViz config side.

**Comment by esteve** [comment]
@xmfcx thanks for checking, I only saw references to the classes in `autoware_launch`, but not the package or the namespace. So all the changes here are self contained and could be merged, right?

**Comment by esteve** [comment]
@yukkysaito could you have a look at these changes when you have a moment? Thanks.

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
