### PR TITLE
fix(freespace_planning_algorithms): remove duplicate candidates in tr…

### PR DESCRIPTION
**Pull request by NorahXiong**
…ansition table

Signed-off-by: NorahXiong <norah.xiong@autocore.ai>

## Description

Duplicate candidates are generated in transition table with default parameters. Besides it's explicit if  **_turning_radius_size_** is set to 1 but 2 radius are used to generate transition table.
## Tests performed

**Debug log before**
image

**Debug log after**
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by liuXinGangChina** [comment]
Hi, Mitsudome-san @mitsudome-r .
This is a pr from Norah of autocore.ai.
Will you help us to accelerate the reviewing process.

Thanks, 
lucas.

**Review by TakaHoribe — APPROVED** [review]
Thanks for the PR. I see this PR can fix the issue No.2
> Besides it's explicit if turning_radius_size is set to 1 but 2 radius are used to generate transition table.

but, how this fixes the issue No.1
> Duplicate candidates are generated in transition table with default parameters.

Is this PR only for fixing the number of radius size? 

Anyway, this looks good to me for the fix of issue No.2

**Comment by NorahXiong** [comment]
> Thanks for the PR. I see this PR can fix the issue No.2
> 
> > Besides it's explicit if turning_radius_size is set to 1 but 2 radius are used to generate transition table.
> 
> but, how this fixes the issue No.1
> 
> > Duplicate candidates are generated in transition table with default parameters.
> 
> Is this PR only for fixing the number of radius size?
> 
> Anyway, this looks good to me for the fix of issue No.2

Issue No.1 is cause by the FOR loop times and zero _**dR**_. Let's take the default parameters for example.

    minimum_turning_radius: 9.0
    maximum_turning_radius: 9.0
    turning_radius_size: 1

The [FOR loop](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/freespace_planning_algorithms/src/astar_search.cpp#L97) will be entered into twice as the break-out condition is _**i < turning_radius_size + 1**_ while the _**dR**_ is zero so the same _**R**_ value will be used twice. This part is where the fix of No.1 issue.

**Comment by liuXinGangChina** [comment]
Hi, @mitsudome-r Mitsudome-san. I think this pr has been approved by taka-san, so will you help us to merge it.

Best regards,
Lucas

**Pull request merged**
