### PR TITLE
docs(lidar_centerpoint): fix path of image

### PR DESCRIPTION
**Pull request by Shin-kyoto**
## Description

- Link in `lidar_centerpoint` is determined to be broken. So I want to change link path.
image
- I uploaded this image file to github, and I got the link below; https://github.com/autowarefoundation/autoware.universe/assets/58775300/2a89063a-8e0e-4f59-8d48-f339d4f7c0ff

image

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@Shin-kyoto 
Is there a specific reason to avoid uploading images directly into the repository?
Other packages in universe seem to be doing so

**Comment by Shin-kyoto** [comment]
> @Shin-kyoto Is there a specific reason to avoid uploading images directly into the repository? Other packages in universe seem to be doing so

I avoid uploading it directly into the repo because it makes `git clone` slower.
I got an advice from @kminoda. Do you, @kminoda think about it?

**Review by yukke42 — APPROVED** [review]

**Review by knzo25 — APPROVED** [review]
LGTM

**Comment by Shin-kyoto** [comment]
Thanks!

Additionally, I think we should move this doc to autoware documentation page because today's situation that README.md is included in `launch` directory is not good and the way to compare two model is suitable to be written down on documentation.

**Pull request merged**
