### PR TITLE
feat(behavior_path_planner): use enough backward length for drivable area

### PR DESCRIPTION
**Pull request by takayuki5168**
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
drivable area's backward length from the ego pose must be shorter than 5.0 meters (`drivable_lane_backward_length` parameter).
In the current implementation, only `vehilce_length * 2.0` meters is compensated which might be shorter than 5.0 meters.

In this PR, 5.0 meters will be compensated.

**Comment by h-ohta** [comment]
@takayuki5168 How Can I check this PR?

**Comment by h-ohta** [comment]
In my environment, I confirmed like following images
Before
image
After
image (1)

**Review by h-ohta — APPROVED** [review]
LGTM

**Pull request merged**
