### PR TITLE
fix(behavior_path_planner): prevent re-acceleration in pull over

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

The vehicle decelerate before goal seach area but,  after the vehicle passes the search start point the point can not be found.
So deleration velocity can not be set and the vehicle accerates again.
In this PR, after passing search start point, set the current velocity to the pass.

[Screencast from 2023年03月09日 11時11分52秒.webm](https://user-images.githubusercontent.com/39142679/223906937-e3ef4b85-ce20-4f6d-adb1-d83ab55fa0c3.webm)

## Tests performed

[Screencast from 2023年03月09日 11時53分24秒.webm](https://user-images.githubusercontent.com/39142679/223907288-2e41e5d6-f441-4583-bbb3-d3f9fc8c0f03.webm)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by rej55** [comment]
@kosuke55 Let me confirm.
Could you tell me the reason of using current speed?
It seems using `parameters_.pull_over_velocity` is suitable.

**Comment by kosuke55** [comment]
@rej55 
ah, you are right :+1:

**Comment by kosuke55** [comment]
@rej55 thanks, fixed in https://github.com/autowarefoundation/autoware.universe/pull/3036/commits/5660a7f97d2a848ae800ccbf37b9cf58d98a2ce2

**Review by rej55 — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
[TIERIV internal scenerio test](https://evaluation.tier4.jp/evaluation/reports/42728665-9c6b-5702-8c92-6b27b1bf5cdb?project_id=prd_jt) 882/882

**Pull request merged**
