### PR TITLE
docs(lane_change): stopping position when an object exists ahead

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

(Currently, due to a bug, it does not actually work as described in the following document, but it does show the ideal behavior.)

image

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by rej55** [comment]
@kosuke55 
Could you add description for the new parameters?
https://github.com/autowarefoundation/autoware.universe/pull/5300
https://github.com/autowarefoundation/autoware.universe/pull/5434

**Comment by kosuke55** [comment]
@rej55 
I updated docs

**Review by rej55 — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
@TakaHoribe 
Could you please check if the UseCase is ok for you? :pray:

**Review by TakaHoribe — APPROVED** [review]
LGTM

One comment: the function of "stop for lane change" should be explained before describing each use case.

**Comment by kosuke55** [comment]
> One comment: the function of "stop for lane change" should be explained before describing each use case.

fixed in https://github.com/autowarefoundation/autoware.universe/pull/5523/commits/25bc279b139d0c802a90222bc5cb03700ebad62c

**Pull request merged**
