### PR TITLE
feat(default_ad_api): add object recognition api

### PR DESCRIPTION
**Pull request by tkhmy**
## Description
- add api for getting the object recognized by autoware

## Related links
https://github.com/autowarefoundation/autoware/issues/3225#issuecomment-1409895712
https://github.com/autowarefoundation/autoware-documentation/pull/321
https://github.com/autowarefoundation/autoware_adapi_msgs/pull/25

## Tests performed
- launch planning simulator
- put a vehicle object in the map
- echo the topic `/api/perception/object_recognition/objects`
- the object will be published

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkhmy** [comment]
@isamu-takagi Hi, sorry for the long wait, can you help me to review this PR?

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by isamu-takagi** [comment]
Wait for document merge https://github.com/autowarefoundation/autoware-documentation/pull/321.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
