### PR TITLE
fix: export editable color values autoware overlay

### PR DESCRIPTION
**Pull request by KhalilSelyan**
## Description

This PR adds the capability to use editable color values directly through RViz for the speed limit indicator display. The colors for the speed limit indicator can now be customized, allowing for better visualization and adherence to user preferences.

## Tests performed

The functionality was tested by setting different light and dark color values for the speed limit indicator and verifying the color transitions based on speed-to-limit ratios. The updated function was tested within the RViz environment to ensure the colors update as expected.

https://github.com/autowarefoundation/autoware.universe/assets/36904941/7196d0f5-6b47-4daf-bd5f-d5f488837ad6

## Effects on system behavior

Not applicable.

## Interface changes

The following new parameters are introduced to allow color customization through RViz:

- `light_color`: The color used for the lower end of the speed-to-limit ratio.
- `dark_color`: The color used for the upper end of the speed-to-limit ratio.
- `bg_color`: The background color for the speed limit indicator.
- `bg_alpha`: The transparency level for the background color.

These parameters can be adjusted via the RViz UI to achieve the desired visualization effect.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by KhalilSelyan** [comment]
@xmfcx should i make these similar changes to the mission overlay in this same PR as well or not necessary ?

**Comment by xmfcx** [comment]
@KhalilSelyan It would be good to add them in this same PR too, they packages are very similar anyways.

**Comment by KhalilSelyan** [comment]
@xmfcx It has been done.

**Comment by yukkysaito** [comment]
@KhalilSelyan It's cool :+1:
There have been so many changes. could you do `git rebase`?

**Comment by KhalilSelyan** [comment]
> @KhalilSelyan It's cool :+1:
> There have been so many changes. could you do `git rebase`?

I tried to rebase and i ended up with this calling all reviewers etc i might have done it wrong

**Pull request closed without merging**
