### PR TITLE
feat(costmap_generator): merge extra costmap

### PR DESCRIPTION
**Pull request by HiroIshida**
## Description

This commits enables merging extra costmap into the costmap in the costmap generator.  
For example, if you add the following in remapping of costmage_generator's launch file
```
 ("~/input/extra_occgrid", "/perception/occupancy_grid_map/map"),
```
and add 
```
"use_extra_occgrid": True,
"extra_occgrid_thres": 1.0,
```
to the parameters, then you can get the following costmap: 

uhouho

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]

**Comment by yukkysaito** [comment]
It may be better to use only extra grid map and don't use dynamic object.

**Comment by yukkysaito** [comment]
@HiroIshida Can you add the parameters to launch?

**Comment by HiroIshida** [comment]
@yukkysaito 
Sorry for late reply. 
> It may be better to use only extra grid map and don't use dynamic object.?
> Can you add the parameters to launch?

To my understanding, launch file is of this module is outside of this repository. 
Should I edit the launch file in the following package? 
https://github.com/tier4/autoware_launch

https://github.com/tier4/autoware_launch/blob/00c3607c65ab6526044c99555acc7cd26665060c/planning_launch/launch/scenario_planning/parking.launch.py#L50

Or, just should I edit the xml launch file in the dummy_perception_publisher_module ?

**Comment by yukkysaito** [comment]
@HiroIshida sorry for the late reply. I'll be review soon

**Comment by mitsudome-r** [comment]
@yukkysaito @HiroIshida 
Could you share the status of this PR?
It seems this was left as draft for quite a long time. Please consider closing the PR if you don't plan to merge this anymore.

**Comment by yukkysaito** [comment]
@TakaHoribe How about this PR?

**Comment by HiroIshida** [comment]
@yukkysaito @TakaHoribe 
This PR is for auto-parking feature that I worked on in the part-time. This chage is included in the private branch for auto-parking. I guess, no one but me, need this feature and the change is quite simple, it's better to close this PR.

**Pull request closed without merging**
