### PR TITLE
fix(behavior_path_planner): concurrency issue

### PR DESCRIPTION
**Pull request by VRichardJP**
solves #2495

## Description

Properly lock mutex for `planner_data_` and `bt_manager_` read/write.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@xmfcx @purewater0901 Could you review this PR? Thanks in advance :pray:

**Comment by mitsudome-r** [comment]
@satoshi-ota @purewater0901 
This PR is probably better to be reviewed by the code-owner who knows the code very well so @purewater0901 would be a better reviewer than @xmfcx

**Comment by VRichardJP** [comment]
I don't know much about the new planner manager, but if it is not thread-safe like the old behavior tree manager, then the concurrency issues raised in #2495 still hold on the new API.

I have updated the code accordingly.

**Comment by xmfcx** [comment]
@VRichardJP could you rebase this PR?

Then, @purewater0901 could you review this PR?

**Comment by purewater0901** [comment]
@xmfcx Sorry for being late in response. I'll take a look at it later.

**Comment by purewater0901** [comment]
@xmfcx Could you tell me what is the problem in the current code?

**Comment by VRichardJP** [comment]
@purewater0901 This PR fixes the concurrency issue described here https://github.com/autowarefoundation/autoware.universe/issues/2495#issuecomment-1439549862

**Comment by purewater0901** [comment]
@VRichardJP Thank you for your comment. My concern is that if you lock the `planner_data_` in the `run()` function, we cannot update the route and map until it finishes the process. That's why I separate `planner_data_` from `planner_data`

**Comment by VRichardJP** [comment]
@purewater0901 And this is exactly how things should be, no?
If the map is changed while the planner modules are working on it, the code behavior is impredictible. For example, consider a routine going through all the lanelets of the route:
```c++
for (const &llt: route_lanelets)
{
  doSomething(llt);
}
```
Imagine the route is updated during this routine. This could happen:
```
llt = route_lanelets[0];
doSomething(llt);
llt = route_lanelets[1];
doSomething(llt);
llt = route_lanelets[2];
doSomething(llt);
// route_lanelets updated!!! 
// New route has only 2 lanelets
llt = route_lanelet[3];
doSomething(llt)
-> Segmentation Fault
```

**Comment by purewater0901** [comment]
@VRichardJP 
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L978
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L1025
I think your idea is incorrect. Since the route update is only performed right before each module uses the route, the above issues you mentioned would not happen in the current code. Note that when `behavior_path_planner` gets new route, it does not update the route in the `planner_data_`. You can find the code [here](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L1378-L1383)

**Comment by VRichardJP** [comment]
Yes, the current implementation does not crash at the moment because no one else is modifying the map/route. But if any piece of code, somewhere, was to lock the mutex and modify the map/route, then the code would have totally unpredictable behavior (this is what I show [here](https://github.com/autowarefoundation/autoware.universe/issues/2495#issuecomment-1439549862)). And this is a problem.

I understand your concern regarding the lock in `onMap` and `onRoute`. I could remove the `mutex_pd_` lock by moving the `planner_data_->route_handler->setMap(*map_ptr_)` and `planner_data_->route_handler->setRoute(*route_ptr_)` in the `run()` (at the same place than the old `createLatestPlannerData()`). However, it does not mean we can get away with no locking mechanism. Since `map_ptr_` is the only pointer holding the data, as soon as you do `map_ptr_ = msg;` the destructor of the object pointed by `map_ptr_` is called (because the shared_ptr counter becomes 0), so you cannot have someone else doing `planner_data_->route_handler->setMap(*map_ptr_)` at the same time. In other words, if you want to remove the `mutex_pd_` lock in `onMap()` and `onRoute()`, you need to add a `mutex_map_` and a `mutex_route_`. These mutexes would only be locked shortly for the `planner_data_->route_handler->setMap(*map_ptr_)` and `planner_data_->route_handler->setRoute(*route_ptr_)`.

What do you think?

**Comment by VRichardJP** [comment]
Just to make sure I am clear, here is a toy example that shows why updating the pointer without mutex is not safe:
```C++
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>
#include <vector>

using namespace std::chrono_literals;

class Foo {
public:
  Foo(size_t n, int x)
    : data(n, x) 
  {
  }

  ~Foo() {
    std::cout << "deleting data..." << std::endl;
  }

  std::vector<int> data;
};

static std::shared_ptr<Foo> foo_ptr;

void updateFoo() {
  static int x = 0;
  std::cout << "updating ptr!" << std::endl;
  foo_ptr = std::make_shared<Foo>(100, x++);
}

void accessFoo(const Foo &foo) {
  for (int i=0; i < foo.data.size(); ++i) {
    std::cout << "foo[" << i << "] = " << foo.data[i] << std::endl; 
    std::this_thread::sleep_for(1s);
  }
}

int main(int argc, char** argv) {

  // init
  updateFoo();

  // like onMap() callback
  std::thread update_routine([] {
    for (;;) {
      std::this_thread::sleep_for(5s);
      updateFoo();
    }
  });

  // like run() timer callback
  for (;;) {
    // concurrent unprotected access
    accessFoo(*foo_ptr);
  }

  update_routine.join();

  return 0;
}
```

The code is fairly simple:
- there is a shared ptr to a `Foo` object (like map/route).
- a routine is updating the ptr with a object every 5s (like `onMap` and `onRoute`)
- the main thread read the pointed data (like `run()` callback), and slowly print it to stdout
- to make the concurrency obvious, I added a few sleeps but I would also happen without

If you compile and run you see this:
```bash
$ g++ main.cc -o main && ./main                                                                                
updating ptr!
foo[0] = 0
foo[1] = 0
foo[2] = 0
foo[3] = 0
foo[4] = 0
updating ptr!
deleting data...
foo[5] = 0
foo[6] = 0
foo[7] = 0
foo[8] = 0
foo[9] = 0
updating ptr!
deleting data...
foo[10] = 2
foo[11] = 2
foo[12] = 2
foo[13] = 2
foo[14] = 2
updating ptr!
deleting data...
foo[15] = 2
foo[16] = 2
foo[17] = 2
foo[18] = 2
foo[19] = 2
updating ptr!
deleting data...
foo[20] = 4
foo[21] = 4
foo[22] = 4
``` 

What happens? While the main thread is only accessing the data of the initial foo object (`x = 0`), which is a 0-vector of size 100, it does not always print 0. This because the data the thread is reading is being overwritten by the other thread. Why? Because when the `foo_ptr` is updated, there is no other `shared_ptr` pointing to the old data, so the Foo object is destroyed. Meaning that the memory the old pointer was pointing is free to be used by something else.

On the other hand, if the `foo_ptr` is duplicated before it is reasigned, then there is no issue. Do we need a lock for that? From the pure C++ standard point of view you have no guarantee the pointer swaping is done atomicall. On x86 it might be true? Still, the compiler is free to optimize out the duplicated pointer if no explicit lock mechanism is used. So there are actually 2 solutions of the map/route pointers: either use a mutex, or we could wrap the pointers with `std::atomic<std::shared_ptr<T>>`.

**Comment by VRichardJP** [comment]
@purewater0901 Sorry I messed a lot with the rebase, I think the code is ok now.

**Comment by purewater0901** [comment]
@VRichardJP 
First of all, thank you for your detailed explanations and examples. They helped me a lot to understand your point. 

>EDIT: actually my last sentence is overkill, it would just be necessary to lock the map/route mutex to copy the shared_ptr, so that the pointed data destructor would not be called. Once we have an handle to the old data, the map_ptr_ or route_ptr_ could point to something else without problem. What do you think?

I agree with your idea that creating a new pointer to copy the old data (a handler to the old data). It seems that since the route handler has a pointer to the map and route in its data, the data in the 'planner_data' is modified through `planner_data_'. 

Anyway, to protect the data from being overwritten by other threads, your current implementation seems reasonable to me.

**Comment by purewater0901** [comment]
@VRichardJP Just to make sure that in order to prevent illegal access from other threads, you added a new pointer like 

```C++
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>
#include <vector>

using namespace std::chrono_literals;

class Foo {
public:
    Foo(size_t n, int x)
            : data(n, x)
    {
    }

    ~Foo() {
        std::cout << "deleting data..." << std::endl;
    }

    std::vector<int> data;
};

static std::shared_ptr<Foo> foo_ptr;

void updateFoo() {
    static int x = 0;
    std::cout << "updating ptr!" << std::endl;
    foo_ptr = std::make_shared<Foo>(100, x++);
}

void accessFoo(const Foo &foo) {
    for (int i=0; i < foo.data.size(); ++i) {
        std::cout << "foo[" << i << "] = " << foo.data[i] << std::endl;
        std::this_thread::sleep_for(1s);
    }
}

int main(int argc, char** argv) {

    // init
    updateFoo();

    // like onMap() callback
    std::thread update_routine([] {
        for (;;) {
            std::this_thread::sleep_for(5s);
            updateFoo();
        }
    });

    // like run() timer callback
    for (;;) {
        // concurrent unprotected access
        std::shared_ptr<Foo> planner_data = foo_ptr;  // new pointer
        accessFoo(*planner_data);
    }

    update_routine.join();

    return 0;
}
```

I run this code and it seems okay 
```
updating ptr!
foo[0] = 0
foo[1] = 0
foo[2] = 0
foo[3] = 0
foo[4] = 0
updating ptr!
foo[5] = 0
foo[6] = 0
foo[7] = 0
foo[8] = 0
foo[9] = 0
updating ptr!
deleting data...
foo[10] = 0
foo[11] = 0
foo[12] = 0
foo[13] = 0
foo[14] = 0
updating ptr!
deleting data...
foo[15] = 0
foo[16] = 0
foo[17] = 0
foo[18] = 0
foo[19] = 0
updating ptr!
deleting data...
foo[20] = 0
foo[21] = 0
foo[22] = 0
foo[23] = 0
foo[24] = 0
updating ptr!
deleting data...
foo[25] = 0
foo[26] = 0
foo[27] = 0
foo[28] = 0
foo[29] = 0
updating ptr!
deleting data...
foo[30] = 0
foo[31] = 0
foo[32] = 0
foo[33] = 0
foo[34] = 0
updating ptr!
deleting data...
foo[35] = 0
foo[36] = 0
foo[37] = 0
foo[38] = 0
foo[39] = 0
updating ptr!
deleting data...
foo[40] = 0
foo[41] = 0
foo[42] = 0
foo[43] = 0
foo[44] = 0
updating ptr!
deleting data...
foo[45] = 0
foo[46] = 0
foo[47] = 0
```

**Comment by VRichardJP** [comment]
@purewater0901 
Yes, this snippet works on x86:
```C++
    for (;;) {
        // concurrent unprotected access
        std::shared_ptr<Foo> planner_data = foo_ptr;  // new pointer
        accessFoo(*planner_data);
    }
```
However I don't think it's C++ compliant. There are CPU architectures for which a memory fence would be mandatory to read the new `foo_ptr` value (e.g. typically if the CPU cores have separate cache).

**Comment by purewater0901** [comment]
@VRichardJP 
So you mean if the `foo_ptr` is overwritten as
```C++
foo_ptr = std::make_shared<Foo>(100, x)
```
in some places, the new pointer `planner_data` also points to new values?

**Comment by VRichardJP** [comment]
If the `shared_ptr` is duplicated before it is reassigned to something (like `foo_ptr = std::make_shared<Foo>(100, x)`), the old data stays alive (with `planner_data` pointing to it). As long as `planner_data` exists, no one will destroy it.

With this updated example, I think the issue is clearer:
```C++
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>
#include <vector>

using namespace std::chrono_literals;

class Foo {
public:
    Foo(size_t n, int x)
            : data(n, x)
            , x_(x)
    {
        std::cout << "Creating data: x = " << x_ << std::endl;
    }

    ~Foo() {
        std::cout << "deleting data: x = " << x_ << std::endl;
    }

    std::vector<int> data;
    int x_;
};

static std::shared_ptr<Foo> foo_ptr;

void updateFoo() {
    static int x = 0;
    foo_ptr = std::make_shared<Foo>(100, x++);
}

void accessFoo(const Foo &foo) {
    for (int i=0; i < foo.data.size(); ++i) {
        std::cout << "foo[" << i << "] = " << foo.data[i] << std::endl;
        std::this_thread::sleep_for(1s);
    }
}

int main(int argc, char** argv) {

    // init
    updateFoo();

    // like onMap() callback
    std::thread update_routine([] {
        for (;;) {
            std::this_thread::sleep_for(5s);
            updateFoo();
        }
    });

    // like run() timer callback
    for (;;) {
        // concurrent unprotected access
        #if 0
        std::shared_ptr<Foo> planner_data = foo_ptr;  // new pointer
        accessFoo(*planner_data);
        #else
        accessFoo(*foo_ptr);
        #endif
    }

    update_routine.join();

    return 0;
}
```

The only difference is I show what is the value of x when the data is created/deleted:

```bash
$ g++ -O3 main.cc -o main && ./main
Creating data: x = 0
foo[0] = 0
foo[1] = 0
foo[2] = 0
foo[3] = 0
foo[4] = 0
Creating data: x = 1
deleting data: x = 0   <--- deleted!
foo[5] = 0
foo[6] = 0
foo[7] = 0
foo[8] = 0
foo[9] = 0
Creating data: x = 2
deleting data: x = 1
foo[10] = 2
foo[11] = 2
foo[12] = 2
foo[13] = 2
foo[14] = 2
Creating data: x = 3
deleting data: x = 2
foo[15] = 2
foo[16] = 2
```

Here you can clearly see the destructor for `x = 0`, while we are reading its content (through `*foo_ptr`). Note that it would be different if we passed `foo_ptr` by copy.

If the pointer is duplicated first, you see the `x=0` is never deleted while the main thread is running:

```bash
$ g++ -O3 main.cc -o main && ./main
Creating data: x = 0
foo[0] = 0
foo[1] = 0
foo[2] = 0
foo[3] = 0
foo[4] = 0
Creating data: x = 1
foo[5] = 0
foo[6] = 0
foo[7] = 0
foo[8] = 0
foo[9] = 0
Creating data: x = 2
deleting data: x = 1
foo[10] = 0
foo[11] = 0
foo[12] = 0
```

**Comment by purewater0901** [comment]
@VRichardJP Okay, but once `planner_data` is destroyed (after the accessFoo function has finished), the x=0 data is also going to be destroyed right? If so, do we have any serious problems?

**Comment by VRichardJP** [comment]
Yes, it is deleted right after the `accessFoo(*planner_data)`, when the shared_ptr planner_data is destroyed.

**Comment by VRichardJP** [comment]
I ran a couple more test, and I confirm a mutex lock is definitely required:
```C++
#include <chrono>
#include <iostream>
#include <memory>
#include <mutex>
#include <thread>
#include <vector>

using namespace std::chrono_literals;

class Foo {
public:
    Foo(size_t n, int x)
            : data(n, x)
            , x_(x)
    {}

    std::vector<int> data;
    int x_;
};

static std::mutex mtx;
static std::shared_ptr<Foo> foo_ptr;

void updateFoo() {
    static int x = 0;
    std::lock_guard<std::mutex> lk(mtx);
    foo_ptr = std::make_shared<Foo>(100, x++);
}

void accessFoo(const Foo &foo) {
    for (int i=0; i < foo.data.size(); ++i) {
      if (foo.data[i] != foo.x_) {
        throw std::runtime_error("Failed!!");
      }
    }
}

int main(int argc, char** argv) {

    // init
    updateFoo();

    // like onMap() callback
    std::thread update_routine([] {
        for (;;) {
            std::this_thread::sleep_for(1ms);
            updateFoo();
        }
    });

    // like run() timer callback
    for (;;) {
        // Case 1: throw "Failed!!"
        // accessFoo(*foo_ptr);

        // Case 2: SIGABRT
        std::shared_ptr<Foo> planner_data = foo_ptr;  // new pointer
        accessFoo(*planner_data);

        // Case 3:
        // std::shared_ptr<Foo> planner_data{nullptr};
        // {
        //   std::lock_guard<std::mutex> lk(mtx);
        //   planner_data = foo_ptr;
        // }
        // accessFoo(*planner_data);
    }

    update_routine.join();

    return 0;
}
```

This is the same code, just no more print/sleep.

In case 1, I have no lock, no copy. The main detects the data has been modified and throw an error:
```bash
$ g++ -O3 main.cc -o main && ./main
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed!!
fish: Job 1, './main' terminated by signal SIGABRT (Abort)
```

In case 2, I have no lock, but I copy the pointer. The program crashes due to double free:
```
double free or corruption (top)
fish: Job 1, './main' terminated by signal SIGABRT (Abort)
```

In case 3, I lock ptr access, and make a copy. The program never crash.

**Comment by purewater0901** [comment]
@VRichardJP I also run the code and encountered the exact same issue. Thank you for your experiment, and I get a deeper insight into multithreading.

**Comment by purewater0901** [comment]
For case2, do you know why we have the double free problem?

**Comment by VRichardJP** [comment]
Because I added optimization `-O3` ^^
To be precise, without optimizations，case 1 and 2 both fail because of the runtime error.
```bash
$ g++ main.cc -o main && ./main
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed!!
Aborted (core dumped)
```
When the optimizations are turned on, the case 1 seems to always fail with the runtime error, but the case 2 has a random memory error (double free is one of them):
```sh
$ g++ -O2 main.cc -o main && ./main
free(): too many chunks detected in tcache
Aborted (core dumped)
$ g++ -O2 main.cc -o main && ./main
double free or corruption (out)
Aborted (core dumped)
$ g++ -O2 main.cc -o main && ./main
Segmentation fault (core dumped)
```

This illustrates the undefined behavior I pointed out earlier: in both cases 1 and 2, nothing says `foo_ptr` could be modified by someone else, so the compiler may assume the pointer will never change and optimize things (reorder, move data, skip planner_data, etc), and totally break the code logic doing so.

**Comment by purewater0901** [comment]
@VRichardJP I see. Thank you so much. I'll approve this PR

**Review by purewater0901 — APPROVED** [review]
LGTM

**Comment by VRichardJP** [comment]
yes

**Pull request merged**
