### PR TITLE
feat(accel_brake_map_calibrator): add test scripts for acc/brake cmd generator

### PR DESCRIPTION
**Pull request by TakaHoribe**
Signed-off-by: Takamasa Horibe <horibe.takamasa@gmail.com>

Add super useful test scripts for the accel brake map calibration. It generates an ActuationCmd with a constant accel/brake value interactively given through CLI by a user. 

## Tests performed

Check if the scripts work following the description in readme.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mkuri** [comment]
@TakaHoribe 
The class and node names in the actuation_cmd_publisher.py are still brake_publisher, could you please correct them to actuation_cmd_publisher?

**Comment by TakaHoribe** [comment]
@mkuri Thank you! Done!
```
$ ros2 node list
/actuation_cmd_publisher
/vehicle_accel_tester
/vehicle_brake_tester
```

**Review by mkuri — APPROVED** [review]
LGTM

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
