### PR TITLE
feat(localization): enable logging_level_configure

### PR DESCRIPTION
**Pull request by kminoda**
## Description

Enable logging_level_configure for localization.
Note that I only enable it for ndt_scan_matcher pipeline and not for YabLoc and other localization methods for now.

Related: https://github.com/autowarefoundation/autoware.universe/pull/5131

## Tests performed

Confirmed that, through the RViz plugin, the logging level can be configured runtime.

## Effects on system behavior

Not applicable

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
@Motsu-san Hi, would you review this PR?

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Review by isamu-takagi — APPROVED** [review]

**Comment by YamatoAndo** [comment]
@kminoda Please add `tier4_autoware_utils` as a depend package  to the `localization_error_monitor`'s packages.xml.

**Comment by kminoda** [comment]
@YamatoAndo Thank you. Done.

**Review by YamatoAndo — APPROVED** [review]

**Pull request merged**
