### PR TITLE
refactor(vehicle_velocity_converter)!: prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add the autoware prefix to `vehicle_velocity_converter` package.

## Related links
Related PRs
- aip_launch: https://github.com/tier4/aip_launcher/pull/319
- autoware-documentation: https://github.com/autowarefoundation/autoware-documentation/pull/618
- autoware_tools: https://github.com/autowarefoundation/autoware_tools/pull/124
- sample_sensor_kit_launch: https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/107
  - awsim_labs_sensor_kit_launch: https://github.com/autowarefoundation/awsim_labs_sensor_kit_launch/pull/11
  - awsim_sensor_kit_launch: https://github.com/tier4/awsim_sensor_kit_launch/pull/27
- single_lidar_sensor_kit_launch: https://github.com/autowarefoundation/single_lidar_sensor_kit_launch/pull/5

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by RyuYamamoto — APPROVED** [review]
LGTM

**Comment by YamatoAndo** [comment]
@KeisukeShima @taikitanaka3 @TakaHoribe @takayuki5168 @tkimura4 
Please review this pr.

**Review by takayuki5168 — APPROVED** [review]

**Review by tkimura4 — APPROVED** [review]
LGTM

**Review by taikitanaka3 — APPROVED** [review]

**Review by KeisukeShima — APPROVED** [review]

**Comment by shmpwk** [comment]
@a-maumau Ready to merge?!

**Comment by a-maumau** [comment]
@shmpwk all related PR is approved so if there is no further suggestion, it should be OK.

**Comment by a-maumau** [comment]
@shmpwk sorry, could you wait a moment? seems some of repo ( like https://github.com/autowarefoundation/single_lidar_sensor_kit_launch) also needs to be fixed.

**Comment by a-maumau** [comment]
I created a PR to [single_lidar_sensor_kit_launch](https://github.com/autowarefoundation/single_lidar_sensor_kit_launch/pull/5).
After the review of the PR in single_lidar_sensor_kit_launch, it should be OK this time.

**Comment by shmpwk** [comment]
@a-maumau Thank you so much! Let's merge all PRs.

**Comment by shmpwk** [comment]
@a-maumau 
Srr, could you resolve conflicts?

**Comment by a-maumau** [comment]
@shmpwk I have fixed the conflict!

**Comment by shmpwk** [comment]
Thank you so much!

**Pull request merged**
