### PR TITLE
feat(tier4_adapi_rviz_plugin): add legacy state panel

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Adding legacy state panel because https://github.com/autowarefoundation/autoware.universe/pull/7036 reduces debug functionality.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]

**Comment by xmfcx** [comment]
@isamu-takagi I've just realized this was added back.

Why do you think the current one is reducing the debug functionality?

image

Could you provide feedback?

**Comment by xmfcx** [comment]
Which information is missing from the new panel?

**Comment by armaganarsln** [comment]
I also don’t understand why, instead of addressing the issue of what changes are required for better debug functionality, the state panel was added back without consulting.

**Comment by isamu-takagi** [comment]
@xmfcx @armaganarsln 
All I really needed was the operation_mode part, but I copied the old source code because I could use it as is. Sorry for the confusion of having two panels with same functions.

This is redundant in normal use and is not necessary for the `tier4_state_rviz_plugin`, but we needed to display the following to check the correctness of the implementation. I will later extract the relevant part as a panel dedicated to debugging.

- The current mode when is_mode_available is false.

Screenshot from 2024-09-21 09-22-50
Screenshot from 2024-09-21 09-23-12
Screenshot from 2024-09-21 09-24-11

- The destination mode during transition.

Screenshot from 2024-09-21 09-26-29
Screenshot from 2024-09-21 09-26-56

**Comment by xmfcx** [comment]
I see, these cases are not represented correctly in the new version.

(I also understand why you needed the old version now, thanks. I've left a comment in #8933 as well.)

cc. @KhalilSelyan @isamu-takagi 

Could you confirm if the proposed changes would make it better?

## `Stop` button should be selected in these cases

And the remaining buttons should be disabled.

image

image

## `Auto` button should be selected in these cases

And the remaining buttons should be disabled.

image

image

**Comment by isamu-takagi** [comment]
@xmfcx 

> Could you confirm if the proposed changes would make it better?

Yes, it's good that these are visible to the user.
- Stop button should be selected, rest should be disabled
- Stop button should be selected, rest should be enabled
- Auto button should be selected, rest should be disabled
- Auto button should be selected, rest should be enabled


> Should we allow users to press buttons during the transitions?

No, changing modes during a transition is not an expected usage. It is better to allow this operation only from the debug panel.

**Pull request merged**
