### PR TITLE
build(traffic_light_fine_detector): disable downloading artifacts by default

### PR DESCRIPTION
**Pull request by esteve**
## Description

Use the `DOWNLOAD_ARTIFACTS` option to not download artifacts by default, same rationale as https://github.com/autowarefoundation/autoware.universe/pull/4110.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ambroise-arm** [comment]
The structure looks like

```
if(data_exist)
	msg(found)
	if(hash_match)
		msg(ok)
		return
	else
		msg(diff)
		if(DOWNLOAD)
			download
		else
			msg(warn)
else
	if(DOWNLOAD)
		download
	else
		msg(warn)
```

Would it make sense to simplify as
```
if(data_exist)
	msg(found)
	if(hash_match)
		msg(ok)
		return
	msg(diff)
if(DOWNLOAD)
	download
else
	msg(warn)
```

It would avoid the duplication of the download commands.

**Comment by esteve** [comment]
@ambroise-arm thanks for having a look. I've updated the logic in 5c005815b327a77bac834c5a4a403a163d29d0ce, could you check that it addresses your feedback? Thanks.

**Review by ambroise-arm — APPROVED** [review]
Looks good to me!

**Review by Mingyu1991 — APPROVED** [review]
LGTM

**Comment by miursh** [comment]
@esteve Can we close this PR since https://github.com/autowarefoundation/autoware.universe/pull/4896 is already merged?

**Comment by esteve** [comment]
@miursh yeah, thanks for the reminder

**Pull request closed without merging**
