### PR TITLE
refactor(pose_estimator_arbiter)!: prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add a `autoware_` prefix to `pose_estimator_arbiter`.

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Checked the node is launching or not with `ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/to/map vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit pose_source:=ndt_yabloc_eagleye_artag`.

Did not check the functionality.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by SakodaShintaro** [comment]
@a-maumau 
Unfortunately, some CI checks failed.
Could you check the cppcheck-differential and pre-commit-optional?
It may be better to make another pull request to only fix cppcheck-differential's error.

**Review by SakodaShintaro — CHANGES_REQUESTED** [review]
The CI check has not yet passed.

**Comment by a-maumau** [comment]
I updated the source to pass the cppcheck.

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that logging_simulator works well and the mean error against AWSIM GT is roughly the same as before.

- **Directory Name**
  - [x] Add `autoware_` as a prefix to the directory name.

- **packages.xml**
  - [x] Add `autoware_` to the `name` element.

- **CMakeLists.txt**
  - [x] Change the `project` name to `autoware_***`.
  - [x] Add `autoware::` to `PLUGIN`.

- **Header Files (.hpp)**
  - [x] Fix `#ifndef` include guards
  - [x] Add `autoware::` to `namespace`.

- **Source Files (.cpp)**
  - [x] Add `autoware::` inside `RCLCPP_COMPONENTS_REGISTER_NODE`.

- **Launch Files**
  - [x] Add `autoware_` before `find-pkg-share`.
  - [x] Change `node pkg="<pkgname>"` to `autoware_<pkgname>`.

- **Verification Points**
  - [x] Search `find-pkg-share` in autoware
  - [x] Check README file (especially json schema)

**Pull request merged**
