### PR TITLE
feat: add mirror info into global param

### PR DESCRIPTION
**Pull request by wep21**
## Description

add mirror info into global param to load mirror info from ParameterSubstitution

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Thank you, but I'm not sure whether we should add it or not. So I'll request other architects to also review it.

**Comment by kenji-miyake** [comment]
@xmfcx @yukkysaito @mitsudome-r Is it okay to add mirror params to the global params? I personally think it's okay for now. If necessary, we can reconsider changing the list of global params in the future.

**Comment by yukkysaito** [comment]
We need to think a bit more about whether to put this in the global parameters.
Footprints and bounding boxes are also currently defined, and we need to sort out how they are used and the differences between them.

**Comment by yukkysaito** [comment]
Can we have a consensus within TIER IV?

**Comment by xmfcx** [comment]
Last time, I've created https://github.com/autowarefoundation/autoware-documentation/pull/79 to add [the docs page for vehicle dimensions](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/vehicle-dimensions/#vehicle-dimensions_1) including the mirror as a part of the footprint.

It's better to create a PR/discussion on updating this documentation page with proper reasoning.

Then we can also edit the universe/launch repositories too.

**Pull request closed without merging**
