### PR TITLE
fix: fix Boost.Optional build error on Jazzy

### PR DESCRIPTION
**Pull request by f0reachARR**
## Description

Since Boost 1.79 (maybe), the part that performs IO operations for optional has been separated.
This causes errors when compiling gtest, which will be corrected in this PR.

Ref: https://github.com/orgs/autowarefoundation/discussions/4893

## Tests performed

`colcon test` passed in both Humble and Jazzy environment.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by YoshiRi — APPROVED** [review]
Test also worked within my humble environement.
LGTM

**Comment by YoshiRi** [comment]
@rej55 @takayuki5168 Could you help approving the planning part?

**Review by takayuki5168 — APPROVED** [review]

**Comment by f0reachARR** [comment]
Thank you for approving.
Now I merged latest main branch.

**Comment by Timple** [comment]
I recently learned the opener of the PR is expected to merge after an approval.
But often is lacking rights.

Can someone with write permissions merge this since it's approved?

**Comment by f0reachARR** [comment]
I just noticed this PR has some conflict, and I fixed it.
As you said, I do not have permissions to merge this PR.
Therefore, I would appreciate if someone could merge this PR (after review)

**Comment by HansRobo** [comment]
@f0reachARR 
I approved CI rus ans enable auto-merge.
If all required CIs are green, this will be merged soon.

**Pull request merged**
