### PR TITLE
refactor(stop_filter): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- Link https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — CHANGES_REQUESTED** [review]
Thank you!
I think the two launch files need to be changed as well.

`$(find-pkg-share stop_filter)` -> `$(find-pkg-share autoware_stop_filter)`

* in `localization/autoware_stop_filter/launch/stop_filter.launch.xml`

https://github.com/autowarefoundation/autoware.universe/blob/4b266d44abe7eba46c496fda1fdb9b67473b1b65/localization/autoware_stop_filter/launch/stop_filter.launch.xml#L2

* in `launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml`

https://github.com/autowarefoundation/autoware.universe/blob/598eca1c60d056da9a70ce28a620c51f6f3f70b9/launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml#L20

**Comment by esteve** [comment]
@SakodaShintaro fixed in 662e0f7504

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that logging_simulator works well.
Looks Good To Me :+1:

**Comment by SakodaShintaro** [comment]
There are errors with cppcheck, but it seems that they will be fixed by merging the latest main branch.

**Pull request merged**
