### PR TITLE
chore(gnss_poser): add autoware prefix to gnss_poser

### PR DESCRIPTION
**Pull request by TaikiYamada4**
## Description

[Following the movement of adding `autoware_` prefix to package names](https://github.com/autowarefoundation/autoware/issues/4569), this PR adds autoware prefix to gnss_poser.

## Related links

**Since this PR strongly relates to sensor launching systems, this PR must be merged together with the following PRs.**
- https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/100
- https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/17/
- https://github.com/tier4/aip_launcher/pull/283
- https://github.com/autowarefoundation/awsim_labs_sensor_kit_launch/pull/4

## How was this PR tested?

Confirmed that gnss_poser launches and works as normal in the [rosbag replay simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/).

## Notes for reviewers

**Since this PR strongly relates to sensor launching systems, this PR must be merged together with the following PRs.**
- https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/100
- https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/17/
- https://github.com/tier4/aip_launcher/pull/283
- https://github.com/autowarefoundation/awsim_labs_sensor_kit_launch/pull/4

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kyoichi-sugahara** [comment]
@TaikiYamada4 
As described in the following comment,
> Since this PR strongly relates to sensor launching systems, this PR must be merged together with the following PRs.

Multiple PRs need to be merged simultaneously.
However, due to this PR being unintentionally merged, it appears that errors are occurring during rosdep execution.

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that logging_simulator works well.

And I checked 

- **Directory Name**
  - [x] Add `autoware_` as a prefix to the directory name.

- **packages.xml**
  - [x] Add `autoware_` to the `name` element.

- **CMakeLists.txt**
  - [x] Change the `project` name to `autoware_***`.
  - [x] Add `autoware::` to `PLUGIN`.
  - [x] (Optional) Stop using `${PROJECT_NAME}`.

- **Header Files (.hpp)**
  - [x] Start `#ifndef` guards with `AUTOWARE__`.
  - [x] Add `autoware::` to `namespace`.
  - [x] Change the comment after `namespace` definition.

- **Source Files (.cpp)**
  - [x] Add `autoware::` to `namespace`.
  - [x] Change the comment after `namespace` definition.
  - [x] Add `autoware::` inside `RCLCPP_COMPONENTS_REGISTER_NODE`.

- **Launch Files**
  - [x] Add `autoware_` before `find-pkg-share`.
  - [x] Change `node pkg="<pkgname>"` to `autoware_<pkgname>`.

- **CODEOWNERS**
  - [x] Add `autoware_` to the relevant package.
  - [x] Arrange entries alphabetically within the same component.

- **Include**
  - [x] Add `autoware` folder as necessary and update include statements accordingly.
  - [x] Check for impacts on other packages.

- **Verification Points**
  - [x] Search `find-pkg-share` in autoware
  - [x] Check README file (especially json schema)
  - [x] Pay attention to complex cases like `sensor_launch` as seen in `gnss_poser`

**Review by esteve — APPROVED** [review]
@TaikiYamada4 LGTM, thanks!

**Comment by TaikiYamada4** [comment]
Sorry for my mistake on git operation, I will fix this soon.

**Pull request merged**
