### PR TITLE
feat: use multi thread for obstacle stop

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Related Issue(required)

https://github.com/autowarefoundation/autoware.universe/issues/275

## Description(required)

To solve [this problem](https://github.com/autowarefoundation/autoware.universe/issues/275) in obstacle stop planner,  multi thread is used for callbacks by passing a different callback group, whose type is MutuallyExclusive, to each calback.

## Review Procedure(required)

Run simple psim, and see if each callback of subscribes is called in a steady cycle

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@takayuki5168 Please write some descriptions so that others can understand the issue.

**Comment by yukkysaito** [comment]
related issue: #275

**Comment by yukkysaito** [comment]
@takayuki5168 pls check spell miss

**Comment by takayuki5168** [comment]
I verified that multithread callback (between main callback and others) works well with [this branch](https://github.com/takayuki5168/autoware.universe/tree/feature/multi-thread-obstacle-stop-test).
```
[component_container_mt-15] [ERROR] [1642663490.409771081] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.422219663] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.447238016] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.451786051] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.452142596] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.472353882] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.472631328] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
[component_container_mt-15] [ERROR] [1642663490.497339749] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.508872697] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.522309004] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.547277888] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.551806081] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.552074034] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.570870934] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
[component_container_mt-15] [ERROR] [1642663490.572225181] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.597214536] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.609464164] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.622223087] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.647196724] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.651871129] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.652161780] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.671866627] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
[component_container_mt-15] [ERROR] [1642663490.672258048] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.697232334] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.709206215] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.722175590] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.747233379] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.751847334] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.752148003] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.771276500] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
[component_container_mt-15] [ERROR] [1642663490.772275292] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.797235883] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.809096110] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.822185132] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.847241409] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.851775180] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.852151731] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.871150179] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
[component_container_mt-15] [ERROR] [1642663490.872217757] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.897239863] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.909090753] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: main callback
[component_container_mt-15] [ERROR] [1642663490.922295650] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.947259695] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: current velocity callback
[component_container_mt-15] [ERROR] [1642663490.951793203] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: point callback
[component_container_mt-15] [ERROR] [1642663490.952221861] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: start: dynamic object callback
[component_container_mt-15] [ERROR] [1642663490.971470816] [planning.scenario_planning.lane_driving.motion_planning.obstacle_stop_planner]: end: main callback
```

**Comment by takayuki5168** [comment]
@yukkysaito Sorry, I did.
https://github.com/autowarefoundation/autoware.universe/pull/269/commits/cc41cbaac59c3e58264edfe142aa00696d3f9f21

**Review by yukkysaito — APPROVED** [review]

**Comment by takayuki5168** [comment]
@kenji-miyake It seems spell check is tested to so many files which are not modified in this PR, but is this what you intended to test? It's hard to find the error spell from so many warning spells. :pray:

**Comment by kenji-miyake** [comment]
@takayuki5168 Yes, but it's optional.

**Comment by takayuki5168** [comment]
@kenji-miyake
What do you mean by optional, optional to merge this PR? It's required to merge.
image

**Comment by takayuki5168** [comment]
Ahh, I think now I got it. Other pakcages' spell check is optional, and only spell check in this PR is required. :pray:

**Comment by kenji-miyake** [comment]
@takayuki5168 Please update the target branch. `tier4/proposal` isn't used anymore. So I made it `Required` not to be merged unintentionally.

**Comment by takayuki5168** [comment]
@yukkysaito I guess you can merge this PR if you approve.

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
