### PR TITLE
fix(trajectory_follower): detect driving direction with yaw

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

The sign of the curvature is calculated by the speed, and when the speed is 0, the previous value is used according to the following.
`m_sign_vx = ref_vx > ep ? 1 : (ref_vx < -ep ? -1 : m_sign_vx);`
This means that if we drive backward and then send a path with a forward speed of 0, `m_sign_vx` will not be updated, but the sign of the steer command will be reversed.
In this PR, it has been modified to determine if it is forwad driving or not by looking at the yaw of the path points.

## Tests performed
psim 

without this PR

https://user-images.githubusercontent.com/39142679/180802251-c1796e4c-1fa2-4da2-b432-a3a403e4546a.mp4

with this PR

https://user-images.githubusercontent.com/39142679/180801504-c51e10e2-a1fb-4e50-bb3a-2a69fff2bd6a.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
@TakaHoribe 
From this comment it wants curvature to be 0 when stopped, but it only does so until the first run?
https://github.com/autowarefoundation/autoware.universe/blob/main/control/trajectory_follower/src/mpc.cpp#L555-L556
```
    // curvature will be 0 when vehicle stops
    const float64_t ref_k = reference_trajectory.k[static_cast<size_t>(i)] * m_sign_vx;
```

**Comment by kosuke55** [comment]
Some points of mpc_trajectory are too close, and `dx` `dy` will be 0.
yaw between these points can not be calculated correctly, so determine forward with a path rather than a certain point.

**Comment by TakaHoribe** [comment]
@kosuke55 

> it wants curvature to be 0 when stopped, 

It meant the curvature will get unintentionally zero. Your PR will fix it. Great.


> Some points of mpc_trajectory are too close, and dx dy will be 0.

When did this happen? As I remember, there is a minimum velocity that prevents zero-distant points.

**Comment by kosuke55** [comment]
@TakaHoribe 
> It meant the curvature will get unintentionally zero. Your PR will fix it. Great.
OK, with this PR, since the initial value of `m_sign_vx` is 0, it is set to 0 only before the first drive.
Is it better to set `m_sign_vx` before https://github.com/autowarefoundation/autoware.universe/blob/main/control/trajectory_follower/src/mpc.cpp#L551
and no need to make it a member variable?

> When did this happen? As I remember, there is a minimum velocity that prevents zero-distant points.
It almost always happens when the car is driving at low speed forward or backward.

**Comment by TakaHoribe** [comment]
@kosuke55 

It would be better to make the is_forward a member variable.

> no need to make it a member variable?

Wierd. Need to check.

**Comment by kosuke55** [comment]
@TakaHoribe 
I checked that there are no overlapping points after `resampleMPCTrajectoryByDistance`

**Comment by kosuke55** [comment]
@TakaHoribe 
I updated to check `is_forward_shift` after resample and make `is_forward_shift_` a member variable instead of `m_sign_vx`
https://github.com/autowarefoundation/autoware.universe/pull/1424/commits/57455d49e0c0c8a55d274ee2fd63893ba8d993c2

**Comment by kosuke55** [comment]
@takayuki5168 
And I also updated to return `boost::none` in `isDrivingFoward` when the driving direction is unknown.
image

**Review by TakaHoribe — APPROVED** [review]
LGTM.
It was tested in kashiwanoha map parking lot.

**Pull request merged**
