### PR TITLE
feat!: replace ogm at scenario simulation

### PR DESCRIPTION
**Pull request by taikitanaka3**
Signed-off-by: tanaka3 <ttatcoder@outlook.jp>

## Description

sync autoware launch
https://github.com/tier4/scenario_simulator_v2/pull/803
https://github.com/tier4/autoware_launch/pull/344
use ogm only psim . 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@0x126 
Can you approve this if this?
this PR is to replace ogm at scenario simulation

**Comment by taikitanaka3** [comment]
because ogm is published from scenario simulator for considering computation cost.
and ogm is used to.create only for perception occupanygrid map topic

**Comment by yukkysaito** [comment]
I see.
But in near future, we should decide the range of scenario simulation.
If it is included in the range of scenario simulation, it will be reverted

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
