### PR TITLE
feat(tier4_autoware_utils): add setter/getter of longitudinal velocity

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@yukkysaito Is it ok to add getter/setter of longitudinal velocity for path_with_lane_id/path/trajectory?
If ok, I'll create test

**Review by yukkysaito — COMMENTED** [review]
@takayuki5168 Looks good :+1:

**Comment by takayuki5168** [comment]
@yukkysaito I've added the test. Give me LGTM!

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
