### PR TITLE
fix(ndt_scan_matcher): pose_array_interpolator

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Description

Fix code miss.

## Tests performed

LSim works well.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kminoda — APPROVED** [review]
LGTM

**Review by KYabuuchi — CHANGES_REQUESTED** [review]
The `success_` is not initialized :cry: in the second constructor . Please add `,success_(true)` between line 39 and 40.  
image

**Comment by YamatoAndo** [comment]
@KYabuuchi In the second constructor, the first constructor is called, so `success_` is initialized.

**Review by KYabuuchi — APPROVED** [review]
I am sorry. I was wrong :pray:

**Pull request merged**
