### PR TITLE
fix(ndt_scan_matcher): ndt_scan_matcher crash when input cloud is empty.

### PR DESCRIPTION
**Pull request by zygfrydw**
## Description
The node `ndt_scan_matcher` crashes when receiving an empty point cloud from a sensor. In such a case the node should log a warning and keep waiting for a valid cloud instead of crashing.

## Tests performed
Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
Thank you for the PR! I'll review shortly.

FYI, I will post a related issue here just for a memo: https://github.com/autowarefoundation/autoware.universe/issues/3034

**Review by kminoda — APPROVED** [review]
LGTM

**Comment by KYabuuchi** [comment]
The code owner has approved this PR, you can merge this PR with yourself. :+1:
If you do not have write access, please request reviewers or maintainers to merge it.

(See [here](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/#general-pull-request-workflow) for more details on pull request rules.)

**Comment by shmpwk** [comment]
LGTM

**Pull request merged**
