### PR TITLE
feat(tensorrt_classifier): add README.md

### PR DESCRIPTION
**Pull request by Mingyu1991**
## Description
Add README.md to the package as mentioned [here](https://star4.slack.com/archives/C4P0NSMB5/p1688988968483219)

## Tests performed

Nothing.

## Effects on system behavior

Nothing.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — COMMENTED** [review]
Could you correct the typo?
image

**Comment by Mingyu1991** [comment]
> Could you correct the typo? image

@miursh 
Fixed in [4a89d0d](https://github.com/autowarefoundation/autoware.universe/pull/4264/commits/4a89d0d7b42d4026666edc9fb5577f90f1ba7048)

**Comment by miursh** [comment]
@Mingyu1991 
How about the others?
image

**Comment by Mingyu1991** [comment]
> @Mingyu1991 How about the others? image

@miursh 
I'm sorry .
Fixed in [5dd1e22](https://github.com/autowarefoundation/autoware.universe/pull/4264/commits/5dd1e22d5ee00edd3ddc6819419ad5680efad8da)

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
