### PR TITLE
build(tensorrt_yolox): remove download logic from CMake

### PR DESCRIPTION
**Pull request by esteve**
## Description

See #3137

Depends on https://github.com/autowarefoundation/autoware_common/pull/164

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Mingyu1991** [comment]
@wep21 @dan-dnn @manato 
this is just a friendly reminder that this PR is not active for more than 1 week.

**Comment by manato** [comment]
@esteve 
Thank you for the proposal. The code modification itself makes sense to me. Actually, I'm not familiar with the background of this topic, therefore, I'd appreciated it if you answered my question: If this PR is merged, which process will download the models, especially for general autoware users?

**Comment by esteve** [comment]
@manato thanks for your feedback. The download of models will be moved to ansible scripts (see https://github.com/autowarefoundation/autoware/pull/3375) and also documented for those users who want to do it manually (see https://github.com/autowarefoundation/autoware-documentation/pull/345)

**Comment by manato** [comment]
@esteve I understood. Thank you for your explanation. One more question: Is there any default directory where the models are downloaded? (I could not find out it as long as I checked the PRs you kindly shared.) The launch files included in this `tensorrt_yolox` package expect an [argument](https://github.com/esteve/autoware.universe/blob/0dbe211447df4c6aabef40915487f80f39df8989/perception/tensorrt_yolox/launch/yolox_s_plus_opt.launch.xml#L6) named `model_path`, which represent a directory path that contains ONNX (and label) files. If the default directory exists, changing the default value of the `model_path` would be nice to specify the directory. 
(This launcher-related topic might be out-of-scope of this PR. If you would like to treat this launcher-related topic in another PR, let me know freely :) )

**Comment by esteve** [comment]
@manato in fact we just discussed that in the ASWG :-) We'll have a default folder where artifacts will be downloaded, but the user will be able to override in the command line or changing the launch files. I'll submit a PR with that change and I'd appreciate if I could get your feedback, thanks!

**Review by miursh — APPROVED** [review]
LGTM

**Comment by esteve** [comment]
@miursh thank you for your review, unfortunately I need approval from one of the code owners to merge this (ping @wep21 @dan-dnn @manato)

**Review by wep21 — APPROVED** [review]
LGTM

**Pull request merged**
