### PR TITLE
feat: add publisher for detailed stop reason

### PR DESCRIPTION
**Pull request by TakumiKozaka-T4**
## Description

Modify some planning modules to publish detailed reason of vehicle stop.
The additional message includes stop reason, its detail, and state.

The purpose of this change is to enable external application to recognize the reason of vehicle stop at each stop point.

Modified modules are the following:
* scene modules in behavior velocity planner, obstacle
* obstacle stop planner 
* surround obstacle checker

## Related links

Modify launcher for remap in [this PR](https://github.com/tier4/autoware_launch/pull/298)

## Tests performed
1. Run planning simulator.
2. Put initial pose and goal.
3. Open another terminal and run the launcher : `ros2 launch default_ad_api default_ad_api.launch.py`
4. Run the command : `ros2 topic echo /api/get/motion_factors`

The topic should be published as follows:

> ---
> header:
>   stamp:
>     sec: 1654647537
>     nanosec: 500246668
>   frame_id: map
> motion_factors:
> - pose:
>     position:
>       x: 3717.7839452345706
>       y: 73723.42854108683
>       z: 0.7956681883687983
>     orientation:
>       x: 0.0
>       y: 0.0
>       z: 0.23976677505715965
>       w: 0.9708305174327234
>   distance: 5.599999904632568
>   reason: 9
>   status: 2
>   detail: ''
> - pose:
>     position:
>       x: 0.0
>       y: 0.0
>       z: 0.0
>     orientation:
>       x: 0.0
>       y: 0.0
>       z: 0.0
>       w: 1.0
>   distance: .inf
>   reason: 3
>   status: 1
>   detail: ''
> ---

 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Please resolve conflicts.

**Comment by TakumiKozaka-T4** [comment]
The conflict is resolved.

**Comment by kenji-miyake** [comment]
Mm, I'm sorry. I guess I can't spare time to review this for a while and that I'm not the right person to review this... :thinking: 
Could you choose another appropriate reviewer?

**Comment by yukkysaito** [comment]
@TakumiKozaka-T4 cc @isamu-takagi  Please share the API design document?

**Comment by shmpwk** [comment]
@.TakumiKozaka-T4 has left. 
hould we continue to develop this PR?

**Comment by isamu-takagi** [comment]
@shmpwk 
I'll take over this PR. And convert it a draft once to match [this API](https://github.com/autowarefoundation/autoware-documentation/pull/154).

**Comment by isamu-takagi** [comment]
This PR is taken over https://github.com/autowarefoundation/autoware.universe/pull/1985.

**Pull request closed without merging**
