### PR TITLE
ci(build-and-test): update image tags

### PR DESCRIPTION
**Pull request by amadeuszsz**
## Description

CUDA CI might not work as expected.

In build-and-test CUDA workflow I see packages are not being built properly due to missing libraries e.g. [here](https://github.com/autowarefoundation/autoware.universe/actions/runs/11366699702/job/31617666596#step:13:15438). This is because previous images had an [issue](https://github.com/autowarefoundation/autoware/issues/5219), which is already [fixed](https://github.com/autowarefoundation/autoware/pull/5332). This fix applies for already [changed](https://github.com/autowarefoundation/autoware/pull/5201) image tags. Currently CI operates on [deprecated](https://github.com/autowarefoundation/autoware.universe/actions/runs/11366699702/job/31617666596#step:2:19) tags and consists of quite old update:
```
ghcr.io/autowarefoundation/autoware                                                    latest-autoware-universe-cuda   f7ff8a8144d2   5 weeks ago    10.4GB
```

This PR update tags.

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

If applied tags are not correct or I missed any deprecated tag occurrence - feel free to apply your changes. 

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by youtalk — APPROVED** [review]
LGTM
Good catch!

**Comment by amadeuszsz** [comment]
@youtalk 

CI [fails](https://github.com/autowarefoundation/autoware.universe/actions/runs/11376328355/job/31648732921?pr=9096#step:5:153). If I'm not mistaken, new images are missing `CCACHE_DIR` environment variable. I'm a bit confused since it [exists](hhttps://github.com/autowarefoundation/autoware/blob/2ab4f1cfaaf4027f748cd5d36edfd2eb7e0156a9/ansible/roles/build_tools/tasks/main.yaml#L8). Also I'm not sure if this [script](https://github.com/autowarefoundation/autoware/blob/2ab4f1cfaaf4027f748cd5d36edfd2eb7e0156a9/.webauto-ci/main/autoware-build/run.sh#L17-L24) is applied in CI. If so, maybe hardcoding `CCACHE_DIR` is a solution.

**Comment by youtalk** [comment]
Hmm... I have not changed `ccache` configuration for a while.
I need to understand the difference between `autoware` and `autoware.universe` build configurations.
Please give me some time to do it.

**Comment by youtalk** [comment]
I closed this PR because #9286 was merged.

**Pull request closed without merging**
