### PR TITLE
feat(surround_obstacle_checker): separate surround_obstacle_checker from hierarchical planning flow

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description
The function of `surround_obstacle_checker` is to keep the stopped state when the vehicle is stopped and there are obstacles around the vehicle. In current implementation, the feature is achieved by inserting ZERO velocity into trajectory in the hierarchical motion planning flow.
On the other hand, the feature is alse achieved by using external velocity limit with simpler implementation. (no need to insert stop point)

In this PR,

- use external velocity limit in `surround_obstacle_checker`
- separate `surround_obstacle_checker` from hierarchical planning flow

https://user-images.githubusercontent.com/44889564/165709891-5db5a0bd-c80a-4ce9-bd46-d98c60309f1e.mp4

## Related links
- https://github.com/autowarefoundation/autoware.universe/issues/832

## Tests performed

1. checkout launcher branch to feature/surround-obstacle-checker (https://github.com/tier4/autoware_launch/pull/304)
2. launch planning_simulator.launch.xml.
3. put GOAL.
4. put obstacke around vehicle.
5. engage and check whether Ego does NOT move.
6. remove obstacle and check whether Ego moves toward the GOAL after few seconds.

## Notes for reviewers

- change event driven to timer driven. (default: 10Hz)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by satoshi-ota** [comment]
I missed fixing `tier4_planning_launch`.

Fix `tier4_planning_launch` in https://github.com/autowarefoundation/autoware.universe/pull/830/commits/a516756e117f181449fad727522fcb7e016c737a.

**Comment by satoshi-ota** [comment]
@yukkysaito @TakaHoribe please check autoware_launch :pray: 

https://github.com/tier4/autoware_launch/pull/304

**Comment by yukkysaito** [comment]
I confirmed to work on following tutorials

**Comment by satoshi-ota** [comment]
> I confirmed to work on following tutorials

@yukkysaito thanks for your review :smile:

**Pull request merged**
