### PR TITLE
feat(mission_planner): add route updater

### PR DESCRIPTION
**Pull request by purewater0901**
## Description
Add a route update that updates route of the route handler in default planner

### <samp>🤖 Generated by Copilot at 1f1e50b</samp>

This pull request enables the default planner plugin to handle route information from the mission planner node. It adds an `updateRoute` method to the `PlannerPlugin` interface and implements it in the `DefaultPlanner` class. It also modifies the `MissionPlanner` class to call the `updateRoute` method of the planner plugin when the route changes.

## Tests performed
Planning SImulator

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
@purewater0901 
nice! And how about resetting the route_lanelets when `change_route()` without args is called?

**Comment by purewater0901** [comment]
@kosuke55 If you looked at the `change_route()`, it is only used when clearing the route. So I guess we do not have to do specific process.

**Comment by kosuke55** [comment]
@purewater0901 
`change_route()` seems to reset just the goal but not the route, so `route_lanelets` of `route_handler` is still kept as the previous one.

**Comment by purewater0901** [comment]
@kosuke55 Yes, the route handler still keeps the previous route. However, since there is no way to clear all of the member variables in the route handler, I could not clear the route

**Comment by kosuke55** [comment]
@purewater0901 
yes, I meant adding public `clearRoute()` in route_handler and use it in mission_planner, how do you think?
```
void RouteHandler::clearRoute(){
  route_lanelets_.clear();
  preferred_lanelets_.clear();
  start_lanelets_.clear();
  goal_lanelets_.clear();
  // and more?
}
```

**Comment by purewater0901** [comment]
I add a clear function for route handler with [this PR](https://github.com/autowarefoundation/autoware.universe/pull/3338)

**Review by kosuke55 — APPROVED** [review]
LGTM

**Pull request merged**
