### PR TITLE
fix(autoware_radar_fusion_to_detected_object): fix variableScope

### PR DESCRIPTION
**Pull request by Nagi70**
## Description

This is a fix based on cppcheck variableScope warnings

```
perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp:274:10: style: The scope of the variable 'sum_target_value' can be reduced. [variableScope]
  double sum_target_value = 0.0;
         ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by technolojin — APPROVED** [review]
LGTM

**Review by miursh — APPROVED** [review]
LGTM

**Comment by miursh** [comment]
@Nagi70 
Could you try merging the main branch of AutowareFoundation into your branch in order to pass the CI tests?

**Comment by kobayu858** [comment]
@miursh 
Thanks for the advice, I have merged the main branch.

**Pull request merged**
