### PR TITLE
fix(diagnostic_graph_aggregator): fix uninitMemberVar

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck uninitMemberVar warnings.

```
system/diagnostic_graph_aggregator/src/common/graph/config.hpp:51:12: warning: Member variable 'UnitConfig::index' is not initialized in the constructor. [uninitMemberVar]
  explicit UnitConfig(const TreeData & data) : data(data) {}
           ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by isamu-takagi** [comment]
This variable will be used later by setting a value, so there is no point in initializing it to the default.

**Comment by kobayu858** [comment]
@isamu-takagi 

Thanks for the advice.
The goal this time is to eliminate the cppcheck warning.
Therefore, something needs to be done.

There are three ways to eliminate the warnings. Currently I am using #1.

1. default initialization in member variable declarations
2. initialize in constructor
3. suppress it with a comment

Any opinions on which method is better would be appreciated.

**Comment by isamu-takagi** [comment]
@kobayu858 Could you initialize it with SIZE_MAX to indicate it's uninitialized?

**Comment by kobayu858** [comment]
@isamu-takagi 

Thanks for the advice.
Changed to initialize with the maximum value.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
