### PR TITLE
feat(interpolation): add akima spline interpolation

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

**No behavior changes** since this is not used in any package.
Implemented akima spline interpolation according to https://en.wikipedia.org/wiki/Akima_spline

e.g.) when using akima spline interpolation in behavior velocity planner.
thin path and path footprint of the output of behavior velocity planner are visualized.
before
image

after
image

**TODO (after this PR merged)**
when the ego is running along the road, the first several path points are unstable (path points moves laterally).
In order to always use akima spline instead of normal spline, we have to fix this issue.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@purewater0901 Sorry for the delay, I added the unit test.

**Comment by taikitanaka3** [comment]
@takayuki5168 
Can you add the test or share result for this case (point interval 1e-4) ?
```
  std::vector<double> base_keys ={0.0,1.0,1.0001,2.0,3.0,4.0};
  std::vector<double> base_vals ={0.0,0.0,0.1   ,0.1,0.1,0.1};
  std::vector<double> query_keys={0.0,1.0,1.5   ,2.0,3.0,4.0};
```

**Comment by takayuki5168** [comment]
@taikitanaka3 
I've added. Akima spline interpolation is much better as expected.
https://github.com/autowarefoundation/autoware.universe/blob/24750c5183a560ffff8a1f544bda56baf53db92b/common/interpolation/test/src/test_spline_interpolation.cpp#L113-L116
https://github.com/autowarefoundation/autoware.universe/blob/24750c5183a560ffff8a1f544bda56baf53db92b/common/interpolation/test/src/test_spline_interpolation.cpp#L212-L215

**Comment by taikitanaka3** [comment]
@takayuki5168 
AkimaSplineで値が飛ばなくなりそうっすね。とても素晴らしい！

**Review by purewater0901 — APPROVED** [review]
LGTM

**Review by taikitanaka3 — APPROVED** [review]

**Pull request merged**
