### PR TITLE
feat(twist2accel)!: add new package for estimating acceleration in localization module

### PR DESCRIPTION
**Pull request by kminoda**
## Description
I would like to add a new package that estimates acceleration.

### Motivation
Currently, several packages (especially in planning & control modules) in Universe independently estimate acceleration in a very similar fashion. Instead, it is better to have one single package that is responsible for estimating acceleration in a reliable algorithm so that the above packages can subscribe to the estimated acceleration.

As far as I know, the packages in Universe that estimates acceleration by themselves are as follows:
- [behavior_velocity_planner](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/planning/behavior_velocity_planner/include/behavior_velocity_planner/planner_data.hpp#L155-L189) (source: EKF, lowpass gain: 0.5)
- [obstacle_cruise_planner](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/planning/obstacle_cruise_planner/src/node.cpp#L459-L470) (source: EKF, lowpass gain: 0.2)
- [obstacle_stop_planner](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/planning/obstacle_stop_planner/src/node.cpp#L1126-L1149) (source: EKF, lowpass gain: 0.9)
- [longitudinal_controller_node](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/control/trajectory_follower_nodes/src/longitudinal_controller_node.cpp#L676-L689) (source: EKF, lowpass gain: 0.2)
- [accel_brake_map_calibrator](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp#L451) (source: , lowpass gain: 0.25)
- [control_performance_analysis](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/control/control_performance_analysis/src/control_performance_analysis_core.cpp#L257-L270) (source: EKF, lowpass gain: 0.0?)
- [tier4_control_rviz_plugin](https://github.com/autowarefoundation/autoware.universe/blob/fc6d1a2bae2989b711fb86eb7ef031fb949defb0/common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp#L220-L230) (source: vehicle odom, lowpass gain: 0.13...?)

### Proposal
Screenshot from 2022-06-14 13-45-18

I want to create a new package that estimates acceleration. The package subscribes to the output of EKF. 
I use a lowpass filter with a gain of 0.9 to filter out noise for now, but we can tune this value depending on the requirements from the other packages.

bb6cf10d-15d4-4a67-ad3c-6472ee6f54cc
(The above figure shows the acceleration with lowpass=0.0, 0.2, 0.5, and 0.9. After some discussion with @taikitanaka3, I will use 0.9 to mitigate the large noise)

### Future work
I think there are several ways to improve acceleration estimation, for example as follows:
- use vehicle odometry output instead of EKF output
- integrate the acceleration into the EKF state
I will leave them as future work, as most of the current packages that estimate acceleration use lowpass and EKF output.

## Related links
https://github.com/autowarefoundation/autoware/discussions/1#discussioncomment-2217517

## Tests performed
I checked that the output of acceleration estimator is reasonable by comparing with the acceleration from IMU.
Screenshot from 2022-06-14 14-00-55

## Notes for reviewers
In order to solve the above-mentioned issue, we also have to modify the above packages so that they subscribe the output of this new package.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
FYI: A relationship between lowpass gain and estimated acceleration
Screenshot from 2022-06-14 15-12-16

**Comment by yukkysaito** [comment]
@kminoda I think it is better to implement accel into EKF state(only the current state).
How about you?

**Comment by kminoda** [comment]
@yukkysaito Thank you for the comment! May I ask the reason why you think so?

I personally think that the acceleration should be estimated outside of EKF (unless the accelerometer is also fed to EKF) due to the following reasons:
- It would not improve the estimation of the other state variables.
- It would increase EKF computational complexity.
- If we want to improve the acceleration estimation performance by taking advantage of multiple sensors, we can build another package that performs sensor fusion solely for acceleration.

**Comment by kminoda** [comment]
@yukkysaito 
Having a second thought, I agree that it is worth considering integrating acceleration as a new state in EKF, as it may fit better to the real vehicle model than the current model with random walk velocity. 

So how about this?

- For now, we take this `twist2accel` proposal and proceed to replace all the acceleration estimation in current planning/control\vehicle modules. 
- After it is done, we start working on the improvement of acceleration estimation (if necessary), e.g. by incorporating accel into EKF state.

**Comment by yukkysaito** [comment]
@kminoda 
>For now, we take this twist2accel proposal and proceed to replace all the acceleration estimation in current planning/control\vehicle modules.
After it is done, we start working on the improvement of acceleration estimation (if necessary), e.g. by incorporating accel into EKF state.

Ok. I agree :+1:

**Comment by taikitanaka3** [comment]
@kminoda 
can you add ! to PR title ? because I think this is a major update. ref: https://www.conventionalcommits.org/ja/v1.0.0/
eg)
feat(package_name)!: PR name

**Comment by kminoda** [comment]
Which do you think is better?
1. Modify all the planning/control/vehicle modules that currently estimate acceleration, making them subscribe /localization/acceleration
2. Merge this PR as it is right now, and we work on the above in the different PR(s).

**Comment by taikitanaka3** [comment]
@kminoda 
please separate PR as much as possible for no braking change, so in this PR you add `/localization/acceleration` and then replace existing acceleration calculation in another PR.

**Comment by TakaHoribe** [comment]
@kminoda Thank you for the great work.

>For now, we take this twist2accel proposal and proceed to replace all the acceleration estimation in current planning/control\vehicle modules.
After it is done, we start working on the improvement of acceleration estimation (if necessary), e.g. by incorporating accel into EKF state.

I totally agree with this approach. Please mention the future design in the document. You can create #design or #future-task chapter and write there.

**Pull request merged**
