### PR TITLE
fix(simulator, controller): fix inverse pitch calculation

### PR DESCRIPTION
**Pull request by soblin**
## Related links

launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/613

### Before this PR

https://github.com/autowarefoundation/autoware.universe/assets/28677420/568b1060-3799-4c56-9c17-460a2237cae6

### After this PR

https://github.com/autowarefoundation/autoware.universe/assets/28677420/1241e6ad-3273-440a-ad7f-1b1a0563a5e7

## Interface changes

none.

## Effects on system behavior

ego's pitch angle will align with the map slope.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].
- [X] The PR has been properly tested.
- [X] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.
- [X] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by brkay54** [comment]
> @brkay54 This is a very simple fix for the wrong pitch sign in the simulator reported by you. This may cause a conflict with your PRs, but can we merge this PR?

It is better to merge this one before the mine PRs about PID controller. Already I need to make some changes with respect to your review, while doing this I can also solve the conflicts. Thank you @TakaHoribe -san !

**Review by TakaHoribe — APPROVED** [review]

**Comment by brkay54** [comment]
@TakaHoribe @soblin If everything is okay, can we enable auto-merge?

**Comment by soblin** [comment]
I make a minor change to the added figure then merge this PR

**Comment by soblin** [comment]
I attached before/after video in the description

**Pull request merged**
