### PR TITLE
refactor: simplify Rolling support

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

As a follow-up of #849, I replaced the custom-defined macros with `ROS_DISTRO` macros.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@kenji-miyake thanks for simplifying this code. Regarding these blocks:

```c++
#ifdef ROS_DISTRO_GALACTIC
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#else
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
```

do it the other way around, because otherwise we'd have to add an `#ifdef` for Rolling, Humble, etc. so instead:

```
#ifdef ROS_DISTRO_FOXY
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#else
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
```

a different option is to keep the code as is, but instead of adding `USE_TF2_GEOMETRY_MSGS_DEPRECATED_HEADER` to the compile definitions in the CMakeLists.txt files, add it to `autoware_cmake()` when compiling for anything lower than Galactic. What do you think?

**Comment by esteve** [comment]
@kenji-miyake forget what I just wrote, for some reason I thought we supported Foxy and that the special case for Galaxy was the same as for Rolling and Humble.

**Comment by esteve** [comment]
@kenji-miyake is it documented anywhere that we no longer support Foxy? Otherwise this code would fail when compiling on Foxy.

**Comment by kenji-miyake** [comment]
@esteve Although there is no background written, the supported distros are here.
https://autowarefoundation.github.io/autoware-documentation/main/installation/#ros-version

**Comment by esteve** [comment]
@kenji-miyake thanks for the links, in that case the changes look good to me.

**Review by esteve — APPROVED** [review]

**Pull request merged**
