### PR TITLE
chore(tensorrt_common): fix spell-check

### PR DESCRIPTION
**Pull request by kminoda**
## Description
Fix spell-check in `tensorrt_common`.

`ltype` was not in a dictionary, and thus I would like to fix this abbreviation. (see [spell-check-all](https://github.com/autowarefoundation/autoware.universe/actions/runs/5599696834/jobs/10241010045#step:11:1394))

## Related links
N/A

## Tests performed
Confirmed that it builds successfully

## Notes for reviewers
N/A

## Interface changes
N/A

## Effects on system behavior
N/A

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by wep21 — APPROVED** [review]
LGTM

**Review by HansRobo — APPROVED** [review]
I'm not a reviewer, but I came to say "LGTM" because it's so wonderful!!
Thank you for your contribution!

**Comment by kminoda** [comment]
build CI tooranai :cry:

**Comment by HansRobo** [comment]
pien

**Comment by wep21** [comment]
Are this pr and https://github.com/autowarefoundation/autoware.universe/pull/4289 duplicate?

**Comment by HansRobo** [comment]
Oh, the changes in this PR seem to be fully covered by #4289

**Comment by kminoda** [comment]
Yes, I talked with @miursh and confirmed that either can be merged first

**Pull request merged**
