### PR TITLE
fix(traffic_light_selector, traffic_light_arbiter): fix header

### PR DESCRIPTION
**Pull request by purewater0901**
## Description
Fix header type in traffic light related packages

Related PR: https://github.com/autowarefoundation/autoware_msgs/pull/68

## Tests performed

Not applicable.

## Effects on system behavior

No effects

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
What is this change for? Will the `frame_id` be used?

**Review by miursh — APPROVED** [review]
LGTM

**Comment by purewater0901** [comment]
@isamu-takagi This change is for building the autoware with new traffic light interface

**Comment by miursh** [comment]
@purewater0901 Since we have decided no to use msg header with autoware_perception_msg, I would close this PR.

**Pull request closed without merging**
