### PR TITLE
fix(radar_crossing_objects_noise_filter): refactor CMakeLists

### PR DESCRIPTION
**Pull request by scepter914**
## Description

Refactor CMakeLists of `radar_crossing_objects_noise_filter`

## Tests performed

Checked by compile

## Effects on system behavior

No

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by HansRobo** [comment]
I updated this branch to import https://github.com/autowarefoundation/autoware.universe/pull/6278.
This will help you pass build-and-test-differential faster.

**Comment by miursh** [comment]
@scepter914 
Could you please let me know the reason for this change?

**Comment by scepter914** [comment]
@miursh 
Because the deleted code overlaps with [autoware_cmake](https://github.com/autowarefoundation/autoware_common/blob/main/autoware_cmake/cmake/autoware_package.cmake#L17) and it is unintentional duplication.
For now if autoware_cmake changes, it may work with unintended build options.

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
