### PR TITLE
fix(tier4_state_rviz_plugin): fix unusedFunction

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unusedFunction warnings.

```
common/tier4_state_rviz_plugin/src/custom_button.cpp:56:0: style: The function 'minimumSizeHint' is never used. [unusedFunction]
QSize CustomElevatedButton::minimumSizeHint() const
^

common/tier4_state_rviz_plugin/src/custom_button.cpp:61:0: style: The function 'updateStyle' is never used. [unusedFunction]
void CustomElevatedButton::updateStyle(
^

common/tier4_state_rviz_plugin/src/custom_button.cpp:74:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomElevatedButton::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_container.cpp:29:0: style: The function 'setCornerRadius' is never used. [unusedFunction]
void CustomContainer::setCornerRadius(int radius)
^

common/tier4_state_rviz_plugin/src/custom_container.cpp:35:0: style: The function 'getCornerRadius' is never used. [unusedFunction]
int CustomContainer::getCornerRadius() const
^

common/tier4_state_rviz_plugin/src/custom_container.cpp:40:0: style: The function 'getLayout' is never used. [unusedFunction]
QGridLayout * CustomContainer::getLayout() const
^

common/tier4_state_rviz_plugin/src/custom_segmented_button.cpp:43:0: style: The function 'getButtonGroup' is never used. [unusedFunction]
QButtonGroup * CustomSegmentedButton::getButtonGroup() const
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:35:0: style: The function 'setColors' is never used. [unusedFunction]
void CustomSegmentedButtonItem::setColors(
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:54:0: style: The function 'setHovered' is never used. [unusedFunction]
void CustomSegmentedButtonItem::setHovered(bool hovered)
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:60:0: style: The function 'setCheckableButton' is never used. [unusedFunction]
void CustomSegmentedButtonItem::setCheckableButton(bool checkable)
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:74:0: style: The function 'setDisabledButton' is never used. [unusedFunction]
void CustomSegmentedButtonItem::setDisabledButton(bool disabled)
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:80:0: style: The function 'setActivated' is never used. [unusedFunction]
void CustomSegmentedButtonItem::setActivated(bool activated)
^

common/tier4_state_rviz_plugin/src/custom_container.cpp:43:0: style: The function 'minimumSizeHint' is never used. [unusedFunction]
QSize CustomContainer::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_container.cpp:48:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomContainer::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_icon_label.cpp:53:0: style: The function 'minimumSizeHint' is never used. [unusedFunction]
QSize CustomIconLabel::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_icon_label.cpp:58:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomIconLabel::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_label.cpp:49:0: style: The function 'minimumSizeHint' is never used. [unusedFunction]
QSize CustomLabel::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_label.cpp:54:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomLabel::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_segmented_button.cpp:58:0: style: The function 'minimumSizeHint' is never used. [unusedFunction]
QSize CustomSegmentedButton::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_segmented_button.cpp:63:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomSegmentedButton::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp:79:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomSegmentedButtonItem::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_slider.cpp:22:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomSlider::paintEvent(QPaintEvent *)
^

common/tier4_state_rviz_plugin/src/custom_toggle_switch.cpp:33:0: style: The function 'paintEvent' is never used. [unusedFunction]
void CustomToggleSwitch::paintEvent(QPaintEvent *)
^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@kobayu858 I think these are functions called by the Qt framework. Did the UI appearance in rviz remain the same?
@KhalilSelyan Can you check if it is OK to remove these functions for custom widgets?

**Comment by KhalilSelyan** [comment]
A lot of those have a passive automatic call by Qt that is being overridden by being recreated in the custom component, others are there as these are generic components in case of re-use and being needed later i think it's not necessary to remove them for potential later use in this or other panels @isamu-takagi

**Comment by kobayu858** [comment]
@isamu-takagi @KhalilSelyan 

Thanks for the advice.
I have changed to suppression in the comments about what was actually used.

I removed setCornerRadius, getCornerRadius, and setColors as they do not seem to be used.
The rationale is that they did not look the same in rviz, and as a result of print debugging.

The above three functions are treated as functions that are declared but not defined, such as setContainerWidth, and the declarations are left in hpp.

**Comment by isamu-takagi** [comment]
@kobayu858 Thank you for updating. Could you please remove the declaration from the header as it would be confusing to readers? The other parts are fine.

**Comment by kobayu858** [comment]
@isamu-takagi 
Thank you for the advice. I have removed the header declaration.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
