### PR TITLE
feat(behavior_path_planner): resample output path

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

Resampled output path in behavior path planner so that users can modify interval of the path.
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@TakaHoribe What do you think about the default path interval as 5.0?

**Comment by takayuki5168** [comment]
After deciding the parameter, I will check if all the behavior velocity module works well with the default interval in psim.

**Comment by takayuki5168** [comment]
It's working well with behavior velocity modules.
image

@TakaHoribe @purewater0901 Give me LGTM

**Review by purewater0901 — APPROVED** [review]
LGTM

**Pull request merged**
