### PR TITLE
ci(build-and-test-differential): set checkout fetch-depth to 1

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

Right now this step takes about 2m22s.

This happens for all jobs even before checking if any relevant files are changed.

**Before:** it downloaded the entire history and branches of the repository.
**After:** it only downloads the latest state of the repo (shallow copy).

## Tests performed

This PR CI, now it takes 5s (down from 2m22s).

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Comment by HansRobo** [comment]
@xmfcx @mitsudome-r 
It seems that the `get-modified-packages` action does not work properly when the fetch depth is set to 1.
This action refers to the base branch to identify changed packages, so it seems necessary to checkout including the base branch.

For example, [this pull-request](https://github.com/autowarefoundation/autoware.universe/pull/7437) has many changes but no modified packages are detected by `get-modified-packages` action.

https://github.com/autowarefoundation/autoware.universe/actions/runs/9462550973/job/26065788764

**Comment by xmfcx** [comment]
@HansRobo 

https://github.com/autowarefoundation/autoware-github-actions/blob/45b31c5a26cf49f3db28f5129a5fc2c8def665f0/get-modified-packages/get-modified-packages.sh#L53

This is the only line that might use it. I'm wondering if it is possible to just fetch base branch and the feature branch only. Do you have any suggestions?

**Comment by HansRobo** [comment]
@mitsudome-r 
I am working on `fetch-base-branch-for-modified-package` branch.
https://github.com/autowarefoundation/autoware-github-actions/commits/fetch-base-branch-for-modified-package/
But a straightforward solution cannot work well...

**Pull request merged**
