### PR TITLE
fix(autoware_livox_tag_filter): fix unusedStructMember

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unusedStructMember warnings.

```
sensing/livox/autoware_livox_tag_filter/src/livox_tag_filter_node.cpp:25:9: style: struct member 'LivoxPoint::x' is never used. [unusedStructMember]
  float x;
        ^

sensing/livox/autoware_livox_tag_filter/src/livox_tag_filter_node.cpp:26:9: style: struct member 'LivoxPoint::y' is never used. [unusedStructMember]
  float y;
        ^

sensing/livox/autoware_livox_tag_filter/src/livox_tag_filter_node.cpp:27:9: style: struct member 'LivoxPoint::z' is never used. [unusedStructMember]
  float z;
        ^

sensing/livox/autoware_livox_tag_filter/src/livox_tag_filter_node.cpp:28:9: style: struct member 'LivoxPoint::intensity' is never used. [unusedStructMember]
  float intensity;
        ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by mitsudome-r — APPROVED** [review]

**Comment by kobayu858** [comment]
@mitsudome-r 

It was possible to avoid the error by deleting the initialization part at the same time.
I am sorry, but please check again.

**Comment by kobayu858** [comment]
@knzo25 @mitsudome-r 
Please confirm the PR. Thank you very much.

**Review by knzo25 — CHANGES_REQUESTED** [review]
Even if static checkers say it is not used, this PR should not be merged.
From what I see in the code (it is legacy so we do not "use" it), it uses some fields as filters, but still expects to output the other fields.

I marked this PR as "request changes" but it should be either closed or changed so the cppcheck are silenced

**Review by knzo25 — APPROVED** [review]
LGTM !

**Pull request merged**
