### PR TITLE
build(traffic_light_ssd_fine_detector): remove download logic from CMake

### PR DESCRIPTION
**Pull request by esteve**
## Description

See #3137

Depends on https://github.com/autowarefoundation/autoware_common/pull/164

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Mingyu1991** [comment]
@wep21 
this is just a friendly reminder that this PR is not active for more than 1 week.

**Comment by esteve** [comment]
@xmfcx @mitsudome-r this PR is now ready for review

**Comment by wep21** [comment]
https://github.com/autowarefoundation/autoware.universe/actions/runs/5530434966/jobs/10089832235?pr=3145
@esteve Please remove data from install if you remove download logic.

**Comment by esteve** [comment]
@wep21 removed, thanks!

**Pull request merged**
