### PR TITLE
fix(tier4_perception_launch): fix camera_lidar_radar_fusion_based_detection

### PR DESCRIPTION
**Pull request by 0x126**
## Description
Correcting a few errors of the topic remapping in the `camera_lidar_radar_fusion` mode.

## Tests performed
- Launched `logging_simulator` and checked the information of the related nodes.
```
$ ros2 launch autoware_launch logging_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit perception_mode:=camera_lidar_radar_fusion map_path:=... 
```
```
$ ros2 node info /perception/object_recognition/detection/radar/radar_tracks_msgs_converter
/perception/object_recognition/detection/radar/radar_tracks_msgs_converter
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /localization/kinematic_state: nav_msgs/msg/Odometry
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /sensing/radar/front_center/objects_raw: radar_msgs/msg/RadarTracks
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/radar/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar/output/radar_tracked_objects: autoware_auto_perception_msgs/msg/TrackedObjects
    /rosout: rcl_interfaces/msg/Log
...
$ ros2 node info /perception/object_recognition/detection/radar_object_fusion_to_detected_object
/perception/object_recognition/detection/radar_object_fusion_to_detected_object
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/camera_lidar_fusion/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar/objects: autoware_auto_perception_msgs/msg/DetectedObjects
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar_object_fusion_to_detected_object/debug/low_confidence_objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /rosout: rcl_interfaces/msg/Log
...
```

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by 0x126** [comment]
Confirmed in other modes.
### lidar_radar_fusion
```
$ ros2 launch autoware_launch logging_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit perception_mode:=lidar_radar_fusion map_path:=...

$ ros2 node info /perception/object_recognition/detection/radar/radar_tracks_msgs_converter
/perception/object_recognition/detection/radar/radar_tracks_msgs_converter
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /localization/kinematic_state: nav_msgs/msg/Odometry
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /sensing/radar/front_center/objects_raw: radar_msgs/msg/RadarTracks
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/radar/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar/output/radar_tracked_objects: autoware_auto_perception_msgs/msg/TrackedObjects
    /rosout: rcl_interfaces/msg/Log
...

$ ros2 node info /perception/object_recognition/detection/radar_object_fusion_to_detected_object
/perception/object_recognition/detection/radar_object_fusion_to_detected_object
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/lidar/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar/objects: autoware_auto_perception_msgs/msg/DetectedObjects
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/radar_object_fusion_to_detected_object/debug/low_confidence_objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /rosout: rcl_interfaces/msg/Log
...
```

**Comment by 0x126** [comment]
### `radar` mode
```
$ ros2 launch autoware_launch logging_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit perception_mode:=radar map_path:=...

$ ros2 node info /perception/object_recognition/detection/radar_tracks_msgs_converter
/perception/object_recognition/detection/radar_tracks_msgs_converter
  Subscribers:
    /clock: rosgraph_msgs/msg/Clock
    /localization/kinematic_state: nav_msgs/msg/Odometry
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /sensing/radar/front_center/objects_raw: radar_msgs/msg/RadarTracks
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/object_recognition/detection/objects: autoware_auto_perception_msgs/msg/DetectedObjects
    /perception/object_recognition/detection/output/radar_tracked_objects: autoware_auto_perception_msgs/msg/TrackedObjects
    /rosout: rcl_interfaces/msg/Log
...
```

**Review by miursh — APPROVED** [review]
LGTM

**Review by scepter914 — APPROVED** [review]
LGTM

**Pull request merged**
