### PR TITLE
build(iron): remove rmw qos with ifdef block

### PR DESCRIPTION
**Pull request by wep21**
## Description

remove rmw qos with ifdef block

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kenji-miyake — APPROVED** [review]
It looks okay, but I'm concerned that it may increase maintenance costs a little.
I think it might be good to wait for comments for a while because there might be other good solutions.
If this issue is a blocker for you, I think it's okay to merge it without waiting.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by Timple** [comment]
Why was this closed despite being approved?

**Comment by wep21** [comment]
@Timple I'm sorry, but it is difficult for me to handle this pull request.
@yukkysaito Could someone continue this work instead of me?

**Comment by isamu-takagi** [comment]
@wep21 @yukkysaito @Timple
I think the main branch of autoware.universe supports ROS humble. And when migrating from ROS galactic to humble, we created branches for each distribution and switched between them. If we plan to do the same transition from ROS humble to iron, then `ifdef` is not needed because [rclcpp version is 21 or later in ROS iron](https://github.com/ros2-gbp/rclcpp-release?tab=readme-ov-file#rclcpp-iron---2101-1).

**Comment by yukkysaito** [comment]
With Jazzy on LTS soon to be released, it is a matter of discussion whether to support Iron in the first place.
It is my understanding that there are few requests for changes for Iron at this time, so unless there is a decision to support Iron, I think it is fine to keep it closed.

**Pull request closed without merging**
