### PR TITLE
fix(lidar_apollo_segmentation_tvm, tvm_utility): fixed output dim and pipeline

### LINKED ISSUE #1988: Investigate `lidar_apollo_segmentation_tvm` detection quality
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

I have tested the TVM package replacing the TRT package in the [rosbag demo](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) as part of the PR: https://github.com/autowarefoundation/autoware.universe/pull/1181#issuecomment-1259269257. And the quality of the detection wasn't as good as the detection from the TRT package, at least visually. Some cars were not detected, the lines and circles which indicate the velocity (or planned trajectory, I'm not sure) were wrong, at least on parked vehicles. And the type of detected vehicles might be wrong, it would need to be checked.

### Purpose

Get the detection quality of the TVM package on par with the TRT package.

### Possible approaches

There are multiple possible causes for the difference:

- The TVM version of the package is derived from an [old version from TierIV](https://github.com/tier4/lidar_instance_segmentation_tvm); I expect the TRT version in this repository is more recent
- The neural network may have been updated since then; trained differently/better
- The port may have introduced issues/bugs
- The parameters may not be correct or not all there

### Definition of done

- [x] confirm and document the issue
- [x] find the cause(s)
- [x] update the `lidar_apollo_segmentation_tvm*` packages and/or the [neural network](https://github.com/autowarefoundation/modelzoo/tree/master/perception/lidar_obstacle_detection/baidu_cnn/onnx_bcnn) in use, depending on what is necessary

### PR DESCRIPTION
**Pull request by angry-crab**
Signed-off-by: Xinyu Wang <xinyu.wang@tier4.jp>

## Description

Resolve #1988 
Changed default allocation device according to config. Fixed output data transfer in case of GPU involved. 
Reason discussed in the follwing issue.
#1898 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by angry-crab** [comment]
[update bcnn](https://github.com/autowarefoundation/modelzoo/pull/75) has to be merged before this one.

**Review by ambroise-arm — CHANGES_REQUESTED** [review]
With the update of the model, the unit test of `lidar_apollo_segmentaiton_tvm` doesn't pass anymore: https://github.com/autowarefoundation/autoware.universe/blob/2997983d087cf66d46dce5e6b53435ed3becdaa1/perception/lidar_apollo_segmentation_tvm/test/main.cpp#L89

Which needs to become `test_segmentation(false, false, false)`.
The comments won't make much sense then. Maybe you could put the 4 `test_segmentation()` intensity/constant feature combinations in a single test group.

**Review by ambroise-arm — APPROVED** [review]
LGTM

**Comment by angry-crab** [comment]
@ambroise-arm It seems that approving from reviewers with write access is required. Would you talk to @mitsudome-r about this? Thanks.

**Comment by angry-crab** [comment]
@mitsudome-r This PR can be merged.

**Comment by xmfcx** [comment]
@angry-crab can you rebase this PR? Auto-rebase warns of conflicts.

**Comment by angry-crab** [comment]
> @angry-crab can you rebase this PR? Auto-rebase warns of conflicts.

Done!

**Pull request merged**
