### PR TITLE
feat(behavior_planning): use acceleration from localization module

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

- update following module to use acceleration from localization module

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@TakaHoribe 
This PR : [791/823](https://evaluation.tier4.jp/evaluation/reports/d9393c96-fb41-576c-8c27-f1107c4f44aa?project_id=prd_jt)
Baseline : [791/823](https://evaluation.tier4.jp/evaluation/reports/71a2bdf1-3cc6-50ce-86ff-acce7d7a78ba?project_id=prd_jt)

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Review by taikitanaka3 — APPROVED** [review]
LGTM
@satoshi-ota 
~can you link autoware_launcher's PR?~

**Comment by satoshi-ota** [comment]
@taikitanaka3 @TakaHoribe 
- https://github.com/tier4/autoware_launch/pull/482

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
