### PR TITLE
fix(freespace_planner): collision check

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

fix https://github.com/autowarefoundation/autoware.universe/issues/662

## Related links

https://github.com/autowarefoundation/autoware.universe/issues/662

## Tests performed

I haven't reproduced this bug so not tested.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
@TakaHoribe 
I can't set @HiroIshida  as a reviewer, so please review it.

**Comment by xmfcx** [comment]
@kosuke55 do you know if this PR would fix this issue:
- https://github.com/autowarefoundation/autoware.universe/issues/980

**Review by brkay54 — APPROVED** [review]
Thank you for this PR, I think you are right, in current implementation boundaries of the vehicle may not be added to `coll_indexes_table_` exactly. Your implementation should solve this issue. Code is also well, I approved.

**Comment by kosuke55** [comment]
@brkay54 
thank you for your review!

**Pull request merged**
