### PR TITLE
feat(map_height_fitter): add service node

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Add map height fitter node for python tools.

## Tests performed

Check `/map/map_height_fitter/service`.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
>Add map height fitter node for python tools.


May I ask for a little more background information?
Does this node start in runtime?
I am wondering if it will be a new component interface.

**Comment by isamu-takagi** [comment]
>May I ask for a little more background information?
Does this node start in runtime?
I am wondering if it will be a new component interface.

This node is not launched by default. Launch with the tool if it is used by tool. So it's not a component interface.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by YamatoAndo — APPROVED** [review]
I have confirmed that `/map/map_height_fitter/service` works.

**Pull request merged**
