### PR TITLE
feat(obstacle_cruise_planner): add an explanation

### PR DESCRIPTION
**Pull request by purewater0901**
Signed-off-by: yutaka <purewater0901@gmail.com>

## Description
Add more explanations to the terminal stop parameter

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
@purewater0901 
Could you update README? https://github.com/autowarefoundation/autoware.universe/tree/main/planning/obstacle_cruise_planner

**Comment by purewater0901** [comment]
@kosuke55 I just updated the parameter description on the readme. Let me know if you think we should have more details about this new parameter.

**Review by kosuke55 — APPROVED** [review]
Thaks! looks good!

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Pull request merged**
