### PR TITLE
fix(reaction_analyzer): fix unreadVariable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unreadVariable warnings.

```
tools/reaction_analyzer/src/utils.cpp:225:27: style: Variable 'current_distance' is assigned a value that is never used. [unreadVariable]
  double current_distance = 0.0;
                          ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
@brkay54 

Please confirm the PR. Thank you very much.

**Review by brkay54 — APPROVED** [review]
No need to define `current_distance` before the loop. LGTM. Thanks.

**Review by brkay54 — CHANGES_REQUESTED** [review]
Sorry for the inconvenience, it seems there is another PR which proposed almost same changes: 
- https://github.com/autowarefoundation/autoware.universe/pull/8450

making `const double` is better so IMO we can close this PR.

**Comment by veqcc** [comment]
@brkay54 
Thank you for the reply!! I will colse this PR instead of @kobayu858 ans merge https://github.com/autowarefoundation/autoware.universe/pull/8450

**Pull request closed without merging**
