### PR TITLE
chore(system_monitor): fix typos

### PR DESCRIPTION
**Pull request by kenji-miyake**
## Description

Fixed several spell-check errors.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by ito-san — APPROVED** [review]
Thank you for the PR!
LGTM!

**Comment by kenji-miyake** [comment]
```
/__w/autoware.universe/autoware.universe/system/system_monitor/reader/hdd_reader/hdd_reader.cpp:57:8: error: redefinition of ‘struct HddInfo’
   57 | struct HddInfo
      |        ^~~~~~~
In file included from /__w/autoware.universe/autoware.universe/system/system_monitor/reader/hdd_reader/hdd_reader.cpp:20:
/__w/autoware.universe/autoware.universe/system/system_monitor/include/hdd_reader/hdd_reader.hpp:72:8: note: previous definition of ‘struct HddInfo’
   72 | struct HddInfo
```

I removed `_` from the struct, but was it to avoid redefinition? :thinking: 
I'll consider renaming it.

**Comment by kenji-miyake** [comment]
Since this PR is a little big, I'll split the refactoring part into a separate PR.

**Comment by kenji-miyake** [comment]
@ito-san Since I've drastically changed this PR, could you recheck it, please?

**Review by ito-san — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
