### PR TITLE
feat(behavior_velocity): use multi thread

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Related Issue(required)

https://github.com/autowarefoundation/autoware.universe/issues/275

## Description(required)

To solve [this problem](https://github.com/autowarefoundation/autoware.universe/issues/275) in behavior velocity planner,  multi thread is used for callbacks by passing a different callback group, whose type is MutuallyExclusive, to each calback.

## Review Procedure(required)

Run simple psim, and see if each callback of subscribes is called in a steady cycle.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
related issue: https://github.com/autowarefoundation/autoware.universe/issues/275

**Comment by takayuki5168** [comment]
I verified that multithread callback (between main callback and others) works well with [this branch](https://github.com/takayuki5168/autoware.universe/tree/feature/multi-thread-behavior-vel-test).
```
[component_container_mt-13] [ERROR] [1642662882.794377204] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: main callback
[component_container_mt-13] [ERROR] [1642662882.799579164] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.807371924] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: no ground point callback
[component_container_mt-13] [ERROR] [1642662882.807749267] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: predicted objects grid callback
[component_container_mt-13] [ERROR] [1642662882.808056155] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: occupancy grid callback
[component_container_mt-13] [ERROR] [1642662882.824459486] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.843439910] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: end: main callback
[component_container_mt-13] [ERROR] [1642662882.849384627] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.874474323] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.894636876] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: main callback
[component_container_mt-13] [ERROR] [1642662882.899492986] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.907409380] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: no ground point callback
[component_container_mt-13] [ERROR] [1642662882.907746741] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: predicted objects grid callback
[component_container_mt-13] [ERROR] [1642662882.908022094] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: occupancy grid callback
[component_container_mt-13] [ERROR] [1642662882.924401888] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.944702387] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: end: main callback
[component_container_mt-13] [ERROR] [1642662882.949379014] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.974541035] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662882.994380741] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: main callback
[component_container_mt-13] [ERROR] [1642662882.999506913] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.007293838] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: no ground point callback
[component_container_mt-13] [ERROR] [1642662883.007773559] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: predicted objects grid callback
[component_container_mt-13] [ERROR] [1642662883.007947657] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: occupancy grid callback
[component_container_mt-13] [ERROR] [1642662883.024536749] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.043817180] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: end: main callback
[component_container_mt-13] [ERROR] [1642662883.049391444] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.074506153] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.094305281] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: main callback
[component_container_mt-13] [ERROR] [1642662883.099483413] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.107392075] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: no ground point callback
[component_container_mt-13] [ERROR] [1642662883.107746080] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: predicted objects grid callback
[component_container_mt-13] [ERROR] [1642662883.108260254] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: occupancy grid callback
[component_container_mt-13] [ERROR] [1642662883.124450754] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.144403158] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: end: main callback
[component_container_mt-13] [ERROR] [1642662883.149395858] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.174492421] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.194346627] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: main callback
[component_container_mt-13] [ERROR] [1642662883.199456582] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.207319854] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: no ground point callback
[component_container_mt-13] [ERROR] [1642662883.207770522] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: predicted objects grid callback
[component_container_mt-13] [ERROR] [1642662883.208020012] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: occupancy grid callback
[component_container_mt-13] [ERROR] [1642662883.224432867] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: start: vehicle velocity callback
[component_container_mt-13] [ERROR] [1642662883.243250057] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: end: main callback
```

**Review by yukkysaito — DISMISSED** [review]

**Comment by taikitanaka3** [comment]
@takayuki5168 
I changed target branch to main. Can we merge this now?

**Review by taikitanaka3 — APPROVED** [review]
LGTM

please write release note

**Comment by taikitanaka3** [comment]
cc: @yukkysaito 
FYI: I want to reduce cost for subscribing occupancy grid as much as possible by this PR.

**Review by yukkysaito — APPROVED** [review]

**Comment by yukkysaito** [comment]
@kenji-miyake why doesn't build-and-test-differential finish yet?

**Comment by kenji-miyake** [comment]
I think the branch is old. Will rebase.

**Pull request merged**
