### PR TITLE
refactor(localization): remove unnecessary dependency in localization packages

### PR DESCRIPTION
**Pull request by KYabuuchi**
## Description

To minimize package dependencies, I removed unnecessary package dependencies from the package.xml. 

The selection of packages to remove was based on https://github.com/autowarefoundation/autoware/issues/3468#issuecomment-2235846503

## Related links

https://github.com/orgs/autowarefoundation/discussions/5007
In this discussion, it is mentioned that "slimming down the container image sizes is the next urgent task."

## How was this PR tested?
I deleted the build/ and install/ directories and confirmed that the build was successful.

## Notes for reviewers

None.

## Interface changes

Does not change.

## Effects on system behavior

Does not change.

### CODE REVIEW

**Comment by KYabuuchi** [comment]
@a-maumau maybe our works are conflicted.  sorry  :sob:

**Comment by KYabuuchi** [comment]
To the maintainers,
since @a-maumau  has conducted more detailed testing, I have asked him to review this and share his detailed analysis.
Please wait your reviews until he has completed his review.

**Comment by a-maumau** [comment]
I have [updated the script](https://github.com/autowarefoundation/autoware/issues/3468#issuecomment-2242360027) for checking some `autoware_*` dependency and the result is following:

<details>
<summary>updated result</summary>

```Text
--- Checking src/universe/autoware.universe/localization/autoware_landmark_based_localizer/autoware_landmark_manager/package.xml ---

--- Checking src/universe/autoware.universe/localization/autoware_landmark_based_localizer/autoware_ar_tag_based_localizer/package.xml ---
ament_index_cpp should be rather be marked as either <build_depend> or <test_depend>, not <depend>
autoware_lanelet2_extension seems not to be used

--- Checking src/universe/autoware.universe/localization/pose_initializer/package.xml ---

--- Checking src/universe/autoware.universe/localization/ekf_localizer/package.xml ---

--- Checking src/universe/autoware.universe/localization/pose_estimator_arbiter/package.xml ---
pcl_ros seems not to be used
pluginlib seems not to be used
ublox_msgs seems not to be used
yabloc_particle_filter seems not to be used

--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_pose_initializer/package.xml ---

--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_image_processing/package.xml ---

--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_monitor/package.xml ---

--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_common/package.xml ---

--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_particle_filter/package.xml ---

--- Checking src/universe/autoware.universe/localization/autoware_pose_covariance_modifier/package.xml ---

--- Checking src/universe/autoware.universe/localization/twist2accel/package.xml ---

--- Checking src/universe/autoware.universe/localization/autoware_stop_filter/package.xml ---

--- Checking src/universe/autoware.universe/localization/gyro_odometer/package.xml ---

--- Checking src/universe/autoware.universe/localization/localization_util/package.xml ---
autoware_universe_utils seems not to be used
fmt seems not to be used
nav_msgs seems not to be used
sensor_msgs seems not to be used
std_srvs seems not to be used
tf2_ros seems not to be used
tf2_sensor_msgs seems not to be used
tier4_debug_msgs seems not to be used
tier4_localization_msgs seems not to be used

--- Checking src/universe/autoware.universe/localization/ndt_scan_matcher/package.xml ---
std_msgs seems not to be used

--- Checking src/universe/autoware.universe/localization/pose_instability_detector/package.xml ---
ament_index_cpp should be rather be marked as either <build_depend> or <test_depend>, not <depend>
tier4_debug_msgs seems not to be used

--- Checking src/universe/autoware.universe/localization/localization_error_monitor/package.xml ---
diagnostic_updater seems not to be used

--- Checking src/universe/autoware.universe/localization/geo_pose_projector/package.xml ---

--- Checking src/universe/autoware.universe/localization/pose2twist/package.xml ---
```
</details>

At least for compiling, we can follow the above result for erasing the unused dependency except for `autoware_universe_utils` in localization_util.

It seems it will cause
```
fatal error: diagnostic_msgs/msg/diagnostic_array.hpp: No such file or directory
   20 | #include <diagnostic_msgs/msg/diagnostic_array.hpp>
```
for some reason.

**Comment by KYabuuchi** [comment]
I have updated the dependencies based on a-maumau's review.  :pray: 

And, I have reconfirmed that all packages build successfully again.

Now, this PR is ready for review :bow:

**Review by YamatoAndo — APPROVED** [review]
I have confirmed that the all packages build successfully and the Lsim works with sample rosbag.

**Pull request merged**
