### PR TITLE
chore(radar_object_tracker): move tracker config directory to parameter yaml

### PR DESCRIPTION
**Pull request by YoshiRi**
## Description

Move launch parameter file description to yaml.

> [!WARNING]
> Need to fix autoware_launch first. https://github.com/autowarefoundation/autoware_launch/pull/838

## Tests performed

Build and test with lsim.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by scepter914 — APPROVED** [review]
LGTM

**Review by kminoda — COMMENTED** [review]
Please edit tracking.launch.xml in tier4_perception_launch so that `object_recognition_tracking_radar_object_tracker_node_param_path` is properly passed to the node. (Currently it doesn't)

Probably you should add an argument here:
```
    <!--radar long range dynamic object tracking-->
    <include file="$(find-pkg-share radar_object_tracker)/launch/radar_object_tracker.launch.xml">
      <arg name="input" value="$(var radar_tracker_input)"/>
      <arg name="output" value="$(var radar_tracker_output)"/>
      <arg name="data_association_matrix_path" value="$(var object_recognition_tracking_radar_object_tracker_data_association_matrix_param_path)"/>
      <arg name="tracker_setting_path" value="$(var object_recognition_tracking_radar_object_tracker_tracking_setting_param_path)"/>
    </include>
```

**Comment by YoshiRi** [comment]
@kminoda 
Thanks for you suggestion. Fixed here https://github.com/autowarefoundation/autoware.universe/pull/6250/commits/7f41f63794105b7835d6e6a9d88b5167e43721de

**Review by kminoda — APPROVED** [review]
LGTM

**Review by miursh — APPROVED** [review]

**Pull request merged**
