### PR TITLE
feat(default_ad_api): add vehicle info api

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Add vehicle dimension API.

## Tests performed

`ros2 service call /api/vehicle/info/dimensions autoware_adapi_v1_msgs/srv/GetVehicleDimensions `

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by mitsudome-r** [comment]
@isamu-takagi Is the usecase for this API shared somewhere?
I feel uncomfortable adding new APIs without knowing how it is going to be used.

**Comment by isamu-takagi** [comment]
> @isamu-takagi Is the usecase for this API shared somewhere?
> I feel uncomfortable adding new APIs without knowing how it is going to be used.

The use cases are added in https://github.com/autowarefoundation/autoware-documentation/pull/381.

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Pull request merged**
