### PR TITLE
fix: rename `use_external_emergency_stop` to  `check_external_emergency_heartbeat` (#2455)

### PR DESCRIPTION
**Pull request by shmpwk**
## Description

This PR cherry picked https://github.com/autowarefoundation/autoware.universe/pull/2455 to upgrade the galactic branch.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
@TakaHoribe Just approval is OK, thank you.

**Comment by shmpwk** [comment]
@TakaHoribe Could you review this? Just approval is OK because this is cherry-picking to galactic branch.
Could you also approve this sinse they are relavant? https://github.com/autowarefoundation/autoware_launch/pull/126

**Comment by shmpwk** [comment]
@TakaHoribe Could you check this?

**Comment by shmpwk** [comment]
@takayuki5168 Could you just approve this?

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
