### PR TITLE
fix(mission_planner): fix initialize function

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

fix initialize function of mission planner

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@isamu-takagi Could you review the PR.

**Comment by isamu-takagi** [comment]
@takayuki5168 To prevent similar mistakes, I think it's good to make private function for common parts.

```cpp
void DefaultPlanner::initialize(rclcpp::Node * node)
{
  initialize_common(node);
  map_subscriber_ = node_->create_subscription<HADMapBin>(...)
}

void DefaultPlanner::initialize(rclcpp::Node * node, const HADMapBin::ConstSharedPtr msg)
{
  initialize_common(node);
  map_callback(msg);
}
```

**Comment by takayuki5168** [comment]
@isamu-takagi Thank you for your suggestion. I did.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Review by mitsudome-r — APPROVED** [review]

**Pull request merged**
