### PR TITLE
fix(tier4_control_launch): fix aeb input predicted object topic name

### PR DESCRIPTION
**Pull request by ismetatabay**
## Description

This PR fixes AEB predicted object input topic.

## Related links

**Parent Issue:**

- Link https://github.com/autowarefoundation/autoware.universe/issues/9008

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by mitsudome-r** [comment]
@ismetatabay Are there any links to related discussions/issues/PRs regarding this change?

**Comment by ismetatabay** [comment]
@mitsudome-r -san, I created this one, thank you for pointing out:

- https://github.com/autowarefoundation/autoware.universe/issues/9008

**Comment by danielsanchezaran** [comment]
@ismetatabay thank you so much for noticing and providing a fix, it seems the moving[ from python launch to xm](https://github.com/autowarefoundation/autoware.universe/pull/7682/files)l launch brought this problem. I tested locally and this PR works.

**Review by danielsanchezaran — APPROVED** [review]
LGTM

**Review by takayuki5168 — APPROVED** [review]

**Pull request merged**
