### PR TITLE
build(lidar_centerpoint): use APT version of python3-open3d as dependency

### PR DESCRIPTION
**Pull request by esteve**
## Description

This uses the APT version of the dependency (instead of from PyPI), see https://github.com/ros/rosdistro/pull/36052

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@yukke42 
Just in case, I will try with the data from the old PR as in my experience open3d changes the api between versions

**Comment by knzo25** [comment]
Tested with the  data from
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-19941)

**Comment by knzo25** [comment]
@esteve 
Could you fix `build-and-test-differential`?
It seems the rosdep update is not working as expected there

**Review by knzo25 — APPROVED** [review]
LGTM, thanks !

**Comment by esteve** [comment]
@knzo25 thanks for the quick review!

**Pull request merged**
