### PR TITLE
feat(rtc_auto_mode_manager): add new module

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Register new module `avoidance_by_lane_change_right/left` to rtc auto mode manager.

Related PR: https://github.com/tier4/tier4_autoware_msgs/pull/71

## Tests performed

I can change rtc mode via rtc manager rviz plugin.

rviz_screenshot_2023_04_20-10_49_49
rviz_screenshot_2023_04_20-10_50_11

## Effects on system behavior

This PR make it possible to change `avoidance_by_lane_change` module rtc mode.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@satoshi-ota 
please add autoware message PR link

**Comment by satoshi-ota** [comment]
> @satoshi-ota please add autoware message PR link

@taikitanaka3 DONE :+1: 

https://github.com/tier4/tier4_autoware_msgs/pull/71

**Comment by taikitanaka3** [comment]
@satoshi-ota 
and maybe config in autoware launch for auto mode manager PR is also necessary

**Comment by satoshi-ota** [comment]
@taikitanaka3 Sorry for lack of explanation.

Now, `avoidance_by_lc` module is **NOT** launched as default. So, I don't add the config intentionally since following warn message are shown.

```
[rtc_auto_mode_manager_node-28] [INFO] [1681985105.807869215] [planning.scenario_planning.lane_driving.behavior_planning.rtc_auto_mode_manager]: Waiting for service... [avoidance_by_lane_change_left]
```

**Review by taikitanaka3 — APPROVED** [review]

**Pull request merged**
