### PR TITLE
fix(behavior_path_planner): unsafe mutex operation

### PR DESCRIPTION
**Pull request by NorahXiong**
Signed-off-by: NorahXiong <norah.xiong@autocore.ai>

## Description

Fix unsafe mutex operation in behavior_path_planner.
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L516

If parking scenario is activated, the function will exit without unlocking the mutexes which belong to the class object. The program will try to lock the mutexes again when reentering the function and something unexpected will occur.

## Tests performed

Tested in planning simulator.

Before: no route is generated when scenario changing from parking to lane-driving because behavior_path_planner is stuck
image

After: route is generated after scenario changes from parking to lane-driving
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Review by tkimura4 — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
@TakaHoribe @yukkysaito Please have a look.

**Comment by NorahXiong** [comment]
> LGTM @NorahXiong Is this ready to merge?

Sorry for the late reply. This is ready to merge.

**Pull request merged**
