### PR TITLE
fix(autoware_multi_object_tracker): fix functionConst

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck functionConst warnings.

```
perception/autoware_multi_object_tracker/src/debugger/debugger.hpp:94:8: style: inconclusive: Technically the member function 'autoware::multi_object_tracker::TrackerDebugger::checkDelay' can be const. [functionConst]
  void checkDelay(diagnostic_updater::DiagnosticStatusWrapper & stat);
       ^

perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:63:8: style: inconclusive: Technically the member function 'autoware::multi_object_tracker::InputStream::getNames' can be const. [functionConst]
  void getNames(std::string & long_name, std::string & short_name)
       ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by technolojin — APPROVED** [review]
LGTM

**Comment by kobayu858** [comment]
@technolojin 

```
  diagnostic_updater_.add(
    “Perception delay check from original header stamp”, this, &TrackerDebugger::checkDelay);
```

In the above code, add was not accepting a pointer of type const, resulting in a build error. Therefore, we changed the method to suppress the warning with a comment.

I apologize for the inconvenience, but may I ask you to check again?

**Comment by vividf** [comment]
@technolojin kindly ping

**Review by yukkysaito — APPROVED** [review]

**Review by technolojin — APPROVED** [review]
LGTM

**Pull request merged**
