### PR TITLE
refactor(behavior_velocity_traffic_light_module): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR adds the `autoware_` prefix to the package and puts headers in the `autoware` namespace.

Part of:
- https://github.com/autowarefoundation/autoware/issues/4569

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by rej55 — COMMENTED** [review]
@esteve 
Thank you for your work!
Regarding to this PR, it is necessary to handle the conflicts. 
Could you resolve the conflicts, please?
https://github.com/autowarefoundation/autoware.universe/pull/7314

**Comment by esteve** [comment]
@rej55 I've fixed the conflicts. Could you have a look at the changes when you have a moment? Thanks.

**Review by rej55 — APPROVED** [review]
LGTM

**Review by kyoichi-sugahara — APPROVED** [review]

**Comment by esteve** [comment]
@satoshi-ota @shmpwk @soblin @tkimura4 could please either of you have a look at this PR when you have a moment? Thanks :slightly_smiling_face:

**Review by shmpwk — APPROVED** [review]

**Comment by esteve** [comment]
@shmpwk thanks! :slightly_smiling_face:

**Pull request merged**
