### PR TITLE
fix: use hazard in auto command when emergency_handling is false

### PR DESCRIPTION
**Pull request by tkimura4**
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>

## Description(required)

Fix porting miss in vehicle_cmd_gate.
https://github.com/tier4/AutowareArchitectureProposal.iv/blob/main/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp#L309-310

When `use_emergency_handling` is false, use the auto_commands for hazard_light

## Review Procedure(required)
Set `use_emergency_handling` to false in control.launch.py
Launch planning simulator, and start to run the vehicle.
Transition the vehicle state to Emergency in some way, and confirm that the hazard lights  are not enabled.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [x] Documentation with description of the package is available
- [x] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
If use_emergency_handling is false, does this mean that the hazard lights will turn on according to emergency stop even when emergency stop is not working?

**Comment by tkimura4** [comment]
@yukkysaito 
Currently, yes. I fixed it on this PR.

**Review by yukkysaito — DISMISSED** [review]
@tkimura4 Ok :+1: pls fix PR title

**Comment by tkimura4** [comment]
@yukkysaito 
I changed title and commit message. 
Please approve one more.

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
