### PR TITLE
feat(diagnostic_graph_aggregator): implement diagnostic graph dump functionality

### PR DESCRIPTION
**Pull request by youtalk**
## Description

This PR contains the differences from the [v0.38.0 tag of tier4/autoware.universe](https://github.com/tier4/autoware.universe/tree/v0.38.0) to the [main branch of awf/autoware.universe](https://github.com/autowarefoundation/autoware.universe), excluding changes to `.github` directory.

https://github.com/autowarefoundation/autoware.universe/compare/main...tier4:autoware.universe:v0.38.0

This PR is the first step in implementing changes based on https://github.com/orgs/autowarefoundation/discussions/5292. Next, I plan to update the versions in package.xml on the main branch of awf/autoware.universe.

## Related links

https://github.com/orgs/autowarefoundation/discussions/5292

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

___

### **PR Type**
enhancement

___

### **Description**
- Introduced a new script `dump.py` to the `diagnostic_graph_aggregator` system for handling diagnostic graphs.
- The script includes functionality to print diagnostic data in a formatted table.
- Implemented a ROS2 node `DumpNode` that subscribes to the `DiagnosticGraph` topic and processes incoming messages.
- Added command-line argument parsing to allow specification of the diagnostic topic.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>dump.py</strong><dd><code>Add diagnostic graph dumping script with table output</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

system/diagnostic_graph_aggregator/script/dump.py

<li>Added a new Python script <code>dump.py</code> for diagnostic graph aggregation.<br> <li> Implemented a function to print diagnostic data in a table format.<br> <li> Introduced a <code>DumpNode</code> class to subscribe to diagnostic graph messages.<br> <li> Included command-line argument parsing for topic specification.<br>

</details>

  </td>
  <td><a href="https://github.com/autowarefoundation/autoware.universe/pull/9261/files#diff-892539d9e9f89921f060fe0e32c593ac08d9c81d7ab0fcc1b390dd9bd3b65f8d">+94/-0</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by xmfcx** [comment]
/ask Could you propose 3 different titles for this pr? Should follow conventional commit guidelines. Similar to `feat(system): bla bla`

**Comment by xmfcx** [comment]
@youtalk -san, could we rename the title of this PR to `feat(diagnostic_graph_aggregator): implement diagnostic graph dump functionality`? The reason might be to have version control but the PR is still a normal PR.

**Comment by youtalk** [comment]
@xmfcx I've changed the commits to remain the tier4 commit history and changed the title. 
We need to merge this PR by a merge commit not a squash merge.

**Comment by xmfcx** [comment]
> We need to merge this PR by a merge commit not a squash merge.

Why though?
This PR only adds a single file. Why would we have to do a merge commit?
Why not just make this a normal squash commit?

If we do a merge commit, it will ruin the linear history that we've built up over years.

image

will turn into this:

image

I don't want to allow this, it will make tracking history harder.
cc. @mitsudome-r

**Comment by youtalk** [comment]
@xmfcx `Rebase and merge` is also OK if you prefer the linear commit history. We need to remain the changes that the only `tier4/autoware.autoware` has.

**Comment by youtalk** [comment]
Alternatively, to proceed faster, we could start with a `squash merge` and switch to `merge commits` or `rebase merges` only if issues arise in the commit history. So please proceed with the review.

**Comment by mitsudome-r** [comment]
@youtalk We can't do a merge commit history with 543 commits unless fair reasons is provided. Making TIER IV easier to release is not good enough.

**Comment by youtalk** [comment]
@mitsudome-r I got it. Please review this and use a `squash merge`.

**Comment by xmfcx** [comment]
@youtalk -san, is it ok if I apply `feat(diagnostic_graph_aggregator): implement diagnostic graph dump functionality` title as I merge it?

**Review by xmfcx — APPROVED** [review]

**Comment by xmfcx** [comment]
image

Something's up with the DCO in this PR, will investigate.

**Comment by xmfcx** [comment]
Maybe 543 commits has confused it. I'll temporarily bypass it.

**Comment by xmfcx** [comment]
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/6427

Not sure when it was removed.

**Pull request merged**
