### PR TITLE
fix(obstacle_stop_planner): fix the issues when use_predicted_objects true

### PR DESCRIPTION
**Pull request by brkay54**
## Description

In obstacle_stop_planner, use_predicted_object option was added but it does not work as we wanted. Firstly, there are some bugs while checking the obstacle. For example, it uses the last collision footprint to set collision point.

Screenshot from 2023-04-26 23-54-30

Also, it checks only intersected points while checking collision, however, corner points also need to be checked.

Screenshot from 2023-04-15 18-01-36

Also I needed make some changes in adaptive_cruise_planner while using predicted objects, because perception side is estimating obstacle velocity, adaptive_cruise_control does not need to estimate the velocity.

## Tests performed

For Z-Axis-Filtering: 

Screenshot from 2023-04-26 09-38-13

Stop test: 

https://user-images.githubusercontent.com/45468306/234703822-f77bb994-44c5-4cea-91b1-fb4b973e74b0.mp4

Vehicle following:

https://user-images.githubusercontent.com/45468306/234703863-45086564-16a7-4bf9-82fb-0c5840198111.mp4

Slow-down:

https://user-images.githubusercontent.com/45468306/234703885-1a831ab6-36a1-434f-bb34-e3e90ddc2538.mp4

## Effects on system behavior

There is no effect for system behavior, all things working as we wanted.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by brkay54** [comment]
@satoshi-ota @shmpwk @taikitanaka3 @tkimura4 also if it is not problem, I want to add myself as maintainer. I want to maintain this package.

**Comment by satoshi-ota** [comment]
> @satoshi-ota @shmpwk @taikitanaka3 @tkimura4 also if it is not problem, I want to add myself as maintainer. I want to maintain this package.

@brkay54 OK. We TIER IV are glad you are maintaining this package. Then, please add your name in package.xml like that. I think it is better to create other PR for adding maintainer. I'll approve quickly if you done.

https://github.com/autowarefoundation/autoware.universe/blob/e7f8c1258afb559f5be6b3fe8110ca90db74ca0c/planning/obstacle_stop_planner/package.xml#L8

**Comment by brkay54** [comment]
Thank you @satoshi-ota . I created PR for this: https://github.com/autowarefoundation/autoware.universe/pull/3559

**Comment by satoshi-ota** [comment]
@brkay54 I ran action and updated code owner in https://github.com/autowarefoundation/autoware.universe/pull/3557.

**Comment by satoshi-ota** [comment]
@brkay54 Sorry for late response. I would like to check this PR by scenario tests. Is this PR ready for review?

**Comment by brkay54** [comment]
@satoshi-ota Yes all of the PRs ready for review. 

FYI: Merge order should be like this:
* https://github.com/autowarefoundation/autoware.universe/pull/3556
* https://github.com/autowarefoundation/autoware.universe/pull/3558
* https://github.com/autowarefoundation/autoware.universe/pull/3560

**Comment by satoshi-ota** [comment]
Scenarios test is running now...
Please wait a while.

**Review by satoshi-ota — APPROVED** [review]
LGTM

**Comment by brkay54** [comment]
@satoshi-ota Thank you for your review 🙏🏼 . Other PRs are rebased.

**Comment by takayuki5168** [comment]
@brkay54 cc @mehmetdogru 

We have a new obstacle_cruise_planner package to stop/cruise/slow down against predicted objects.
https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_cruise_planner/

We TIER IV will replace the obstacle_stop_planner with the obstacle_cruise_planner for the stop/cruise/slow down planner. 
I heard that Ota-kun introduced this package to you, but do you have any reason not to use the obstacle_cruise_planner?

**Comment by brkay54** [comment]
Hi, @takayuki5168 we are also planning to switch to obstacle_cruise_planner but currently using obstacle_stop_planner because the last time I asked in Discord, @mitsudome-r said it is only used in R&D vehicles to be tested. 

While testing the obstacle_stop_planner, we saw some bugs and fixed those. After testing the latest obstacle_stop_planner enough, we will also switch to obstacle_cruise_planner. Thank you for your recommendation! 🙏🏼

**Comment by satoshi-ota** [comment]
Hi @brkay54 
I found that you are **NOT** registered as CODEOWNER correctly.

Github says:

> Unknown owner on line 51: make sure a user with the email address berkay@leodrive.ai exists and has write access to the repository

in [this](https://github.com/autowarefoundation/autoware.universe/blob/cf4e9ba411ce35886df81de7ca1c5bde534d04e4/.github/CODEOWNERS#LL135C43-L135C43) file.

Have you registered your company email address with github? If you haven't, could you register it? (Or fix address in package.xml.)

**Comment by brkay54** [comment]
@satoshi-ota Thank you for informing me! Sorry for that. I added the mail address as a secondary address. Can you check it again, please?

**Pull request merged**
