### PR TITLE
feat(base_interface): add base_interface package

### PR DESCRIPTION
**Pull request by HaoruXue**
Signed-off-by: Haoru Xue haoru.xue@autoware.org

## Description

Adds `base_interface` package to Autoware.Universe

## Related links

https://github.com/autowarefoundation/autoware.universe/issues/1451

## Tests performed

New tests are included in this package.

## Notes for reviewers

According to the [architecture design](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/vehicle-interface/), Autoware is missing an `ActuationStatus` message as a feedback back to control modules, which may need further discussion on.

`StationaryLockingCommand`, if still needed, may be missing a corresponding `StationaryLockingReport`.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by HaoruXue** [comment]
As discussed with @mitsudome-r the package is renamed to `base_interface` to avoid any confusion with existing vehicle interfaces

**Comment by brkay54** [comment]
Sorry I couldn't review this PR because I was busy with other works. And, I can not review for next 2 week because I am going to take annual leave.

**Comment by brkay54** [comment]
Hello again, It seems that I am not going to available this month because of vehicle tests. So, I won't be able to review this PR. I am sorry for that.

**Comment by mitsudome-r** [comment]
@Sharrrrk @brkay54 I'm planning to finish review this week. Would you like to take a look before I merge it after the review?

**Comment by mitsudome-r** [comment]
Since there were no action for long time, I'm closing the PR.
We can reopen it if we need the feature again.

**Pull request closed without merging**
