### PR TITLE
docs(autoware_multi_object_tracker): add default values on the schema json

### PR DESCRIPTION
**Pull request by tby-udel**
## Description
Fixing the #7333 issue of the `multi_object_tracker` package.

 * Added the default values to 2 schema files.

## Tests performed
Package built and launched locally.

## Notes for reviewers
 Nothing inside the src code part was changed, only updating schema file.

## Interface changes
Parameter values are now required to be passed to the node when launched.

## Effects on system behavior
None

## Pre-review checklist for the PR author
The PR author **must** check the checkboxes below when creating the PR.

 * [x]  I've confirmed the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
 * [x]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

 ## In-review checklist for the PR reviewers
 The PR reviewers **must** check the checkboxes below before approval.

 * [ ]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
 * [ ]  The PR has been properly tested.
 * [ ]  The PR has been reviewed by the code owners.
 
 ## Post-review checklist for the PR author
 The PR author **must** check the checkboxes below before merging.
 
 * [ ]  There are no open discussions or they are tracked via tickets.
 * [ ]  The PR is ready for merge.
 
 After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by tby-udel** [comment]
@technolojin I think this is caused by some parameters in schema files are lack of certain default values, I have updated the schema files. On github, it says that this branch has conflicting files "perception/multi_object_tracker/README.md", but I can't see any conflicts after I updated my local branch and merged main into this branch.

**Comment by technolojin** [comment]
@tby-udel 
I think it is better to rebase to the latest main.

**Comment by technolojin** [comment]
@tby-udel 
Thank you for your additional work. 

We had to rename all the package names to have prefix `autoware_`, and the works are done. 
I am sorry for late response and confusing changes.

Your current branch contains 212 commits and those are by merging the main to your branch.
Therefore, I suggest to rebase your commits to the latest main branch, to that the PR contains only your changes.

**Review by technolojin — APPROVED** [review]
LGTM

**Pull request merged**
