### PR TITLE
feat(behavior_path_planner): use akima spline for xy only first

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

Applied akima spline for xy only first when getting centerline from lanelet.

**TODO**
- [x] add a figure to compare when enabling and disabling akima spline.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@takayuki5168 would you make a PR for launcher?

**Comment by TakaHoribe** [comment]
No large behavior change found, but looks ok.

**Cubic**
image

image



image


**Akima**

image

image


image

**Review by TakaHoribe — APPROVED** [review]

**Comment by tkimura4** [comment]
@takayuki5168 
Is it ready to merge?

**Comment by takayuki5168** [comment]
@tkimura4 It seems I have to make a PR to awf/autoware_launch.
Do you wanna use this PR's function? I'm just curious about the reason you asked.

**Comment by tkimura4** [comment]
@takayuki5168 
It is just a part of repository maintenance.
I have not checked the contents of the PR.

**Pull request merged**
