### PR TITLE
refactor(geography_utils): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — COMMENTED** [review]
Thank you very much. I have one question.

According to [the documentation](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/), the recommended directory structure is `autoware_{name}/include/autoware/{name}`, but in this pull request, it seems to be `autoware_geography_utils/include/autoware_geography_utils`. Is this intentional?

**Review by isamu-takagi — APPROVED** [review]
LGTM (default_ad_api package)

**Comment by esteve** [comment]
@SakodaShintaro thanks for pointing that out, working on it.

**Comment by esteve** [comment]
@SakodaShintaro fixed in 837df86013c09a5ab8c866c375944f5a3917725e

**Review by SakodaShintaro — APPROVED** [review]
Thank you for the correction.
I have confirmed that logging_simulator works well.
LGTM (under /localization and /map)

**Comment by esteve** [comment]
@xmfcx could you have a look at this PR when you have a moment? It's been sitting in the PR queue for two weeks. Thanks.

**Comment by esteve** [comment]
@mitsudome-r @youtalk could you have a look at this PR when you have a moment? It's been in the queue for over month and a half. Thanks.

**Comment by youtalk** [comment]
We need approval from @kminoda, @kosuke55 and @takayuki5168 but they might be in summer vacation.

**Review by kminoda — APPROVED** [review]
LGTM

**Pull request merged**
