### PR TITLE
build(yabloc_pose_initializer): remove downloading logic from CMake

### PR DESCRIPTION
**Pull request by lexavtanke**
## Description

See https://github.com/autowarefoundation/autoware.universe/issues/3137

According to discussion above remove downloading logic from building stage. For now it will be possible to download model files either by ansible or manually as explained in this [PR](https://github.com/autowarefoundation/autoware-documentation/pull/345)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by esteve — COMMENTED** [review]
@lexavtanke changes look good, thanks. Not sure if this PR is ready for review. Just some feedback, could you update the title and the commit message so that they follow the Autoware conventions? That is, "build(yabloc_pose_initializer): remove downloading logic from CMake" Thanks.

**Comment by esteve** [comment]
@lexavtanke is this PR now ready for review?

**Comment by lexavtanke** [comment]
@esteve Yes it is ready, but it should be merged after [3855](https://github.com/autowarefoundation/autoware/pull/3855) in autoware. As artifacts for yabloc should be extracted before usage. 
So I keep it draft for now.

**Comment by esteve** [comment]
@KYabuuchi @Motsu-san could you have a look at this PR when you have a moment? Thanks.

**Comment by KYabuuchi** [comment]
@lexavtanke Thank you for creating the PR.
There are two other files that explain the old download instructions, so please fix those as well. :pray:
Please remove or update the text outlined in red below.

* `README.md`
image

* `src/camera/semantic_segmentation.cpp`
image

**Comment by lexavtanke** [comment]
@KYabuuchi Thank you for your feedback. I've made updates to these files. Can you please review the PR then you will have time?

**Review by KYabuuchi — APPROVED** [review]
Thank you for adding clear download instructions. This PR looks good to me :+1:

**Pull request merged**
