### PR TITLE
refactor(euclidean clustering): read parameters from autoware_launch

### PR DESCRIPTION
**Pull request by ismetatabay**
## Description
This PR refactors the euclidean_cluster package for read parameters from autoware_launch config file. 
autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/445
Releated: #4250
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ismetatabay** [comment]
@yukkysaito can you check universe PR as well :+1: ?

**Comment by yukkysaito** [comment]
@ismetatabay 
Thank you :+1: LGTM
@badai-nguyen Please double check:pray:

**Comment by badai-nguyen** [comment]
@ismetatabay Thank you for your PR. I confirmed it works and reflects parameters from autoware_launch. 
It would be nice if you could also update the param file path in [euclidean_cluster/launch/euclidean_cluster.launch.py](https://github.com/autowarefoundation/autoware.universe/blob/e282c4fe9b6acb6c98874665b2277375f0a6a70b/perception/euclidean_cluster/launch/euclidean_cluster.launch.py#L135-L142)https://github.com/autowarefoundation/autoware.universe/blob/e282c4fe9b6acb6c98874665b2277375f0a6a70b/perception/euclidean_cluster/launch/euclidean_cluster.launch.py#L135-L142

**Comment by ismetatabay** [comment]
@yukkysaito @badai-nguyen Hi, I forgot it sorry :+1: , I updated euclidean_cluster.launch.py

**Review by badai-nguyen — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
