### PR TITLE
docs(traffic_light_ssd_fine_detector): add document for training model with mmdetection

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

Add document to apply ML model trained with [open-mmlab/mmdetection](https://github.com/open-mmlab/mmdetection).
This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/3485

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ktro2828** [comment]
@wep21 I created PR for the detail to train SSD with mmdetection. Please check it whenever it's convenence:pray:

**Comment by wep21** [comment]
@ktro2828 It might be better to specify mmdet version because the following points have been changed from 2.x to 3.x.
- `resume-from` is changed to `resume`.
- `pytorch2onnx.py` is removed from deployment directory.

**Comment by ktro2828** [comment]
@wep21 You're right, thank you! Added our tested version information by https://github.com/autowarefoundation/autoware.universe/pull/3538/commits/600288d859b5d9d3cf59d7fbccc054e6dfaa5fd9

**Review by wep21 — APPROVED** [review]
LGTM👍

**Pull request merged**
