### PR TITLE
build: add missing build dependency

### PR DESCRIPTION
**Pull request by jspricke**
## Description

See https://github.com/autowarefoundation/autoware/issues/3222

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@jspricke thanks, I've triggered the CI to make sure the PR is correct.

**Comment by jspricke** [comment]
Failing build without this: https://github.com/jspricke/autoware_packages/actions/runs/3986476130
Successful build with this: https://github.com/jspricke/autoware_packages/actions/runs/3986552483 (check the raw logs as long as it is running)

The failing CI job seems unrelated.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by ito-san — APPROVED** [review]

**Review by kenji-miyake — APPROVED** [review]

**Comment by esteve** [comment]
@jspricke thanks for your contribution, I'm tasked with working on generating Debian packages (hence the PRs to your repostory), so I'll take it from here. I might have to close this PR and break it into smaller PRs because we require package maintainers to approve the changes, and the list in this PR is growing quickly.

**Comment by jspricke** [comment]
@esteve sure feel free to rework this, feel free to ask again if you get stuck. I'm really happy that you try to use the action and sorry for being strict with how it works but I have enough experience with build farms to know that you need to be strict with their interfaces to make it work for everyone.

**Comment by jspricke** [comment]
@esteve also, as there are a lot of packages in the repo, @v4hn is working on a action that chains multiple builds: https://github.com/v4hn/ros-o-builder/actions/runs/3990975152
Currently it is rather specific to ROS one, tough.

**Comment by esteve** [comment]
> @esteve sure feel free to rework this, feel free to ask again if you get stuck. I'm really happy that you try to use the action and sorry for being strict with how it works but I have enough experience with build farms to know that you need to be strict with their interfaces to make it work for everyone.

@jspricke no worries, I understand, I've been doing open source for over 20 years and sometimes you just need to be more strict with the contributions you accept. And I get what you say about build farms, I became quite familiar with the ROS build farm when I was at OSRF, that's why I insisted on correctness about the `exec_depend` tag, even if it seemed to fixed the issue :slightly_smiling_face:

**Comment by esteve** [comment]
> @esteve also, as there are a lot of packages in the repo, @v4hn is working on a action that chains multiple builds: https://github.com/v4hn/ros-o-builder/actions/runs/3990975152
> Currently it is rather specific to ROS one, tough.

@jspricke that's really cool, let us know if there's something we can help with

**Comment by jspricke** [comment]
> @jspricke no worries, I understand, I've been doing open source for over 20 years and sometimes you just need to be more strict with the contributions you accept. And I get what you say about build farms, I became quite familiar with the ROS build farm when I was at OSRF,

Ha, part of this is honestly to fix things from back when I was at Willow ;).

> that's why I insisted on correctness about the `exec_depend` tag, even if it seemed to fixed the issue slightly_smiling_face

Sure, though bloom does not distinguish the difference and neither Debian and I'm not aware of any build system that does.

**Comment by esteve** [comment]
> Ha, part of this is honestly to fix things from back when I was at Willow ;).

Cool story ;-)

> Sure, though bloom does not distinguish the difference and neither Debian and I'm not aware of any build system that does.

My memory is a bit blurry, I'd say OpenEmbedded/Yocto/Bitbake do differentiate, but I can't remember well and anyway that's not the point of this PR. Also, Debian uses Build-Depends and Depends, but bloom probably does not care about that. In any case, the `exec/build/buildtool` difference makes sense when you're crosscompiling, but again, let's not delve too much into that, that's not the point :-)

**Comment by jspricke** [comment]
> My memory is a bit blurry, I'd say OpenEmbedded/Yocto/Bitbake do differentiate, but I can't remember well and anyway that's not the point of this PR. Also, Debian uses Build-Depends and Depends, but bloom probably does not care about that. In any case, the `exec/build/buildtool` difference makes sense when you're crosscompiling, but again, let's not delve too much into that, that's not the point :-)

bloom does differentiate for (Build-)Depends, that's usually build_depend and exec_depend (or run_depend in old versions). Use the bloom packages for cross compiling in Debian would be nice but would need quiet some work on the ROS side..

**Comment by v4hn** [comment]
> > @esteve also, as there are a lot of packages in the repo, @v4hn is working on a action that chains multiple builds: https://github.com/v4hn/ros-o-builder/actions/runs/3990975152
> > Currently it is rather specific to ROS one, tough.
> 
> @jspricke that's really cool, let us know if there's something we can help with

I'll try to finalize my work on that repository soon to move it to the ros-o organization and aim to get all support it needs back into @jspricke's action.
After that, major requirements from my side for the future are
1. only update package versions if the contents changed. Jochen proposed to check this via reproducible builds and byte-identity of the contents.
2. Running all package tests. This is entlüften disabled. 
3. Support for parallel jobs. My setup currently uses only sequential builds. I don't want a single job per package, but 2-5 manually split jobs to build leaf/twig packages in different repos files would be great.

**Review by xmfcx — APPROVED** [review]

**Pull request closed without merging**
