### PR TITLE
feat(lane_departure_checker): include neighbor lanelets as optional

### PR DESCRIPTION
**Pull request by brkay54**
Signed-off-by: Berkay Karaman <brkay54@gmail.com>

## Description

In current implementation, `lane_departure_checker` is only checking the vehicle's current lane. However, in some conditions, vehicle can be driven in other lanes. For example, because bus is large vehicle, it can not fit in lanes especially in sharp turns and `lane_departure_checker` publishes emergency then make vehicle stop. But, user should define the borders of drivable area for `lane_departure_checker`. To do this, I added some options about which lanes should be included to drivable area borders.

## Notes for reviewers

cc. @kyoichi-sugahara 
It is little urgent change, we need to merge this before BusODD.
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mehmetdogru** [comment]
@brkay54 please create another PR in autoware_launch repo for the changes you made in` lane_departure_checker.param.yaml` file

**Comment by kyoichi-sugahara** [comment]
@brkay54 
sorry for late check.
Applied the parameters below and checked lane_departure checker doesn't output emergency.
`include_right_lanes = true`
`include_opposite_lanes = true`

So could you prepare config file in autoware_launch repo?
Then I will approve this PR.

Screenshot from 2023-02-09 18-22-06

**Comment by brkay54** [comment]
@kyoichi-sugahara I am appreciated for your review. I created PR for autoware_launch: https://github.com/autowarefoundation/autoware_launch/pull/217

**Comment by kyoichi-sugahara** [comment]
@kosuke55 
With this implementation, shoulder lane is not included in the neighbor lanelets. Shoulder lane will be added to routing_graph in near future?

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM

**Pull request merged**
