### PR TITLE
refactor(heatmap_visualizer): add JSON Schema and remove default value definition

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

- Add ROS node configuration with JSON Schema as discussed in https://github.com/orgs/autowarefoundation/discussions/3371
- Remove default parameter specified in `declare_parameter()`

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ktro2828** [comment]
@miursh Could you approve this PR because there is no reviewers:pray:

**Review by miursh — COMMENTED** [review]
@ktro2828 
Could you updatge Core Parameters written in README as well?

**Comment by ktro2828** [comment]
> @ktro2828 Could you update Core Parameters written in README as well?

@miursh I updated in https://github.com/autowarefoundation/autoware.universe/pull/4901/commits/1991d219b16d02f32e6e1436a7a75713600570d9

**Review by miursh — COMMENTED** [review]
Need to add `config` to here

**Comment by ktro2828** [comment]
@miursh Sorry for I forgot to update CMakeLists.txt. I updated in https://github.com/autowarefoundation/autoware.universe/pull/4901/commits/3a6d4d6973b24e215ce118f7293f919e6c2a786f

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
