### PR TITLE
refactor(autoware_lidar_transfusion): split config

### PR DESCRIPTION
**Pull request by amadeuszsz**
## Description

This PR split `autoware_lidar_transfusion` parameter file for two configs:
* Parameters strictly related to deployed model.
* Parameters related to runtime behavior.

The same approach is applied in `autoware_lidar_centerpoint` package.

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware_launch/pull/1093
- https://github.com/autowarefoundation/autoware/pull/5036

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by amadeuszsz** [comment]
@kminoda @knzo25 
`json-schema-check` fails due to same file name prefix [here](https://github.com/autowarefoundation/autoware-github-actions/blob/main/json-schema-check/validate_json_schemas.py#L17).
Unfortunately, we can't remove asterisk from `{base_name}*.param.yaml` in CI because this convention is widely used among Autoware packages to apply schema file on multiple param files. We can:
* Change file name convention from `<MODEL>_ml_package.param.yaml` to `ml_package_<MODEL>.param.yaml`.  We will need to change deployment path and launch files for transfusion, centerpoint and pointpainting.
* Bypass this test by file extension thus don't check this config in CI as it is now in centerpoint.

I would go for change naming convention if I didn't miss any drawback. If you have no objection, I will apply this for centerpoint and pointpainting as well.

**Comment by kminoda** [comment]
@amadeuszsz Thanks for the proposal :pray: 
However, I don't think it is a good idea to rename the parameter file name, as they are already widely used both in Autoware and Pilot.Auto / Web.Auto, and changing those file names would take a bit of time. 

So I would say it's better to consider a workaround.

**Comment by knzo25** [comment]
@amadeuszsz 
In centerpoint we face similar concerns, and as a workaround (https://github.com/autowarefoundation/autoware.universe/pull/7421) we are considering calling the vanilla model `centerpoint_base`, which sounds awful, but is compatible with the schema.
I agree with your name change, but also understand that the change would affect several places, so it would time...

**Comment by amadeuszsz** [comment]
> @amadeuszsz In centerpoint we face similar concerns, and as a workaround (#7421) we are considering calling the vanilla model `centerpoint_base`, which sounds awful, but is compatible with the schema. I agree with your name change, but also understand that the change would affect several places, so it would time...

I'm not a big fan of this. It will require few copies of same schema files and still affects many places due to file renaming, as you said. 

We could restructure design for both packages to:
```
|-config
|----|-ml_package.param.yaml
|----|-ml_package_tiny.param.yaml
|----|-ml_package_sigma.param.yaml
|----|-centerpoint.param.yaml
|----|-centerpoint_tiny.param.yaml
|----|-centerpoint_sigma.param.yaml
|----|-detection_class_remapper.param.yaml
|
|-schema
|----|-ml_package.schema.json
|----|-centerpoint.schema.json
|----|-detection_class_remapper.schema.json
``` 

At the same time we can keep old configs on cloud server to let people pull files if they didn't update repository.

**Comment by knzo25** [comment]
Update: we decided to skip the problematic schemas in the meantime, so this PR can be merged

**Review by knzo25 — APPROVED** [review]
LGTM

**Review by YoshiRi — APPROVED** [review]
LGTM

**Pull request merged**
