### PR TITLE
fix(simple_planning_simulator): fix param file levels

### PR DESCRIPTION
**Pull request by HaoruXue**
Signed-off-by: Haoru Xue <haoru.xue@autoware.org>

## Description

Fix a bug in `simple_planning_simulator` where the parameters in the param files are not correctly loaded into the node. The issue was not previously apparent because every parameter has a default value.

How to replicate:

1. In `simple_planning_simulator_core.cpp`,  remove a default value in a paramter declaration, for example, `vehicle_model_type`
2. The launch will now throw a parameter not set exception: `ros2 launch simple_planning_simulator simple_planning_simulator.launch.py  initial_engage_state:=true`

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
LGTM.

@TakaHoribe @yukkysaito Could you approve this PR.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by yukkysaito** [comment]
@TakaHoribe Pls double check

**Review by TakaHoribe — APPROVED** [review]
Confirmed it worked with 
```
ros2 launch simple_planning_simulator simple_planning_simulator.launch.py initial_engage_state:=false
```

LGTM. Thank you!

**Pull request merged**
