### PR TITLE
fix(dummy_perception_publisher): fix clang-diagnostic-unused-private-field

### PR DESCRIPTION
**Pull request by veqcc**
## Description

Fixed `clang-diagnostic-unused-private-field` error
```
simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp:127:8: error: private field 'use_real_param_' is not used [clang-diagnostic-unused-private-field]
  bool use_real_param_;
       ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by veqcc** [comment]
@yukkysaito 
Hi

**Comment by veqcc** [comment]
@yukkysaito
Hi

**Comment by veqcc** [comment]
@yukkysaito
This is final reminder.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
