### PR TITLE
fix(diagnostic_graph_aggregator): fix uselessOverride warning

### PR DESCRIPTION
**Pull request by veqcc**
## Description

This is a fix based on cppcheck `uselessOverride` warning

```
system/diagnostic_graph_aggregator/src/common/graph/units.hpp:142:8: style: The function 'update_status' overrides a function in a base class but is identical to the overridden function [uselessOverride]
  void update_status() override;
       ^
system/diagnostic_graph_aggregator/src/common/graph/units.hpp:132:8: note: Virtual function in base class
  void update_status() override;
       ^
system/diagnostic_graph_aggregator/src/common/graph/units.hpp:142:8: note: Function in derived class
  void update_status() override;
       ^
```

Though the program is totally the same, I found a TODO comment `// TODO(Takagi, Isamu): update link flags.`.
If you do not want to delete it, please come up with some workarounds!

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@veqcc As noted in the TODO comments, this will be processed differently in the future. So this is intentional, can I disable the check on a code block?

**Comment by veqcc** [comment]
@isamu-takagi 
Thank you for your quick response.

> As noted in the TODO comments, this will be processed differently in the future. So this is intentional, can I disable the check on a code block?

OK, then I will restore the code block and use inline cppcheck suppression (I'll do it tomorrow).
Btw, do you know when the TODO comment will be resolved?

**Comment by veqcc** [comment]
@isamu-takagi 
Could you wait till the cppcheck-differential workflow is updated sp that PRs which changes only .hpp or .cpp can avoid false positive or false negative results?

Related Link (TIER IV internal): https://star4.slack.com/archives/C070FQMREVB/p1719877783942809

**Comment by veqcc** [comment]
@isamu-takagi 
Now it's ready for being merged!

**Comment by isamu-takagi** [comment]
>Btw, do you know when the TODO comment will be resolved?

It's not decided yet. I'll update this if I need more detailed diagnostics after using graph.

**Review by isamu-takagi — APPROVED** [review]
Thank you. LGTM

**Pull request merged**
