### PR TITLE
feat(behavior_path_planner): add avoid_margin for over distance case

### PR DESCRIPTION
**Pull request by beyzanurkaya**
Signed-off-by: beyza <bnk@leodrive.ai>

## Description

Fixes: #2197

Before PR:

Untitled Diagram drawio (4)

After PR:

Untitled Diagram drawio (3)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by beyzanurkaya** [comment]
waiting for review :)

**Comment by mitsudome-r** [comment]
ping @takayuki5168

**Comment by satoshi-ota** [comment]
@beyzanurkaya @mitsudome-r @takayuki5168 Thanks for your contribute. I'll review in this week.

**Comment by satoshi-ota** [comment]
@beyzanurkaya Thanks for your PR :smile: 

I assume that this PR modification will let the avoidance module generate an unpassable avoidance path due to insufficient lateral margin. Could you please tell me about the benefits of this PR? You want avoidance module to generate an avoidance path even if it is insufficient for the lateral margin defined by the parameter?

**Comment by xmfcx** [comment]
@mehmetdogru will share more details on this issue/PR.

**Comment by mehmetdogru** [comment]
@satoshi-ota 

Sorry for not being clear enough and of course in the suggested way some avoidance path would have insufficient clearance for the ego. So let me explain the issue we are having with the current implementation first then I will shortly present my new proposal. 

So in avoidance module there are two margin params ([lateral_collision_margin](https://github.com/autowarefoundation/autoware.universe/blob/11ff8ef6cd915275c189a9301956f05a1aa2772c/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml#L19) & [lateral_collision_safety_buffer](https://github.com/autowarefoundation/autoware.universe/blob/11ff8ef6cd915275c189a9301956f05a1aa2772c/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml#L20)) added to vehicle_width/2 to calculate `avoid_margin`. They are of course the same for all the lanes and roads regardless of how wide or narrow they are. In cases where there are both wide and narrow roads such as in campuses things are getting tricky.  

We know that:

```cpp
avoid_margin = lat_collision_safety_buffer + lat_collision_margin + 0.5 * vehicle_width;
```

---

In **case 1** I tune my parameters for narrow roads:

So I keep lat_collision_margin, lat_collision_safety_buffer and road_shoulder_safety_margin as small as possible. However for wide roads I want ego to shift more since there are plenty of space on the lane but I tuned the params for narrow road so it is not possible:

avoid_margin_1

---

In **case 2** I tune my parameters for wide roads:

I set params above as I think is proper for the safety and comfort then for narrow roads ego wouldn't do the avoidance:

avoid_margin_2

---

My proposal is that instead of keeping avoid_margin stable (at_collision_safety_buffer + lat_collision_margin + 0.5 * vehicle_width), we can let it vary between `max_allowable_lateral_distance` and `min_safety_lateral_distance`. 

`max_allowable_lateral_distance` already exists:

```cpp
max_allowable_lateral_distance = o.to_road_shoulder_distance - road_shoulder_safety_margin - 0.5 * vehicle_width
```

And lets define  `min_safety_lateral_distance` as:

```cpp
min_safety_lateral_distance = lat_collision_safety_buffer + 0.5 * vehicle_width
```

So I think in the current implementation `lat_collision_margin` and `lat_collision_safety_buffer` does the same job since just summation of these two is used. With the approach I am proposing we can set min & max margin using `lat_collision_margin` and  `lat_collision_safety_buffer` then let avoid_margin vary between them. In this case for the both scenarios above, ego would do the avoidance as user wanted.

@satoshi-ota to please review the proposed changes in the PR.

**Comment by satoshi-ota** [comment]
@mehmetdogru @beyzanurkaya Thank you. They are clear to me.

I was concerned that even if it was a shift point that could not be passed, an avoidance path would be generated and the vehicle would follow it. Now, I understand that what you want to do by your explanation and [this commit](https://github.com/autowarefoundation/autoware.universe/pull/2198/commits/cbaab34e03463608d027d37271f0f4b109265980) :+1: 

I think your method looks good to me.

**Comment by mehmetdogru** [comment]
@satoshi-ota 

Shall we go ahead and merge these changes? Are you ok with them?

**Comment by satoshi-ota** [comment]
@beyzanurkaya @mehmetdogru Could you update avoidance documentation in another PR?

**Pull request merged**
