### PR TITLE
feat(ci): update `autoware`'s image tag

### PR DESCRIPTION
**Pull request by youtalk**
## Description

- [x] https://github.com/autowarefoundation/autoware/pull/4961

This PR updates the tag names of the docker images used in the GitHub Actions workflow, based on corrections from the PR https://github.com/autowarefoundation/autoware/pull/4961.

## Related links

https://github.com/orgs/autowarefoundation/discussions/4661#discussioncomment-9995806

## How was this PR tested?

https://github.com/autowarefoundation/autoware.universe/actions/runs/10054982444?pr=7952

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by youtalk** [comment]
https://github.com/autowarefoundation/autoware/pull/4961#issuecomment-2219615243
> It seems like some of the workflows in Autoware.Universe uses prebuilt image. If we are removing them, we should update Autoware.Universe CIs to use devel environment instead. https://github.com/autowarefoundation/autoware.universe/blob/ea0276acd134a75bc0227aeeb96266c26db7100e/.github/workflows/build-and-test-differential.yaml#L36

@mitsudome-r This PR resolves the problem.

**Comment by youtalk** [comment]
`build-and-test-differential / build-and-test-differential (humble, -cuda)` was failed. I need to fix it.

**Comment by youtalk** [comment]
`build-and-test-differential` was succeeded by using the multi-arch image https://github.com/autowarefoundation/autoware.universe/pull/7952/commits/c81e99432ca4654670e81194e3121ca97f5b702f.
It's ready for review.

**Review by mitsudome-r — APPROVED** [review]

**Comment by xmfcx** [comment]
## Before

- **Container**: `ghcr.io/autowarefoundation/autoware:latest-prebuilt`
- **Workflow**: https://github.com/autowarefoundation/autoware.universe/actions/runs/10054009056/workflow?pr=8162
- **CI Run**: https://github.com/autowarefoundation/autoware.universe/actions/runs/10054009056/job/27787804239?pr=8162#step:5:10

image

## After (This PR)

- **Container**: `ghcr.io/autowarefoundation/autoware:latest-autoware-universe`
- **Workflow**: https://github.com/autowarefoundation/autoware.universe/actions/runs/10054982444/workflow
- **CI Run**: https://github.com/autowarefoundation/autoware.universe/actions/runs/10054982444/job/27790660036#step:5:10

image

## Disk space usage change

New image uses 0.8GB more disk space.

Also,
- https://github.com/autowarefoundation/autoware/pull/5023
this PR does not help CI because it seems autoware-universe image didn't have artifacts anyway.

**Pull request merged**
