### PR TITLE
feat(crosswalk): support crosswalk regulatory element

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Crosswalk module supports regulatory element.

See https://github.com/orgs/autowarefoundation/discussions/3036

## Related links

:arrow_down: This PR must be merged before this PR.
https://github.com/autowarefoundation/autoware_common/pull/187

## Tests performed

- [x] Can open lanelet map file includes crosswalk regulatory element.
- [x] Crosswalk module works well on that map.
- [x] [PASS TIER IV INTERNAL SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/d2e92155-1f1f-5d62-beb4-5dfa07d0f402?project_id=prd_jt)

## Notes for reviewers

Crosswalk module checks the existence of regulatory elements.

## Interface changes

Nothing.

## Effects on system behavior

Nothing.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
It seems that the lanelet2_map_visualization node has not yet supported the crosswalk reguratory element. 
Will you implement it in another PR?

**Comment by tkimura4** [comment]
The crosswalk module works well for crosswalk regulatory elements.
image

**Comment by tkimura4** [comment]
@satoshi-ota 
In some cases, the shape of the crosswalk polygon seems to be strange. Could you check it?
image

**Comment by satoshi-ota** [comment]
@tkimura4 hmm... The map seems to be little bit wierd...? The crosswalk separates two lanelet. I guess that there is a special lane for bicycle.

image

**Comment by satoshi-ota** [comment]
> It seems that the lanelet2_map_visualization node has not yet supported the crosswalk reguratory element. Will you implement it in another PR?

add crosswalk areas marker in https://github.com/autowarefoundation/autoware.universe/pull/3939/commits/4c3a75c09bf40924ba35e10fa70cb9cf018242e0.

image

**Review by tkimura4 — APPROVED** [review]
LGTM!

**Review by kminoda — DISMISSED** [review]

**Review by kminoda — APPROVED** [review]
LGTM

**Pull request merged**
