### PR TITLE
feat(tier4_perception_launch): sync perception launch to autoware_launch

### PR DESCRIPTION
**Pull request by miursh**
## Description
Resolve differences between tier4_perception_launch in autoware.universe and perception_launch in autoware_launch.

## Related Links
https://github.com/tier4/autoware_launch/pull/534

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by shmpwk — APPROVED** [review]
LGTM, thank you!

**Review by yukke42 — APPROVED** [review]
I checked that the predicted objects, ground-segmentation and traffic light run without any error and there aren't any concern about the output from them.

**Comment by shmpwk** [comment]
@yukkysaito Could you approve this as this code owner?

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
