### PR TITLE
feat: add angle limitation to mpt

### PR DESCRIPTION
**Pull request by tkimura4**
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>

## Description

add angle limitation to the nearest index/segment search in obstacle_avoidance_planner.

## Background

In the current implementation, when the route intersects, there is a possibility that the nearest point of the own vehicle will be calculated incorrectly. I fixed it by adding angle limitation to search the nearest point.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
TODO:

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L297-L298

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L388-389

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L425-L426

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L678-L679

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L1194-L1195

https://github.com/autowarefoundation/autoware.universe/blob/580565a24ff9af8c86006905681f3d1036c8724a/planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp#L1280-L1281

**Comment by tkimura4** [comment]
**`findNearestSegmentIndex` also doesn't consider the ego-vehicle's yaw at all, so it needs to be fixed. This is not limited to the obstacle_avoidance planner.**

**Comment by tkimura4** [comment]
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/include/utilization/util.hpp#L219
In the future, it will be necessary to unify with logic like this function `findFirstNearSearchRangeIndex`
Such the logic needs to be applied to both findNearestIndex and findNearestSegmentIndex.

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Pull request merged**
