### PR TITLE
feat(tier4_autoware_utils, obstacle_cruise_planner): add function to create deleted marker

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

added a function to delete wall marker in tier4_autoware_utils, and applied it to obstacle_cruise_planner.

In the following video, with this PR, the stop red wall disappeared quickly once the object was removed (and the trajectory's color becomes green).

without this PR
https://user-images.githubusercontent.com/20228327/182741991-fd301c65-3890-4fbb-854f-844c07d8c281.mp4

with this PR
https://user-images.githubusercontent.com/20228327/182741970-481211de-2189-4040-8501-e68fc0527888.mp4

If you want to confirm if this works, 
- merge [this commit](https://github.com/autowarefoundation/autoware.universe/pull/1515) to this branch first,
- set "obstacle_cruise_planner" in [this "cruise_planner" argument](https://github.com/autowarefoundation/autoware.universe/blob/7da6cd45c258416f17da9683422f3bc7e3f94da5/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py#L289)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Comment by h-ohta** [comment]
#1116

**Comment by taikitanaka3** [comment]
@h-ohta 
Could you close #1116 if there is no any more problems?

**Comment by h-ohta** [comment]
No. This PR is the part of fix for #1116.

**Pull request merged**
