### PR TITLE
refactor(map_packages): remove unused depend in pakcages.xml files

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Description
This PR derived from https://github.com/autowarefoundation/autoware.universe/pull/3606

result of unused.sh (https://github.com/autowarefoundation/autoware/issues/3468)

```
--- Checking src/universe/autoware.universe/map/map_projection_loader/package.xml ---
rclcpp_components seems not to be used

--- Checking src/universe/autoware.universe/map/util/lanelet2_map_preprocessor/package.xml ---
pcl_ros seems not to be used

--- Checking src/universe/autoware.universe/map/map_loader/package.xml ---
pcl_ros seems not to be used
std_msgs seems not to be used
tf2_geometry_msgs seems not to be used
tf2_ros seems not to be used
tier4_autoware_utils seems not to be used

--- Checking src/universe/autoware.universe/map/map_height_fitter/package.xml ---
tf2 seems not to be used

--- Checking src/universe/autoware.universe/map/map_tf_generator/package.xml ---
```

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kminoda — APPROVED** [review]
LGTM

**Review by isamu-takagi — APPROVED** [review]

**Comment by YamatoAndo** [comment]
@mitsudome-r please review about `lanelet2_map_preprocessor`

**Review by Motsu-san — APPROVED** [review]
LGTM (on the changes match with the result of unused.sh)
[LGTMeow](https://lgtmeow.com)

**Comment by YamatoAndo** [comment]
@mitsudome-r

**Comment by YamatoAndo** [comment]
@mitsudome-r @mitsudome-r

**Review by mitsudome-r — APPROVED** [review]

**Pull request merged**
