### PR TITLE
chore(autoware_pcl_extensions): refactored the pcl_extensions

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Refactored the former `tier4_pcl_extensions` to `autoware_pcl_extensions`
## Related links

**Parent Issue:**

- Link

## How was this PR tested?
Checked that the filter using the classes from this package could be launched correctly

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by knzo25** [comment]
@technolojin 
PCL extensions are usually kept inside the `pcl` namespace, so I did not change them to the `autoware` one for now. If you consider it necessary, I will move it though.

**Comment by knzo25** [comment]
@drwnz remember this one please :pray:

**Comment by knzo25** [comment]
@drwnz

**Review by drwnz — APPROVED** [review]
LGTM. Since codeowners is modified, it has thrown up an issue highlighting that we also need to clean up that file, but that's a separate issue.

**Pull request merged**
