### PR TITLE
refactor(object_recognition_utils): add autoware prefix to object_recognition_utils

### PR DESCRIPTION
**Pull request by esteve**
## Description

Added `autoware` prefix to `object_recognition_utils`

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by technolojin — APPROVED** [review]
LGTM

**Review by takayuki5168 — APPROVED** [review]

**Comment by badai-nguyen** [comment]
@esteve Could you also [add the prefix in CODEOWNERS file](https://github.com/esteve/autoware.universe/blob/prefix-object_recognition_utils/.github/CODEOWNERS#L27)?

**Review by amadeuszsz — APPROVED** [review]
LGTM for `autoware_lidar_transfusion`

**Review by knzo25 — APPROVED** [review]
LGTM

**Comment by esteve** [comment]
@technolojin @takayuki5168 @amadeuszsz @knzo25 @xmfcx @mitsudome-r I've added the prefix to `CODEOWNERS` and fixed the conflicts with main, please have a look at the changes. Thanks.

**Comment by technolojin** [comment]
- perception_online_evaluator : @ktro2828 @YoshiRi 
- autoware_cluster_merger : @yukkysaito @badai-nguyen 
- autoware_detected_object_validation : @yukkysaito @YoshiRi @badai-nguyen
- autoware_image_projection_based_fusion : @yukkysaito @YoshiRi @badai-nguyen @ktro2828
- autoware_tensorrt_yolox : @ktro2828 

@ktro2828 + @YoshiRi OR @badai-nguyen OR @yukkysaito 
Can you review this PR?

**Review by badai-nguyen — APPROVED** [review]
LGTM

**Review by YoshiRi — APPROVED** [review]
LGTM for my part

**Comment by esteve** [comment]
@xmfcx would it be possible to merge these changes without waiting for all the reviewers? This PR has already 6 approvals.

**Comment by xmfcx** [comment]
Waiting for https://github.com/autowarefoundation/autoware.universe/actions/runs/11341739442/job/31550579344 to complete.

**Comment by xmfcx** [comment]
For this PR, I will compile it to make sure and then merge bypassing the requirements.

---

[Also](https://github.com/autowarefoundation/autoware.universe/commits/main/):
image

https://github.com/autowarefoundation/autoware.universe/actions/runs/11341739442/job/31550579344

@mitsudome-r these are still managing to fail. Let's try to find a solution in the Software WG meeting.

Probably failing because of lack of memory.
These are CodeBuild machines come pre-set for GitHub actions.
I couldn't find a way to assign swap to these machines.

Current options:
- Limit the number of parallel jobs without using taskset?
- Reduce the cpus assigned to taskset?
- Current codebuild cost is about $500 per month, maybe just find another place to simply host about 10 dedicated machines and set up github actions runners on them?
   - Example: https://eco.ovhcloud.com/en/soyoustart/sys-1/
   - Will be cheaper and would provide higher compute capabilities with more configurability. (due to being self hosted)

**Comment by xmfcx** [comment]
I've compiled it with the latest Autoware and ran

`colcon test --event-handlers console_cohesion+ --mixin coverage-pytest --ctest-args -L .* --executor sequential --packages-select $(colcon list --base-paths src/universe/autoware.universe -n | awk '{printf "%s ", $1}')`

And it finished successfully.

**Pull request merged**
