### PR TITLE
fix(behavior_velocity): calculate detection area from the nearest point from ego

### PR DESCRIPTION
**Pull request by TomohitoAndo**
## Description
I fixed `createDetectionAreaPolygons` to calculate detection area from the nearest point from ego

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TomohitoAndo** [comment]
@taikitanaka3 
by this change, you have to clip the `predicted_path` from the ego pose in occlusion spot module. (I think this is better because path velocity is smoothed from nearest point from ego)
and you don't need `offset_from_start_to_ego` once you clip the path from ego.
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/src/scene_module/occlusion_spot/scene_occlusion_spot.cpp#L127-L128

Could you fix the code or can I fix?

**Comment by taikitanaka3** [comment]
@TomohitoAndo 
thankyou offset from start to ego is necessary because smoothed path is added path behind at last step. you can see util.cpp smooth function.
however we need to use velocity of the path from closest to ego while detection area start.position is.front bumper right?
can you fix it if its possible?

**Comment by taikitanaka3** [comment]
this part
https://github.com/autowarefoundation/autoware.universe/blob/b2f90a0952bf37969517f72ccd5a1ea86f253ce5/planning/behavior_velocity_planner/include/utilization/trajectory_utils.hpp#L179

**Comment by TomohitoAndo** [comment]
@taikitanaka3 
I fixed to calculate the distance from the nearest point of the path. 
 200a46532b2e9890a9818fb5ade3dca77b2e43ad
I changed to pass the nearest_idx instead of offset because to calculate ego nearest point from offset is redundant.

**Comment by TomohitoAndo** [comment]
I confirmed occlusion_spot module works in psim.
https://user-images.githubusercontent.com/11865769/164171235-3ac55e9e-8b1d-434a-a2d1-a94a23fef5a5.mp4

**Comment by TomohitoAndo** [comment]
struct was passd by value so I changed it to pass by reference.
https://github.com/autowarefoundation/autoware.universe/pull/730/commits/10fb00c281fe3e4f905b5d02f7b13d7dccaad7e9

**Comment by taikitanaka3** [comment]
@TomohitoAndo 
sorry for late. nearest_idx at interpolated path and nearest index in smoothed path is different so please find nearest index in util function.

**Comment by TomohitoAndo** [comment]
@taikitanaka3 
I fixed to find nearest index in util function. https://github.com/autowarefoundation/autoware.universe/pull/730/commits/f4bc7b8fc9b7f7ac7368a756175883fd81537fc0

I've confirmed that occlusion spot module works in psim.

https://user-images.githubusercontent.com/11865769/164366728-ee5bb993-0f04-41ae-8843-613061696ed3.mp4

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Pull request merged**
