### PR TITLE
refactor(autoware_map_msgs): modify pcd metadata msg

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Description
I have modified the code to reflect the changes in `autoware_map_msgs`.

## Related links

https://github.com/autowarefoundation/autoware_msgs/pull/96

**Parent Issue:**

- Link

## How was this PR tested?

build with https://github.com/autowarefoundation/autoware_msgs/pull/96
Lsim works

## Notes for reviewers

The build tests will not pass unless https://github.com/autowarefoundation/autoware_msgs/pull/96 is merged first.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — APPROVED** [review]
I have also confirmed that logging_simulator works properly with data that uses divided pcds.
(psim also works properly)
Looks Good To Me

**Comment by YamatoAndo** [comment]
compare_map_segmentation's codeowners (@amc-nu @yukkysaito @badai-nguyen) 
elevation_map_loader's codeowners (@kosuke55 @Shin-kyoto)
Please review :bow:

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by xmfcx** [comment]
This was reverted by:
- https://github.com/autowarefoundation/autoware.universe/pull/7852

**Pull request merged**
