### PR TITLE
chore(build): remove tier4_autoware_utils.hpp sensing/

### PR DESCRIPTION
**Pull request by soblin**
## Description

https://github.com/autowarefoundation/autoware.universe/issues/4821

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by soblin** [comment]
Merge this after https://github.com/autowarefoundation/autoware.universe/pull/4849

**Comment by soblin** [comment]
@scepter914 Can you approve this PR ?

**Review by scepter914 — APPROVED** [review]
LGTM

**Review by kminoda — APPROVED** [review]
LGTM

**Pull request merged**
