### PR TITLE
fix(autoware_traffic_light_fine_detector): fix constParameterReference

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck constParameterReference warnings

```
perception/traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp:216:36: style: Parameter 'id2expectRoi' can be declared as reference to const [constParameterReference]
  std::map<int, TrafficLightRoi> & id2expectRoi,
                                   ^

perception/traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp:239:36: style: Parameter 'id2expectRoi' can be declared as reference to const [constParameterReference]
  std::map<int, TrafficLightRoi> & id2expectRoi,
                                   ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
It is not possible to put const directly on `id2expectRoi `because the non-const member function `traffic_light_type` must be called for the element `id2expectRoi[id]`.
Therefore, I chose to suppress the warning by commenting.

**Comment by veqcc** [comment]
@kobayu858 
> because the non-const member function traffic_light_type must be called for the element id2expectRoi[id].

Is it really true?
`traffic_light_type` is not a function but a uint8_t member
```
sensor_msgs/RegionOfInterest roi
int64 traffic_light_id
uint8 traffic_light_type
```

**Comment by kobayu858** [comment]
I did not communicate it well.
The error occurs because you tried to use a modifiable reference (operator[]) while trying to access a std::map element with a const modifier.

```
/home/emb4/autoware_cppcheck/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp: In member function ‘void autoware::traffic_light::TrafficLightFineDetectorNode::detectionMatch(const std::map<int, tier4_perception_msgs::msg::TrafficLightRoi_<std::allocator<void> > >&, std::map<int, std::vector<tensorrt_yolox::Object> >&, autoware::traffic_light::TrafficLightFineDetectorNode::TrafficLightRoiArray&)’:
/home/emb4/autoware_cppcheck/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp:295:45: error: passing ‘const std::map<int, tier4_perception_msgs::msg::TrafficLightRoi_<std::allocator<void> > >’ as ‘this’ argument discards qualifiers [-fpermissive]
  295 |     tlr.traffic_light_type = id2expectRoi[id].traffic_light_type;
      |                                             ^
In file included from /usr/include/c++/11/map:61,
                 from /opt/ros/humble/include/rclcpp/rclcpp/node.hpp:22,
                 from /opt/ros/humble/include/image_transport/image_transport/image_transport.hpp:37,
                 from /home/emb4/autoware_cppcheck/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.hpp:18,
                 from /home/emb4/autoware_cppcheck/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp:15:
/usr/include/c++/11/bits/stl_map.h:512:7: note:   in call to ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](std::map<_Key, _Tp, _Compare, _Alloc>::key_type&&) [with _Key = int; _Tp = tier4_perception_msgs::msg::TrafficLightRoi_<std::allocator<void> >; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, tier4_perception_msgs::msg::TrafficLightRoi_<std::allocator<void> > > >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = tier4_perception_msgs::msg::TrafficLightRoi_<std::allocator<void> >; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = int]’
  512 |       operator[](key_type&& __k)
      |       ^~~~~~~~
gmake[2]: *** [CMakeFiles/autoware_traffic_light_fine_detector.dir/build.make:76: CMakeFiles/autoware_traffic_light_fine_detector.dir/src/traffic_light_fine_detector_node.cpp.o] エラー 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/autoware_traffic_light_fine_detector.dir/all] エラー 2
gmake: *** [Makefile:146: all] エラー 2
---
Failed   <<< autoware_traffic_light_fine_detector [5.08s, exited with code 2]
```

**Comment by kobayu858** [comment]
`tlr.traffic_light_type = id2expectRoi.at(id).traffic_light_type;`

I was able to work around this by doing this, so I fixed it.
Also fixed the conflicts.

**Review by veqcc — APPROVED** [review]

**Review by miursh — APPROVED** [review]

**Pull request merged**
