### PR TITLE
fix(tier4_perception_launch): fix input twist topic name

### PR DESCRIPTION
**Pull request by kminoda**
## Description

Add twist input topic name for concatenate node in obstacle segmentation.

## Tests performed

Confirmed that it works with tier4/pilot-auto.x2 (not for AWF, but will do if necessary)

## Effects on system behavior

Obstacle segmentation performance should improve.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — APPROVED** [review]
Thanks!!
LGTM

**Review by yukkysaito — CHANGES_REQUESTED** [review]
It may be better to have the twist output from localization be used for perception.

**Comment by yukkysaito** [comment]
@kminoda Currently, each component of Autoware uses the output of localization for speed.
However, the senisng module is an exception because it is the first stage process of localization, so it uses IMU and vehicle speed as they are.

**Comment by kminoda** [comment]
@yukkysaito Make sense. Then I will change this PR to use the localization output.
(The fix itself is urgent for the project, but could be temporarily handled with manual modification instead of cherry-pick, so no worries)

**Pull request closed without merging**
