### PR TITLE
feat(behavior_path_planner): make not too large drivable area after repositioning ego pose

### PR DESCRIPTION
**Pull request by takayuki5168**
## Related Issue(required)

https://github.com/autowarefoundation/autoware.universe/issues/503

## Description(required)

Because of the current algorithm of generating drivable area, the drivable area tries to capture both ego pose and the trajectory to follow.
Therefore, if ego pose is far away from the trajectory (like once generating trajectory, and then reposition the ego pose far away), the size of drivable area will be so large.
This cannot happen in the real world, but happen in the simulation.

To fix this issue, drivable area tries to capture just the trajectory to follow

## Review Procedure(required)

in simple psim, check if the size of drivable area won't be large after once generating trajectory and repositioning the ego pose far away.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by zulfaqar-azmi-t4** [comment]
Confirmed that the fix is working by using odaiba map (large size) and keep repeatedly change ego starting and goal.

### Before fix
When first place ego
Screenshot from 2022-03-10 00-32-19

After reposition
Screenshot from 2022-03-10 00-32-45

### After fix
When first place ego
Screenshot from 2022-03-10 00-36-18

After reposition
Screenshot from 2022-03-10 00-36-42

**Comment by zulfaqar-azmi-t4** [comment]
LGTM

**Review by zulfaqar-azmi-t4 — APPROVED** [review]
LGTM

**Review by taikitanaka3 — APPROVED** [review]

**Comment by taikitanaka3** [comment]
@takayuki5168 
can you add this to release note?

**Comment by takayuki5168** [comment]
Thank you for your review. I merge the PR

**Pull request merged**
