### PR TITLE
feat(behavior_path_planner): change planner data update method

### PR DESCRIPTION
**Pull request by purewater0901**
Signed-off-by: yutaka <purewater0901@gmail.com>

## Description
Currently, `planner_data_` is copied incorrectly, and it might cause some serious issues. In this PR, I fixed the problem. 

[Related Issues](https://github.com/autowarefoundation/autoware.universe/issues/2495)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by VRichardJP** [comment]
Although it should not be a problem in practice, there is still a concurrency issue.
For example you have the 2 snippets:

```
void BehaviorPathPlannerNode::updatePlannerData()
{
  // update planner data (pose, map and route)
  planner_data_->self_pose = self_pose_listener_.getCurrentPose();
  if (has_received_map_) {
    planner_data_->route_handler->setMap(*map_ptr_);
    has_received_map_ = false;
  }
  //...
```

```
void BehaviorPathPlannerNode::onMap(const HADMapBin::ConstSharedPtr msg)
{
  map_ptr_ = msg;
  has_received_map_ = true;
}
```

When 2 threads are working in parallel, the following situation may occur:
1. Let's say a new map has been received, so we need to update `route_handler`
2. thread 1 enters `updatePlannerData` and reach the `if (has_received_map_)`
3. since `has_received_map_` is `true`, the thread 1 execute `planner_data_->route_handler->setMap(*map_ptr_)`
4. at the same time, a new map is received. Thread 2 executes `onMap`: `map_ptr_` points to new data, `has_received_map_` is set to true.
5. thread 1 finally finishes with the `setMap()` line, and execute `has_received_map_ = false`

-> Consequence: 
- a new map has been received: `map_ptr_` points to a new map
- but `has_received_map` is set to `false`, so the new data will never be used.

The pattern is exactly the same with the `route_ptr_`.

**Comment by purewater0901** [comment]
@VRichardJP Thank you. Then how about creating a new `mutex` to protect `has_received_map_` from written over by other threads? The code will be 

```
void BehaviorPathPlannerNode::updatePlannerData()
{
  // update planner data (pose, map and route)
  mutex_map_.lock();
  planner_data_->self_pose = self_pose_listener_.getCurrentPose();
  if (has_received_map_) {
    planner_data_->route_handler->setMap(*map_ptr_);
    has_received_map_ = false;
  }
mutex_map_.unlock();
  //...
```

**Comment by VRichardJP** [comment]
Yes, I think you cannot get rid of a mutex.
As for your code you could also use a [lock_guard](https://en.cppreference.com/w/cpp/thread/lock_guard) instead of manually locking/unlocking.

**Comment by purewater0901** [comment]
@VRichardJP Thank you so much! I'll add the mutex in my code.

**Comment by purewater0901** [comment]
@VRichardJP I just added the mutex, could you please check my modification?

**Comment by purewater0901** [comment]
@VRichardJP I just added the mutex, could you please check my modification?

**Review by TakaHoribe — APPROVED** [review]

**Pull request merged**
