### PR TITLE
fix(emergency_handler): fix bug of takeover_request

### PR DESCRIPTION
**Pull request by veqcc**
Signed-off-by: veqcc [ryuta.kambe@tier4.jp]

@mkuri @asana17 

## Description
The parameter `is_takeover_requested_` was not properly used. It was changed `true` when `MRMState::NORMAL`. However, the timeout process was implemented only in the state `MRMState::OPERATING`.

### CODE REVIEW

**Comment by isamu-takagi** [comment]
The takeover state is removed when changing from EmergencyState to MrmState. What is this parameter currently used for?

**Comment by mkuri** [comment]
@isamu-takagi 
> The takeover state is removed when changing from EmergencyState to MrmState. What is this parameter currently used for?

The takeover state on the officially supported API was removed when MrmState was created, but the takeover state in the emergency handler that existed in the previous design remains.

The current behavior is that when the above parameter is true, the system waits for a certain period of time after a failure, and if the operator does not takeover, the system will switch to MRM.
The following two options are available.

- Remove all features related to takeover (maybe some products use the takeover feature)
- Leave it as a base for when takeover will be formally designed

This PR is based on the latter policy, and is a PR to fix a bug found in the existing takeover state.

**Comment by isamu-takagi** [comment]
@mkuri 
I got it. I understood that old `TAKEOVER_REQUETING` state is now `NONE` state. However, the `operateMrm` function clears the `behavior` when the state is `NONE`. I think it should be retained.

**Comment by isamu-takagi** [comment]
@mkuri @veqcc 
[MRM state](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/features/fail-safe/) expects `{state: MRM_OPERATING, behavior: NONE}` during takeover requesting. Neither the current nor fixed implementation fits this. So I think it's better to remove this processing. The takeover request will be a new topic and are being discussed in https://github.com/autowarefoundation/autoware/issues/3487.

**Comment by mkuri** [comment]
@isamu-takagi 
Yes, I agree with removing the take_over process.

@veqcc 
How about we close this PR and remove the process related to take over in the new PR to solve the following issue?

> The parameter is_takeover_requested_ was not properly used. It was changed true when MRMState::NORMAL. However, the timeout process was implemented only in the state MRMState::OPERATING.

Reference
https://github.com/autowarefoundation/autoware.universe/pull/2994#issuecomment-1464849767
> The following two options are available.
> Remove all features related to takeover (maybe some products use the takeover feature)
> Leave it as a base for when takeover will be formally designed

I will adopt the former policy.

**Comment by veqcc** [comment]
> @veqcc
How about we close this PR and remove the process related to take over in the new PR to solve the following issue?
I see. I will close it and make a new one.

**Pull request closed without merging**
