### PR TITLE
fix(freespace_planning_algorithms): non-successive waypoints problem in hybrid A* algorithm

### LINKED ISSUE #1151: Non-successive way points generated by A-star algorithm in freespace planner
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Way points generated by A-star algorithm are not successive as the red circle shows. It could result in poor trajectory following performance.

image

### Expected behavior

Way points generated by A-star algorithm are successive. Here successive means the vehicle can move from the former point to the next point through a movement in the transition_table_. Possible transitions are defined as below.
[AstarSearch::TransitionTable createTransitionTable function](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/freespace_planning_algorithms/src/astar_search.cpp#L74)

### Actual behavior

Way points generated by A-star algorithm are not successive.

### Steps to reproduce

1. Start autoware planning simulator using default
2. Set pose estimate and goal pose the parking lot

(These steps can not guarantee the problem will repeat. According to my experience, there is a higher probability if the number of arcs in ReesShepp solution is large.)

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: Autoware.universe:main

### Possible causes

image

According to the transition table design, two consecutive points should be like the blue arrows. The yellow ones(shift_theta greater than dθ) and the green ones(can not reach the next point precisely through any of the transition types) should not have been appeared.

If the preceding node changed, the nodes behind should recheck the transition relation and recalculate the actual cost or just break the connection. But these steps are not implemented now. So if a node in the closed list is rewritten during the search, and its child node stays the same, the output may be as the green arrows show. 

For example. In the following picture, S is the start point, G is the goal point and P(P*) is the non-successive point. At first, nodes P* is in the closed list and its child D is in the open list. Then point C is chosen from the open list and node P is pushed into the open list (again) as a child of C. Actually P and P* are the same node in search space cause they are in the same grid and have the same orientation. In other words, P and P* use the same part of memory and share the same index in search space. Even though P is not totally equal to P*, D keeps pointing to P/P*. If D is chosen from the open list, the problem may appear as S-C-P-D-G has a chance to be selected as the best way. In that case, we will get a non-successive way point array as the figure shows.

astar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NorahXiong**
Signed-off-by: NorahXiong <norah.xiong@autocore.ai>

## Description

fix #1151 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mitsudome-r** [comment]
@NorahXiong Would you be able to explain the reason for the change? The change in this PR is small, but it is hard to find out why this would solve the issue. Also, it is a bit difficult to estimate how this could effect the searching in Astar. We can set a separate call if needed.

**Comment by xmfcx** [comment]
@NorahXiong Can you also share before&after this PR has been applied results? Some images would be nice, thanks!

**Comment by NorahXiong** [comment]
> @NorahXiong Thanks for the PR. Would you be able to explain the reason for the change? The change in this PR is small, but it is hard to find out why this would solve the issue.

I tried to explain how the case appears in #1151 and added a supplement [here](https://github.com/autowarefoundation/autoware.universe/issues/1151#issuecomment-1203510848). Could you point out which part is confusing?
> Also, it is a bit difficult to estimate how this could effect the searching in Astar. We can set a separate call if needed.

I didn't really get the meaning of "set a separate call". Do you mean to set this PR as an optional algorithm when calling Astar?

**Comment by NorahXiong** [comment]
> @NorahXiong Can you also share before&after this PR has been applied results? Some images would be nice, thanks!

Sorry I chose the small change template because I didn't know how to reproduce the bug. But now I get a setting to trigger the bug as the following picture shows.
image

Testing result: before
image

Testing result: after
image

**Pull request merged**
