### PR TITLE
fix(ground_segmentation): Change ground segmentation parameters

### PR DESCRIPTION
**Pull request by djargot**
## Description

This PR changes parameters for ground segmentation algorithm and fixes: https://github.com/autowarefoundation/autoware.universe/issues/669

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Can you check both:
- https://github.com/autowarefoundation/autoware.universe/blob/main/perception/ground_segmentation/src/ray_ground_filter_nodelet.cpp
- https://github.com/autowarefoundation/autoware.universe/blob/main/perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

Because ray_ground_filter_nodelet might work better than the scan_ground_filter_nodelet

**Comment by yukkysaito** [comment]
@badai-nguyen @miursh May I ask for a review?

**Comment by miursh** [comment]
@xmfcx @djargot 
We have developed new option for scan ground filter https://github.com/autowarefoundation/autoware.universe/pull/1899 
You can still use conventional algorithm, but some option parameter is added https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml#L26-L31.

**Comment by yukkysaito** [comment]
What should we do about this PR?
If no reply within two weeks, I will close it.

**Comment by piotr-zyskowski-rai** [comment]
> What should we do about this PR? If no reply within two weeks, I will close it.

I believe it can be closed. The issue that this PR was supposed to solve was solved in a [different way](https://github.com/autowarefoundation/autoware.universe/pull/1899).

**Pull request closed without merging**
