### PR TITLE
fix(autoware_auto_common): move headers to a separate directory

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR moves headers to a seaparate `autoware_auto_common` directory.

See https://github.com/autowarefoundation/autoware/issues/4070

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
Hi @esteve Could you fix required CI fail...?

**Comment by esteve** [comment]
@satoshi-ota  my apologies, I've fixed the errors in the latest commit. This PR is now ready for review.

**Review by satoshi-ota — APPROVED** [review]

**Review by tkimura4 — APPROVED** [review]

**Comment by satoshi-ota** [comment]
Hi @esteve I guessed https://github.com/autowarefoundation/autoware.universe/pull/5941 caused some conflicts. Could you rebase or fix conficts...?

**Comment by esteve** [comment]
@satoshi-ota I've rebased this PR on top of main and fixed the conflicts, could you have a look at it again? Thanks.

**Review by taikitanaka3 — APPROVED** [review]

**Review by maxime-clem — APPROVED** [review]

**Pull request merged**
