### PR TITLE
fix(tier4_localization_rviz_plugin): fix knownConditionTrueFalse

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck knownConditionTrueFalse warnings.
Prevention against future CI changes.

```
common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp:206:7: style: Condition '!history_.empty()' is always true [knownConditionTrueFalse]
  if (!history_.empty()) {
      ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by YamatoAndo** [comment]
@TakaHoribe @isamu-takagi 
I've never used `pose_history_footprint` before, so I don't know if this change is OK.
Could you please review it?

If it's difficult, I'll review it myself, even if it takes some time.

**Comment by kobayu858** [comment]
@YamatoAndo @TakaHoribe @isamu-takagi 

 Because of the `if (history_.empty()) return;` in line 185, the `if (!history_.empty()) {` in line 206 is always true.

Therefore, the if in line 206 has been removed.

**Comment by YamatoAndo** [comment]
https://github.com/autowarefoundation/autoware.universe/blob/e823bae1dbf420d2e28a09039f730b6174f015eb/common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp#L185

It seems like the warning is saying that the if statement is unnecessary because the function returns at this line.

**Comment by YamatoAndo** [comment]
@kobayu858 Hi, I had forgotten until just now, but there is [a PR that performs static analysis](https://github.com/autowarefoundation/autoware.universe/pull/8683) on the `tier4_localization_rviz_plugin`, so I plan to merge it now.

**Comment by kobayu858** [comment]
@YamatoAndo 
Yes, I understand.

However, there is a problem with the current cppcheck command, which is not parsing the file properly.
Since I'm submitting this PR as a preliminary to resolving that issue, we need to merge first.

**Comment by YamatoAndo** [comment]
@kobayu858 Is it okay to merge https://github.com/autowarefoundation/autoware.universe/pull/8683 first?

**Comment by kobayu858** [comment]
@YamatoAndo 

It's okay. Thank you very much.

**Comment by YamatoAndo** [comment]
@TakaHoribe @isamu-takagi 
The changes in this PR seem simple, so there shouldn't be any issues,
anyway, I'll leave the review of this PR up to you.

**Review by isamu-takagi — APPROVED** [review]
@YamatoAndo 
I haven't created this plugin either, but looking at the code, it seems there is no problem with removing it.

@TakaHoribe 
If you have any problems please comment.

**Review by TakaHoribe — APPROVED** [review]
This fix is straightforward. The early return guarantee the history is not empty. LGTM.

**Pull request merged**
