### PR TITLE
fix(obstacle_avoidance_planner):  fix lateral calculations

### PR DESCRIPTION
**Pull request by beyzanurkaya**
Signed-off-by: beyza <bnk@leodrive.ai>

## Description

fixes: https://github.com/autowarefoundation/autoware.universe/issues/2663

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by beyzanurkaya** [comment]
@takayuki5168 @kosuke55 it's ready to review.

**Comment by beyzanurkaya** [comment]
@takayuki5168 @kosuke55 can you review this PR?

**Comment by xmfcx** [comment]
@takayuki5168 @kosuke55 friendly ping

**Review by takayuki5168 — APPROVED** [review]
Sorry to be late, looks good to me.

**Pull request merged**
