### PR TITLE
feat(map_loader): display curbstone as marker array

### PR DESCRIPTION
**Pull request by saka1-s**
## Description

If the vector map contains a cubestone, we would like to check the position of the curbstone on rviz. I propose adding a marker array of curbstone.
This PR also requires below PR(Merged) to build.
https://github.com/autowarefoundation/autoware_common/pull/206

Curbstone is visualized as dark blue lines.
Screenshot from 2023-09-11 19-29-01

## Tests performed

Psim

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by saka1-s** [comment]
@kminoda Could you review this PR? The PR for common was already merged.
And please let me know if I need to do else when I update common, Thank you.

**Comment by kminoda** [comment]
@saka1-s Would you fix the build issue?

**Review by kminoda — APPROVED** [review]
LGTM

**Comment by Motsu-san** [comment]
@saka1-s How is the progress of this PR?

**Pull request merged**
