### PR TITLE
feat(control_validator): add hold and lpf

### PR DESCRIPTION
**Pull request by yuki-takagi-66**
## Description
This PR add holding function and LPF for the velocity check.
in additon, velocity check is separated to two diags to trigger different MRM behavior.

## Related links
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1193

**Parent Issue:**

- Link

## How was this PR tested?
tier4 internal tests

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kyoichi-sugahara** [comment]
@yuki-takagi-66 
Please update newly introduced parameter description in README and add parameter in the yaml file in the package with default value.

**Comment by kyoichi-sugahara** [comment]
@yuki-takagi-66 
If there's no particular reason for removing the docstrings in this PR, it would be clearer to add them back in accordance with the changes. Or is it possible that they're being temporarily removed due to potential future changes?

Also, since I'm not familiar with the background of these changes, the processing seems fine to me. However, is it appropriate for me to approve without understanding the context or motivation behind these changes?

**Comment by yuki-takagi-66** [comment]
@kyoichi-sugahara 
Thank you for the review.
I've update README and yaml in universe side.

I think we have no additional information to be added as docstrings from the function name and the arg names.
And we do not operate doxygen docs.
Therefore, I think we should **not** maintain the docstrings for this function, although we have option to maintain.

> Also, since I'm not familiar with the background of these changes, the processing seems fine to me. However, is it appropriate for me to approve without understanding the context or motivation behind these changes?
Maybe it is not a sufficient description, LPF and hold is required to achieve the appropriate behavior along with MRM.
I've add some of descriptions.

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM!

**Pull request merged**
