### PR TITLE
fix(avoidance): avoidable right side parked-vehicle

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

~:arrow_down: This must be merged before this PR.~
~https://github.com/autowarefoundation/autoware_launch/pull/223~

For now, part of the avoidance module's target filtering logic depends on left-hand traffic, so there is a issue that the ego could not avoid right side parked-vehicles in right-hand traffic environment.

In this PR, the avoidance module supports right-hand traffic, and it is able to avoid right side parked-vehicles.

### Test perform

**detect the left side stopped vehicle as parked car**

rviz_screenshot_2023_02_22-16_02_40

**detect the right side stopped vehicle as parked car**

rviz_screenshot_2023_02_22-15_55_36

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@zulfaqar-azmi-t4 @mitsudome-r I fixed following issue, so could you review this PR? Thanks in advance :pray: 

https://github.com/autowarefoundation/autoware.universe/issues/2896

**Comment by satoshi-ota** [comment]
**NOTE: :arrow_down: This PR is no longer needed.**
https://github.com/autowarefoundation/autoware_launch/pull/223

**Comment by satoshi-ota** [comment]
Evaluator result

[[TIER IV INTERNAL LINK]](https://evaluation.tier4.jp/evaluation/reports/9871fbf3-4829-5e51-a55b-7602841b5d65?project_id=prd_jt) Baseline 875/877
[[TIER IV INTERNAL LINK]](https://evaluation.tier4.jp/evaluation/reports/5eca0dff-4bdb-5bd2-823f-070424866a66?project_id=prd_jt) This PR 875/877

**Comment by zulfaqar-azmi-t4** [comment]
Tested with two map with difference lane width. It works nicely!
Screenshot from 2023-03-03 14-25-49
Screenshot from 2023-03-03 14-29-24
Screenshot from 2023-03-03 14-29-51

**Review by zulfaqar-azmi-t4 — APPROVED** [review]
LGTM!

**Pull request merged**
