### PR TITLE
fix: fix ticket links to point to https://github.com/autowarefoundation/autoware.universe

### PR DESCRIPTION
**Pull request by esteve**
## Description

The links in the `CHANGELOG.rst` files were pointing to an incorrect URL.

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by esteve** [comment]
@youtalk I don't know why, but when you added the `CHANGELOG.rst` files for all these packages the tickets pointed to your fork and not to the `autowarefoundation`  organization.

**Comment by esteve** [comment]
@xmfcx waiting for a review from all the code owners of all the affected packages will take a long time and it'd be nice to release these packages soon into the ROS buildfarm.  Could you have a look at these changes and merge this PR if they look ok to you? Thanks.

**Review by xmfcx — APPROVED** [review]

**Review by mojomex — APPROVED** [review]
Sensing LGTM!

**Review by yukkysaito — APPROVED** [review]
I checked the links

**Comment by xmfcx** [comment]
(Just waiting for the required ci to finish)

**Comment by youtalk** [comment]
@esteve Thank you for the fix!

**Pull request merged**
