### PR TITLE
refactor(compare_map_segmentation): add package name prefix of autoware_

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description
This PR adds the autoware_ prefix to the package name.

Changes are as following.
1. Folder name (appears as file renaming)
2. Package names in `CMakeLists.txt`, `package.xml`
3. `README.md`
4. Launch files `$(find-pkg-share ...)`
5. `.github/CODEOWNERS`

This PR do not contains any logic change.

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
- Tested Perception performance in the TIER IV Cloud environment.: 
https://evaluation.tier4.jp/evaluation/reports/67843b47-8807-5ad2-b456-5105127cbc2c?project_id=prd_jt
image

- Tested Planning_simulator in local machine:
[compare_map_prefix_planning_simulator.webm](https://github.com/user-attachments/assets/31005c89-147f-49dc-9180-64cc1ee5c5d3)
image

## Notes for reviewers
None.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Comment by technolojin** [comment]
@badai-nguyen 
There is a PR for this work, earlier than this.
https://github.com/autowarefoundation/autoware.universe/pull/7592

Please ask @esteve and get alignment.

**Comment by badai-nguyen** [comment]
@technolojin thanks for your notice, 
@esteve I'm sorry for miss-checking that you already created the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7592) for `compare_map_segmentation`. I will close this PR if you can handle at your side? Please note that [tier4_perception_launch/package.xml](https://github.com/autowarefoundation/autoware.universe/pull/8005/files#diff-cb202e92581298154f49d4bf2f992576c79f4e594e2d7ecce6cc39a14c42a64c) also need to be updated.
Otherwise, I can continue to handle it with my PR.

**Comment by badai-nguyen** [comment]
@esteve Since we would focus to complete prefix update this week, I will take responsibility for `compare_map_segmentation` package and open this PR for review.

**Review by technolojin — APPROVED** [review]
LGTM (regarding `tier4_perception_launch`)

**Comment by badai-nguyen** [comment]
I would like to ask review from you for this PR: 
- Regarding `compare_map_segmentation` @yukkysaito 
- Regarding `tier4_planning_launch` @takayuki5168 @kosuke55 
- Regarding  `elevation_map_loader` @Shin-kyoto
- Regarding `Map_loader` @YamatoAndo  @KYabuuchi

**Review by takayuki5168 — APPROVED** [review]
LGTM for tier4_planning_launch

**Review by KYabuuchi — APPROVED** [review]
LGTM for map/map_loader

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by kosuke55 — APPROVED** [review]

**Comment by esteve** [comment]
@badai-nguyen I was away for the past two weeks, so I couldn't respond. Please check PRs before submitting a new one. Thanks for working on this, I'll close #7592

**Pull request merged**
