### PR TITLE
feat(view_plugin): add operation view plugin and route-set view plugin in the tier4_adapi_rviz_plugins package

### PR DESCRIPTION
**Pull request by Owen-Liuyuxuan**
## Description

In testing the system, sometimes frequently switching from a third-person view following the vehicle and a bird-eye view focusing on the vehicle is needed. 

This PR adds two buttons RViz plugin for convenient switching between the two views.  

## Tests performed

PSim

image

image

## Interface changes

Because operation view only makes sense when it is looking at the vehicle. So in code we force the target frame of operation view  being `base_link` . 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@Owen-Liuyuxuan Thank you for the PR. But these plugins are not related to AD API, so please create a separate package and move them there.

**Comment by Owen-Liuyuxuan** [comment]
@isamu-takagi 

Thanks for the advice.

In this case I will probably make a new PR. The problem is that this package does not seem to relate to AD API but it is related to route setting. This makes me confuse about where to start this plugin at the very first.

**Comment by isamu-takagi** [comment]
> In this case, I will probably make a new PR? 

@Owen-Liuyuxuan  You can update this branch and continue the PR.

**Comment by Owen-Liuyuxuan** [comment]
@isamu-takagi  I am not sure about the review process, but there will be quite a lot of new things if a new package is created.

**Pull request closed without merging**
