### PR TITLE
fix: rename `use_external_emergency_stop` to  `check_external_emergency_heartbeat`

### PR DESCRIPTION
**Pull request by shmpwk**
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>

## Description

 `use_external_emergency_stop` is a parameter to monitor the `~/input/external_emergency_stop_heartbeat` topic and set the parameter to `true` when the topic is interrupted and an emergency stop should be performed.
Note that even when the parameter is `false`, emergency stop request can be received, which may confuse users.

This PR renames `use_external_emergency_stop` to `check_external_emergency_heartbeat` so that it helps users to correctly understand the parameter feature. 

## Related links

- We discuss it in [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C4P0NSMB5/p1670248323818509?thread_ts=1667296549.925499&cid=C4P0NSMB5)

## Tests performed

~~Not yet confirm the behavior. After getting majority consensus, I will test this.~~
I tested this with Psim.

## Notes for reviewers

- The paramter is currently used here. I will change it in `awapi_awiv_adapter` and `autoware_launch` also.
```
$ grep use_external_emergency_stop src/ -r
src/universe/autoware.universe/launch/tier4_control_launch/launch/control.launch.py:                "use_external_emergency_stop": LaunchConfiguration("use_external_emergency_stop"),
src/universe/autoware.universe/launch/tier4_control_launch/launch/control.launch.py:    add_launch_arg("use_external_emergency_stop", "true", "use external emergency stop")
src/universe/autoware.universe/control/vehicle_cmd_gate/README.md:| `use_external_emergency_stop`               | bool   | true when external emergency stop information is used                       |
src/universe/autoware.universe/control/vehicle_cmd_gate/README.md:The parameter `use_external_emergency_stop` (true by default) enables an emergency stop request from external modules.
src/universe/autoware.universe/control/vehicle_cmd_gate/README.md:The `use_external_emergency_stop` parameter must be false when the "external emergency stop" function is not used.
src/universe/autoware.universe/control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp:  bool use_external_emergency_stop_;
src/universe/autoware.universe/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp:  use_external_emergency_stop_ = declare_parameter("use_external_emergency_stop", false);
src/universe/autoware.universe/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp:  if (use_external_emergency_stop_) {
src/universe/autoware.universe/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp:  if (use_external_emergency_stop_) {
src/universe/autoware.universe/control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml:  <arg name="use_external_emergency_stop" default="true"/>
src/universe/autoware.universe/control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml:    <param name="use_external_emergency_stop" value="$(var use_external_emergency_stop)"/>
src/universe/external/tier4_ad_api_adaptor/awapi_awiv_adapter/src/awapi_awiv_adapter_core.cpp:    RCLCPP_WARN_STREAM(get_logger(), "parameter[use_external_emergency_stop] is false.");
src/universe/external/tier4_ad_api_adaptor/awapi_awiv_adapter/launch/awapi_awiv_adapter.launch.xml:  <arg name="param_emergency_stop" default="use_external_emergency_stop"/>
src/launcher/autoware_launch/autoware_launch/launch/planning_simulator.launch.xml:      <arg name="use_external_emergency_stop" value="false"/>
src/launcher/autoware_launch/autoware_launch/launch/autoware.launch.xml:  <arg name="use_external_emergency_stop" default="false" description="use external emergency stop"/>
src/launcher/autoware_launch/autoware_launch/launch/autoware.launch.xml:      <arg name="use_external_emergency_stop" value="$(var use_external_emergency_stop)"/>
```
- Also, I will modify the parameter for the TIER IV private extenal module.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by h-ohta** [comment]
The vehicle_cmd_gate has two heartbeat checker, system_emergency_heartbeat and external_emergency_stop_heartbeat.
The name of `enable_heartbeat_checker` has some confusions, We can't understand which heartbeart of both are disabled.
The `external` should be  added.

**Review by h-ohta — CHANGES_REQUESTED** [review]
Because of https://github.com/autowarefoundation/autoware.universe/pull/2455#issuecomment-1338609507

**Comment by shmpwk** [comment]
@yukkysaito @h-ohta 
Thank you for your comment.
I updated to `check_external_emergency_heartbeat`.

**Comment by shmpwk** [comment]
Yes! 

https://github.com/tier4/autoware_launch/pull/592
https://github.com/tier4/FieldOperatorApplication/pull/536
https://github.com/autowarefoundation/autoware_launch/pull/120
https://github.com/tier4/tier4_ad_api_adaptor/pull/84

**Comment by shmpwk** [comment]
For TIER IV internal, after merging all related PRs, I will uptate the pilot-auto sync.

**Review by h-ohta — APPROVED** [review]
I launched planning simulator and confirmed that autonomous driving worked.

**Comment by shmpwk** [comment]
Thank you for your checking!

**Comment by h-ohta** [comment]
@shmpwk https://github.com/tier4/autoware_launch/pull/592 should be checked after syncing to tier4/autoware.universe.

**Comment by shmpwk** [comment]
@h-ohta  Yes I will.
Sounds like ready for merge this.

**Comment by shmpwk** [comment]
@TakaHoribe Could you just approve this as you are codeowner?

**Review by TakaHoribe — APPROVED** [review]
Thanks!

**Pull request merged**
