### PR TITLE
fix(lanelet2_extension): fix low FPS when visualizing center_line_arrows at a large map

### PR DESCRIPTION
**Pull request by h-ohta**
## Related

https://github.com/autowarefoundation/autoware.universe/pull/931#issuecomment-1144960169

## Description

- This PR fixes low fps when visualizing center_line_arrows at a large map like odaiba.
- I use TRIANGLE_LIST to visualize arrows because this is used in other markers、e. g. left_lane_bound and etc...
- Please check whether FPS in Rviz is improved.
before 

https://user-images.githubusercontent.com/9547070/171779809-ca0de23a-583e-40bb-8798-3215bfdef03e.mp4

after

https://user-images.githubusercontent.com/9547070/171780487-abb117cd-a9ea-4221-bda0-47253e18db18.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
compare with previous it's much better.
image
image

**Review by taikitanaka3 — APPROVED** [review]
LGTM
image


cc: @yukkysaito @TakaHoribe 
can you also approve this?

**Comment by taikitanaka3** [comment]
ref lss =2.0 
image

**Comment by h-ohta** [comment]
I made arrows the same size of turn direction markers

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
