### PR TITLE
refactor(Vehicle_cmd_gate): rework parameters

### PR DESCRIPTION
**Pull request by karishma1911**
## Description

Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the vehicle_cmd_gate package.

Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
Create the schema

## Tests performed

Not applicable.

## Effects on system behavior

More reliable and faster parameter configuration file creation.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
Hi @karishma1911 Thanks for your contribution. But this PR seems to include unnecessary commits. Could you rebase this PR with latest main branch?

**Comment by karishma1911** [comment]
> Not applicable.

Due to uncommitted changes has been pushed in this PR, I want to close this PR
Same changes has been pushed in this PR, I requested to go through this https://github.com/autowarefoundation/autoware.universe/pull/5652

**Comment by satoshi-ota** [comment]
@karishma1911 OK. Please close this PR. I'll review #5652.

**Comment by karishma1911** [comment]
> @karishma1911 OK. Please close this PR. I'll review #5652.

**Pull request closed without merging**
