### PR TITLE
build(tier4_metrics_rviz_plugin): add missing dependency

### PR DESCRIPTION
**Pull request by esteve**
## Description

Adds missing dependency. Waiting for https://github.com/ros/rosdistro/pull/39791 to be merged in the `rosdistro` repository.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
Hi @esteve :hand: I've already added dep to distro in https://github.com/ros/rosdistro/pull/39705. So I think you can use rosdep command to install missing dependency. Please confirm that.

Additionally, could you remove [**this**](https://github.com/autowarefoundation/autoware/blob/483e3b679fdf07355801ddeedbba53eda614107b/ansible/roles/autoware_universe/tasks/main.yaml#L1-L6) ansible task after merging this PR?

**Comment by esteve** [comment]
@satoshi-ota this PR is waiting on https://github.com/ros/rosdistro/pull/39791 to use the correct name for the dependency, Qt5 development packages use the `-dev` suffix.

I'll remove the ansible task in a follow-up PR once this one is merged.

**Comment by esteve** [comment]
@satoshi-ota I've submitted https://github.com/autowarefoundation/autoware/pull/4156 as a draft PR, I'll change it to ready for review once https://github.com/ros/rosdistro/pull/39791 and this PR are merged.

**Comment by esteve** [comment]
@satoshi-ota now that https://github.com/ros/rosdistro/pull/39791 has been merged, could you review this PR when you have a moment? Thanks 🙏

**Comment by esteve** [comment]
@satoshi-ota that was quick! 🙂 Thanks!

**Comment by satoshi-ota** [comment]
@esteve LGTM. Thanks :+1:

**Pull request merged**
