### PR TITLE
fix(longitudinal_controller_node, vehicle_cmd_gate): update stopped condition and behavior

### PR DESCRIPTION
**Pull request by satoshi-ota**
### `longitudinal_controller_node`

- parameterize `STOPPED STATE` entry duration time since vehicle stopped. (default 0.1[s])
- set target velocity Zero in `STOPPED STATE` (remove deceleration limit)

### `vehicle_cmd_gate`

- modified check stopped condition (watch the duration time since vehicle stopped.)

## Tests performed

please plot following topics:

- `/control/trajectory_follower/longitudinal/control_cmd/speed` (target velocity)
- `/control/trajectory_follower/longitudinal/diagnostic/diag_array/data.13` (0: DRIVE, 1: STOPPING, 2: STOPPED, 3: EMERGENCY)

and, check that target velocity is Zero during `STOPPED STATE`.

image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yabuta** [comment]
@satoshi-ota 速度0のときにSTOPPING, STOPになることは確認できました
Test PerformedではSTOPPINGがないのは何故でしたっけ？

I confirmed that state is STOPPING, STOP at speed 0
Why was there no STOPPING in Test Performed?

Screenshot from 2022-04-20 19-28-25

**Comment by satoshi-ota** [comment]
@yabuta Thank you for your comment :+1:  Sorry for the lack of clarity, but I fixed and created this PR in X2 product env, and the product has `smooth_stop` function disable in control config. As a result, longitudinal_controller doesn't have `STOPPING_STATE`.

**Comment by satoshi-ota** [comment]
resolve conflicts

**Review by TakaHoribe — APPROVED** [review]
LGTM. Thank you for your fix and detailed explanation.
The same logic exists in several packages, so please create an issue to track the issue.

**Comment by TakaHoribe** [comment]
Related. https://github.com/tier4/autoware_launch/pull/283

**Comment by satoshi-ota** [comment]
> LGTM. Thank you for your fix and detailed explanation. The same logic exists in several packages, so please create an issue to track the issue.

OK :+1:  I would be happy to undertake that works.

**Pull request merged**
