### PR TITLE
feat(behavior_velocity_planner): keep stopping in hold stop margin distance

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Now, this ego always try to stop at the stop position by re-starting (re-approach) even if the ego is stopped near the planned stop position in the module. On the other hand, if the stopping performance of the vehicle is poor (e.g. it cannot stop for one meter) and once it starts traveling, there is a possibility that the vehicle may over the stop position, in which case there may be a issue for the vehicle to continue stopping on the spot, if the distance between the ego and stop position is closer than threshold.

So, in this PR, I fixed following points.

- add new param `hold_stop_margin_distance` (default: 2.0 [m])
- if the following condisions are satisfied, the ego keep stopping at current position.

condition 1. the ego has stopped
condition 2. the distance between  the ego and stop point is shorter than `hold_stop_margin_distance`

test perform (`hold_stop_margin_distance` = 2.0 [m])

https://user-images.githubusercontent.com/44889564/180943210-21703d3a-7ee3-43ed-80af-6d6bedf85b73.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
Scenario test executing now...

**Comment by satoshi-ota** [comment]
@TakaHoribe I confirmed that there is no critical degradation in this PR by evaluator.

This PR: https://evaluation.tier4.jp/evaluation/reports/1d72bd1e-0212-5433-9698-f6f80d8b8eb5?project_id=prd_jt
Baseline: https://evaluation.tier4.jp/evaluation/reports/822bf00c-c113-57ea-b82a-aef251801a4d?project_id=prd_jt

**Comment by satoshi-ota** [comment]
This PR: https://evaluation.tier4.jp/evaluation/reports/897350f4-9af8-5303-b0d2-8f1bd4046738?project_id=prd_jt (695/768)
Baseline: https://evaluation.tier4.jp/evaluation/reports/ddd34bcc-0fb6-5ea8-8844-0a4961745f5f?project_id=prd_jt (700/768)

**Review by TakaHoribe — APPROVED** [review]
LGTM
image

**Comment by satoshi-ota** [comment]
https://user-images.githubusercontent.com/44889564/182517663-f3919b73-a42c-4829-a815-a304ab3835f4.mp4

tempolaty use following param for test perform

- stop_duration_sec: 5.0 [s]
- hold_stop_margin_distance: 5.0 [m]

**Pull request merged**
