### PR TITLE
fix(ndt_scan_matcher): added coping input_source when rebuilding ndt

### PR DESCRIPTION
**Pull request by SakodaShintaro**
## Description
I found that there was a problem with Driving Log Replayer not working properly, so fix it.

```
[ndt_scan_matcher-39] [WARN 1708474992.863786247] [localization.pose_estimator.ndt_scan_matcher]: No InputSource. Please check the input lidar topic (service_ndt_align() at /home/shintarosakoda/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:864)
[pose_initializer_node-41] [INFO 1708474992.864026735] [localization.util.pose_initializer_node]: NDT align server failed. (align_pose() at /home/shintarosakoda/autoware/src/universe/autoware.universe/localization/pose_initializer/src/pose_initializer/ndt_module.cpp:43)
[service_log_checker-4] [ERROR 1708474992.864308161] [system.service_log_checker]: /localization/initialize: status code 4 'NDT align server failed.' (/localization/util/pose_initializer_node) (set_error() at /home/shintarosakoda/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:83)
[service_log_checker-4] [ERROR 1708474992.865189695] [system.service_log_checker]: /localization/initialize: status code 4 'NDT align server failed.' (/default_ad_api/node/localization) (set_error() at /home/shintarosakoda/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:83)
[service_log_checker-4] [ERROR 1708474992.865347276] [system.service_log_checker]: /api/localization/initialize: status code 4 'NDT align server failed.' (/default_ad_api/node/localization) (set_error() at /home/shintarosakoda/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:83)
```

Related PR

* https://github.com/autowarefoundation/autoware.universe/pull/6394

## Tests performed
https://tier4.github.io/driving_log_replayer/quick_start/installation/
Driving Log Replayer works fine
```bash
driving_log_replayer simulation run -p localization --rate 0.5
```

Logging Simulator works fine
```bash
# terminal 1
ros2 launch autoware_launch logging_simulator.launch.xml \
    map_path:=$HOME/autoware_map/sample-map-rosbag \
    vehicle_model:=sample_vehicle \
    sensor_model:=sample_sensor_kit

# terminal 2
ros2 bag play $HOME/autoware_map/sample-rosbag/sample.db3 -r 0.5 -s sqlite3
```

## Effects on system behavior

There are no effects on system behavior.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by anhnv3991** [comment]
@SakodaShintaro The logging simulator is OK. However, I am trying to install Driving Log Replayer but when colcon build the following error occurred
`Starting >>> eagleye_navigation
--- stderr: rosbag2_py_wrapper                                                                                                                                                                       
lto-wrapper: warning: using serial compilation of 2 LTRANS jobs
---
Finished <<< rosbag2_py_wrapper [24.2s]
Starting >>> eagleye_geo_pose_fusion
--- stderr: geometry                                                                                                                                                                                 
/home/anh/Work/autoware/src/simulator/scenario_simulator/common/math/geometry/src/bounding_box.cpp:15:10: fatal error: quaternion_operation/quaternion_operation.h: No such file or directory
   15 | #include <quaternion_operation/quaternion_operation.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/geometry.dir/build.make:76: CMakeFiles/geometry.dir/src/bounding_box.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:211: CMakeFiles/geometry.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
`
But I could not find that quaternion_operation.h file anywhere in the system. How can I fix it?

**Comment by anhnv3991** [comment]
@SakodaShintaro The logging simulator is OK, but the Driving Log Replayer is not. I tried to install the Driving Log Replayer but when colcon build, the below error showed up
`/home/anh/Work/autoware/src/simulator/scenario_simulator/common/math/geometry/src/bounding_box.cpp:15:10: fatal error: quaternion_operation/quaternion_operation.h: No such file or directory
   15 | #include <quaternion_operation/quaternion_operation.h>
`
I could not find that header anywhere in the system. Do you know how to fix it? This error belongs to the scenario_simulator_v2.

**Comment by SakodaShintaro** [comment]
@anhnv3991 

In my environment, ros-humble-quaternion-operation has been installed.
```bash
$ sudo apt list | grep quaternion-operation

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ros-humble-quaternion-operation-dbgsym/jammy 0.0.11-1jammy.20240126.001735 amd64
ros-humble-quaternion-operation/jammy,now 0.0.11-1jammy.20240126.001735 amd64 [インストール済み]
ros-iron-quaternion-operation-dbgsym/jammy 0.0.7-4jammy.20240207.210444 amd64
ros-iron-quaternion-operation/jammy 0.0.7-4jammy.20240207.210444 amd64
````

This dependency is described in common/math/geometry/package.xml.

https://github.com/tier4/scenario_simulator_v2/blob/master/common/math/geometry/package.xml#L15

So, I think the commands below seem to work.

```
rosdep update
rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
```

**Comment by anhnv3991** [comment]
@SakodaShintaro This is the terminal output of my Driving Log Replayer.
[terminal_output.txt](https://github.com/autowarefoundation/autoware.universe/files/14368719/terminal_output.txt)
This looks OK to me.

**Comment by anhnv3991** [comment]
@SakodaShintaro This is the output of the logging simulator.
[logging_simulator_output.txt](https://github.com/autowarefoundation/autoware.universe/files/14368761/logging_simulator_output.txt)
The 'NoInputSource' error is not found here, so I think it should be OK.
The run looks OK to me.
[Screencast from 22-02-2024 11:35:15.webm](https://github.com/autowarefoundation/autoware.universe/assets/11849905/a98bf406-ece5-4ba3-8cd1-32d53cd53e15)

**Comment by SakodaShintaro** [comment]
@anhnv3991 
This is normal behavior.
Thank you for confirming!

**Review by anhnv3991 — APPROVED** [review]
LGTM! Sorry for my late response.

**Pull request merged**
