### PR TITLE
fix(obstacle_cruise_planner): unknown collision calculation

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
You should remove appendPointToPolygon(Polygon2d & polygon, const geometry_msgs::msg::Point32 & geom_point)
image

**Comment by tkimura4** [comment]
image
image
image


The current implementation seems to work well.

**Comment by takayuki5168** [comment]
Thank you very much for your verification.
Actually, this commit is required to check an unknown's behavior, but I think it will work well too.
https://github.com/tier4/autoware_launch/pull/382/commits/e5228b6b69f308e023054939a16a84a29bbfcf08

**Comment by tkimura4** [comment]
@takayuki5168 
yes, I understood!
In this check,
I was set ignored_outside_obstacle_type.unknown to  true.
https://github.com/autowarefoundation/autoware.universe/pull/1226#issuecomment-1173795138

**Review by tkimura4 — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
:sasugassu:

**Pull request merged**
