### PR TITLE
fix(slow_down_planner): improper parameter used in slow down

### PR DESCRIPTION
**Pull request by satoshi-ota**
Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>

## Description

close https://github.com/autowarefoundation/autoware.universe/issues/2258

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@VRichardJP

**Comment by VRichardJP** [comment]
Is it working on your side?

I have tried your fork with these parameters:
```diff
=== src/universe/autoware.universe (git) ===
diff --git a/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml b/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
index 55a21d6cd..5d30ef879 100644
--- a/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
+++ b/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml
@@ -3,7 +3,7 @@
     hunting_threshold: 0.5                   # even if the obstacle disappears, the stop judgment continues for hunting_threshold [s]
     lowpass_gain: 0.9                        # gain parameter for low pass filter [-]
     max_velocity: 20.0                       # max velocity [m/s]
-    enable_slow_down: False                  # whether to use slow down planner [-]
+    enable_slow_down: True                  # whether to use slow down planner [-]
 
     stop_planner:
       # params for stop position
@@ -29,12 +29,12 @@
 
       # params for detection area
       detection_area:
-        lateral_margin: 1.0                  # offset from vehicle side edge for expanding the search area of the surrounding point cloud [m]
+        lateral_margin: 10.0                  # offset from vehicle side edge for expanding the search area of the surrounding point cloud [m]
 
       # params for velocity
       target_velocity:
-        max_slow_down_velocity: 1.38         # max slow down velocity (use this param if consider_constraints is False)[m/s]
-        min_slow_down_velocity: 0.28         # min slow down velocity (use this param if consider_constraints is False)[m/s]
+        max_slow_down_velocity: 10.0         # max slow down velocity (use this param if consider_constraints is False)[m/s]
+        min_slow_down_velocity: 10.0         # min slow down velocity (use this param if consider_constraints is False)[m/s]
         slow_down_velocity: 1.38             # target slow down velocity (use this param if consider_constraints is True)[m/s]
 
       # params for deceleration constraints (use this param if consider_constraints is True)
diff --git a/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py b/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py
index 91bc71379..8d9f5b9af 100644
--- a/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py
+++ b/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py
@@ -209,7 +209,7 @@ def launch_setup(context, *args, **kwargs):
             obstacle_stop_planner_param,
             obstacle_stop_planner_acc_param,
             vehicle_info_param,
-            {"enable_slow_down": False},
+            # {"enable_slow_down": False},
         ],
         extra_arguments=[{"use_intra_process_comms": LaunchConfiguration("use_intra_process")}],
     )

```

I can see the slow down markers, but the speed seems not to be limited to 10km/h:
image

**Comment by VRichardJP** [comment]
Sorry I am silly. With these parameters it works:
```
max_slow_down_velocity: 2.78
min_slow_down_velocity: 2.78
```

What about the `motion_planning.launch.py`? Does it makes sense to keep the hardcoded `{"enable_slow_down": False}` while it can be set in the yaml file?

**Comment by satoshi-ota** [comment]
@VRichardJP hmm... :thinking: I'll check it again with your parameters setting.

**Comment by satoshi-ota** [comment]
@VRichardJP

> With these parameters it works:

That's good :+1: Previously, `enable_slow_down` was not included in the yaml file, so it was hardcoded into the launch file `motion_planning.launch.py`. Now it is not needed, so I'll remove that in this PR.

**Review by VRichardJP — APPROVED** [review]

**Review by taikitanaka3 — APPROVED** [review]

**Review by taikitanaka3 — APPROVED** [review]

**Review by shmpwk — APPROVED** [review]

**Pull request merged**
