### PR TITLE
feat(neural_networks_provider): port neural_networks_provider

### PR DESCRIPTION
**Pull request by LucaFos**
Port neural_networks from Autoware.Auto, this package
is used to download pre-compiled networks.
Also add artifact hash functionality, used for checking
whether there is a new version of the networks in the S3 bucket.

Issue-Id: SCM-4491
Signed-off-by: Luca Foschiani <luca.foschiani@arm.com>
Change-Id: Ia18e239797989a2639dc01dcea2abeaeacd94f44

## Description
This package adds neural networks downloading functionality. It has been ported from Autoware.Auto.

## Related links
https://github.com/autowarefoundation/autoware.universe/issues/628
https://github.com/autowarefoundation/autoware/discussions/226

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@LucaFos Pls fix some CI errors :pray:

**Comment by ambroise-arm** [comment]
@yukkysaito done

**Comment by yukke42** [comment]
@LucaFos I couldn't understand what this package will do from the package name. In my opinion, the package should be changed to name that means to download the file from model zoo in this PR or after merged.

**Comment by xmfcx** [comment]
@yukke42 wrote:
> @LucaFos I couldn't understand what this package will do from the package name. In my opinion, the package should be changed to name that means to download the file from model zoo in this PR or after merged.

I've tried to explain the structure from the Autoware.Auto here: https://github.com/orgs/autowarefoundation/discussions/226

But I agree we can find better names for these repositories.

@LucaFos @ambroise-arm do you think we can rename the package to `neural_network_downloader` or `model_zoo_downloader`?

Do you think we should do it within this PR or after it is merged?

**Comment by ambroise-arm** [comment]
I have no problem changing the name in this PR.
Note that the package also allows the user to provide their own networks locally, so it is not solely a downloader. What do you think of `neural_networks_provider`?

**Comment by xmfcx** [comment]
> I have no problem changing the name in this PR. Note that the package also allows the user to provide their own networks locally, so it is not solely a downloader. What do you think of `neural_networks_provider`?

@ambroise-arm That sounds good, it should work! Thank you.

**Comment by ambroise-arm** [comment]
Done

**Comment by ambroise-arm** [comment]
@xmfcx If you are happy with the PR can you merge it? Luca is not around to do it.

**Comment by xmfcx** [comment]
@ambroise-arm @LucaFos I've renamed the PR title to reflect the new package name.

Then squashed and renamed the commit name to match the PR title to pass the https://github.com/autowarefoundation/autoware.universe/runs/6964038208?check_suite_focus=true CI.

Also rebased/cherry-picked the commits of https://github.com/autowarefoundation/autoware.universe/pull/893 onto this PR.

Now will merge this to the main branch.

**Pull request merged**
