### PR TITLE
refactor(elevation_map_loader)!: fix namespace and directory structure

### PR DESCRIPTION
**Pull request by technolojin**
## Description
This PR puts headers in the `autoware` namespace.

Additional works
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468)   [LIST](https://github.com/autowarefoundation/autoware.universe/pull/3606)

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Tested in a local recompute environment and the TIER IV Cloud environment.
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/dccc10d6-26a4-5389-9712-b821f000bdb1?project_id=prd_jt)

## Notes for reviewers
None.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Review by esteve — CHANGES_REQUESTED** [review]
@technolojin could you also make the changes to rename the package and the directory? It's easier to review if it's all in one go. Thanks.

**Comment by technolojin** [comment]
> @technolojin could you also make the changes to rename the package and the directory? It's easier to review if it's all in one go. Thanks.

As I mentioned in https://github.com/autowarefoundation/autoware/issues/4569#issuecomment-2188129685, I will do it in separated PRs

**Comment by yukkysaito** [comment]
>As I mentioned in https://github.com/autowarefoundation/autoware/issues/4569#issuecomment-2188129685, I will do it in separated PRs

I feel that splitting the PR is not particularly problematic for me.

**Comment by technolojin** [comment]
@esteve Can you response on this topic?

**Comment by esteve** [comment]
@technolojin we'll discuss this in the ASWG, because the process the perception team at TierIV is following regardin this task doesn't seem to be aligned with what we agreed originally, see https://github.com/orgs/autowarefoundation/discussions/4097#discussioncomment-9234315

As @TakaHoribe said, the Autoware project shouldn't be limited in what it can do or not just because of one company (in this case, TierIV)

**Pull request closed without merging**
