### PR TITLE
refactor(map_projection_loader)!: prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add the `autoware_` prefix to `map_projection_loader`.

***This PR will affect***
-  autoware_tools: https://github.com/autowarefoundation/autoware_tools/pull/93

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Confirmed with running sample-map.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — CHANGES_REQUESTED** [review]
Thank you for the pull request.
Please fix `launch/tier4_map_launch/package.xml` :pray: 

```bash
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tier4_map_launch: Cannot locate rosdep definition for [map_projection_loader]
```

**Comment by a-maumau** [comment]
@SakodaShintaro Sorry for overlooking the `tier4_map_launch`, I fixed it at [4f95dfa](https://github.com/autowarefoundation/autoware.universe/pull/8420/commits/4f95dfa752fc2b97b20b3d7b06a3fd49bc1d473b) .

**Comment by SakodaShintaro** [comment]
@a-maumau Sorry, could you resolve some conflicts?

**Comment by a-maumau** [comment]
@SakodaShintaro I have resolved the conflicts.

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that logging_simulator works well and the mean error is almost the same as before.

- **Directory Name**
  - [x] Add `autoware_` as a prefix to the directory name.

- **packages.xml**
  - [x] Add `autoware_` to the `name` element.

- **CMakeLists.txt**
  - [x] Change the `project` name to `autoware_***`.
  - [x] Add `autoware::` to `PLUGIN`.

- **Header Files (.hpp)**
  - [x] Add `autoware::` to `namespace`.
  - [x] Add `autoware` folder as necessary and update include statements accordingly.

- **Source Files (.cpp)**
  - [x] Add `autoware::` inside `RCLCPP_COMPONENTS_REGISTER_NODE`.

- **Launch Files**
  - [x] Add `autoware_` before `find-pkg-share`.
  - [x] Change `node pkg="<pkgname>"` to `autoware_<pkgname>`.

- **Verification Points**
  - [x] Search `find-pkg-share` in autoware
  - [x] Check README file (especially json schema)
  - [x] Pay attention to complex cases like `sensor_launch` as seen in `gnss_poser`

**Comment by SakodaShintaro** [comment]
@kosuke55 @takayuki5168 
Could you review this pull request?

**Review by takayuki5168 — APPROVED** [review]

**Pull request merged**
