### PR TITLE
refactor(autoware_obstacle_stop_planner): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

See https://github.com/autowarefoundation/autoware/issues/4569

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@satoshi-ota @shmpwk can you have a look at this PR when you have a moment? Thanks.

**Review by shmpwk — APPROVED** [review]

**Comment by esteve** [comment]
@shmpwk I don't know why this PR hasn't been merged automatically after you approved it, do you know why?

**Comment by brkay54** [comment]
@esteve Hi, a required CI check named `pre-commit.ci-pr` was not passed. 
```bash
cpplint..................................................................Failed
- hook id: cpplint
- exit code: 1

planning/autoware_obstacle_stop_planner/src/planner_utils.cpp:392:  Add #include <algorithm> for min  [build/include_what_you_use] [4]
planning/autoware_obstacle_stop_planner/src/planner_utils.cpp:569:  Add #include <limits> for numeric_limits<>  [build/include_what_you_use] [4]
Done processing planning/autoware_obstacle_stop_planner/src/planner_utils.cpp
Total errors found: 2
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp:430:  Add #include <utility> for make_pair  [build/include_what_you_use] [4]
Done processing planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/autoware_obstacle_stop_planner/src/debug_marker.cpp:537:  Add #include <limits> for numeric_limits<>  [build/include_what_you_use] [4]
Done processing planning/autoware_obstacle_stop_planner/src/debug_marker.cpp
Total errors found: 2
```

**Comment by esteve** [comment]
@brkay54 thanks, the issues should be fixed in caf4196a4bc1d47aa63520dac5a9d3af47da99c6

**Pull request merged**
