### PR TITLE
chore(sensing, perception): fix universe documentation

### PR DESCRIPTION
**Pull request by technolojin**
## Description

Fix error of the following pages.

- https://autowarefoundation.github.io/autoware.universe/main/perception/autoware_object_merger/
- https://autowarefoundation.github.io/autoware.universe/main/perception/autoware_probabilistic_occupancy_grid_map/
- https://autowarefoundation.github.io/autoware.universe/main/perception/autoware_occupancy_grid_map_outlier_filter/
- https://autowarefoundation.github.io/autoware.universe/main/sensing/autoware_pointcloud_preprocessor/docs/blockage_diag/
- https://autowarefoundation.github.io/autoware.universe/main/sensing/autoware_pointcloud_preprocessor/docs/downsample-filter/
- https://autowarefoundation.github.io/autoware.universe/main/sensing/autoware_pointcloud_preprocessor/docs/passthrough-filter/

## Related links

**Parent Issue:**

- Link

## How was this PR tested?

Documentation generation is confirmed by the following local generation method.

https://autowarefoundation.github.io/autoware-documentation/main/contributing/documentation-guidelines/#2-running-an-mkdocs-server-in-your-local-environment

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by vividf** [comment]
@technolojin Hi Lee-San, Thanks for your PR. However, for the sensing one some of them are fixed in another PR https://github.com/autowarefoundation/autoware.universe/pull/9765

**Comment by vividf** [comment]
@technolojin I think also for the perception as well, could we merge that one first? Thanks

**Review by technolojin — COMMENTED** [review]
I added some missing default values.

**Comment by technolojin** [comment]
already done https://github.com/autowarefoundation/autoware.universe/pull/9766 https://github.com/autowarefoundation/autoware.universe/pull/9765

**Pull request closed without merging**
