### PR TITLE
Update range_libc pywrapper scripts

### PR DESCRIPTION
**Pull request by atanasko**
## Description
Update range_libc pywrapper scripts

## Related links

**Parent Issue:**

- Link

## How was this PR tested?
Using test.py script

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by Shin-kyoto** [comment]
@atanasko 

Thank you for submitting PR!
This PR is too large to review. Can you split this PR?

**Comment by atanasko** [comment]
> @atanasko
> 
> Thank you for submitting PR! This PR is too large to review. Can you split this PR?

I'll try to do that. Should I close this PR and create new?

**Comment by Shin-kyoto** [comment]
> > @atanasko
> 
> > 
> 
> > Thank you for submitting PR! This PR is too large to review. Can you split this PR?
> 
> @Shin-kyoto 
> 
> I'll try to do that. Should I close this PR and create new?

Yes, please close this PR and create new 🙏

**Comment by atanasko** [comment]
This pull request is closed due to the new one created #8603

image

**Pull request closed without merging**
