### PR TITLE
feat(lane change): support new framework external request

### PR DESCRIPTION
**Pull request by zulfaqar-azmi-t4**
## Description

Use lane change module to generate external lane change.
Also support lane change new framework.

## Related links

⬇️ modified parameter to disable by default.
https://github.com/autowarefoundation/autoware.universe/pull/3068

## Tests performed

Please set following flag to `FALSE`, and confirm to pass all build.

https://github.com/autowarefoundation/autoware.universe/blob/ad5595389a629346476ee06391260ffea53159ef/planning/behavior_path_planner/CMakeLists.txt#L10

## Notes for reviewers

At the moment, external lane change still couldn't be executed simultaneously.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@zulfaqar-azmi-t4 Do you have any result of Evaluator Test on old manager? If you have and there is no critical regression, it looks good to me. 

On the other hand, unfortunatelly, since the new manager can't execute multiple candidate modules simlutaneously, maybe the ext LC module(s)  don't work as expected on new manager, and I'm working on fixing it now. So, I suppose that it is better to set config to not launch ext LC on the new manager until the issue is fixed.

```yaml
    ext_request_lane_change_left:
      enable_module: false
      enable_simultaneous_execution: false
      priority: 6
      max_module_size: 1
    ext_request_lane_change_right:
      enable_module: false
      enable_simultaneous_execution: false
      priority: 6
      max_module_size: 1
```

**Comment by zulfaqar-azmi-t4** [comment]
@satoshi-ota 
Yes, the PR has been tested on evaluator and no degradation found
[TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/cbfdf519-bfbd-5534-be57-cd2f6243f26f?project_id=prd_jt)

**Comment by satoshi-ota** [comment]
@zulfaqar-azmi-t4 Thanks :+1: I'll approve after the launch PR is merged.

**Comment by zulfaqar-azmi-t4** [comment]
@satoshi-ota 
https://github.com/autowarefoundation/autoware_launch/pull/262

this is the modified parameter PR

**Review by satoshi-ota — APPROVED** [review]
LGTM :+1:

**Review by rej55 — APPROVED** [review]

**Pull request merged**
