### PR TITLE
fix(traffic_light_multi_camera_fusion): assign multiple regulatory element id for one traffic light

### PR DESCRIPTION
**Pull request by TomohitoAndo**
## Description

In the current implementation, if a traffic light is linked to multiple regulatory elements, the multi-camera fusion only publishes one signal with a regulatory element. I've updated it to publish all associated regulatory elements with the traffic light perception results.

image

## Tests performed

Tested in simple planning simulator.
This was tested in a basic planning simulator. Below is the output when traffic light 2400 is associated with regulatory elements 1489 and 1493.

### Before

```
$ ros2 topic echo /perception/traffic_light_recognition/internal/traffic_signals
stamp:
  sec: 1692786155
  nanosec: 696961024
signals:
- traffic_signal_id: 1489
  elements:
  - color: 1
    shape: 1
    status: 0
    confidence: 0.9967631101608276
```

### After

```
stamp:
  sec: 1692786410
  nanosec: 596963840
signals:
- traffic_signal_id: 1489
  elements:
  - color: 1
    shape: 1
    status: 0
    confidence: 0.6648706793785095
- traffic_signal_id: 1493
  elements:
  - color: 1
    shape: 1
    status: 0
    confidence: 0.6648706793785095
```

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TomohitoAndo** [comment]
cc: @tkimura4

**Comment by TomohitoAndo** [comment]
@miursh 
Could you review? :pray:

**Comment by miursh** [comment]
@TomohitoAndo Than you!! I will check this by tonight.

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
