### PR TITLE
chore(blockage_diag): add dust diagnostic option param

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description
- To change dust diagnostics and publish debug image as optional. There is no any change in blockage and dust detection result.
- Need merge together with param update for each product 
   - https://github.com/tier4/aip_launcher/pull/225
   - https://github.com/tier4/aip_launcher/pull/224

## Related link 
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1710731596847099?thread_ts=1710731286.879449&cid=C03S84LDJGG)

## Tests performed

- Confirmed by `logging_simulator` that each `blockage_diag` node reflected the optional params correctly.
```
enable_dust_diag: false
publish_debug_image: false
```
image

```
enable_dust_diag: true
publish_debug_image: false
```

image

```
enable_dust_diag: false
publish_debug_image: true
```

image

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by badai-nguyen** [comment]
@kyoichi-sugahara Could I ask your review for this PR and the releated ones?

**Comment by kyoichi-sugahara** [comment]
how about adding following callback?
```
  if (get_param(p, "publish_debug_image", publish_debug_image_)) {
    RCLCPP_DEBUG(get_logger(), "Setting new publish_debug_image_ to: %d.", publish_debug_image_);
  }
  if (get_param(p, "enable_dust_diag", enable_dust_diag_)) {
    RCLCPP_DEBUG(get_logger(), "Setting new enable_dust_diag_ to: %d.", enable_dust_diag_);
  }
  ```

**Comment by badai-nguyen** [comment]
@kyoichi-sugahara Thank you for your comment.
However, if we make `publish_debug_image` and `enable_dust_diag` to be able to change by callback, then
1. debug image topics and `blockage_diag/debug/ground_dust_ratio` topics will be created but nothing to be published
2. Even `enable_dust_diag=False`, there will be many dust related diag validation will be created in `rqt_runtime_monitor`
image
That might make users confused.

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM!

**Pull request merged**
