### PR TITLE
feat(tier4_localization_rviz_plugin): add pose history footprint

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

Add a plugin to visualize footprint from pose history as in this screenshot.

image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@TakaHoribe Clear command (= clear pose history) will be disabling the plugin?

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Comment by isamu-takagi** [comment]
@TakaHoribe Could you add you as a maintainer?

**Comment by TakaHoribe** [comment]
@isamu-takagi OK.

**Comment by TakaHoribe** [comment]
@isamu-takagi I updated the maintainer list. Please check it.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Review by yabuta — APPROVED** [review]
LGTM

**Pull request merged**
