### PR TITLE
refactor(component_interface_specs): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@esteve Thank you. Could you please update to use `autoware::component_interface_specs::<module>` instead of `autoware::component_interface_specs::<module>_interface`, as the original namespace has become redundant with the addition of the package name? Or I'll update it next week when I can work on it.

**Comment by esteve** [comment]
@isamu-takagi thanks for the review. I've moved this PR back to draft so that I'll make the changes you requested.

**Comment by esteve** [comment]
@isamu-takagi this is now ready for review again

**Review by isamu-takagi — APPROVED** [review]
Thank you. I checked autonomous driving using the planning simulator.

**Comment by SakodaShintaro** [comment]
I got the following error:

```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
autoware_iv_external_api_adaptor: Cannot locate rosdep definition for [component_interface_specs]
```

The following line in the package.xml file at https://github.com/tier4/tier4_ad_api_adaptor/blob/tier4/universe/autoware_iv_external_api_adaptor/package.xml#L18 needs to be modified.

**Comment by SakodaShintaro** [comment]
Sorry, I missed your comment https://github.com/autowarefoundation/autoware.universe/pull/9094#issuecomment-2416556211

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that `logging_simulator` with [sample_rosbag](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works well.
LGTM for localization and map.

**Comment by esteve** [comment]
@isamu-takagi @SakodaShintaro thank you very much for your review

@xmfcx @mitsudome-r given that @isamu-takagi approved this PR and he's one of the maintainers of the `autoware_component_interface_specs` package, would it be ok to merge this PR without waiting for all the other reviewers who are code owners of downstream packages? Thanks

**Comment by xmfcx** [comment]
Combined with:
- https://github.com/tier4/tier4_ad_api_adaptor/pull/126
On my machine, I was able to build and test successfully.
`Summary: 246 packages finished [16min 40s]`

Even if the codebuild CI fails, we can merge this.

**Comment by xmfcx** [comment]
@mitsudome-r with:
- https://github.com/autowarefoundation/autoware.universe/pull/9166

The CI has passed.

**Pull request merged**
