### PR TITLE
fix(ground_segmentation): fix funcArgNamesDifferent

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck funcArgNamesDifferent warnings

```
perception/ground_segmentation/src/ray_ground_filter/node.cpp:275:26: style: inconclusive: Function 'ExtractPointsIndices' argument 3 names different: declaration 'out_only_indices_cloud_ptr' definition 'ground_cloud_msg_ptr'. [funcArgNamesDifferent]
  PointCloud2::SharedPtr ground_cloud_msg_ptr, PointCloud2::SharedPtr no_ground_cloud_msg_ptr)
                         ^

perception/ground_segmentation/src/ray_ground_filter/node.cpp:275:71: style: inconclusive: Function 'ExtractPointsIndices' argument 4 names different: declaration 'out_removed_indices_cloud_ptr' definition 'no_ground_cloud_msg_ptr'. [funcArgNamesDifferent]
  PointCloud2::SharedPtr ground_cloud_msg_ptr, PointCloud2::SharedPtr no_ground_cloud_msg_ptr)
                                                                      ^

perception/ground_segmentation/src/scan_ground_filter/node.cpp:115:73: style: inconclusive: Function 'convertPointcloudGridScan' argument 2 names different: declaration 'out_radial_ordered_points_manager' definition 'out_radial_ordered_points'. [funcArgNamesDifferent]
  const PointCloud2ConstPtr & in_cloud, std::vector<PointCloudVector> & out_radial_ordered_points)
                                                                        ^

perception/ground_segmentation/src/scan_ground_filter/node.cpp:169:73: style: inconclusive: Function 'convertPointcloud' argument 2 names different: declaration 'out_radial_ordered_points_manager' definition 'out_radial_ordered_points'. [funcArgNamesDifferent]
  const PointCloud2ConstPtr & in_cloud, std::vector<PointCloudVector> & out_radial_ordered_points)
                                                                        ^

perception/ground_segmentation/src/scan_ground_filter/node.cpp:336:31: style: inconclusive: Function 'classifyPointCloudGridScan' argument 1 names different: declaration 'in_cloud_ptr' definition 'in_cloud'. [funcArgNamesDifferent]
  const PointCloud2ConstPtr & in_cloud, std::vector<PointCloudVector> & in_radial_ordered_clouds,
                              ^

perception/ground_segmentation/src/scan_ground_filter/node.cpp:456:31: style: inconclusive: Function 'classifyPointCloud' argument 1 names different: declaration 'in_cloud_ptr' definition 'in_cloud'. [funcArgNamesDifferent]
  const PointCloud2ConstPtr & in_cloud, std::vector<PointCloudVector> & in_radial_ordered_clouds,
                              ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by veqcc — APPROVED** [review]

**Comment by kobayu858** [comment]
@amc-nu @badai-nguyen @miursh @YoshiRi @yukkysaito 

Please confirm the PR. Thank you very much.

**Review by YoshiRi — APPROVED** [review]
LGTM

**Comment by YoshiRi** [comment]
@kobayu858 Could you fix conflicts before merge

**Review by badai-nguyen — APPROVED** [review]
LGTM

**Pull request merged**
