### PR TITLE
feat(pointcloud_preprocessor): add test for distortion correction node

### PR DESCRIPTION
**Pull request by vividf**
## Description
Add Integration testing for the distortion correction node.

- test empty twist
- test empty imu
- test empty pointcloud
- test normal input without using imu msg
- test normal input using imu msg

## Tests performed
Build
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select pointcloud_preprocessor
```

Test
```
colcon test --packages-select pointcloud_preprocessor --event-handlers console_cohesion+
```

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by knzo25 — CHANGES_REQUESTED** [review]
I saw you are addressing directly the data of the pointcloud. In python there are still ways to access pointclouds via iterators. If not that approach, ros2_numpy would be an option, but probably not possible in universe. However, **I highly recommend** you re write pointcloud related tests to c++

On another note, please avoid using `don't` and similar abbreviations. They have leaked into other parts where they should not been before

**Comment by vividf** [comment]
@knzo25 

Thanks for the review, 
I agree that writing C++ tests is better for testing, however, this PR is not a Unit test but an Integration test (which tests the single node instead of the function). Regarding the Integration testing on the Autoware contribution ([testing the output of node](https://autowarefoundation.github.io/autoware-documentation/main/contributing/testing-guidelines/integration-testing/#:~:text=Testing%20the%20output,%23)), it suggests us to write in this way. Therefore, I am not sure that I should spend more time migrating it to the C++ version in this case. 

> I saw you are addressing directly the data of the pointcloud. In python there are still ways to access pointclouds via iterators. If not that approach, ros2_numpy would be an option, but probably not possible in universe.

For this comment, could you explain more in detail, Thanks!

**Comment by knzo25** [comment]
```
An integration test is defined as the phase in software testing where individual software modules are combined and tested as a group. Integration tests occur after unit tests, and before validation tests.

The input to an integration test is a set of independent modules that have been unit tested. The set of modules is tested against the defined integration test plan, and the output is a set of properly integrated software modules that is ready for system testing.
```

Having the briefest of looks your test is a unit test, since anyways the distortion correction has essentially one method

**Comment by vividf** [comment]
This PR is set to draft as we want the gtest instead of the component test.

**Comment by vividf** [comment]
The unit test is created by another PR https://github.com/autowarefoundation/autoware.universe/pull/7783.
 Therefore, this pr will be closed.

**Pull request closed without merging**
