### PR TITLE
refactor(autoware_interpolation): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]

**Comment by vividf** [comment]
@esteve please resolve the conflicts :)

**Comment by esteve** [comment]
@vividf fixed. It'd be nice to get a review from the other code owners, this PR was originially submitted almost a month ago, so it'll probably get conflicts again.

**Comment by esteve** [comment]
@xmfcx do you have a moment to review this? Thanks.

**Review by miursh — APPROVED** [review]

**Review by TakaHoribe — APPROVED** [review]

**Review by takayuki5168 — APPROVED** [review]

**Review by YoshiRi — APPROVED** [review]
LGTM for perception packages

**Comment by kosuke55** [comment]
I will check the test failure
https://github.com/autowarefoundation/autoware.universe/actions/runs/10487288486/job/29047329337?pr=8088
```
1:  vehicle model = ACTUATION_CMD
1: 
1: /__w/autoware.universe/autoware.universe/simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp:251: Failure
1: Expected: (dy) < (right_thr), actual: -0.0987763 vs -0.1
1: [curr] state x: -5.20484, y: -0.0987763, yaw: 0.0753325, vx = -7.1469, vy: 0, wz: 0.232693, [init] state x: 0, y: 0, yaw: 0, vx = 0, vy: 0, wz: 0
1: [  FAILED  ] TestForEachVehicleModelTrue/TestSimplePlanningSimulator.TestIdealSteerVel/7, where GetParam() = (4-byte object <01-00 00-00>, "ACTUATION_CMD") (7045 ms)
1: [----------] 8 tests from TestForEachVehicleModelTrue/TestSimplePlanningSimulator (56358 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 8 tests from 1 test suite ran. (56358 ms total)
1: [  PASSED  ] 7 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] TestForEachVehicleModelTrue/TestSimplePlanningSimulator.TestIdealSteerVel/7, where GetParam() = (4-byte object <01-00 00-00>, "ACTUATION_CMD")
```

**Comment by kosuke55** [comment]
merged https://github.com/autowarefoundation/autoware.universe/pull/8630 to debug

**Comment by kosuke55** [comment]
@esteve 

Because I rebased with the latest autoware to pass the test, there are other areas that need to be replaced. Could you please respond to this? :pray: 


image

**Comment by kosuke55** [comment]
@esteve 

> Because I rebased with the latest autoware to pass the test, there are other areas that need to be replaced. Could you please respond to this? 🙏

I pushed to your branch

df599295ecb4f122c017650509b71b929bc4160f

**Comment by kosuke55** [comment]
required tests pass!!


image

**Comment by esteve** [comment]
@kosuke55 thanks for the fixes :bowing_man:  I've rebased this PR on top of `main` and fixed the conflicts.

**Comment by esteve** [comment]
@mitsudome-r @xmfcx I've fixed the conflicts again, could you approve this PR when you can? Thanks

**Comment by xmfcx** [comment]
I see that 
- https://github.com/autowarefoundation/autoware.universe/pull/8903
Caused this to have conflicts again.

So to keep @esteve 's commits intact:
- I've reverted #8903 
- applied esteve's commits without modifications
- then applied #8903 again and fixed the conflicts

Now it's all on the main branch again, rebased.

**Comment by xmfcx** [comment]
@yhisaki could you check if your changes are applied correctly?

**Comment by xmfcx** [comment]
Tested the latest changes using AWSIM Labs to test it end to end. And it works without problems.

image

**Comment by xmfcx** [comment]
@yhisaki I've merged this since it has been up for a long while and it becomes harder as more time passes since it's a large refactor.

Please check and confirm if the changes from:
- https://github.com/autowarefoundation/autoware.universe/pull/8903
are still applied and create a new PR if there is an issue.

**Comment by yhisaki** [comment]
I have confirmation that my PR is properly in place.
Thank you!

**Pull request merged**
