### PR TITLE
docs(simulator): fixed simple_planning_simulator table

### PR DESCRIPTION
**Pull request by soblin**
docs(simulator): fixed simple_planning_simulator table

Signed-off-by: Mamoru Sobue <mamoru.sobue@tier4.jp>

## Description

Fixed markdown table to be rendered properly.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by maxime-clem — APPROVED** [review]
Thank you for fixing this issue. The updated tables look good.

**Comment by soblin** [comment]
Looks like pre-commit-optional is failing because it is mistakenly treating https://<>/<>/#toc-xxx as a dead link in behavior_velocity_planner/run-out-design.md

**Comment by soblin** [comment]
@kenji-miyake This is a very minor change, but can you merge this when available? (the priority is low)

**Comment by kenji-miyake** [comment]
@soblin I believe you have write access to this repository and merge this PR by yourself.

**Comment by kenji-miyake** [comment]
@soblin By the way, you have to update the branch to pass pre-commit. Please click the button.
image

**Comment by maxime-clem** [comment]
Some `flake8 ros` issue may be blocking the merge: https://results.pre-commit.ci/run/github/429651616/1654472924.YDeZ6XC2S-W9JvCE9USHbA
```
common/tier4_debug_tools/scripts/stop_reason2pose.py:96:21: C417 Unnecessary use of map - use a generator expression instead.
        distances = map(lambda p: StopReason2PoseNode.calc_distance2d(p, self_pose), poses)
```
But this is not related to this PR 🤔

**Pull request merged**
