### PR TITLE
feat(obstacle_stop_planner): add configurable lateral_distance for different target objects

### PR DESCRIPTION
**Pull request by beyzanurkaya**
## Description

Fixes: #2222

Before this PR, [#140](https://github.com/autowarefoundation/autoware_launch/pull/140) needs to merge

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by beyzanurkaya** [comment]
@taikitanaka3  It's ready to review.

**Comment by taikitanaka3** [comment]
@beyzanurkaya 
Thank you for PR but there are a lot of changes made.
Can you describe changes in readme?

@satoshi-ota
I want you to review this PR, is it OK?

**Comment by satoshi-ota** [comment]
@beyzanurkaya Thanks for your contribution. I'll review this PR.

**Comment by satoshi-ota** [comment]
@beyzanurkaya I check that the module work correctly in my local env, so lastly, I test this branch by evaluator. Please wait for a while.

https://user-images.githubusercontent.com/44889564/218083014-ec41dbba-ae1c-4346-86c4-2ccb2eb0993f.mp4

**Comment by satoshi-ota** [comment]
@beyzanurkaya I checked that there is no critical bug in this PR by evaluator. LGTM.

**Comment by beyzanurkaya** [comment]
@satoshi-ota Can you approved this PR?

**Review by satoshi-ota — APPROVED** [review]

**Comment by satoshi-ota** [comment]
@beyzanurkaya CI/CD shows pre-commit error. Please check it.

> planning/obstacle_stop_planner/src/node.cpp:994:  Small and focused functions are preferred: ObstacleStopPlannerNode::searchObstacle() has 555 non-comment lines (error triggered by exceeding 500 lines).  [readability/fn_size] [1]
Done processing planning/obstacle_stop_planner/src/node.cpp
Total errors found: 1

**Comment by satoshi-ota** [comment]
@beyzanurkaya I checked it. You can merge this. Thanks :+1:

**Pull request merged**
