### PR TITLE
feat(map_loader): use cylindrical area for map loader

### PR DESCRIPTION
**Pull request by kminoda**
### Background
pose_initializer (map_height_fitter) failed when the z of pointcloud map was over 50m (or under -50m). This was due to the spherical area query in `partial_map_loading`. Instead, we should use cylindrical area query with infinite height.

### Changes
Change [AreaInfo.msg](https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_map_msgs/msg/AreaInfo.msg), which is used as an query to load a specific pointcloud maps in that area, as follows

Before:
```
# Area info used as a query in map loading service
# Note: this only supports spherical area message for now

geometry_msgs/Point center
float32 radius
```

After
```
# Area info used as a query in map loading service
# Note: this only supports cylindrical area message for now

float32 center_x
float32 center_y
float32 radius
```

I changed some nodes that uses the interface accordingly. 

## Related links
- https://github.com/autowarefoundation/autoware_msgs/pull/64

## Tests performed
Confirmed that logging_simulator works with a sample map and rosbag

## Notes for reviewers
No performance changes (except `map_height_fitter`)

## Interface changes
AreaInfo.msg in autoware_map_msgs changes.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by badai-nguyen — APPROVED** [review]
LGTM regarding compare_map_segmentation

**Review by KYabuuchi — APPROVED** [review]
I verified this by running logging_simulator with split sample maps. And it worked correctly. :+1:

**Review by RyuYamamoto — APPROVED** [review]
LGTM

**Comment by kminoda** [comment]
@isamu-takagi @YamatoAndo Could you review this PR as well? (Please dismiss the failing CI, as this PR is also related to autoware_msgs modicification)

**Review by YamatoAndo — APPROVED** [review]
LGTM regarding map_height_fitter

**Pull request merged**
