### PR TITLE
chore(autoware_vehicle_info_utils): move package to common directory

### PR DESCRIPTION
**Pull request by mitsudome-r**
## Description

This moves autoware_vehicle_info_utils into common directory since the package is used by the packages in different modules (planning, control, system, common, etc)

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware.universe/issues/8695

## Notes for reviewers

This PR does not change anything in the code and shouldn't have any affect on Autoware's behavior.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by tkimura4** [comment]
@mitsudome-r 
I think the following files might also need to be changed.

https://github.com/autowarefoundation/autoware.universe/blob/main/.github/CODEOWNERS

**Comment by taikitanaka3** [comment]
@mitsudome-r 
I think git log was deleted by this PR.
so I think it's better to use git filter repo instead

**Comment by mitsudome-r** [comment]
@tkimura4 Thanks. I think the codeowner should be updated automatically by this workflow: https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/update-codeowners-from-packages.yaml

**Comment by mitsudome-r** [comment]
@taikitanaka3 
> I think git log was deleted by this PR.
> so I think it's better to use git filter repo instead

Thanks for the suggestion. I have never used it before. I can take a look, but is the tool able to retain the git history without making a force-push to the main branch? I rather not do disturbing changes to the commit history of the main branch.

Also FYI, you should still able to track the history by adding `--follow` option. (e.g., `git log --follow common/autoware_vehicle_info_utils/src/vehicle_info_utils.cpp`) You can also check through GitHub UI by clicking "Browse History" in [commit history](https://github.com/mitsudome-r/autoware.universe/commits/mv-vehicle-info-utils/common/autoware_vehicle_info_utils/src/vehicle_info.cpp) page, although this only works with a file and not with a directory.
image

**Review by taikitanaka3 — APPROVED** [review]
@mitsudome-r 
lgtm for me

**Review by tkimura4 — APPROVED** [review]

**Comment by youtalk** [comment]
@mitsudome-r Could you merge this?

**Pull request merged**
