### PR TITLE
fix(motion_velocity_smoother): use common ego nearest search

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description
use the new nearest index search algorithm in motion velocity smoother to deal with edge cases shown in the issue.

## Related links
issue
https://github.com/autowarefoundation/autoware.universe/issues/1581

depends on
https://github.com/autowarefoundation/autoware.universe/pull/1582
https://github.com/tier4/autoware_launch/pull/437

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
I confirmed this PR works well

**Review by rej55 — COMMENTED** [review]
@takayuki5168 
Please fix the following function.

https://github.com/autowarefoundation/autoware.universe/blob/7748688557ceffb902f326d79b453add00dc9d81/planning/behavior_velocity_planner/include/utilization/trajectory_utils.hpp#L129-L171

**Comment by takayuki5168** [comment]
@rej55 The function you pointed out is in behavior_velocity_planner. Is it related to this PR?

**Comment by takayuki5168** [comment]
I will wait for the PR of behavior velocity planner.

**Pull request merged**
