### PR TITLE
fix(ad_service_state_monitor): rad2deg conversion

### PR DESCRIPTION
**Pull request by h-ohta**
## Description(required)
This PR fixes
- add parameter setting
- convert degree to radian  for th_arrived_angle

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@h-ohta 
I think this PR name should be feat(~): ~ or chore: ~

**Comment by kenji-miyake** [comment]
Why? It seems a bug fix.

**Comment by h-ohta** [comment]
This is bug fix. 
Before, `state_param_.th_arrived_angle` was not converted degree to radian, but now this is fixed.
In addition to that, I forget `<param name="th_arrived_angle_deg" value="$(var th_arrived_angle_deg)" />` in launch.xml, so I also fix.

**Review by tkimura4 — APPROVED** [review]
LGTM
(Could you add release note to this PR?)

**Comment by tkimura4** [comment]
The DCO check was failed.
You need to sign the commit.

**Comment by h-ohta** [comment]
@tkimura4 Could you tell me where release node is?

**Comment by taikitanaka3** [comment]
@tkimura4 
it looks like it's [written](https://tier4.atlassian.net/wiki/spaces/AIP/pages/2255913621/WIP+universe#ad_service_state_monitor%3A-deg%E3%81%8B%E3%82%89rad%E3%81%B8%E3%81%AE%E5%A4%89%E6%8F%9B%E3%82%92%E5%BF%98%E3%82%8C%E3%81%A6%E3%81%84%E3%81%9F%E5%95%8F%E9%A1%8C%E3%82%92%E4%BF%AE%E6%AD%A3)

**Pull request merged**
