### PR TITLE
style: update rviz plugin icons to match the theme

### PR DESCRIPTION
**Pull request by KhalilSelyan**
## Description
Updated icon colors on the toolbuttons to match the theme
## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4534

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by yukkysaito** [comment]
Cloud you share the screen shot of new theme?

**Comment by yukkysaito** [comment]
>By the way, this icon might work well for people who have switched to Ubuntu’s dark theme, but wouldn't it be hard to see for those using the default theme?

I see :+1: 
You are in the process of changing it to default to dark theme
https://github.com/autowarefoundation/autoware/issues/4534

**Comment by xmfcx** [comment]
image

@yukkysaito the new icons are still readable under the default theme. It has low contrast but it is alright.

@KhalilSelyan these 2 need to be updated from the tools.repos:
image
`tier4_automatic_goal_rviz_plugin`

**Comment by xmfcx** [comment]
- https://github.com/autowarefoundation/autoware.universe/pull/6351

This is how they were initially generated, we just need to update the colors.


- 2D Rough Goal Pose: [Material Symbols Outlined: pin_drop](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apin_drop%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Dummy Pedestrian: [Material Symbols Outlined: directions_walk](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adirections_walk%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Dummy Car: [Material Symbols Outlined: directions_car](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adirections_car%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Dummy Bus: [Material Symbols Outlined: airport_shuttle](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aairport_shuttle%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Checkpoint Pose: [Material Symbols Outlined: flag](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aflag%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- Delete All Objects: [Material Symbols Outlined: delete](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adelete%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Dummy Bicycle: [Material Symbols Outlined: two_wheeler](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atwo_wheeler%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Dummy Unknown: [Material Symbols Outlined: package_2](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apackage_2%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- Third Person View: [Material Symbols Outlined: video_camera_front](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Avideo_camera_front%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- Bird Eye View: [Material Symbols Outlined: raven](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Araven%3AFILL%400%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Append Goal: [Material Symbols Outlined: sports_score](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asports_score%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)
- 2D Append Checkpoint: [Material Symbols Outlined: flag](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aflag%3AFILL%401%3Bwght%40400%3BGRAD%40200%3Bopsz%4020)

**Comment by KhalilSelyan** [comment]
> * [style(update): autoware tools icons #6351](https://github.com/autowarefoundation/autoware.universe/pull/6351)
> 
> This is how they were initially generated, I've updated the colors:
> 
> * 2D Rough Goal Pose: [Material Symbols Outlined: pin_drop](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:pin_drop:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Dummy Pedestrian: [Material Symbols Outlined: directions_walk](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:directions_walk:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Dummy Car: [Material Symbols Outlined: directions_car](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:directions_car:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Dummy Bus: [Material Symbols Outlined: airport_shuttle](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:airport_shuttle:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Checkpoint Pose: [Material Symbols Outlined: flag](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flag:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * Delete All Objects: [Material Symbols Outlined: delete](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:delete:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Dummy Bicycle: [Material Symbols Outlined: two_wheeler](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:two_wheeler:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Dummy Unknown: [Material Symbols Outlined: package_2](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:package_2:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * Third Person View: [Material Symbols Outlined: video_camera_front](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:video_camera_front:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * Bird Eye View: [Material Symbols Outlined: raven](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:raven:FILL@0;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Append Goal: [Material Symbols Outlined: sports_score](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:sports_score:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)
> * 2D Append Checkpoint: [Material Symbols Outlined: flag](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:flag:FILL@1;wght@400;GRAD@200;opsz@24&icon.size=24&icon.color=%238BD0F0)

I used the same links, but they provide bigger icons now for some reason ? should i use some online resizer or something for them ?

**Comment by xmfcx** [comment]
I've updated the links again.
https://github.com/autowarefoundation/autoware.universe/pull/8868#issuecomment-2357870266

could you replace the images with these? 64x64 is alright. But styles will match the old ones now.
especially the raven looks normal now.

**Comment by xmfcx** [comment]
Ideal solution would be to just have the svg icons in the source folder and have custom cmake command to call a python script to color and generate png in the install folder at compile time.

But it would be too much work for just a couple kilobytes.

**Review by xmfcx — APPROVED** [review]
Thx!

**Pull request merged**
