### PR TITLE
feat(emergency_handler, mrm_handler): change to read topic by polling

### PR DESCRIPTION
**Pull request by Autumn60**
## Description

Based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612), change `emergency_handler` and `mrm_handler` to read topic by polling instead of best_effort callback.

## Tests performed

psim test were performed

## Effects on system behavior

nothing

## Interface changes

nothing

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by veqcc** [comment]
@Autumn60 
Thank you for improving `emergency_handler` node!!

Actually, the `emergency_handler` node will be duplicated in several months and `mrm_handler` node will be used instaed.
Are you going to make the same changes to also `mrm_handler` ?
If yes, could you add the changes on `mrm_handler` to this PR?

**Comment by Autumn60** [comment]
@veqcc 
OK, I'll make the change to `mrm_handler` .
Thanks for the info and suggestions!

**Review by veqcc — APPROVED** [review]
LGTM :+1:

**Comment by veqcc** [comment]
@Autumn60 
Could you fix the following bug soon?
Since it is merged to main steam so I want fix it right now.
If you cannot, please inform me
https://github.com/autowarefoundation/autoware.universe/pull/7264#issuecomment-2151740216

**Comment by Autumn60** [comment]
@veqcc 

The bug is already fixed when I merged this PR with main to resolve conflicts.

https://github.com/tier4/autoware.universe/commit/45f1b9599c2b35f1840a310989405b6e4205586b#diff-60980d5de6dc4345c86fd9ee7241f0db5e7909dbad5fa181b3d6dcc75b1f384cR523

**Comment by veqcc** [comment]
@Autumn60 
The main branch doesn't look fixed. Is it true?
https://github.com/autowarefoundation/autoware.universe/blob/a3955e90cf849bb77f4f6e0444a6379b070d227f/system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp#L523

**Comment by Autumn60** [comment]
@veqcc 

Oh, this is totally my mistake. :cry: 
I have created another PR that fixes this, could you please check it?

https://github.com/autowarefoundation/autoware.universe/pull/7362

**Pull request merged**
