### PR TITLE
chore: add maintainer Yoshi Ri to packages

### PR DESCRIPTION
**Pull request by YoshiRi**
## Description

Add maintainer to to some packages.
See [TIER IV INTERNAL LINK](https://tier4.atlassian.net/wiki/spaces/CT/pages/2527037972/SP).

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — APPROVED** [review]

**Review by Shin-kyoto — APPROVED** [review]
Thanks!
LGTM

**Comment by YoshiRi** [comment]
@manato Could you approve this owner adding PR?

**Comment by kyoichi-sugahara** [comment]
@manato 
Can you review this PR when you have time?

**Review by manato — APPROVED** [review]
Sorry for the delay of my review. LGTM!

**Pull request merged**
