### PR TITLE
fix(object_recognition_utils): check polygon area on iou calculation

### PR DESCRIPTION
**Pull request by technolojin**
## Description
Fix a issue reported by @mebasoglu
ISSUE https://github.com/autowarefoundation/autoware.universe/issues/6617

This PR is alternative of PR https://github.com/autowarefoundation/autoware.universe/pull/6618.

## Tests performed
1. A normal recompute simulation under TIER IV data is performed.
2. The issue related data are also confirmed with this fix and the issue is resolved.

## Effects on system behavior
Prevent divide by zero on IoU calculation even abnormal objects size are come. 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by technolojin** [comment]
Dear @mebasoglu, 
This is a replaced fix for the issue you reported.

Can you test it with the data you have?

**Comment by mebasoglu** [comment]
Hello @technolojin , I have tested with our data and confirmed that it works 👍. Thank you.

**Comment by technolojin** [comment]
@scepter914 Can I request to review this PR?

**Review by scepter914 — APPROVED** [review]
LGTM
(Operation confirmation by @technolojin )

**Pull request merged**
