### PR TITLE
refactor(image_projection_based_fusion): read lidar models parameters from autoware_launch

### PR DESCRIPTION
**Pull request by ismetatabay**
## Description

This PR provides migrating lidar detection model parameters from autoware_launch
Releated: https://github.com/autowarefoundation/autoware.universe/issues/4250

- autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/450
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@yukke42 Could you review this PR?

**Comment by ismetatabay** [comment]
@yukke42 I resolved conflicts :+1:

**Comment by shmpwk** [comment]
https://github.com/autowarefoundation/autoware.universe/actions/runs/5612516522/job/15206437184?pr=4278
CI fails due to the shotage of the disk space ...
https://github.com/autowarefoundation/autoware.universe/issues/4349

**Comment by yukke42** [comment]
@ismetatabay Cloud you check to launch logging_simulator.launch in [rosbag replay simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)?

I checked to run lidar_centerpoint and get output from perception in the main branch but not in this PR.

image

**Comment by ismetatabay** [comment]
@yukke42 Hi, I checked and confirmed this PR and autoware_launch PR works as expected in my local environment, logging_simulator demo works without any problem. I also checked changing parameters in autoware_launch and there is no problem for me. How did you reproduce this situation? Can you give me some more info? Could there be a problem in the build phase? (maybe symbolically linked .param file have a issue)

**Comment by yukke42** [comment]
@ismetatabay Sorry, I missed something. I built again and then confirmed that this PR works correctly!

image

**Review by yukke42 — APPROVED** [review]
LGTM

**Comment by ismetatabay** [comment]
@yukkysaito Hi, can you check it also?

**Review by yukkysaito — APPROVED** [review]
LGTM :+1:

**Pull request merged**
