### PR TITLE
feat(tier4_perception_launch): update cam/lidar detection architecture

### PR DESCRIPTION
**Pull request by kaancolak**
Signed-off-by: Kaan Çolak <kaancolak95@gmail.com>

## Description

#2659 

This PR must be merge after : #2844 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by yukkysaito** [comment]
@kaancolak Thank you for PR 👍

**Review by miursh — APPROVED** [review]
LGTM

**Comment by miursh** [comment]
@kaancolak I just noticed that there is a typo in the launch PR here, and it doesn't seem to match the arg on the node launch file.
[thrust_distance](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml#L116) in launch files, but [trust_distance](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml#L23) is correct.

**Comment by kaancolak** [comment]
> @kaancolak I just noticed that there is a typo in the launch PR here, and it doesn't seem to match the arg on the node launch file.
> [thrust_distance](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml#L116) in launch files, but [trust_distance](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml#L23) is correct.

Thanks for correction, I will create quick fix PR.

**Comment by kaancolak** [comment]
Shunsuke-san @miursh, I created PR, please look into it. 

[https://github.com/autowarefoundation/autoware.universe/pull/2926](https://github.com/autowarefoundation/autoware.universe/pull/2926)

**Pull request merged**
