### PR TITLE
fix(walkway): fix module launch condition

### PR DESCRIPTION
**Pull request by satoshi-ota**
### <samp>🤖 Generated by Copilot at 0dc1f94</samp>

Refactor and simplify the walkway manager module in `manager.cpp`. Use a local argument for regulatory elements instead of a class member.

---

Fix module launch condition so that it can activate walkway module in the map which has both regulatory element crosswalk and non regulatory element walkway.

map: X2 Dev/Shiojiri_100laps_Dev/20230828_修正完了_14

image

https://github.com/autowarefoundation/autoware.universe/assets/44889564/5fcd91b0-06c4-4285-8762-64a19bf94f3d

## Tests performed

- [x] [PASS TIER IV INTERNAL SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/3f6a08a9-5751-503e-aad2-d0ea9ed873d4?project_id=prd_jt)

## Effects on system behavior

Make it possible to use walkway module in specific map.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
NOTE: https://github.com/autowarefoundation/autoware.universe/pull/4823/commits/796d9b2700b016555dbd36de4afdacaf5002594b is tmporary commit.

**Comment by satoshi-ota** [comment]
> NOTE: [796d9b2](https://github.com/autowarefoundation/autoware.universe/commit/796d9b2700b016555dbd36de4afdacaf5002594b) is a temporary commit in order to pass build.

REMOVED.

**Comment by zhiwango** [comment]
image
@satoshi-ota 
ローカルPCで該当のPRを入れた後に、PSIMで動作確認はできました。
修正ありがとうございます。

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
