### PR TITLE
refactor(autoware_auto_control_msgs): replace autoware_auto_control_msgs with autoware_control_msgs

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

Closes: https://github.com/autowarefoundation/autoware.universe/issues/3674

### <samp>🤖 Generated by Copilot at 4fa17ed</samp>

This pull request replaces the use of `AckermannControlCommand` and `AckermannLateralCommand` messages from `autoware_auto_control_msgs` with the new generic `Control` and `Lateral` messages from `autoware_control_msgs` in various control modules and tools. This simplifies the control interface, avoids unnecessary conversions, and ensures compatibility with the latest control command definition. The changes affect the source code, header files, package dependencies, and documentation of the `tier4_control_rviz_plugin`, `control_performance_analysis`, `joy_controller`, `mpc_lateral_controller`, and `autonomous_emergency_braking` packages.

## Related links

- Needs to be merged with:
  - https://github.com/tier4/tier4_ad_api_adaptor/pull/106
  - https://github.com/tier4/pacmod_interface/pull/61
  - https://github.com/autowarefoundation/autoware_launch/pull/353
- Simulator PRs:
  - https://github.com/tier4/scenario_simulator_v2/pull/1020
  - https://github.com/tier4/AWSIM/pull/152

## Tests performed

- Compilation works and existing tests pass.
- [Planning simulation demo](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) works.

## Notes for reviewers

- Because this is a very interconnected PR, I've had to make it all in a single PR.
- Needs to be merged with:
  - https://github.com/tier4/tier4_ad_api_adaptor/pull/106
  - https://github.com/tier4/pacmod_interface/pull/61
  - https://github.com/autowarefoundation/autoware_launch/pull/353

### <samp>🤖 Generated by Copilot at 4fa17ed</samp>

*  Replace `autoware_auto_control_msgs` with `autoware_control_msgs` to unify the control message interface across different controllers ([link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-5b64a4bc696bc7711b9348d9610599ba2e6986447c080097ef916b35803f5499L13-R14), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a5a8657b94b1105d141fe214352f1e45e517a74d62a1819bdfd9440517c7dab1L14-R16), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-0cc18a28606e9953bacccba90dfd5c377b5720fa1a1a0f9ce40d7f2076ed2094L27-R29), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-171cb7488d7ed1cf99749e4a77eb83ff52de843b6feb8e8cb8d2d202b581836eL22-R23), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-6eeea4c2cc2133f784a3f8d32eb1789e66fe92fdbe7a7589858fe54fa26035b9L20-R22))
*  Change the control command message type from `AckermannControlCommand` to `Control` and update the corresponding fields, namespaces, headers, publishers, subscribers, buffers, and functions in `tier4_control_rviz_plugin`, `control_performance_analysis`, and `joy_controller` ([link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-5fd28393490d860a54aa8f24adb07da1bea06c249de0013c16d3c74ad4a6e601L113-R117), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-5fd28393490d860a54aa8f24adb07da1bea06c249de0013c16d3c74ad4a6e601L136-R138), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-5fd28393490d860a54aa8f24adb07da1bea06c249de0013c16d3c74ad4a6e601L184-R185), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-190b681ca5dbb48ddcbf50741bc902cb1c9f0301bb41e7fe74818b5a5b75bd80L29-R32), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-190b681ca5dbb48ddcbf50741bc902cb1c9f0301bb41e7fe74818b5a5b75bd80L40-R42), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-190b681ca5dbb48ddcbf50741bc902cb1c9f0301bb41e7fe74818b5a5b75bd80L77-R77), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-e1660a2e3ebb958cfef455f5e14397dceccebc15fc618b1db42cb3dc7b646b2bL27-R29), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-e1660a2e3ebb958cfef455f5e14397dceccebc15fc618b1db42cb3dc7b646b2bL41-R43), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-e1660a2e3ebb958cfef455f5e14397dceccebc15fc618b1db42cb3dc7b646b2bL74-R74), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-e1660a2e3ebb958cfef455f5e14397dceccebc15fc618b1db42cb3dc7b646b2bL106-R106), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L26-R28), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L39-R41), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L55-R56), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L74-R73), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L86-R85), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-a9a80896fda0b4e4012b8d5503832ae1d609a920bd14ee82177fab00799b2500L93-R92), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-15ac61f7cbbe7ac290018fd2509168cc4d2ff201c3a500ae3385364103bdb626L84-R86), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-73a4fb1691cb91096d60060ec20dbf49bc65b811fe7d29e2b1e3769ce8537f19L27-R27), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-73a4fb1691cb91096d60060ec20dbf49bc65b811fe7d29e2b1e3769ce8537f19L65-R65), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-73a4fb1691cb91096d60060ec20dbf49bc65b811fe7d29e2b1e3769ce8537f19L99-R99), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-bc205d5127fcdcda7bf5b0d8b14dfe99fe35996d3d6092b3fc3e42fe037048dfL22-R23), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-bc205d5127fcdcda7bf5b0d8b14dfe99fe35996d3d6092b3fc3e42fe037048dfL83-R83), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-bc205d5127fcdcda7bf5b0d8b14dfe99fe35996d3d6092b3fc3e42fe037048dfL108-R107), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-388110ee10c9684d1ec47329f192b4a749bf8b426bbd0268c526799997e3ca8aL254-R254), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-388110ee10c9684d1ec47329f192b4a749bf8b426bbd0268c526799997e3ca8aL262-R269), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-388110ee10c9684d1ec47329f192b4a749bf8b426bbd0268c526799997e3ca8aL276-R279), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-388110ee10c9684d1ec47329f192b4a749bf8b426bbd0268c526799997e3ca8aL487-R487))
*  Change the lateral control command message type from `AckermannLateralCommand` to `Lateral` and update the corresponding fields, namespaces, headers, publishers, subscribers, buffers, and functions in `mpc_lateral_controller` ([link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-030829d3b609275d79ffa6919606aee842cbe03df3984fae74a704cca0ef01c3L33-R35), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-030829d3b609275d79ffa6919606aee842cbe03df3984fae74a704cca0ef01c3L47-R49), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-030829d3b609275d79ffa6919606aee842cbe03df3984fae74a704cca0ef01c3L177-R177), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-030829d3b609275d79ffa6919606aee842cbe03df3984fae74a704cca0ef01c3L381-R381), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-8a89e4298b2125992eb5c99ef8f8d12caaf6d9d25646c2e63eee66052fe17a16L37-R40), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-8a89e4298b2125992eb5c99ef8f8d12caaf6d9d25646c2e63eee66052fe17a16L125-R125), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-8a89e4298b2125992eb5c99ef8f8d12caaf6d9d25646c2e63eee66052fe17a16L163-R164), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-8a89e4298b2125992eb5c99ef8f8d12caaf6d9d25646c2e63eee66052fe17a16L181-R186), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-8a89e4298b2125992eb5c99ef8f8d12caaf6d9d25646c2e63eee66052fe17a16L200-R200), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-3928795445dcd4b3ae03f4b6202b7170627811d40ff0246c8eb7917686cb9c4bL33-R33), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-3928795445dcd4b3ae03f4b6202b7170627811d40ff0246c8eb7917686cb9c4bL372-R371))
*  Update the README files for `tier4_control_rviz_plugin`, `control_performance_analysis`, `joy_controller`, and `mpc_lateral_controller` to reflect the new message types and fields for control command and lateral control ([link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-1cf606f792fcf0ba924b742a76c2dad5204d4bd17e1bfc3b376e326b80b4d280L18-R22), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-f3f59f78f0fc649f13fec38a8f923fabda3d6d257492d8db7c842ab9023b8b85L28-R34), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-c2b5931b2aa4a8f481961d2b96113bd6681624eccbb073b04a6e813cf2392ec7L18-R26), [link](https://github.com/autowarefoundation/autoware.universe/pull/3677/files?diff=unified&w=0#diff-14b7e76dd74fbb8acf66c33015394a2dd6119591c9280e2963e6a9021531f0a2L73-R73))

## Effects on system behavior

Shouldn't change the system behavior.

### <samp>🤖 Generated by Copilot at 4fa17ed</samp>

> _`Control` replaces_
> _`AckermannControlCommand`_
> _Simpler interface_

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Side task:
- [ ] Once this PR is merged, fix the filename of https://github.com/autowarefoundation/autoware.universe/blob/main/system/mrm_emergency_stop_operator/READEME.md

**Comment by xmfcx** [comment]
Tested with the [Planning simulation demo](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) and it works fine.

Screenshot from 2023-05-16 16-41-38

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by xmfcx** [comment]
I've added 2 missing PRs too, now everything should work together.

(I've previously missed them because I didn't do `vcs status src` on all repos)

**Comment by xmfcx** [comment]
I have had to squash and re-base while fixing the conflicts with the https://github.com/autowarefoundation/autoware.universe/commit/8fcac0e2cae8ba65dd1ca0e7df115d160a2ad27c

Compiled and tested with the planning simulator again to make sure it works.

**Comment by takayuki5168** [comment]
@xmfcx pre-commit failed.
@TakaHoribe Could you review the PR.

**Comment by TakaHoribe** [comment]
@xmfcx Thank you!!! It looks good, but I thought the output of the trajectory_follower would be the ControlHolizon msg.
I don’t think we have to discuss right now though.

If you don’t have a large concern, I’d like to merge this PR.

**Comment by xmfcx** [comment]
> @xmfcx pre-commit failed. @TakaHoribe Could you review the PR.

@takayuki5168 I've added the missing header, now it should be fine:
- https://github.com/autowarefoundation/autoware.universe/pull/3677/commits/df9ec979ca2a77ecc3a280fe3841acbf341d96e3

**Comment by takayuki5168** [comment]
@xmfcx @TakaHoribe 
I found that If we merge this PR now, the scenario simulator will not work well with the latest autoware.universe, which I think is critical.
Don't you apply the same change to the scenario simulator as well?
https://github.com/tier4/scenario_simulator_v2

**Comment by xmfcx** [comment]
> I found that If we merge this PR now, the scenario simulator will not work well with the latest autoware.universe, which I think is critical. Don't you apply the same change to the scenario simulator as well? https://github.com/tier4/scenario_simulator_v2

Thanks for noticing, I've just talked to @mitsudome-r about this, he mentioned https://github.com/tier4/scenario_simulator_v2 and AWSIM both won't work. He will talk to internal team to find a resolution.

I will create a branch on scenario simulator to perform refactoring anyways.
Same with AWSIM.

**Comment by xmfcx** [comment]
We can merge this once the following issue is resolved:
- https://github.com/autowarefoundation/autoware.universe/issues/3845

Please feel free to add your comments on the issue.

**Comment by xmfcx** [comment]
Confirmed that planning simulator works with all the PRs combined.
Screenshot from 2023-07-06 12-04-39

**Comment by xmfcx** [comment]
All of the PRs are finished, please review them.

Needs to be tested/merged at the same time with 
  - https://github.com/tier4/tier4_ad_api_adaptor/pull/106
  - https://github.com/tier4/pacmod_interface/pull/61
  - https://github.com/autowarefoundation/autoware_launch/pull/353
for entire Autoware to compile and function.

To test the simulators, need to be in following branches:
- https://github.com/tier4/scenario_simulator_v2/pull/1020
- https://github.com/tier4/AWSIM/pull/152

**Comment by xmfcx** [comment]
I'm closing all of my message migration issues and PRs.

**Pull request closed without merging**
