### PR TITLE
docs(reaction_analyzer): update bag files and the README

### PR DESCRIPTION
**Pull request by batuhanbeytekin**
## Description
While running the reaction analyzer tool within Autoware Universe, I encountered errors due to changes in message types and PointCloud layout. The current bag files need to be updated to be compatible with the new message types in Autoware.

## Tests performed
Package built and launch locally.

## Pre-review checklist for the PR author
The PR author **must** check the checkboxes below when creating the PR.
- [x] I've confirmed the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
- [x] The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

## In-review checklist for the PR reviewers
The PR reviewers **must** check the checkboxes below before approval.
- [x] The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author
The PR author **must** check the checkboxes below before merging.
- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by brkay54 — APPROVED** [review]
LGTM

Just a minor request, could you add a warning for perception_planning mode in readme like: 
On the first run of the tool in **perception_planning** mode, initialization might take longer than expected. Please allow some time for the process to complete.

**Comment by batuhanbeytekin** [comment]
> LGTM
> 
> Just a minor request, could you add a warning for perception_planning mode in readme like: On the first run of the tool in **perception_planning** mode, initialization might take longer than expected. Please allow some time for the process to complete.

Hi @brkay54, 
Sorry for the late reply. I updated the readme file as you said. Thank you for your feedback.

**Review by SakodaShintaro — COMMENTED** [review]
For some reason, it seems that unrelated changes to localization modules have been included. Could you rebase onto the latest main branch?

**Comment by brkay54** [comment]
@batuhanbeytekin I think the problem is solved, and there are no conflicts with the main branch. Can we merge it now?

**Comment by batuhanbeytekin** [comment]
> @batuhanbeytekin I think the problem is solved, and there are no conflicts with the main branch. Can we merge it now?

There is no conflict anymore. We can merge it for now. Thanks for your feedback.

**Pull request merged**
