### PR TITLE
fix(autoware_obstacle_stop_planner): register obstacle stop planner node with autoware scoping

### LINKED ISSUE #8437: Obstacle stop planner node doesn't start when running in a component container
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

When the obstacle stop planner node is started using a component container, only the component container is shown as running but the actual functionality of the obstacle stop planner node is unavailable.

### Expected behavior

The obstacle stop planner node gets loaded as a composable node plugin into a component container and is listed when `ros2 node list` is run and the expected features of the obstacle stop planner node such as slowing down and stopping behaviors are triggered based on input trajectory and obstacle data (from a lidar pipeline for example).

### Actual behavior

Only the component container starts, but the node doesn't get listed when `ros2 node list` is done. Further, the expected output topics of the obstacle stop planner, `~output/trajectory` and `~output/stop_reasons` are not published and the desired functionality of slow down (if enabled) and stopping aren't available.

What is also difficult to explain is that, a linux process corresponding to starting the node does start and can be found by running a command such as `ps aux | grep <name_of_obstacle_stop_planner_node_in_launch_file>`. Further, the launch file as shown in the example below doesn't report any errors upon launch.

### Steps to reproduce

1. Create a composable node launch file in a ros2 package as follows (Ex: `my_pkg/launch/obstacle_stop_planner_composable.launch.xml`):
```
<launch> 
  <node_container pkg="rclcpp_components" exec="component_container" name="obstacle_stop_planner_container" namespace="" >
        <composable_node pkg="autoware_obstacle_stop_planner" plugin="motion_planning::ObstacleStopPlannerNode" name="obstacle_stop_planner" namespace="" >
            <!-- We need to disable object related velocities for the cruise control here -->
            <param from="$(find-pkg-share autoware_obstacle_stop_planner)/config/common.param.yaml"/>
            <param from="$(find-pkg-share autoware_obstacle_stop_planner)/config/adaptive_cruise_control.param.yaml" />
            <param from="$(find-pkg-share autoware_obstacle_stop_planner)/config/obstacle_stop_planner.param.yaml" />
            <param from="$(find-pkg-share autoware_vehicle_info_utils)/config/vehicle_info.param.yaml" />
            <remap from="~/input/trajectory" to="/input/trajectory"/>
            <remap from="~/output/trajectory" to="/planning/scenario_planning/trajectory"/>
            <remap from="~/output/max_velocity" to="/planning/scenario_planning/max_velocity_candidates"/>
            <remap from="~/output/velocity_limit_clear_command" to="/planning/scenario_planning/clear_velocity_limit"/>
            <remap from="~/input/pointcloud" to="/obstacle/clusters"/>
            <remap from="~/input/odometry" to="/odom"/>
            <remap from="~/input/objects" to="/perception/object_recognition/objects"/>
            <remap from="~/output/stop_reason" to="/planning/scenario_planning/status/stop_reason"/>
            <remap from="~/output/stop_reasons" to="/planning/scenario_planning/status/stop_reasons"/>
        </composable_node>
    </node_container>
</launch>
```
2. `ros2 launch <my_pkg> obstacle_stop_planner_composable.launch.xml`
3. `ros2 node list` - Only lists `obstacle_stop_planner_container`, but not `obstacle_stop_planner`.
4. `ps aux | grep obstacle_stop` will return a hit for a process that gets created upon launch, but it seemingly isn't doing anything as expected.

### Versions

- OS: Ubuntu Jammy 22.04 LTS
- ROS2: Iron/Jazzy
- Autoware: Latest version of `autoware_obstacle_stop_planner` on `main` branch of `autoware.universe`

### Possible causes

The likely cause is that the composable node plugin is not registered correctly in the `CMakeLists.txt` [here](https://github.com/autowarefoundation/autoware.universe/blob/13ac473947a282293196a984a40e911e5c935137/planning/autoware_obstacle_stop_planner/CMakeLists.txt#L28).

In the source file for the node, [the node component is exported](https://github.com/autowarefoundation/autoware.universe/blob/13ac473947a282293196a984a40e911e5c935137/planning/autoware_obstacle_stop_planner/src/node.cpp#L1607) as `autoware::motion_planning::ObstacleStopPlannerNode`, while in `CMakeLists.txt`, it is registered as `motion_planning::ObstacleStopPlannerNode`, _without_ `autoware::` scoping.

I did a source checkout and changed the registration in `CMakeLists.txt` to include `autoware::` scoping and then tested the composable node from the same launch file as mentioned above. Everything works as expected, i.e.,
- The node is listed when `ros2 node list` is run
- The expected output topics are published
- And the expected markers such as the obstacle stop and obstacle slow down can be visualized in RViz when obstacles are on the desired trajectory of the vehicle.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbharatheesha**
## Description

This PR updates the name of the composable node registration in CMakeLists.txt to include autoware:: scoping as specified in the node source file.

This change is fixes #8437 .

**Parent Issue:**

- [Link](https://github.com/autowarefoundation/autoware.universe/issues/8437)

## How was this PR tested?
A composable node from an xml launch file was created as stated in the linked issue and the launch file was used to start the obstacle stop planner node.

The node started as expected in the component container and the expected obstacle slow down and obstacle stopping behaviors were visualized on RViz.

## Notes for reviewers
This PR is created based on a previous PR and review by @brkay54 . In the process of fixing the sign off commits, I made some mistakes and that led to some unexpected workflow failures. So, I have closed the older PR #8438 in favor of this one. Apologies for the inconvenience!

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by brkay54 — APPROVED** [review]
My previous [comment](https://github.com/autowarefoundation/autoware.universe/pull/8438#pullrequestreview-2242459259).
Thank you, LGTM.

**Comment by brkay54** [comment]
Hi @satoshi-ota @TakaHoribe @takayuki5168 , currently obstacle_stop_planner does not work. Could you check the PR when you are available?

**Review by satoshi-ota — APPROVED** [review]
Good Job. Thanks!

**Comment by mbharatheesha** [comment]
@brkay54 @satoshi-ota Since I have not done PRs to this repo in the past, I am curious. Is it normal that some of the workflows like `cppcheck-differential` `build-and-test-differential(humble)` etc take more than a few days to report their statuses? I just wanted to know if there's anything pending from my side to have those workflow statuses.

Initially, I thought it may have something to do with not updating to latest `main` and I did that a few times last week. I can do it again, but just wanted to confirm if there's anything else.

**Pull request merged**
