### PR TITLE
fix(interpolation): implementation of template function to header

### PR DESCRIPTION
**Pull request by HiroIshida**
## Description

I think template function must be implemented in header, if without explicit instantiation in the impl file. 
Otherwise, using such function may cause compile time error, or worse  symbol lookup error in runtime. 

@takayuki5168 
@TakaHoribe 

reference: 
https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file

A test was added in https://github.com/autowarefoundation/autoware.universe/commit/f4723923e738352bd684c77a96432ea0adc8d6fc
which cannot be compiled with the original code with the following message: 
```
/usr/bin/ld: CMakeFiles/test_interpolation.dir/test/src/test_spline_interpolation.cpp.o: in function `spline_interpolation_SplineInterpolationPoints2dPolymorphism_Test::TestBody()':
test_spline_interpolation.cpp:(.text+0x21b7): undefined reference to `void SplineInterpolationPoints2d::calcSplineCoefficients<autoware_auto_planning_msgs::msg::TrajectoryPoint_<std::allocator<void> > >(std::vector<autoware_auto_planning_msgs::msg::TrajectoryPoint_<std::allocator<void> >, std::allocator<autoware_auto_planning_msgs::msg::TrajectoryPoint_<std::allocator<void> > > > const&)'
```
After the bug fix commit https://github.com/autowarefoundation/autoware.universe/commit/63a1cc24e3d9705a2b0a6a8c28896140827b73d4
, the test code can be successfully compiled and no error in the runtime also. 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]
> I think template function must be implemented in header
You are totally right.

Nice modification! LGTM

**Comment by takayuki5168** [comment]
I've fixed a little so that all CI will pass.

@HiroIshida Just checking. Could you verify that simple planning simulator works with this PR.
If there is no problem, you can merge. :+1:

**Comment by HiroIshida** [comment]
@takayuki5168 
Before opening PR, I already checking this change is compatible with other package (obstacle avoidance planner which uses  SplineInterpolationPoint2d inside), by recompiling that package and run a planning simulator. 

Just in case, yesterday, I tried compiling whole source of autoware universe and tried psim after that. Then, I found planning simulator get stacked after putting an goal position with  `autoware/state` = 4 (planning). I'm not sure it is because of the change  in this PR or problem in build. Take me a little bit time to check the real cause of problem. 

By the way, I don't have priviledge to merge. so after resolving the above issue, I want to ask you to merge.

**Comment by takayuki5168** [comment]
@HiroIshida Got it. Take your time.

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Comment by HiroIshida** [comment]
@takayuki5168  @TakaHoribe 
I checked this change is OK, please merge this commit.

**Pull request merged**
