### PR TITLE
chore(lidar_centerpoint): add trained model of centerpoint

### PR DESCRIPTION
**Pull request by yukke42**
Signed-off-by: yukke42 <yusuke.muramatsu@tier4.jp>

## Description

Update the trained model of lidar_centerpoint.  The inference execution time increased when running the package with sensing even though no packages requiring GPU executed. The cause haven't been identified yet.

|             | DNN inference time [ms] |
|-------------|---------------------|
| w/ sensing  | 33.53               |
| w/o sensing | 19.49               |

### centerpoint_tiny

GPU Memory [MiB]: 1493
Exec Time [ms]: 47.59 ± 5.73

https://user-images.githubusercontent.com/24660808/176686033-2382d49c-bb71-40a0-bc7f-77ea82fde56f.mp4

### centertpoint

GPU Memory [MiB]: 1615
Exec Time [ms]: 63.31 ± 10.05

https://user-images.githubusercontent.com/24660808/176686338-e62c6837-c80c-4803-9386-0550d2eaa5db.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
Is this improved? :pray: 
I didn't feel it is improved and seemed to increase false positives.

**Comment by yukke42** [comment]
> Is this improved? 
> I didn't feel it is improved and seemed to increase false positives.

@yukkysaito 
Yes, it looks almost the same performance in a sample-bag, but the evaluation performance gets better in our internal dataset.

**Comment by yukkysaito** [comment]
@yukke42 can you share the movie?

**Comment by yukkysaito** [comment]
@tkimura4 @yukke42 can you test the real vehicle since the calc cost is increased?

**Comment by yukke42** [comment]
> @yukke42 can you share the movie?

Yellow: previous model
Green: this model

The large vehicles detection isn't perfect yet, but it's getting better.

https://user-images.githubusercontent.com/24660808/177090109-aa56ab24-95de-44d3-accb-5dcf05eb0c6d.mp4

**Comment by yukke42** [comment]
I will add the previous model as the default model and add option to use the updated model. Then I will create other PR to deal with the computational issue.

**Comment by yukke42** [comment]
> I will add the previous model as the default model and add option to use the updated model. Then I will create other PR to deal with the computational issue.

Done.

**Comment by yukke42** [comment]
@yukkysaito I want to merge this PR If reviewers confirm that updated codes have no problem, before we check that the added model runs on real vehicle without any issue, because the default model of lidar_centerpoint is the same as before.

**Comment by miursh** [comment]
@yukke42 
I confirmed two models were working properly. However, I couldn't find any obvious difference between centerpoint and centerpoint-tiny.
Please give me some more time to confirm.

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
