### PR TITLE
refactor(tvm_utility): redefine network node and inference config

### PR DESCRIPTION
**Pull request by angry-crab**
Signed-off-by: Xinyu Wang <xinyu.wang@tier4.jp>

## Description

Relates to #2308 
According to [Template config.hpp input and output type](https://github.com/autowarefoundation/modelzoo/issues/81), individual input and output node might have different data type. `NetworkNode` needs to be refactored. 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by angry-crab** [comment]
This PR is ready to be reviewed .

**Review by ambroise-arm — CHANGES_REQUESTED** [review]
This would need to be completed by further changes in the codebase. For example, the references to `network_outputs[n].second` need to become `output_config[n].node_shape` and so on. For all packages making use of this.
Also, once you're happy with the state of the ModelZoo repository we can tag it and then update `MODELZOO_VERSION` in tvm_utility-extras.cmake. I think this needs to be done before merging this PR, otherwise it won't compile unless adding `--cmake-args -DMODELZOO_VERSION=latest` to the colcon command.

**Comment by angry-crab** [comment]
> This would need to be completed by further changes in the codebase. For example, the references to `network_outputs[n].second` need to become `output_config[n].node_shape` and so on. For all packages making use of this. Also, once you're happy with the state of the ModelZoo repository we can tag it and then update `MODELZOO_VERSION` in tvm_utility-extras.cmake. I think this needs to be done before merging this PR, otherwise it won't compile unless adding `--cmake-args -DMODELZOO_VERSION=latest` to the colcon command.

Thanks for the heads-up. This pr accommodates  changes to `tvm_utility` and `lidar_apollo_segmentation_tvm`. 'centerpoint_tvm' will be handled in another pr. #2468

**Review by ambroise-arm — CHANGES_REQUESTED** [review]
There is one `datatype_bytes` left at perception/lidar_apollo_segmentation_tvm/src/lidar_apollo_segmentation_tvm.cpp:103 (instead of `output_datatype_bytes`).

You can now replace `latest` with `3.0.0-20221221` in tvm_utility-extras.cmake.

**Review by ambroise-arm — APPROVED** [review]
LGTM

**Pull request merged**
