### PR TITLE
refactor(updated-localization-error-monitor): rework parameters

### PR DESCRIPTION
**Pull request by santosh-interplai**
## Description

Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the localization_error_monitor package.

Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
Create the schema

## Tests performed

Not applicable.

## Effects on system behavior

More reliable and faster parameter configuration file creation.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
Would you also reflect the parameter update in Readme?

**Comment by santosh-interplai** [comment]
Hi 
The parameters are already part of Readme file. Let me know which are to be added.
Thank you.

**Comment by kminoda** [comment]
Sorry my comment lacked details.
I recommend to follow other Readme-s, which use the JSON schema to automatically generate the description. See https://github.com/Interplai/autoware.universe/blob/update-localization-error-monitor-package/localization/gyro_odometer/README.md for example, which is then automatically generated here: https://autowarefoundation.github.io/autoware.universe/main/localization/gyro_odometer/#parameters

**Comment by YamatoAndo** [comment]
@santosh-interplai  Hi, how is the progress going?

**Comment by YamatoAndo** [comment]
I'll take over the work on this PR.

I have create a new PR.https://github.com/autowarefoundation/autoware.universe/pull/6156

**Pull request closed without merging**
