### PR TITLE
feat(rviz_plugin): add side shift control to state panel

### PR DESCRIPTION
**Pull request by taikitanaka3**
Signed-off-by: tanaka3 <ttatcoder@outlook.jp>

## Description

currently there is no good way to develop side shift for open source user so I added side shift control as rviz plugin

https://user-images.githubusercontent.com/65527974/173217705-afc8e3fb-b0d7-47c3-8476-2e7a7d081253.mp4

image

## Tests performed

by Psim
shift param below is going to make smooth shift path
```
      shift_request_time_limit: 0.0
```

## Notes for reviewers

run psim

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
In near future, we plan to remove side shift function because we wanna use only RTC.
So, it maybe good not to merge this PR.
@tkimura4 what do you think?

**Comment by taikitanaka3** [comment]
@yukkysaito 
Thank you for good opinion, however currently side shift module is very hard to use not only me but also for open source users because FOA is tier4's internal repository and only accessible from xx1 project repository. I think it's better to remove this plugin function when side shift is going to be removed(really?).

**Comment by tkimura4** [comment]
> In near future, we plan to remove side shift function because we wanna use only RTC.

@yukkysaito 
I heared that the side-shift function would continue to be used in the future. cc. @rej55 
I think this plugin is useful. What do you think?

**Comment by rej55** [comment]
Now, side shift module cannot use RTC interface because RTC cannot use numerical command.
If we use side shift module, it is necessary to send specific topic includes `lateral_offset` value.

**Comment by taikitanaka3** [comment]
I will reopen this PR if side shift will be used.

**Pull request closed without merging**
