### PR TITLE
fix: take dummy objects' height into calculation when locating their Z position

### PR DESCRIPTION
**Pull request by Tier4Guan**
## Description

close https://github.com/autowarefoundation/autoware.universe/issues/3111

fix: take dummy objects' height into calculation when locating their Z position

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
Thank you for your PR.
I'll review later :+1:

**Comment by yukkysaito** [comment]
LGTM
Before
image (5)

After
image

**Review by yukkysaito — COMMENTED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by yukkysaito** [comment]
Could you check to pass for CI

**Comment by satoshi-ota** [comment]
@yukkysaito Thanks for your review. I ran all CI again.

**Pull request merged**
