### PR TITLE
feat: add CRC error monitoring to net_monitor

### PR DESCRIPTION
**Pull request by v-nakayama7440-esol**
## Description
Add CRC error monitoring in `net_monitor`.
The `net_monitor` monitors CRC error on Ethernet and reports `Warning` if error.

## Related links

https://github.com/autowarefoundation/autoware.universe/issues/1770

### Preparation
- Prepare a jig to short RxD+ and RxD- line on a network cable or connector.
- Setup network as follows:
image

### Verify `net_monitor: Network CRC Error` reports `OK` in normal operation.
1. Run Autoware.
2. Run rqt_runtime_monitor.
    ```console
    ros2 run rqt_runtime_monitor rqt_runtime_monitor
    ```
3. Verify `net_monitor: Network CRC Error` reports `OK`.
image

### Verify no warning and error messages in a normal run.

image

### Verify `network_crc_error` is aggregated in `resource_monitoring`.
1. Run rqt_robot_monitor.
    ```console
    ros2 run rqt_robot_monitor rqt_robot_monitor
    ```
image

### Verify `net_monitor: Network CRC Error` reports `Warning` in abnormal operation.
1. Run iperf server on Autoware ECU.
    ```console
    iperf -s -u
    ```
2. Run iperf client on the host machine.
    ```console
    iperf -c 192.168.10.2 -u -b 30M -i 1 -t 300
    ```
3. Short RxD+ and RxD- and observe an error occurs by using `ip` command.
    ```console
    watch -n 0.1 ip -s link show
    ```
image

4. Verify `net_monitor: Network CRC Error` reports `Warning`.
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@v-nakayama7440-esol @ito-san cc @kenji-miyake 
I would like to write a little more description in the readme
- what can errors be detected?
- when can errors be detected?

**Comment by v-nakayama7440-esol** [comment]
@yukkysaito cc @ito-san @kenji-miyake 

```
・what can errors be detected?
・when can errors be detected?
```
Added the above information to README.md.
71c55ca394d57f9c51de94841eacae95963a46eb

**Review by ito-san — APPROVED** [review]
LGTM

**Comment by ito-san** [comment]
Verified in bus project with humble.
- `OK`
image
- `Warning`
image

**Pull request merged**
