### PR TITLE
fix(turn_signal_decider): fix getintersectionturnsignal of turn_signal_decider

### PR DESCRIPTION
**Pull request by k-obitsu**
## Description(required)

Deleted if-condition in getIntersectionTurnSignal of turn_signal_decider 
## Related PR(optional)

https://github.com/tier4/autoware.iv/pull/2430
## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@Mergifyio rebase

**Comment by tkimura4** [comment]
Uppercase letters in PR titles are not allowed, so I fixed it

**Review by tkimura4 — APPROVED** [review]
LGTM

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
