### PR TITLE
fix(bytetrack): no need to throw exception when idx is out of range

### PR DESCRIPTION
**Pull request by chihungtzeng**
## Description

Since ColorMapper just returns a unique color to the caller, we simply use modulo to get a valid color index.
In such a way there is no need to check the index validity and throw a runtime exception.

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by YoshiRi — APPROVED** [review]
Make sense. @manato do you have any comments?

**Comment by yukkysaito** [comment]
@chihungtzeng Thanks for PR.
It has a very large number of diffs. could you do `git rebase`?

**Comment by chihungtzeng** [comment]
@yukkysaito Thanks for the quick reply. The file really modified is bytetrack_visualizer_node.hpp. However, when I sync with the official autoware.universe, run `git rebase` and then push the source branch, github mistakenly think that I modified many files that actually have merged into the main branch. Do you have SOP to resolve my problem?

**Comment by yukkysaito** [comment]
@chihungtzeng If git rebase is not working well, it might be faster to create a new branch from the latest main. Sorry for the inconvenience.

**Comment by kminoda** [comment]
@chihungtzeng Hi, thank you for the PR. Let us make this PR a draft for now from the maintenance perspective. Please open the PR once it's ready to be reviewed again. Thank you for your understanding.

**Comment by vividf** [comment]
@chihungtzeng I will close this PR now since it seems that it is easier to create a new PR for your work.

**Comment by chihungtzeng** [comment]
@vividf OK. Thanks for your help.

**Pull request closed without merging**
