### PR TITLE
feat(obstacle_stop_planner): add optional check for predicted trajectory

### PR DESCRIPTION
**Pull request by brkay54**
Signed-off-by: Berkay Karaman <brkay54@gmail.com>

## Description
Related issue: https://github.com/autowarefoundation/autoware.universe/issues/2252

In current planning control design, autoware does not check the predicted trajectory for collision. Because trajectory is not draw from base_link of ego vehicle for some situations, we need to check the predicted trajectory in addition to trajectory output of planning module. 

This PR checks the predicted trajectory and motion planning trajectory for collision, then compare them. It makes decision for the nearest collision or slowdown points. 

It is optional, in default it will be disabled.

## Tests performed

I tested changes in planning simulator. It works good but there is a problem for some scenarios:

https://user-images.githubusercontent.com/45468306/203044604-08a24063-2cf5-4ad1-9136-b5891f482539.mp4

Controllers depend trajectory velocities while calculating the predicted trajectory. If there is a object on predicted trajectory, obstacle_stop_planner adds stop point to trajectory. Then, this affect the predicted trajectory so on.

Except this, it works as we wanted.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@brkay54 Thanks for your PR, but I would rather not feedback control outputs into planning module for the following reason:

- Planning module and Control module would be tightly coupled, and decrease modularity.
- Not all vehicles use MPC and this method cannot be used when using pure pursuite.

On the other hand, other solution is proposed in [discussion](https://github.com/autowarefoundation/autoware/discussions/2859), so could you check that?

**Comment by TakaHoribe** [comment]
@brkay54 Thank you for this PR. 

We must be careful about adding this functionality: return predicted path information computed in control to the planning module. First, this PR will significantly change the interface between modules. It also changes the role of each module. Additionally, having FB loop between modules also brings up complex issues, exactly as in the video you posted.

There are reasons for separating control and planning, mainly to maintain high modularity as an OSS. However some performance is sacrificed by separating the modules, for example, path planning has to be done without consideration of control performance.

However, it is clear that we want to do the stop planning from the actual ego position. [A solution using object_collision_checke](https://github.com/autowarefoundation/autoware.universe/issues/2252)r is proposed in the issue, but is this not enough? Using this module will not degrade modularity and will allow stop planning for the predictive path output by the control while maintaining the existing interfaces between the modules.

In addition, we can suggest that instead of getting the predicted path from control, the predicted path be calculated in the planning stage ([It was suggested before](https://github.com/autowarefoundation/autoware/discussions/2859#discussioncomment-3714275)). There are several calculation methods. For instance,
- To integrate the vehicle's speed and angular velocity over a certain period of time (the simplest one).
- To create a model that converges to the target path from ego (e.g., lateral deviation decreases at a constant rate).
- The duplicated MPC (or the same controller used in the control module) runs in the planning module (if the computational resources are available).


What do you think?

@xmfcx @mitsudome-r If you have any comments.

**Comment by brkay54** [comment]
Thank you for your comment @TakaHoribe san.
 

> However, it is clear that we want to do the stop planning from the actual ego position. [A solution using object_collision_checke](https://github.com/autowarefoundation/autoware.universe/issues/2252)r is proposed in the issue, but is this not enough? Using this module will not degrade modularity and will allow stop planning for the predictive path output by the control while maintaining the existing interfaces between the modules.
> 
Actually, it can not solve our problem exactly. `obstacle_collision_checker` just send emergency if the object inside of braking distance. If `emergency_hold` not true, It will cause unwanted behavior (like move - stop - move - stop and go on).

> In addition, we can suggest that instead of getting the predicted path from control, the predicted path be calculated in the planning stage ([It was suggested before](https://github.com/autowarefoundation/autoware/discussions/2859#discussioncomment-3714275)). There are several calculation methods. For instance,
> 
>     * To integrate the vehicle's speed and angular velocity over a certain period of time (the simplest one).
> 
>     * To create a model that converges to the target path from ego (e.g., lateral deviation decreases at a constant rate).
> 
>     * The duplicated MPC (or the same controller used in the control module) runs in the planning module (if the computational resources are available).
> 

Of course we can calculate an estimated path which start from ego base_link, however all of these methods will produce worse estimated path than controller produce. And also these methods cause a lot of false positive collisions (because we will use just current state of vehicle for prediction). Therefore, in my opinion, the most reliable predicted path will be output of controller.

> We must be careful about adding this functionality: return predicted path information computed in control to the planning module. First, this PR will significantly change the interface between modules. It also changes the role of each module. Additionally, having FB loop between modules also brings up complex issues, exactly as in the video you posted.
> 
> There are reasons for separating control and planning, mainly to maintain high modularity as an OSS. However some performance is sacrificed by separating the modules, for example, path planning has to be done without consideration of control performance.

I agree with you, separating the control and planning module is better to avoid this type conflicts. But if one module of planning or control will do collision checking in vehicle's actual path, it shouldn't be planning because control has better and more reliable estimated path and we should use it.

Alternative to this PR, I want to propose that we can add new functionalities to `obstacle_collision_checker`. It is currently checking obstacles in path for emergency stop and also it can be used for smooth stop too. It can communicate with the `vehicle_cmd_gate` to stop the vehicle if there is an obstacle on footprints of predicted path. For example it can use [pause_interface](https://github.com/autowarefoundation/autoware.universe/blob/main/control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp#L422) to stop vehicle or it can calculate the stop accelerations and send them to vehicle_cmd_gate etc. We can design the structure of how we stop. 

Of course it will cause conflict between `obstacle_collision_checker` and `obstacle_stop_planner`. To avoid this, `obstacle_collision_checker` check only some part of predicted_path that is separated from motion_planning trajectory output.

With these, we can separate the modules and we have more reliable predicted path for collision. What do you think about it?

**Comment by yukkysaito** [comment]
Can we discuss it [here](https://github.com/orgs/autowarefoundation/discussions/2859) since it will be an architecture issue?

IMO : https://github.com/orgs/autowarefoundation/discussions/2859#discussioncomment-4235577

**Pull request closed without merging**
