### PR TITLE
refactor(tensorrt_classifier)!: fix namespace and directory structure

### PR DESCRIPTION
**Pull request by MasatoSaeki**
## Description
This PR puts headers in the `autoware` namespace.

Additional works
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468)   [LIST](https://github.com/autowarefoundation/autoware.universe/pull/3606)

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
I tested by traffic light recognition of driving log replayer. And confirmed that there was no change in accuracy or behavior.

## Notes for reviewers
None.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Comment by yukkysaito** [comment]
>Tested in a local recompute environment.

Could you please describe the tests you performed?

**Comment by MasatoSaeki** [comment]
@yukkysaito 
I tested by traffic light recognition of driving log replayer. And confirmed that there was no change in accuracy or behavior.

**Comment by yukkysaito** [comment]
@MasatoSaeki 
Could you write it down here?







image

**Comment by MasatoSaeki** [comment]
@yukkysaito 
I did it.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by ktro2828 — APPROVED** [review]

**Pull request merged**
