### PR TITLE
feat(perception_rviz_plugin): add 2d dummy bus with height

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Description

current 2d car is moving by default but for some functions in avoidance , no stopping are , intersection occlusion spot needs stopping obstacle so I add rviz plugins for stopping bus.

- add 2d dummy stopping bus
image

image

image

## Tests performed

by psim

## Notes for reviewers

run psim and add panel from + button
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@HiroIshida 
[Q] if I put bus in rviz it's a bit heavy processing point cloud.
is there anyways to make computational cost lighter?

**Comment by HiroIshida** [comment]
@taikitanaka3 

### my thought
I think visualization rather than algorithm may cause the problem. Could you check again? 

### experiment 
I tried you new rviz plugin with the setting below: 
setup

Considering the possibility that newly implemented algorithm in 
https://github.com/autowarefoundation/autoware.universe/pull/527  make the simulation slower, I embeddedd the time measurement function to the dummy perception publisher's timer callback, and measure the difference between processing time of ego-centric (new) and object centric point cloud generation methods. The result below reveals that point cloud generation algorithm does affect much here. 

Note that typical processing time of the algorithms should be 
object-centric without raytracing < ego-centric << object-centric  with raytracing . 
I omitted object-centric with raytracing in this experiment.

newer algorithm, Ego-centric (with raytracing in principle)
```
[dummy_perception_publisher_node-35] [INFO] [1652690826.930240479] [simulation.dummy_perception_publisher]: callback elapsed time: 32.6487
[dummy_perception_publisher_node-35] [INFO] [1652690827.027392244] [simulation.dummy_perception_publisher]: callback elapsed time: 29.8299
[dummy_perception_publisher_node-35] [INFO] [1652690827.124755941] [simulation.dummy_perception_publisher]: callback elapsed time: 27.1835
[dummy_perception_publisher_node-35] [INFO] [1652690827.223872107] [simulation.dummy_perception_publisher]: callback elapsed time: 26.2822
```

old algorithm, Object-centric (disabled raytracing)
```
[dummy_perception_publisher_node-35] [INFO] [1652691405.282255247] [simulation.dummy_perception_publisher]: callback elapsed time: 23.8785
[dummy_perception_publisher_node-35] [INFO] [1652691405.383950450] [simulation.dummy_perception_publisher]: callback elapsed time: 25.5756
[dummy_perception_publisher_node-35] [INFO] [1652691405.482130112] [simulation.dummy_perception_publisher]: callback elapsed time: 23.7911
[dummy_perception_publisher_node-35] [INFO] [1652691405.582512018] [simulation.dummy_perception_publisher]: callback elapsed time: 24.1669
```

I then though maybe visualization (or entailing communication) take much computational effort a lot, so I compare `htop` result turning  on and off the rviz. The result below shows significant computational load decline after turning off rviz. I'm not certainly sure, but from the observation so far, visualization rather than algorithm should be improved in some way. 

with_rviz

without_rviz
.png)

**Comment by HiroIshida** [comment]
@taikitanaka3 
Let me give bit more time to probe this issue. Now I realized that just comparing processing time between the algorithm is not enough.

**Comment by HiroIshida** [comment]
(DRAFT) now writing... 

when running with object centric mode:
```
$ ps -aux |grep dummy_perception_publisher_node|head -1| awk '{print $2}' | xargs -i pidstat -p {} 5 100
Linux 5.14.0-1036-oem (stonet4) 	05/18/2022 	_x86_64_	(12 CPU)

05:41:54 AM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
05:41:59 AM  1000    188562    3.80    0.00    0.00    0.40    3.80     6  dummy_perceptio
05:42:04 AM  1000    188562    4.00    0.00    0.00    0.00    4.00     5  dummy_perceptio
05:42:09 AM  1000    188562    4.00    0.00    0.00    0.20    4.00     3  dummy_perceptio
05:42:14 AM  1000    188562    4.00    0.00    0.00    0.20    4.00     6  dummy_perceptio
05:42:19 AM  1000    188562    3.80    0.00    0.00    0.40    3.80     7  dummy_perceptio
^C
Average:     1000    188562    3.92    0.00    0.00    0.24    3.92     -  dummy_perceptio
```
when running with ego-centric mode:
```
$ ps -aux |grep dummy_perception_publisher_node|head -1| awk '{print $2}' | xargs -i pidstat -p {} 5 100
Linux 5.14.0-1036-oem (stonet4) 	05/18/2022 	_x86_64_	(12 CPU)

05:46:31 AM   UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
05:46:36 AM  1000    199150   13.60    0.40    0.00    0.80   14.00     5  dummy_perceptio
05:46:41 AM  1000    199150   13.60    1.00    0.00    0.60   14.60     7  dummy_perceptio
05:46:46 AM  1000    199150   13.20    0.80    0.00    0.60   14.00     3  dummy_perceptio
05:46:51 AM  1000    199150   13.20    1.00    0.00    0.80   14.20     4  dummy_perceptio
05:46:56 AM  1000    199150   13.40    1.20    0.00    0.60   14.60     9  dummy_perceptio
^C
Average:     1000    199150   13.40    0.88    0.00    0.68   14.28     -  dummy_perceptio
```

**Comment by HiroIshida** [comment]
@taikitanaka3 
I made a PR that reduce the aboud 50% computational load.  
https://github.com/autowarefoundation/autoware.universe/pull/926

**Comment by taikitanaka3** [comment]
@HiroIshida 
Thank you I will take a look and test this at today evening.

**Review by shmpwk — COMMENTED** [review]
@taikitanaka3 
Could you add info about this nice feature at README?

**Comment by shmpwk** [comment]
Screenshot from 2022-05-30 16-41-59
I added icon for bus rviz tool by [8f26b4b](https://github.com/autowarefoundation/autoware.universe/pull/903/commits/8f26b4bf7be43d2f14820874341e086fa38a538b)

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
