### PR TITLE
fix(ad_service_state_monitor): add missing vector map input

### PR DESCRIPTION
**Pull request by brian841102**
These updates could fix the issue #1168

### CODE REVIEW

**Comment by wep21** [comment]
before
```
❯ ros2 launch ad_service_state_monitor ad_service_state_monitor.launch.xml

❯ ros2 topic list
/api/autoware/get/engage
/autoware/engage
/autoware/state
/control/command/control_cmd
/control/trajectory_follower/control_cmd
/diagnostics
/initialpose3d
/input/vector_map
/localization/kinematic_state
/localization/pose_twist_fusion_filter/pose
/map/pointcloud_map
/map/vector_map
/parameter_events
/perception/object_recognition/objects
/perception/obstacle_segmentation/pointcloud
/planning/mission_planning/route
/planning/scenario_planning/trajectory
/rosout
/system/emergency/control_cmd
/tf
/tf_static
/vehicle/status/control_mode
/vehicle/status/steering_status
/vehicle/status/velocity_status
```

**Comment by wep21** [comment]
after
```
❯ ros2 topic list
/api/autoware/get/engage
/autoware/engage
/autoware/state
/control/command/control_cmd
/control/trajectory_follower/control_cmd
/diagnostics
/initialpose3d
/localization/kinematic_state
/localization/pose_twist_fusion_filter/pose
/map/pointcloud_map
/map/vector_map
/parameter_events
/perception/object_recognition/objects
/perception/obstacle_segmentation/pointcloud
/planning/mission_planning/route
/planning/scenario_planning/trajectory
/rosout
/system/emergency/control_cmd
/tf
/tf_static
/vehicle/status/control_mode
/vehicle/status/steering_status
/vehicle/status/velocity_status
```

**Review by wep21 — APPROVED** [review]
@brian841102 Thank you for the fix. It looks good to me.
I recommend that you use github template even though it's a small fix.

**Comment by brian841102** [comment]
> @brian841102 Thank you for the fix. It looks good to me. I recommend that you use github template even though it's a small fix.

Thanks for your advice. But I am new to Autoware Community, could you tell me which github template I should follow?

**Comment by shmpwk** [comment]
@brian841102 
Thank you for your contribution!
PR guideline is here.

https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

You can choose template from preview page
Screenshot from 2022-06-26 00-17-35

**Comment by brian841102** [comment]
> @brian841102 Thank you for your contribution! PR guideline is [here](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
> 
> You can choose PR template from preview page: standard change or small change. But once you don't choose template, it may disappear. So you cannot use a template for this PR maybe. FYI, template is created from [here](https://github.com/autowarefoundation/autoware.universe/blob/main/.github/PULL_REQUEST_TEMPLATE.md).
> 
> Screenshot from 2022-06-26 00-31-35

Haha Okay~ Actually I noticed after pull request was sent. 
And like you said, I cannot get the template afterward. 
I will follow the template next time. ＾＿＾

**Pull request merged**
