### PR TITLE
feat: add detected object feature remover

### PR DESCRIPTION
**Pull request by YoheiMishina**
Related Issue
#1 

Related Link

Description
Add detected object feature remover from https://github.com/tier4/AutowareArchitectureProposal.iv

How to review
Check the following item

Readme
Launch file

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@YoheiMishina 
PR tiltle should be list below
```
Available types:
 - feat
 - fix
 - docs
 - style
 - refactor
 - perf
 - test
 - build
 - ci
 - chore
 - revert
 ```

**Comment by YoheiMishina** [comment]
@taikitanaka3 I fixed it

**Review by taikitanaka3 — APPROVED** [review]

**Comment by taikitanaka3** [comment]
f91e5d3 this commit may need feat: ~

**Comment by YoheiMishina** [comment]
> [f91e5d3](https://github.com/autowarefoundation/autoware.universe/commit/f91e5d3e2aa612ebd01924e895cc5fbdd0a7652b) this commit may need feat: ~

I can't edit commit titles.
Cloud you tell me how to fix?

**Comment by YoheiMishina** [comment]
Create new PR #110

**Pull request closed without merging**
