### PR TITLE
feat(map_loader): show intersection areas

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Show intersection area polygon.

related PR: 

- https://github.com/autowarefoundation/autoware_common/pull/211
- https://github.com/autowarefoundation/autoware_launch/pull/655

Screenshot from 2023-10-25 09-07-16

## Tests performed

Psim.

## Effects on system behavior

Nothing.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Motsu-san** [comment]
@satoshi-ota Thank you for your PR! Could you tell us who you want to review this?

**Comment by satoshi-ota** [comment]
> @satoshi-ota Thank you for your PR! Could you tell us who you want to review this?

@Motsu-san Thanks! Yes, I would like you to review this PR. (On the other hand, I asked @mitsudome-r san to review this in [slack](https://star4.slack.com/archives/C4P0NSMB5/p1698192997966019).)

**Comment by Motsu-san** [comment]
@satoshi-ota The following PR is related isn't it?
https://github.com/autowarefoundation/autoware_launch/pull/655

**Comment by satoshi-ota** [comment]
> @satoshi-ota The following PR is related isn't it? [autowarefoundation/autoware_launch#655](https://github.com/autowarefoundation/autoware_launch/pull/655)

@Motsu-san YES! I'll add link to PR description.

**Review by Motsu-san — APPROVED** [review]
[LGTMeow](https://lgtmeow.com)

**Comment by Motsu-san** [comment]
Sorry for my confusing LGTM post, I will approve this after all checks are passed.

**Review by mitsudome-r — APPROVED** [review]

**Comment by mitsudome-r** [comment]
FYI, I have merged the dependent PR in autoware_common.

**Comment by satoshi-ota** [comment]
Conflict... :pleading_face: I'll fix it.

**Pull request merged**
