### PR TITLE
fix(raw_vehicle_cmd_converter): csv paths are resolved in param.yaml

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6473

Continuation of:
- https://github.com/autowarefoundation/autoware.universe/pull/6456
- https://github.com/autowarefoundation/autoware.universe/pull/6136
- https://github.com/autowarefoundation/autoware.universe/pull/5134

Related PR:
- https://github.com/autowarefoundation/autoware_launch/pull/884
  - `autoware_launch` PR should be merged after this PR.

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
@rej55 from:
- https://github.com/autowarefoundation/autoware.universe/pull/6136
> However, if we launch `raw_vehicle_cmd_converter` from `autoware_launch`, some parameters defined in launch files does not appear.
> 
> In this change, I fixed above problems.
> 
> accel/brake/steer map path should change at launch, so I removed `csv_path_**_map` from yaml file and add them into xml file.

What do you mean by this?

What is wrong with having things this way?

As long as we have this:
https://github.com/autowarefoundation/autoware.universe/blob/50bb61361a522650124b8566298f433c119bd00b/vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml#L11

`<param from="$(var config_file)" allow_substs="true"/>` it should work alright.

**Comment by xmfcx** [comment]
@mkuri @taikitanaka3
 @TakaHoribe could you review this as a code owner?
I would like to merge this as soon as possible and make the action required.

**Comment by xmfcx** [comment]
@rej55 could you look into this? I want to merge this.

**Comment by rej55** [comment]
@xmfcx 
The change looks okay but we have to change some launch files in other repository.
I will change it in this week, so could you wait, please?

**Comment by xmfcx** [comment]
@rej55 It's alright, I am waiting for your updates :+1: 

cant wait

**Review by rej55 — APPROVED** [review]
I checked that it worked with this change.
LGTM

**Pull request merged**
