### PR TITLE
feat(behavior_path_planner): modified goal with uuid

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

publish modified goal with uuid as proposed in https://github.com/autowarefoundation/autoware/discussions/2983

> modified goal stamp
Use the stamp of the timing when behavior_path_planner is triggered for modified goal. It is the same as path_with_lane_id's one.

> modified goal publish timing
Only when the goal is modified and do not publish in a module that does not have a modification function.

image

TODO other than this PR
- support uuid in mission planner (generate uuid etc)
- support PoseStampedWithUuid visualization in rviz_plugin

## Related links

https://github.com/tier4/autoware_launch/pull/674

## Tests performed

psim

publish modified goal only when goal is modified

https://user-images.githubusercontent.com/39142679/210081598-88f2aac5-8d8a-479e-879d-e2349906c970.mp4

state change to ARRIVED when arrived the modified goal
Screenshot from 2022-12-30 23-14-34

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@kosuke55 When is goal modified? And can it be tested with sample-map-planning on [this page](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/)?

**Comment by kosuke55** [comment]
@isamu-takagi 
In only pull_over scene module, the path is checked for safety at 10hz and if it is unsafe, the goal is modified and published. (like video in the description)

No, I did not check with sample-map-planning, so will check it.

**Comment by isamu-takagi** [comment]
@kosuke55 I tried to put obstacles near the goal like in the video, but the stop line appeared and the goal was not modified.

**Comment by kosuke55** [comment]
@isamu-takagi 
pull over is triggered when a goal is placed on a `road_shoulder`. The location on the sample map is shown in the video.
And the goal is modified when the `modified_goal` is farther than a certain distance (parking area is green). When it is closer, the path is determined (the parking area turns yellow) and the goal is not modified.


https://user-images.githubusercontent.com/39142679/211706036-3f3deec6-0e26-4c67-a33d-ee05abdadd93.mp4

**Review by isamu-takagi — APPROVED** [review]
@kosuke55 Thank you. It worked. However, since the UUID is always zero, it was not possible to check whether it was reflected. It needs to be checked when mission planner generates UUID.

**Review by rej55 — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
Changed msg name for https://github.com/autowarefoundation/autoware_msgs/pull/50 in https://github.com/autowarefoundation/autoware.universe/pull/2602/commits/d4db058d22a0ddf4d5f4a1feac5333369e77524f

**Comment by kosuke55** [comment]
visualizer of pose_with_uuid_stamped https://github.com/autowarefoundation/autoware.universe/pull/2662

**Pull request merged**
