### PR TITLE
feat(vehicle_cmd_gate): add an option for using raw external commands

### LINKED ISSUE #4324: Add an option for don't using filtered control commands for external input
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

At the current design of autoware, we cannot use raw external remote controller commands. For example, if we use DS4 joystick in [joy_controller](https://github.com/autowarefoundation/autoware.universe/tree/main/control/joy_controller) package, the raw joystick commands filtered by [external_cmd_converter](https://github.com/autowarefoundation/autoware.universe/tree/main/vehicle/external_cmd_converter) and [vehicle_cmd_gate](https://github.com/autowarefoundation/autoware.universe/tree/main/control/vehicle_cmd_gate). 

### Purpose

If we make our vehicle which can be controlled like R/C car, we can want to use raw joystick message input for ```/control/command/control_cmd```. There is no need acceleration map, braking map or filtering

### Possible approaches

Add an option for skipping filtering on input external control commands.

### Definition of done

Update external_cmd_converter and vehicle_cmd_gate for this purpose

### PR DESCRIPTION
**Pull request by ismetatabay**
## Description

This PR adds an option for using raw external commands for vehicle such as R/C controlled car

## Related links

closes #4324

autoware_launch PR: 
- https://github.com/autowarefoundation/autoware_launch/pull/460

## Tests performed
Planning simulator with joy controller:

- ```use_raw_remote_control_command_input``` is set to false (full right on DS4):

 https://github.com/autowarefoundation/autoware.universe/assets/56237550/b80a67d9-4019-47ed-a66d-c822de5b61dc

- ```use_raw_remote_control_command_input``` is set to true:

https://github.com/autowarefoundation/autoware.universe/assets/56237550/47231807-059b-4689-b946-882c718f59bf

## Interface changes

use_raw_remote_control_command_input is added to tier4_control_component.launch.xml

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ismetatabay** [comment]
Hi @TakaHoribe , I hope you are well. What do you think of this PR?

**Comment by TakaHoribe** [comment]
@ismetatabay Thank you for your PR.

The modification in the `vehicle_cmd_gate` makes sense. Would you please change the parameter name to `enable_cmd_limit_filter`?

I don't know why you need to modify the `external_cmd_converter`. The role of the module is to convert the external command to the Ackermann control command. If you send the Ackermann control command directly from joy, why don't you just send it directly to the `vehicle_cmd_gate`?

**Comment by ismetatabay** [comment]
@TakaHoribe Thank you for your reply :+1:. I modified ```external_cmd_converter``` because I did not want to change autoware.universe launch file directly:

https://github.com/autowarefoundation/autoware.universe/blob/13b96ad3c636389b32fea3a47dfb7cfb7813cadc/launch/tier4_control_launch/launch/control.launch.py#L172

I could change this topic, but I don't want change anything in autoware.universe. If the input topic names as parameters that migrating in ```autoware_launch```, I can change it directly on ```autoware_launch``` fork. What is your suggestion at this point, what would make more sense to do?

**Comment by ismetatabay** [comment]
@TakaHoribe Sorry for late reply, I have been on field test. Thanks for the valuable information and guidance, I get it and I updated it as you said :+1: .

**Comment by ismetatabay** [comment]
@TakaHoribe friendly ping

**Comment by ismetatabay** [comment]
Hi @TakaHoribe, can you have a chance for checking this PR?

**Comment by TakaHoribe** [comment]
@ismetatabay Sorry for being late. This PR is almost ok, but any reason why you set `enable_cmd_limit_filter` parameter directly in the launch file, not in the param.yaml file? 

The parameters to change the node behavior should be stored in the param file. Only parameters that change the launch configuration should be defined in the launch file directly. In this case, it is better to have `enable_cmd_limit_filter` in the param.yaml file.

**Comment by ismetatabay** [comment]
@TakaHoribe Hi, thank your for reply. I forgot moving the parameter in .param.yaml file.(In the beginning, I want to use this param at vehicle_cmd_gate and external_cmd_converter)

I updated param file, and I deleted ```enable_cmd_limit_filter``` argument at launch file :+1:

**Comment by TakaHoribe** [comment]
@ismetatabay please merge it with launch PR: https://github.com/autowarefoundation/autoware_launch/pull/460

**Pull request merged**
