### PR TITLE
[obsolete] feat(tier4_planning_launch): generalize launch files

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

Updated tier4_planning_launch so that tier4_planning_launch will be product-agnostic.
Not all parameters may be extracted in `planning.launch.xml`, but most of them which are important to be product-agnostic were extracted.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kenji-miyake — DISMISSED** [review]

**Comment by takayuki5168** [comment]
Sorry, I forgot to add these parameters, which I removed from launch
https://github.com/autowarefoundation/autoware.universe/pull/770/commits/0b2e36fb74554bb42f7109a2b97811a877f2d466

**Comment by takayuki5168** [comment]
With this commit,
- Added default parameters of `declare_parameter` of cpp files in launch config file.
- Copied launch config file to obstacle_stop_planner package's config file.
https://github.com/autowarefoundation/autoware.universe/pull/770/commits/1cf1d0a25907bae846312d2802e626691434104f

**Comment by takayuki5168** [comment]
I verified this PR with the following one, removing default parameters of `declare_parameter`.
https://github.com/autowarefoundation/autoware.universe/pull/772

Now it's ready to merge.

**Review by kenji-miyake — APPROVED** [review]
It seems some default values have changed, so users who directly refer here should take care of them.

**Comment by takayuki5168** [comment]
@kenji-miyake 
> It seems some default values have changed, so users who directly refer here should take care of them.
Lemme check.
enable_slow_down, motion_velocity_smoother_type, use_surround_obstacle_checker, bt_tree_config_file can be changed.
Is this what you are concerning about?

**Comment by kenji-miyake** [comment]
No, this part.
image

**Comment by takayuki5168** [comment]
Right. Thanks for your comment.

**Comment by yukkysaito** [comment]
@takayuki5168 Do you undo some of the parameters that have been changed?

**Comment by takayuki5168** [comment]
@yukkysaito 
Then planning package's parameters and launcher's parameters differs. Is that OK?

**Pull request closed without merging**
