### PR TITLE
refactor(autoware_pointcloud_preprocessor): rework parameters

### PR DESCRIPTION
**Pull request by Ariiees**
## Description
Implement the ROS Node configuration layout for the sensing/pointcloud_preprocessor package.

## Test performed
1. **Build**
 ```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to autoware_vehicle_info_utils
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to autoware_pointcloud_preprocessor
```
2. **Launch** 
```
ros2 launch pointcloud_preprocessor approximate_downsample_filter.launch.xml
ros2 launch pointcloud_preprocessor blockage_diag.launch.xml
ros2 launch pointcloud_preprocessor distortion_corrector.launch.xml
ros2 launch  pointcloud_preprocessor dual_return_outlier_filter.launch.xml
ros2 launch pointcloud_preprocessor lanelet2_map_filter.launch.xml
ros2 launch pointcloud_preprocessor pickup_based_voxel_grid_downsample_filter.launch.xml
ros2 launch pointcloud_preprocessor pointcloud_accumulator.launch.xml
ros2 launch pointcloud_preprocessor polygon_remover.launch.py
ros2 launch pointcloud_preprocessor preprocessor.launch.xml
ros2 launch pointcloud_preprocessor radius_search_2d_outlier_filter.launch.xml
ros2 launch pointcloud_preprocessor random_downsample_filter.launch.xml
ros2 launch pointcloud_preprocessor ring_outlier_filter.launch.xml
ros2 launch pointcloud_preprocessor ring_passthrough_filter.launch.xml
ros2 launch pointcloud_preprocessor vector_map_inside_area_filter.launch.xml
ros2 launch pointcloud_preprocessor voxel_grid_downsample_filter.launch.xml
ros2 launch pointcloud_preprocessor voxel_grid_outlier_filter.launch.xml
```

## Notes for reviewers
None

## Interface Changes
1. Remove all default values in declare_parameter() function
2. Create .yaml files for all used nodes.
3. Update .launch.xml file to import .yaml.
4. Create schema for each launch file.
5. Update README.md
6. Test **build** and **launch** successfully.

## Effects on system behavior
None

## Pre-review checklist for the PR author
The PR author must check the checkboxes below when creating the PR.
- [x] I've confirmed  the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/)
- [x] The PR follows the [pull request guidelines](https://github.com/autowarefoundation/autoware.universe/pull/7204) 

## In-review checklist for the PR reviewers
The PR reviewers must check the checkboxes below before approval.
- [ ] The PR follows the [pull request guidelines](https://github.com/autowarefoundation/autoware.universe/pull/7204)
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author
The PR author must check the checkboxes below before merging.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.
After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by vividf** [comment]
@Ariiees 
Some issues need to be fixed. 
- I couldn't find the schema for radius_search_2d_outlier_filter.schema.json
- The default parameters for all nodes have not been removed. 
- Cropbox schema misses the `negative` parameter

The command you provide is the old version of `pointcloud_preprocessor`. Now it is called `autoware_pointcloud_preprocessor`. 
Please make sure you test all of the launchers and also double-check all of the files.
Thanks :)

**Comment by Ariiees** [comment]
@vividf Thank you so much for your patience and help recently! I have updated the src folder and solved the schema problem. 

But after I combined the code to the current main, I encountered an error during the build for autoware_universe_utitls: tier4_debug_msgs/msg/processing_time_node.hpp: No such file or directory. 

(autoware_universe_utilis is a new folder under common)

**Comment by vividf** [comment]
@Ariiees I think it would be easier if you modify the src/xxx.cpp file again (I think it will not be too hard since we already have the accurate version to compare with). From the https://github.com/autowarefoundation/autoware.universe/pull/8297/commits/37a7d37b32cac8beae30303ddebb0e46c39c8048 there are some conflicts, and I think that is why the build is failed.

**Comment by vividf** [comment]
@Ariiees 
I apologize for the recent delays; there have been significant changes in Autoware that have made it difficult to finalize this PR. Upon reviewing the PR again, I noticed that some files are missing, and the large number of changes has made it challenging to identify the bug accurately.

To address this, I propose breaking down this large PR into smaller, more manageable ones, which will make the review process more efficient. However, I realize this may require considerable time and effort on your part, so I will take over the task of separating the PRs to ensure a smoother review process.

Thank you again for your hard work! I will be sure to acknowledge your contributions in each PR.

**Comment by vividf** [comment]
Separate large PR to smaller PRs

**Comment by Ariiees** [comment]
> @Ariiees I apologize for the recent delays; there have been significant changes in Autoware that have made it difficult to finalize this PR. Upon reviewing the PR again, I noticed that some files are missing, and the large number of changes has made it challenging to identify the bug accurately.
> 
> To address this, I propose breaking down this large PR into smaller, more manageable ones, which will make the review process more efficient. However, I realize this may require considerable time and effort on your part, so I will take over the task of separating the PRs to ensure a smoother review process.
> 
> Thank you again for your hard work! I will be sure to acknowledge your contributions in each PR.

Hi @vividf. Thank you so much for your help and patience with me on this PR! I will work on the new separate PR!

**Pull request closed without merging**
