### PR TITLE
feat(pose_initializer): check error initial pose and gnss pose, output diagnostics

### PR DESCRIPTION
**Pull request by RyuYamamoto**
## Description
- Check 2D(x-y) Error between Initial Pose result and GNSS Pose, if pose error is large, output an message in the /diagnostics topic.
- This feature is off by default, but can be enabled by setting pose_error_check_enabled to true when the GNSS is reliable, such as RTK-GNSS.

Screenshot from 2024-09-24 18-48-16

## Related links
https://github.com/autowarefoundation/autoware_launch/pull/1180

**Parent Issue:**

- Link

## How was this PR tested?
- checkout autoware_launch to [feat/initial_pose_check_with_gnss](https://github.com/autowarefoundation/autoware_launch/pull/1180)
- Check that localization works correctly in logging_simulator.
- Set pose_error_check_enabled to True and check that diagnostics (gnss_pose_error_2d, is_gnss_pose_error) are output. If set to False, gnss_pose_error_2d and is_gnss_pose_error are not output.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that both the `logging_simulator` and `e2e_simulator` work well.
I also checked that when I give an initial pose far from the GNSS pose to the `e2e_simulator`, a warning is output.
LGTM

**Review by TaikiYamada4 — COMMENTED** [review]
@RyuYamamoto 
Regarding the keys in the `/diagnostics`, I think these key names might be better for presentation

- `is_gnss_pose_error` -> `is_gnss_pose_error_large` or `has_gnss_pose_large_error`
- `initial_pose_reliable` -> `is_initial_pose_reliable`

**Comment by RyuYamamoto** [comment]
I will fix it with ```is_hogehoge``` to match.
```is_gnss_pose_error``` -> ```is_gnss_pose_error_large```
```initial_pose_reliable``` -> ```is_initial_pose_reliable```

**Comment by RyuYamamoto** [comment]
renamed in b574603e78e0f2507d4bb69a668910ce77253c31

**Review by TaikiYamada4 — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
