### PR TITLE
fix: update trt api

### PR DESCRIPTION
**Pull request by wep21**
## Description

closes #1436 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
is it supported to work on x86 and nvidia gpu not only Jetson AGX ?

**Comment by yukke42** [comment]
The packages have been failed to be built in the environment of [autoware](https://github.com/autowarefoundation/autoware/blob/main/amd64.env).

```
Starting >>> lidar_apollo_instance_segmentation
--- stderr: lidar_apollo_instance_segmentation                                
/home/yusuke/ghq/github.com/tier4/pilot-auto.xx1/src/autoware/universe/perception/lidar_apollo_instance_segmentation/src/detector.cpp: In constructor ‘LidarApolloInstanceSegmentation::LidarApolloInstanceSegmentation(rclcpp::Node*)’:
/home/yusuke/ghq/github.com/tier4/pilot-auto.xx1/src/autoware/universe/perception/lidar_apollo_instance_segmentation/src/detector.cpp:63:13: error: ‘class nvinfer1::IBuilderConfig’ has no member named ‘setMemoryPoolLimit’
   63 |     config->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE, 1 << 30);
      |             ^~~~~~~~~~~~~~~~~~
/home/yusuke/ghq/github.com/tier4/pilot-auto.xx1/src/autoware/universe/perception/lidar_apollo_instance_segmentation/src/detector.cpp:63:42: error: ‘nvinfer1::MemoryPoolType’ has not been declared
   63 |     config->setMemoryPoolLimit(nvinfer1::MemoryPoolType::kWORKSPACE, 1 << 30);
      |                                          ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/lidar_apollo_instance_segmentation.dir/build.make:76: CMakeFiles/lidar_apollo_instance_segmentation.dir/src/detector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/lidar_apollo_instance_segmentation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< lidar_apollo_instance_segmentation [10.0s, exited with code 2]

Summary: 10 packages finished [13.7s]
  1 package failed: lidar_apollo_instance_segmentation
  1 package had stderr output: lidar_apollo_instance_segmentation
```

```
❯ sudo dpkg -l | grep libnvinfer
hi  libnvinfer-dev                                      8.2.4-1+cuda11.4                     amd64        TensorRT development libraries and headers
hi  libnvinfer-plugin-dev                               8.2.4-1+cuda11.4                     amd64        TensorRT plugin libraries
hi  libnvinfer-plugin8                                  8.2.4-1+cuda11.4                     amd64        TensorRT plugin libraries
hi  libnvinfer8                                         8.2.4-1+cuda11.4                     amd64        TensorRT runtime libraries
```

**Comment by wep21** [comment]
This PR requires https://github.com/autowarefoundation/autoware/pull/2766.

**Comment by yukke42** [comment]
@wep21 I checked the lidar_centerpoint package runs successfully with <https://github.com/autowarefoundation/autoware/pull/2766>. But there are no outputs from the lidar_apollo_instance_segmentation package by the error `[lidar_apollo_instance_segmentation_node-29] ERROR: 3: [executionContext.cpp::executeV2::521] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::executeV2::521, condition: !mEngine.hasImplicitBatchDimension()`. So traffic_light_classifier may also have the same error. Cloud you please check this error?

**Comment by wep21** [comment]
@yukke42 Could you try https://github.com/autowarefoundation/autoware.universe/pull/1436 first? It may be better to keep backward compatibility for multiple l4t version e.g. 32.6(tensorrt 8.2) and 34.1(tensorrt 8.4).

**Comment by wep21** [comment]
@NilaySener I added modifications to compile without adding `-Wno-deprecated-declarations` except for `lidar_apollo_instance_segmentation`. Could you try and review this PR?

**Comment by wep21** [comment]
@yukke42 I added more modifications to build with tensorrt 8.2. Could you try to run with a rosbag again?
I reverted changes for `lidar_apollo_instance_segmentation` because explicit batch is not supported for caffe parser.  https://github.com/NVIDIA/TensorRT/issues/470

**Review by yukke42 — APPROVED** [review]
I confirmed for these packages to run successfully.

**Comment by NilaySener** [comment]
> @NilaySener I added modifications to compile without adding `-Wno-deprecated-declarations` except for `lidar_apollo_instance_segmentation`. Could you try and review this PR?

@wep21  I tried to compile this PR and it didn't give a deprecation error on Jetson AGX-Orin.

**Comment by wep21** [comment]
@NilaySener Thank you for confirming it. [Your PR](https://github.com/autowarefoundation/autoware.universe/pull/1436) is closed due to merging this PR, but thank you for your contribution.

**Pull request merged**
