### PR TITLE
fix(behavior_velocity_planner): fix blind spot over-detection

### PR DESCRIPTION
**Pull request by tkimura4**
## Description
To prevent over-detection of blind_spot, I added yaw difference threshold between ego and target objects as detection conditions.

## Tests performed
On the planning-simulator, I checked blind_spot behavior by setting pedestrian objects around a intersection

Before:
image
image

After:
image
image

(Note that even if this PR is merged the over-detection will not fully fix. )
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].
- [X] The PR has been properly tested.
- [X] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.
- [X] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by taikitanaka3 — APPROVED** [review]

**Review by soblin — APPROVED** [review]
LGTM

@tkimura4 This overdetection is mainly because of this previous PR: https://github.com/autowarefoundation/autoware.universe/pull/2279. I think I can revert the detection condition of this PR when prediction is improved.

**Review by 1222-takeshi — APPROVED** [review]
LGTM
image

**Comment by soblin** [comment]
@shmpwk can you just approve this ?

**Review by shmpwk — APPROVED** [review]
LGTM

**Comment by tkimura4** [comment]
@purewater0901 
Could you approve this?

**Review by purewater0901 — APPROVED** [review]
@tkimura4 Sure! LGTM

**Pull request merged**
