### PR TITLE
chore(build): remove tier4_autoware_utils.hpp/motion_utils.hpp from behavior_velocities

### PR DESCRIPTION
**Pull request by soblin**
## Description

depends https://github.com/autowarefoundation/autoware.universe/pull/4934

https://github.com/autowarefoundation/autoware.universe/issues/4821

## Tests performed

none

## Effects on system behavior

none

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kyoichi-sugahara — APPROVED** [review]

**Review by kosuke55 — APPROVED** [review]

**Review by isamu-takagi — APPROVED** [review]

**Review by taikitanaka3 — APPROVED** [review]

**Comment by soblin** [comment]
@TomohitoAndo @maxime-clem @ahmeddesokyebrahim @satoshi-ota Can you approve this PR ?

**Review by maxime-clem — APPROVED** [review]

**Review by TomohitoAndo — APPROVED** [review]

**Review by taikitanaka3 — APPROVED** [review]

**Comment by soblin** [comment]
@mehmetdogru Can you review this PR ?

**Review by mehmetdogru — APPROVED** [review]
Tested `speed bump` module. Works as intended.

**Review by satoshi-ota — APPROVED** [review]

**Review by TakaHoribe — APPROVED** [review]

**Review by tkimura4 — APPROVED** [review]
LGTM

**Pull request merged**
