### PR TITLE
fix(autoware_auto_perception_rviz_plugin): move headers to a separate directory

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR moves headers to a directory that matches the name of the package.

See https://github.com/autowarefoundation/autoware/issues/4070
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@scepter914 @taikitanaka3 @1222-takeshi @xmfcx @mitsudome-r could you have a look at these changes when you have a moment? Thanks.

**Review by miursh — APPROVED** [review]
LGTM
@esteve could you fix the conflicts?

**Comment by esteve** [comment]
@miursh done, thanks for the review.

**Comment by esteve** [comment]
@miursh thanks for the review, unfortunately I can't merge this PR, not sure if it's because it needs a review from one of the code owners (@1222-takeshi @scepter914 @taikitanaka3). Can you merge it? Thanks

**Comment by esteve** [comment]
@scepter914 thanks!

**Pull request merged**
