### PR TITLE
feat(obstacle_cruise_planner): add goal safe distance

### PR DESCRIPTION
**Pull request by purewater0901**
Signed-off-by: yutaka <purewater0901@gmail.com>

## Description
Add a new parameter for safe stop distance when stopping at a goal
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by purewater0901** [comment]
@kosuke55

**Comment by purewater0901** [comment]
[Launch PR](https://github.com/tier4/autoware_launch/pull/503)

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
memo:
terminal collision check was implemented in https://github.com/autowarefoundation/autoware.universe/pull/1807

**Pull request merged**
