### PR TITLE
feat(motion_utils): insertTargetPoint with negative length

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

support negative length for the following insertTargetPoint function.
```cpp
template <class T>
inline boost::optional<size_t> insertTargetPoint(
  const size_t src_segment_idx, const double insert_point_length, T & points,
  const double overlap_threshold = 1e-3)
```

## Tests performed

Unit test

## Effects on system behavior

Nothing

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@purewater0901 Could you review the PR.

**Comment by purewater0901** [comment]
@takayuki5168 It seems that your change includes obstacle avoidance planner. Are you going to include these changes in this PR？

**Comment by takayuki5168** [comment]
@purewater0901 Sorry about my mistake. I fixed the PR.

**Review by purewater0901 — APPROVED** [review]
LGTM

**Pull request merged**
