### PR TITLE
feat(image_projection_based_fusion): add timekeeper

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add time keeper feature to `image_projection_based_fusion`.

This PR must merge with https://github.com/autowarefoundation/autoware_launch/pull/1274

Sample output:
```
# roi_cluster_fusion
    🌲 Total Processing Time Tree 🌲
    100.00% roiCallback: total 11.86 [ms], avg. 0.00 [ms], run count: 4103

    100.00% subCallback: total 5867.53 [ms], avg. 10.03 [ms], run count: 585
        ├── 0.00% preprocess: total 0.28 [ms], avg. 0.00 [ms], run count: 585
        ├── 86.38% fuseOnSingleImage: total 5068.63 [ms], avg. 1.44 [ms], run count: 3510
        ├── 0.00% postprocess: total 0.00 [ms], avg. 0.00 [ms], run count: 585
        └── 13.61% rest: 798.62 [ms]

# pointpainting_fusion
    🌲 Total Processing Time Tree 🌲
    100.00% roiCallback: total 7920.99 [ms], avg. 1.93 [ms], run count: 4103
        ├── 88.52% postprocess: total 7012.00 [ms], avg. 27.39 [ms], run count: 256
        ├── 11.16% fuseOnSingleImage: total 883.83 [ms], avg. 2.79 [ms], run count: 317
        │   ├── 0.01% publish debug message: total 0.73 [ms], avg. 0.00 [ms], run count: 317
        │   └── 11.15% rest: 883.10 [ms]
        └── 0.32% rest: 25.16 [ms]

    100.00% subCallback: total 24641.75 [ms], avg. 42.19 [ms], run count: 584
        ├── 5.04% preprocess: total 1240.97 [ms], avg. 2.12 [ms], run count: 584
        ├── 55.29% fuseOnSingleImage: total 13625.33 [ms], avg. 4.40 [ms], run count: 3094
        │   ├── 5.42% publish debug message: total 1335.00 [ms], avg. 0.43 [ms], run count: 3094
        │   └── 49.88% rest: 12290.34 [ms]
        ├── 37.80% postprocess: total 9314.53 [ms], avg. 28.31 [ms], run count: 329
        └── 1.87% rest: 460.92 [ms]

# roi_pointcloud_fusion
    🌲 Total Processing Time Tree 🌲
    100.00% roiCallback: total 21.70 [ms], avg. 0.01 [ms], run count: 4103
        ├── 1.20% fuseOnSingleImage: total 0.26 [ms], avg. 0.00 [ms], run count: 130
        ├── 21.63% postprocess: total 4.69 [ms], avg. 0.04 [ms], run count: 129
        └── 77.17% rest: 16.75 [ms]

    100.00% subCallback: total 763.37 [ms], avg. 1.31 [ms], run count: 584
        ├── 0.01% preprocess: total 0.10 [ms], avg. 0.00 [ms], run count: 584
        ├── 90.50% fuseOnSingleImage: total 690.81 [ms], avg. 0.20 [ms], run count: 3375
        ├── 1.96% postprocess: total 14.96 [ms], avg. 0.03 [ms], run count: 456
        └── 7.53% rest: 57.50 [ms]

# roi_detected_object_fusion
    🌲 Total Processing Time Tree 🌲
    100.00% roiCallback: total 12.57 [ms], avg. 0.00 [ms], run count: 4103

    100.00% subCallback: total 1313.67 [ms], avg. 2.25 [ms], run count: 585
        ├── 0.12% preprocess: total 1.61 [ms], avg. 0.00 [ms], run count: 585
        ├── 90.47% fuseOnSingleImage: total 1188.42 [ms], avg. 0.34 [ms], run count: 3510
        │   ├── 0.34% generateDetectedObjectRoIs: total 4.43 [ms], avg. 0.00 [ms], run count: 3510
        │   ├── 0.01% fuseObjectsOnImage: total 0.07 [ms], avg. 0.00 [ms], run count: 3510
        │   └── 90.12% rest: 1183.91 [ms]
        └── 9.41% rest: 123.63 [ms]

# segmentation_pointcloud_fusion
    🌲 Total Processing Time Tree 🌲
    100.00% subCallback: total 1837.04 [ms], avg. 3.15 [ms], run count: 584
        ├── 0.01% preprocess: total 0.17 [ms], avg. 0.00 [ms], run count: 584
        ├── 72.87% fuseOnSingleImage: total 1338.73 [ms], avg. 2.29 [ms], run count: 584
        ├── 18.70% postprocess: total 343.55 [ms], avg. 0.59 [ms], run count: 584
        └── 8.42% rest: 154.60 [ms]

    100.00% roiCallback: total 1.43 [ms], avg. 0.00 [ms], run count: 587
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by technolojin** [comment]
@a-maumau Can you test the timekeeper for all variant of the nodes and paste the result in the description please?

**Comment by a-maumau** [comment]
@technolojin I add the all node's sample output in the top PR comment.

**Review by technolojin — APPROVED** [review]
LGTM

**Comment by technolojin** [comment]
@badai-nguyen @tzhong518 

Can you review this PR?

**Pull request merged**
