### PR TITLE
fix(obstacle_avoidance_planner): add guard for empty points array to prevent dying

### PR DESCRIPTION
**Pull request by tkimura4**
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>

## Description
Add return in getOptimizedTrajectory. (There is a same process soon before it, but the clipping may cause interpolated_points to become empty again. )
```
      if (interpolated_points.empty()) {
        return boost::none;
      }
```

## Tests performed
Set a vehicle position and a goal, then move the vehicle position to another location.
image
After merging the PR, motion_planning_container does not die.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by shmpwk — APPROVED** [review]

**Comment by tkimura4** [comment]
@takayuki5168 
Could you approve this?

**Comment by tkimura4** [comment]
@takayuki5168
Could you approve this?

**Comment by tkimura4** [comment]
@takayuki5168 @kosuke55 
Could you review this?

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Pull request merged**
