### PR TITLE
refactor(pose_instability_detector)!: prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add the `autoware_` prefix to `pose_instability_detector`.

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Checked with running the autoware sample-map.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by SakodaShintaro — CHANGES_REQUESTED** [review]
`rosdep install` occurs an error.
```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tier4_localization_launch: Cannot locate rosdep definition for [pose_instability_detector]
```

**Comment by a-maumau** [comment]
@SakodaShintaro Sorry for my careless mistake, I fixed it at 0c9d517 .

**Comment by SakodaShintaro** [comment]
There is also a new conflict. :cry: 
(Why are there so many conflicts?)

**Comment by a-maumau** [comment]
I resolved the conflict at 4276c27 .

(I think the conflict is coming from my own PRs that is changing the order of packages...)

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that logging_simulator works well.

- **Directory Name**
  - [x] Add `autoware_` as a prefix to the directory name.

- **packages.xml**
  - [x] Add `autoware_` to the `name` element.

- **CMakeLists.txt**
  - [x] Change the `project` name to `autoware_***`.
  - [x] Add `autoware::` to `PLUGIN`.

- **Header Files (.hpp)**
  - [x] Start `#ifndef` guards with `AUTOWARE__`.
  - [x] Add `autoware::` to `namespace`.

- **Source Files (.cpp)**
  - [x] Add `autoware::` inside `RCLCPP_COMPONENTS_REGISTER_NODE`.

- **Launch Files**
  - [x] Add `autoware_` before `find-pkg-share`.
  - [x] Change `node pkg="<pkgname>"` to `autoware_<pkgname>`.

- **Include**
  - [x] Add `autoware` folder as necessary and update include statements accordingly.
  - [x] Check for impacts on other packages.

- **Verification Points**
  - [x] Search `find-pkg-share` in autoware
  - [x] Check README file (especially json schema)
  - [x] Pay attention to complex cases like `sensor_launch` as seen in `gnss_poser`

**Pull request merged**
