### PR TITLE
refactor(ground_segmentation): refactor based on cppcheck 

### PR DESCRIPTION
**Pull request by veqcc**
## Description

These are refactoring based on cppcheck:
```
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:105:10: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
  } else if (unit_axis_ == "z") {
         ^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:107:5: note: Found duplicate branches for 'if' and 'else'.
  } else {
    ^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:105:10: note: Found duplicate branches for 'if' and 'else'.
  } else if (unit_axis_ == "z") {
         ^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:387:12: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
    } else if (unit_axis_ == "z") {
           ^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:389:7: note: Found duplicate branches for 'if' and 'else'.
    } else {
      ^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:387:12: note: Found duplicate branches for 'if' and 'else'.
    } else if (unit_axis_ == "z") {
           ^
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp:352:19: style: Variable 'prev_p' is assigned a value that is never used. [unreadVariable]
    auto * prev_p = &in_radial_ordered_clouds[i][0];  // for checking the distance to prev point
                  ^
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp:472:23: style: Variable 'local_slope' is assigned a value that is never used. [unreadVariable]
    float local_slope = 0.0f;
                      ^
```

## Tests performed

Done "Rosbag Replay Simulation"
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
Thanks for your PR.
It would be better to verify the operation of the rosbag replay simulator in the Tutorial.

**Comment by veqcc** [comment]
@yukkysaito 
I have confirmed the rosbag replay somulation works well :+1:

**Comment by yukkysaito** [comment]
The code looks good, have @YoshiRi  check it out.

**Review by YoshiRi — APPROVED** [review]
LGTM
Validated with perception mode test.

**Pull request merged**
