### PR TITLE
fix(behavior_path_planner): add angle limits to nearest point search

### PR DESCRIPTION
**Pull request by tkimura4**
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>

## Description
When searching for closest point to the ego-vehicle in behavior_path_planner, there is no angle limit.
Therefore, the closest point could not be searched correctly for the intersecting paths.

In this PR, an angle limits is added to closest-point search to fix this bug.

With the PR
image

Without the PR
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@taikitanaka3  has created a function to search, and I would like to use it.

**Review by TakaHoribe — DISMISSED** [review]
~LGTM~

oops. I missed the comment above.

**Comment by tkimura4** [comment]
@yukkysaito 

> I would like to move this one to common utils for motion planner.

What function is it for?

**Comment by yukkysaito** [comment]
>What function is it for?

Sorry, it is not enough.
When the path intersects, this function searches the neighborhood within the path before the intersection.

**Comment by tkimura4** [comment]
@yukkysaito 
The behavior path planner already used tier4_autoware_utils::findNearestIndex function.

**Comment by yukkysaito** [comment]
@tkimura4  `findFirstNearSearchRangeIndex` should be used. I will describe it in detail later.

**Comment by yukkysaito** [comment]
After discussion, a formal fix will be made in a separate PR.

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
