### PR TITLE
refactor(autoware_object_merger): move headers to src and rename package

### PR DESCRIPTION
**Pull request by esteve**
## Description

Move headers to src and rename package

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by esteve** [comment]
@technolojin I've submitted this PR as a follow-up to https://github.com/autowarefoundation/autoware.universe/pull/7642 to update the package name and move the headers, let me know if the changes are ok. Thanks.

**Review by technolojin — CHANGES_REQUESTED** [review]
> @technolojin I've submitted this PR as a follow-up to https://github.com/autowarefoundation/autoware.universe/pull/7642 to update the package name and move the headers, let me know if the changes are ok. Thanks.

Thank you for your work.

1. package renaming
I explained that the package names in /perception will be changed later altogether to minimize impact of other linked repositories and systems rely on.
This package name seems to be fine to be changed (considering the package name is used within autoware_universe).

2. moving headers
I am considering the association to be shared in the future. this association part is the same as `multi_object_tracker`, `radar_object_tracker`, and `tracking_object_merger`.
Let me do the re-organization later.

**Comment by esteve** [comment]
@technolojin I've moved the header files to a public directory, can you have a look at the changes when you have a moment? Thanks.

**Comment by esteve** [comment]
@yukkysaito @YoshiRi @miursh can you have a look at this PR? Thanks.

**Comment by yukkysaito** [comment]
@esteve Thank you for the reminder.
@technolojin  Could you please review this for me?

**Review by technolojin — CHANGES_REQUESTED** [review]
Can you fix the launcher? 
`$(find-pkg-share object_merger) -> $(find-pkg-share autoware_object_merger)`

**Review by technolojin — APPROVED** [review]
I fixed the launchers.

**Pull request merged**
