### PR TITLE
fix(pointcloud_preprocessor): temporarily remove distortion corrector unit test

### PR DESCRIPTION
**Pull request by vividf**
## Description
The threshold in the distortion corrector unit test is a bit higher.
When the point stamps have some jitter, sometimes tests won't pass. (this only happens sometime, but will make the build_and_test_differential fail)
 
Since there is another PR fixing the unit test https://github.com/autowarefoundation/autoware.universe/pull/7833, I would like to temporarily remove the test to avoid autoware contributor couldn't pass build_and_test_differential

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by knzo25 — APPROVED** [review]
Ok, let's remove the tests in the meantime.

For next time:
 - prepare an analysis of this phenomena
 - use reverts, not a PR that deleted everything (almost the same, but different from the point of view of maintaining ant all)

**Comment by knzo25** [comment]
@vividf 
You told me it is urgent, so I will merge it myself

**Comment by xmfcx** [comment]
Link to a failed test:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9803854835/job/27070651289#step:16:13789

<details>
  <summary>🖱️Click here to expand🔛</summary>

```
6: Test command: /usr/bin/python3.10 "-u" "/__w/autoware.universe/autoware.universe/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/test_results/pointcloud_preprocessor/distortion_corrector_node_tests.gtest.xml" "--package-name" "pointcloud_preprocessor" "--output-file" "/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/ament_cmake_gtest/distortion_corrector_node_tests.txt" "--command" "/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/distortion_corrector_node_tests" "--gtest_output=xml:/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/test_results/pointcloud_preprocessor/distortion_corrector_node_tests.gtest.xml"
6: Test timeout computed to be: 60
6: -- run_test.py: invoking following command in '/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor':
6:  - /__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/distortion_corrector_node_tests --gtest_output=xml:/__w/autoware.universe/autoware.universe/build/pointcloud_preprocessor/test_results/pointcloud_preprocessor/distortion_corrector_node_tests.gtest.xml
6: [==========] Running 14 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 14 tests from DistortionCorrectorTest
6: [ RUN      ] DistortionCorrectorTest.TestProcessTwistMessage
6: [       OK ] DistortionCorrectorTest.TestProcessTwistMessage (1040 ms)
6: [ RUN      ] DistortionCorrectorTest.TestProcessIMUMessage
6: [       OK ] DistortionCorrectorTest.TestProcessIMUMessage (1019 ms)
6: [ RUN      ] DistortionCorrectorTest.TestIsInputValid
6: [WARN] [1720172310.535401490] [test_node]: input pointcloud or twist_queue_ is empty.
6: [       OK ] DistortionCorrectorTest.TestIsInputValid (1031 ms)
6: [ RUN      ] DistortionCorrectorTest.TestSetPointCloudTransformWithBaseLink
6: [       OK ] DistortionCorrectorTest.TestSetPointCloudTransformWithBaseLink (1019 ms)
6: [ RUN      ] DistortionCorrectorTest.TestSetPointCloudTransformWithLidarFrame
6: [       OK ] DistortionCorrectorTest.TestSetPointCloudTransformWithLidarFrame (1025 ms)
6: [ RUN      ] DistortionCorrectorTest.TestSetPointCloudTransformWithMissingFrame
6: [WARN] [1720172313.613435184] [test_node]: "missing_lidar_frame" passed to lookupTransform argument source_frame does not exist. 
Error: OR] [1720172313.613592131] [test_node]: Please publish TF base_link to missing_lidar_frame
6: [       OK ] DistortionCorrectorTest.TestSetPointCloudTransformWithMissingFrame (1035 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloudWithEmptyTwist
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloudWithEmptyTwist (1030 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloudWithEmptyPointCloud
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloudWithEmptyPointCloud (1033 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud2dWithoutImuInBaseLink
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloud2dWithoutImuInBaseLink (1034 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud2dWithImuInBaseLink
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloud2dWithImuInBaseLink (1042 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud2dWithImuInLidarFrame
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloud2dWithImuInLidarFrame (1032 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud3dWithoutImuInBaseLink
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloud3dWithoutImuInBaseLink (1035 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud3dWithImuInBaseLink
6: [       OK ] DistortionCorrectorTest.TestUndistortPointCloud3dWithImuInBaseLink (1036 ms)
6: [ RUN      ] DistortionCorrectorTest.TestUndistortPointCloud3dWithImuInLidarFrame
6: /__w/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/test/test_distortion_corrector_node.cpp:587: Failure
6: The difference between data_ptr[i * 5] and expected_pointcloud[i][0] is 5.340576171875e-05, which exceeds 5e-5, where
6: data_ptr[i * 5] evaluates to 20.010353088378906,
6: expected_pointcloud[i][0] evaluates to 20.010299682617188, and
6: 5e-5 evaluates to 5.0000000000000002e-05.
6: [  FAILED  ] DistortionCorrectorTest.TestUndistortPointCloud3dWithImuInLidarFrame (1036 ms)
```
</details>

@vividf please add links to the problem and also a snippet too (action run logs are deleted after a while). This helps understanding why something was made with concrete evidence, even after a long time has passed.

**Comment by knzo25** [comment]
@xmfcx 
It seems the cause was using non-deterministic functions in the unit test.It is being worked here
https://github.com/autowarefoundation/autoware.universe/pull/7833#issuecomment-2212653433

**Comment by vividf** [comment]
@xmfcx Thanks I added in the description of this PR.

**Pull request merged**
