### PR TITLE
feat(lidar_centerpoint): migrate to point_cloud_msg_wrapper

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR replaces the standard point cloud iterators from the `sensor_msgs` package with [Point Cloud Message Wrapper](https://gitlab.com/ApexAI/point_cloud_msg_wrapper)

## Related links

https://github.com/autowarefoundation/autoware.universe/issues/1199

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukke42** [comment]
@esteve CI build failed. Cloud you check it ?

**Comment by yukke42** [comment]
> @esteve CI build failed. Cloud you check it ?

Cloud you check again?

**Comment by mitsudome-r** [comment]
For the distortion correction, we reverted migration to point_cloud_msg_wrapper.
Should we wait for [this](https://github.com/autowarefoundation/autoware-documentation/pull/180)  to be fixed?

**Comment by Mingyu1991** [comment]
@esteve 
this is just a friendly reminder that this PR is not active for more than 8 months.

**Comment by esteve** [comment]
@mitsudome-r should I revive this PR? I remember we put this on hold, but can't remember why. Otherwise, it should be closed.

**Comment by miursh** [comment]
@mitsudome-r @esteve 
Do we still have the motivation to use this point_cloud_msg_wrapper? 
If not, would it be acceptable to close this PR for now?

**Comment by miursh** [comment]
We are closing this issue for now since there has been no response for a month. Please feel free to reopen it if the issue still persists.

**Comment by esteve** [comment]
@miursh thanks

**Pull request closed without merging**
