### PR TITLE
feat(ndt_scan_matcher): use glog

### PR DESCRIPTION
**Pull request by kminoda**
## Description

Use glog for ndt_scan_matcher.
Please see https://github.com/autowarefoundation/autoware.universe/pull/4714 for more info about glog.

We recently had an issue where ndt_scan_matcher fails in some situation but cannot reproduce, making it difficult for us to investigate. Thus I would like to introduce glog for ndt_scan_matcher, at least temporarily, to improve the traceability.

## Related links

[INTERNAL LINK
](https://tier4.atlassian.net/browse/RT0-29699)

## Tests performed

- Launched Autoware and confirmed that the Autoware works with sample rosbag (with logging_simulator)
- Intentionally put an error in ndt_scan_matcher that terminates the node, and make sure that the glog outputs the log as it is expected
- Confirmed that the test passes
- **Confirmed that the NDT is launched with multi-threaded executor**

## Notes for reviewers
None

## Interface changes
None

## Effects on system behavior
None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by KYabuuchi** [comment]
After this PR is merged, we need to keep in mind that `ndt_scan_matcher/launch/ndt_scan_matcher.launch.xml` will not be launched except for `test/test_ndt_scan_matcher_launch.py`, and when launched with it, it will not be a multi-thread-executer. :point_left:

**Comment by kminoda** [comment]
@KYabuuchi Thanks. Changed my mind and now I think it's better to make the sample launch file executed in MultiThreadedExecuter as well. Fixed here: https://github.com/autowarefoundation/autoware.universe/pull/5465/commits/02fc4097d5234e6078c2738c06d17ae6478e8ac1

**Comment by kminoda** [comment]
I directly use glog instead of using it as glog_component (Special thanks: @KYabuuchi )

**Review by KYabuuchi — COMMENTED** [review]
Please add `<depend>libgoogle-glog-dev</depend>` in package.xml.

After it is added, I wil approve :soon:

**Comment by kminoda** [comment]
@KYabuuchi Thank you for all the careful reviews! Fixed: https://github.com/autowarefoundation/autoware.universe/pull/5465/commits/a858ddd8fa99f734511a47a57bd5e53c16707818

**Review by KYabuuchi — APPROVED** [review]
LGTM :heart:

**Pull request merged**
