### PR TITLE
fix(ndt_scan_matcher): disable `march=native` when the target is Intel processor

### PR DESCRIPTION
**Pull request by harihitode**
# Description

Current options causes a SIMD misaligned segmentation faults, when the pre-build Autoware is executed on the different machine.

The `-march=native` option might make an invalid instruction for the target machine.

# Changes

For Intel (x86-64), SIMD options are added explicitly for each SIMD version. These sse options are most stable.

For other machine like ARM, no option is added as default, because the difference of instruction sets are smaller than the Intel.
The SIMD optimization is a default feature of the compiler, so we need not to add any other compiler options.

# Related Issue

When you use the `ndt_omp` as ndt_scan_matcher implementation, you need to merge the [related fix] (https://github.com/tier4/ndt_omp/commit/d67ac1efdfeeefc4f3711d28a45806f437742278) in `ndt_omp` .

# Pre-review checklist for the PR author
PR author must check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
- [ ] The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

# In-review checklist for the PR reviewers
Reviewers must check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

# Post-review checklist for the PR author
PR author must check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has the write access can merge the PR.

### CODE REVIEW

**Comment by harihitode** [comment]
This is the related PR to the one in [ndt_omp](https://github.com/tier4/ndt_omp/pull/12), @KeisukeShima 

If this PR is merged, the above `ndt_omp` 's PR should be merged for `ndt_omp` users.

**Comment by kenji-miyake** [comment]
@harihitode Thank you for fixing this.
Adding some brief comments in CMakeLists.txt would be great. :+1:

**Comment by harihitode** [comment]
@kenji-miyake All right! It will be done.

**Comment by kenji-miyake** [comment]
Could you address the CI failure?
https://github.com/autowarefoundation/autoware.universe/runs/5670803974?check_suite_focus=true

**Comment by yukkysaito** [comment]
@harihitode pls fix some typo

**Comment by harihitode** [comment]
Thank you @yukkysaito .  I am sorry but one check, `codecov/project` still fails.

Could you please tell me how to fix it?

**Comment by kenji-miyake** [comment]
@harihitode It's not a required CI check, so you can ignore it.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
