### PR TITLE
feat(perception): change detection region

### PR DESCRIPTION
**Pull request by badai-nguyen**
Signed-off-by: badai-nguyen <dai.nguyen@tier4.jp>

## Description

This PR to extend the detection region of ground segmentation. As the result, it also extend the region of perception module. 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@badai-nguyen I think the computational cost will increase. May I ask you to compare the CPU utilization of ground segmentation and compare map filter, which seems to have a large impact?

**Review by miursh — COMMENTED** [review]
I'm ok fot this.
Could you provide evidence to show that there is no significant impact on CPU usage?
Also, could you modify [this](https://github.com/tier4/autoware_launch/blob/awf-latest/perception_launch/config/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml) ?

**Comment by badai-nguyen** [comment]
> 
Since ground_segmentation is included in component that's quite hard to monitor cpu usage percent, so I compare the processing_time before and after change the detection range. 
Before extending:

**Comment by badai-nguyen** [comment]
> 
@miursh 
Thank you. I modified [here](https://github.com/tier4/autoware_launch/pull/630). Could I ask you for review it

**Comment by yukkysaito** [comment]
@badai-nguyen Thank you! LGTM 👍 
Could you resolve the conflict?

**Comment by badai-nguyen** [comment]
> @badai-nguyen Thank you! LGTM +1 Could you resolve the conflict?

@yukkysaito Since  ground_segmentation.param.yaml was removed by commit #2539 and I also create [PR](https://github.com/tier4/autoware_launch/pull/630)
for autoware_launch. Shall we close this PR?

**Comment by yukkysaito** [comment]
@badai-nguyen Thank you!
It's ok 👍

**Comment by badai-nguyen** [comment]
Close because the ground_segmentation.param.yaml was removed.

**Comment by miursh** [comment]
@badai-nguyen You need to change param in [autoware_launch](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml) instead of tier4_perception_launch

**Pull request closed without merging**
