### PR TITLE
feat(rviz_plugins): add velocity limit to autoware state panel

### PR DESCRIPTION
**Pull request by taikitanaka3**
Signed-off-by: tanaka3 <ttatcoder@outlook.jp>

## Description

add velocity limit to rviz plugin panel to test easily

https://user-images.githubusercontent.com/65527974/167554153-a2ad3118-cd70-4690-86f9-40dcc6858db1.mp4

## Tests performed

By Psim

## Notes for reviewers

please add autoware state panel first

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by h-ohta** [comment]
@taikitanaka3 LGTM, but It seems better to set velocity limit by km/h.

**Comment by taikitanaka3** [comment]
@h-ohta 
OK I will change this to km/h unit

**Comment by taikitanaka3** [comment]
[a94514c](https://github.com/autowarefoundation/autoware.universe/pull/879/commits/a94514c0ba1a0d9c499eeee2bca7068574c5740f)
has km/h unit setting
image

**Review by h-ohta — APPROVED** [review]

**Comment by shmpwk** [comment]
Sorry for late reply and LGTM.

**Pull request merged**
