### PR TITLE
feat: add GPU clock monitoring to gpu_monitor

### PR DESCRIPTION
**Pull request by v-nakayama7440-esol**
Signed-off-by: v-nakayama7440-esol <v-nakayama7440@esol.co.jp>

## Description
According to the safety analysis made by TIER IV, input clock error in NVIDIA GPU will cause wrong GPU instructions, processing delays, or hungup.
However, I'm wondering if there is no way to monitor input clock to GPU, so I'm trying to add a functionality to monitor GPU clock runs in supported clocks in GPU.
The diagnostic information `GPU Frequency` will report `Warning` when the current clock is out of supported clocks.
This function is supported for external GPU card only because these information is obtained via NVML([NVIDIA Management Library](https://developer.nvidia.com/nvidia-management-library-nvml)).

## Related links
https://github.com/autowarefoundation/autoware.universe/issues/1770

### Verify `gpu_monitor: GPU Frequency` reports `OK` in normal operation.

1. Run Autoware.
1. Run rqt_runtime_monitor.
    ```console
    ros2 run rqt_runtime_monitor rqt_runtime_monitor
    ```
1. Verify `gpu_monitor: GPU Frequency` reports `OK`.
image

1. Display supported clocks and find the clock which is reported by `GPU Frequency`.
   ```console
   nvidia-smi -q -d SUPPORTED_CLOCKS
   ```
   image

### Verify no warning and error messages in a normal run.
image

### Verify `gpu frequency` is aggregated in `resource_monitoring`.

1. Run rqt_robot_monitor. 
   ```console
   ros2 run rqt_robot_monitor rqt_robot_monitor
   ```
   image

### Verify `gpu_monitor: GPU Frequency` reports `Warning` in abnormal operation.

There is no way to manipulate GPU intentionally, so this test can be skipped.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ito-san** [comment]
@v-nakayama7440-esol 
This is not related to this PR, but I'm getting the following build error.
```console
~/pilot-auto.x2 develop/v1.2.0/humble autoware@AVA-3510-2204
❯ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select system_monitor
...
/home/autoware/pilot-auto.x2/src/autoware/universe/system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp: In member function ‘void GPUMonitor::addProcessUsage(int, nvmlDevice_t, diagnostic_updater::DiagnosticStatusWrapper&)’:
/home/autoware/pilot-auto.x2/src/autoware/universe/system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp:186:9: error: ‘nvmlDeviceGetComputeRunningProcesses_v2’ was not declared in this scope; did you mean ‘nvmlDeviceGetComputeRunningProcesses_v3’?
  186 |   ret = nvmlDeviceGetComputeRunningProcesses_v2(device, &info_count, infos.get());
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         nvmlDeviceGetComputeRunningProcesses_v3
/home/autoware/pilot-auto.x2/src/autoware/universe/system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp:200:9: error: ‘nvmlDeviceGetGraphicsRunningProcesses_v2’ was not declared in this scope; did you mean ‘nvmlDeviceGetGraphicsRunningProcesses_v3’?
  200 |   ret = nvmlDeviceGetGraphicsRunningProcesses_v2(device, &info_count, infos.get());
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         nvmlDeviceGetGraphicsRunningProcesses_v3
gmake[2]: *** [CMakeFiles/gpu_monitor_lib.dir/build.make:90: CMakeFiles/gpu_monitor_lib.dir/src/gpu_monitor/nvml_gpu_monitor.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:340: CMakeFiles/gpu_monitor_lib.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< system_monitor [1min 12s, exited with code 2]

Summary: 0 packages finished [1min 13s]
  1 package failed: system_monitor
  1 package had stderr output: system_monitor
```

Could you please remove `_v2` suffix?

**Comment by v-nakayama7440-esol** [comment]
@ito-san
```
Could you please remove _v2 suffix?
```
I fixed it by merging the main branch.

**Review by ito-san — APPROVED** [review]
LGTM

**Comment by ito-san** [comment]
> I fixed it by merging the main branch.

The build error has gone away and verified gpu_monitor works.
image

**Pull request merged**
