### PR TITLE
feat(yabloc_image_processing): support both of  raw and compressed image input

### PR DESCRIPTION
**Pull request by KYabuuchi**
## Description

With this PR, YabLoc can take both compressed_image and image_raw as inputs. 
[As pointed out in this issue](https://github.com/autowarefoundation/autoware.universe/issues/4318), YabLoc could not work with AWSIM before, but this PR resolves that. 

The [undistort node](https://github.com/autowarefoundation/autoware.universe/tree/1c2c59d0ab81400b692aa8d9c3b595be0222b9ab/localization/yabloc/yabloc_image_processing#undistort), which is the first node of YabLoc, subscribes to both compressed image and raw image topics. If raw image is subscribed to even once, compressed image will no longer be subscribed to. 

## Related links
* https://github.com/autowarefoundation/autoware.universe/issues/4318

## Tests performed

I have confirmed that YabLoc works correctly using the `logging_simulator.launch.xml`.

Specifically, I verified that when only `compressed_image` is being streamed, YabLoc subscribes to `compressed_image`, and when `image_raw` is being streamed, it prioritizes subscribing to `image_raw`.

* map: https://github.com/tier4/AWSIM/releases/download/v1.1.0/nishishinjuku_autoware_map.zip
* rosbag https://drive.google.com/file/d/1zKTGRH4lD-wptpOdNCgpiPfGRDP0XrUm/view?usp=sharing
```
ros2 launch autoware_launch logging_simulator.launch.xml \
  map_path:=$HOME/autoware_map/nishishinjuku \
  vehicle_model:=sample_vehicle \
  sensor_model:=awsim_sensor_kit \
  control:=false \
  planning:=false \
  pose_source:=yabloc
```

The above rosbag contains compressed_image. 
Reviewers can verify that YabLoc will subscribe to image_raw by decompressing it with the following script.

```py
#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from sensor_msgs.msg import CompressedImage
from cv_bridge import CvBridge
from rclpy.qos import QoSProfile, QoSReliabilityPolicy
class Decompressor(Node):
    def __init__(self):
        super().__init__("decompressor")
        qos = QoSProfile(
            reliability=QoSReliabilityPolicy.RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT,
            depth=10)
        self.publisher_ = self.create_publisher(
            Image, "/sensing/camera/traffic_light/image_raw", qos)
        self.subscription = self.create_subscription(
            CompressedImage,
            "/sensing/camera/traffic_light/image_raw/compressed",
            self.on_image,
            qos,
        )
        self.bridge_ = CvBridge()

    def on_image(self, msg):
        self.get_logger().info("subscribed")
        mat = self.bridge_.compressed_imgmsg_to_cv2(msg)
        raw_msg = self.bridge_.cv2_to_imgmsg(mat)
        raw_msg.header = msg.header
        raw_msg.encoding = "bgr8"
        self.publisher_.publish(raw_msg)
        self.get_logger().info("published")

def main(args=None):
    rclpy.init(args=args)
    decompressor = Decompressor()
    rclpy.spin(decompressor)
    decompressor.destroy_node()
    rclpy.shutdown()

if __name__ == "__main__":
    main()
```
## Notes for reviewers
Nothing.

## Interface changes
YabLoc now supports image_raw as well as compressed images.
If image_raw is subscribed to even once, compressed image will no longer be subscribed to. 

## Effects on system behavior
Nothing.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
Recommend to fill out all the sections in description (in order not to be warned by the Bot in slack for release-note)

**Comment by KYabuuchi** [comment]
Thanks. I have filled all sections.

**Review by kminoda — APPROVED** [review]
LGTM

**Comment by KYabuuchi** [comment]
@Motsu-san  Please approve as the code owner of `yabloc_image_processing` :pray:

**Review by Motsu-san — APPROVED** [review]

**Pull request merged**
