### PR TITLE
build: add nlohmann-json-dev dependency

### PR DESCRIPTION
**Pull request by esteve**
## Description

Added missing nlohmann-json-dev dependency

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by YoshiRi — APPROVED** [review]
LGTM

**Review by scepter914 — APPROVED** [review]
LGTM

**Comment by esteve** [comment]
@YoshiRi @scepter914 thanks for your reviews. I don't know why, but CI seems to be stuck in build-and-the test-differential, any ideas? Thanks.

**Comment by YoshiRi** [comment]
@esteve 
Due to the recent change in autoware CI, we need to add [run-build-and-test-differential](https://github.com/autowarefoundation/autoware.universe/labels/run-build-and-test-differential) label manually to run build-and-the test-differential. (Maybe because of the computation resource issue.)

**Pull request merged**
