### PR TITLE
feat(traffic-light-rviz-panel): select traffic light ID from Combobox

### PR DESCRIPTION
**Pull request by soblin**
## Description

The PR modifies `tier4_traffic_light_rviz_plugin` so the user can select the ID of traffic light from pull-down menu, unlike directly setting the number from the input button previously.

cc: @kminoda @shmpwk 

## Related links

[link](https://autowarefoundation.github.io/autoware-documentation/pr-129/tutorials/ad-hoc-simulation/planning-simulation/)

This link is work in progress, but I'm working on to add this `planning with traffic light recognition` page to the Advanced section of Autoware tutorial and exhibit the image attached below.

## Tests performed

You can select and set/publish traffic light status like in the attached pic.
Screenshot from 2022-05-31 19-46-07

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.
- [X] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
Could you add information about this nice feature in README?

**Comment by satoshi-ota** [comment]
Great work :+1: 
Almost OK, but I think it is better to remove unnecessary namespace, if you use alias.
Please check above suggests.

**Comment by soblin** [comment]
Now it's ready.

I update the README (+ mkdocs.yaml to upload gif file to [universe documentation](https://autowarefoundation.github.io/autoware.universe/main/common/tier4_traffic_light_rviz_plugin/))

**Comment by satoshi-ota** [comment]
There are two commits which have been merged. Could you rebase your branch in order to clean up ?

Screenshot from 2022-06-05 20-33-07

**Comment by satoshi-ota** [comment]
https://results.pre-commit.ci/run/github/429651616/1654472358.QOJCe3t7SiK01N6XsxB-Jw
What's wrong with pre-commit.ci ? :thinking: cc @kenji-miyake

**Comment by kenji-miyake** [comment]
@satoshi-ota It's resolved by https://github.com/autowarefoundation/autoware.universe/pull/1040.

**Comment by satoshi-ota** [comment]
> @satoshi-ota It's resolved by #1040.

@kenji-miyake I see. Thanks for your quick comments !

**Comment by satoshi-ota** [comment]
It is hard to find taget traffic light id when we use this plugin in huge environment that has a lot of traffic light like odiaba. :sweat_smile: 
So, could you modify the implementation to sort these id ?

image

**Comment by soblin** [comment]
I'm trying out this setting https://stackoverflow.com/questions/50789605/how-to-add-a-scrollbar-to-a-qcombobox

**Comment by soblin** [comment]
I'm changing the box to a scrollable one and sorting the IDs. I'm also trying to limit the size of the box if possibl
Screenshot from 2022-06-06 14-47-33
e

**Comment by satoshi-ota** [comment]
> I'm changing the box to a scrollable one and sort the IDs. I'm also trying to limit the size of the box if possible Screenshot from 2022-06-06 14-47-33
> 
> How do you think about this ?

Great :+1: 

> I'm also trying to limit the size of the box if possible.

Yeah, I think that it is nice idea, too.

**Comment by soblin** [comment]
@satoshi-ota I couldn't find the resource for how to set fixed size of item list in combo box (maybe I can set fixed number height in px units, but I do not think it's a good idea), but anyway the IDs are sorted and the user will be able to scroll up/down to find desired traffic light ID.

**Comment by satoshi-ota** [comment]
> @satoshi-ota I couldn't find the resource for how to set fixed size of item list in combo box (maybe I can set fixed number height in px units, but I do not think it's a good idea), but anyway the IDs are sorted and the user will be able to scroll up/down to find desired traffic light ID.

OK, it looks good to me :+1:

**Review by satoshi-ota — APPROVED** [review]

**Pull request merged**
