### PR TITLE
feat(avoidance): change lateral margin based on if it's parked vehicle

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

The module creates avoidance path not only for PARKED vehilce but also NON-PARKED vehicle. And, it used common lateral margin for both type of vehicle. But I think the module should be able to use different lateral margin for each types based on the assumption that the door might open and the driver might get out the car if it's a PARKED vehilce. In that case, we should set larger lateral margin for PARKED vehicle than the param for NON-PARKED vehicle.

In this PR, I rebuild lateral params and make it possible to set lateral params dependently.

For example, it's able to tune as follow. In this setting, avoidance module keeps 1.5m (0.3 + 0.5 + **0.7**) for PARKED vehicle.

```yaml
        bus:
...
          lateral_margin:
            soft_margin: 0.5                           # [m]
            hard_margin: 0.2                           # [m]
            hard_margin_for_parked_vehicle: 0.7        # [m]
...
          envelope_buffer_margin: 0.3
...
```

For PARKED vehilce. (Grid: 0.5 x 0.5m)

Screenshot from 2024-03-05 09-38-49

On the other hand, it keeps  1.0m (0.3 + 0.5 + **0.2**) for NON-PARKED vehicle.

Screenshot from 2024-03-05 09-37-11

## Tests performed

- [x] [PASS TIER IV INTERNAL SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/85105ab2-8c20-5dd1-b56f-d4c75c3603c6?project_id=prd_jt)

## Effects on system behavior

Improve avoidance behaivor.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TomohitoAndo** [comment]
@satoshi-ota 
Do you have plans to update the documentation?
It appears there have been significant changes to the parameters.
Additionally, it would be beneficial to include a detailed explanation of how the module decides whether other vehicles are PARKED or NON-PARKED.

**Comment by TomohitoAndo** [comment]
I confirmed this works on PSim. Great!

I set the parameter like following to see the change.
```yaml
        car:
          execute_num: 1                               # [-]
          moving_speed_threshold: 1.0                  # [m/s]
          moving_time_threshold: 2.0                   # [s]
          lateral_margin:
            soft_margin: 0.1                           # [m]
            hard_margin: 0.1                           # [m]
            hard_margin_for_parked_vehicle: 0.5        # [m]
          max_expand_ratio: 0.0                        # [-]
          envelope_buffer_margin: 0.1                  # [m]
          safety_buffer_longitudinal: 0.0              # [m]
          use_conservative_buffer_longitudinal: true   # [-] When set to true, the base_link2front is added to the longitudinal buffer before avoidance.
```

PARKED vehicle
image

NON-PARKED vehicle
image
image

**Review by TomohitoAndo — APPROVED** [review]
LGTM

**Review by shmpwk — APPROVED** [review]
LGTM

**Pull request merged**
