### PR TITLE
feat(behavior_velocity): add mandatory detection area for run out module

### PR DESCRIPTION
**Pull request by TomohitoAndo**
## Description

Currently, if you use pointcloud as an input for run_out, points in the `no_obstacle_segmentation_area` are ignored.
But it would not be safe if `no_obstacle_segmentation_area` is so close to the ego vehicle and there is an obstacle in that area like the image below.
So I added `mandatory_detection_area` that the obstacle in this area is not ignored even if it is in the `no_obstacle_segmentation_area` to ensure safety.

### Before
The obstacle in the `no_obstacle_segmentation_area` is ignored.
image

### After
The obstacle in the `mandatory_detection_area` is detected even if it is in the `no_obstacle_segmentation_area`.
image

image

## Related Links

- parameter change for launch
  - (awf/launch)
    - https://github.com/autowarefoundation/autoware_launch/pull/205
  - (tier4)
    - https://github.com/tier4/autoware_launch/pull/770

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TomohitoAndo** [comment]
@mkuri 
Could you review this change? :pray:

**Comment by TomohitoAndo** [comment]
I ran CI here. (TIER IV Internal Link)
https://evaluation.tier4.jp/evaluation/reports/db32b47b-ae6a-58f4-a21b-aa28a9b54f91?project_id=x2_dev

**Comment by mkuri** [comment]
@TomohitoAndo 
I would like to check the maximum shift from the original position by applying the voxel grid filter twice.

**Comment by TomohitoAndo** [comment]
@mkuri 
I looked into the pcl code and it seems that the index of voxel for each points is calculated by the coordinate of points.
That means the coordinate of the voxel doesn't change even if you apply the voxel grid filter twice.
https://github.com/PointCloudLibrary/pcl/blob/pcl-1.12.0/filters/src/voxel_grid.cpp#L370-L374

So I think the maximum shift of the position is like the image below.
In this case, this is about 5.3cm because the leaf size is 0.05m.
image

**Review by mkuri — APPROVED** [review]
LGTM

**Pull request merged**
