### PR TITLE
refactor(autoware_behavior_velocity_speed_bump_module): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR adds the autoware_ prefix to the package and puts headers in the autoware namespace.

Part of:

https://github.com/autowarefoundation/autoware/issues/4569
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by maxime-clem — APPROVED** [review]

**Comment by danielsanchezaran** [comment]
@esteve Doesn't the CODEOWNERS file need to be updated too?

**Comment by esteve** [comment]
@danielsanchezaran I've updated the `CODEOWNERS` file as well.

**Comment by esteve** [comment]
@xmfcx @mitsudome-r @satoshi-ota @shmpwk could you have a look at this PR when you have a moment? Thanks.

**Review by shmpwk — APPROVED** [review]

**Comment by esteve** [comment]
@danielsanchezaran if the changes look ok to you, could you approve this PR? Thank you in advance.

**Review by danielsanchezaran — APPROVED** [review]
LGTM

**Comment by esteve** [comment]
@danielsanchezaran fixed, thanks.

**Pull request merged**
