### PR TITLE
fix(lidar_centerpoint_tvm): fix constVariable warnings

### PR DESCRIPTION
**Pull request by veqcc**
## Description

This is a fix based on cppcheck `constVariable` warnings

```
perception/lidar_centerpoint_tvm/lib/preprocess/generate_features.cpp:45:13: style: Variable 'coordinate' can be declared as const array [constVariable]
    int32_t coordinate[3] = {
            ^
perception/lidar_centerpoint_tvm/lib/preprocess/generate_features.cpp:61:11: style: Variable 'mean' can be declared as const array [constVariable]
    float mean[3] = {
          ^
```

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@veqcc 
We are currently evaluating how to proceed with this package, so please wait a little bit :pray:

**Comment by veqcc** [comment]
@knzo25 
Hi, is there any conclusion what to do for this module?

Currently I am working on cpcheck CI workflow to reduce warnings in autoware.universe.
The warning `constVariable` occurs only in this package. If we solve it, we can make this warning never happens in whole autoware.universe by makeing it requirement.

If it will take more time to make decisions on this module, could you merge this PR?
I believe this change doesn't affect the functionality. Thank you

**Comment by knzo25** [comment]
@veqcc 
Right now there is a discussion in the awf to deprecate tvm nodes, but yes, it will take a while.
I agree that we should merge your PR in the meanwhile, but I can not merge this since I am not a maintainer !

@kminoda @YoshiRi 
Does either of you have force merge permissions here? :pray:

**Comment by knzo25** [comment]
Just in case, I will leave the discussion here:
https://github.com/orgs/autowarefoundation/discussions/4883#discussioncomment-9876908

**Comment by kminoda** [comment]
@knzo25 I think we've waited enough after https://github.com/orgs/autowarefoundation/discussions/4883 has been posted, so let's remove this pacakge.

@veqcc Thank you for the fix, but let us close this PR as this package will be deprecated in a meantime.

**Comment by veqcc** [comment]
> @veqcc Thank you for the fix, but let us close this PR as this package will be deprecated in a meantime.

Okey 👍

**Pull request closed without merging**
