### PR TITLE
feat(multi_object_tracker): increase max-area for truck and trailer

### PR DESCRIPTION
**Pull request by yukke42**
Signed-off-by: yukke42 <yusuke.muramatsu@tier4.jp>

## Description

There are trucks about 18 m length and they are filtered by the max-area gate of multi-object-tracker. I have changed not to filtered large vehicles, and the 70 value is 20 m (large vehicle length with a margin) x 3.5 m (maximum width of general road in Japan).

Blue: /perception/object_recognition/detection/objects
Red: /perception/object_recognition/tracking/objects

before:

https://user-images.githubusercontent.com/24660808/187078134-89f64845-0da5-4c06-b7d7-e2e8baa7d4b3.mp4

after:

https://user-images.githubusercontent.com/24660808/187078136-32baedee-b444-4f93-a4ec-8e92d98ab744.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@yukke42 I have two questions.
- Can you show the size data? because the large truck size is defined as [within 12m x 2.5m](https://x-work.jp/journal/truck/259/?utm_medium=organic_m&utm_campaign=259) in Japan. 
- Is it a trailer, not a truck?

**Comment by yukke42** [comment]
A single grid is 1 m long. The longest vehicle is a trailer, but others are truck, but our model classifies truck and trailer as a same label.

Screenshot from 2022-08-29 00-56-01

**Comment by yukke42** [comment]
Is it better for the model to classify these vehicles as trailer and should I change data-association matrix of the trailer?

**Comment by yukkysaito** [comment]
I think it is better to make a trailer for anything over 12m in post-process of CenterPoint and apollo instance segmentation.

Also, about width, 2.5m maybe too strict, it seems to be good to 3.0m

**Comment by yukke42** [comment]
@yukkysaito 
I have changed the params of truck and trailer in this [86aa161](https://github.com/autowarefoundation/autoware.universe/pull/1710/commits/86aa161f93b265c61cb58ae68a62538339cedf11).

**Comment by yukke42** [comment]
@yukkysaito 
updated max-area matrix values as you advised.

**Comment by yukke42** [comment]
@yukkysaito Sorry for the late, I have updated the params as you said.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
