### PR TITLE
chore(package.xml): bump version to 0.38.0

### PR DESCRIPTION
**Pull request by youtalk**
## Description

This PR is based on https://github.com/orgs/autowarefoundation/discussions/5292 and aims to manage the versioning of `autowarefoundation/autoware.universe` using ROS package release tools. 
All package versions have been unified to 0.38.0 following `https://github.com/tier4/autoware.universe/tree/v0.38.0`.

Note that this PR is a merge request not for the `main` branch, but for the newly created `humble` branch. Once this PR is merged, I plan to tag `0.38.0` on the `humble` branch and create a PR to merge the differences into the `main` branch as well.

Currently, I was manually running the ROS package release tools to create PR, but in the future, we would like to modify https://github.com/tier4/autoware-release-scripts to automate this process.

## Related links

https://github.com/orgs/autowarefoundation/discussions/5292

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by youtalk** [comment]
@mitsudome-r @xmfcx A branch protection rule is needed for the `humble` branch. Please set it up with conditions similar to those of the `main` branch, but it should allow merge commits rather than squash merges.

**Comment by xmfcx** [comment]
@youtalk -san, I can add the branch protection rules.

> but it should allow merge commits rather than squash merges.

Why? We could have the releases and version control without needing merge commits.

I've checked the practices utilized by many official ROS 2 packages and none of them allowed merge commits.
They were versioning and backporting by keeping a linear history just fine.

I'd much prefer not to complicate the commit history by allowing merge commits. And keep a linear history for main and ros-distro branches.

## Examples

https://github.com/ros2/rosbag2
image

https://github.com/ros2/ros2cli
image

https://github.com/ros2/rclcpp
image

**Comment by youtalk** [comment]
@xmfcx If we merge all patch PRs that exist only in the `humble` branch into the `main` branch with individual PRs, squash merging will still be fine going forward.
Please review this! cc @mitsudome-r

**Review by mitsudome-r — APPROVED** [review]
I have confirmed that the  changes are only made to package.xml and CHANGELOG.rst.

For the package.xml, the PR is only updating version to 0.38.

I haven't looked into all the details of each CHANGELOG.rst, but I don't think there is a necessity to review them in details since they are generated automatically. We can always update them if we notice a package with wrong changelogs.

**Review by soblin — APPROVED** [review]
OK for my pkgs

**Review by rej55 — APPROVED** [review]
LGTM

**Pull request merged**
