### PR TITLE
fix(static_drivable_area_expansion): fix bug in drivable bound edge processing logic

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Fix https://github.com/autowarefoundation/autoware.universe/issues/5825.
I found a bug in drivable bound edge(start/goal point) processing logic.

This function got unexpected point index since there is no constraints. As a result, left bound was not built properly.

```c++
size_t findNearestSegmentIndexFromLateralDistance(
  const std::vector<T> & points, const geometry_msgs::msg::Point & target_point)
```

In this PR, I added yaw threshold so that it can get proper point index.

Screenshot from 2023-12-21 09-47-27

## Tests performed

Psim

https://github.com/autowarefoundation/autoware.universe/assets/44889564/3ef02177-182a-480f-b539-4449b6cd7bb0

## Effects on system behavior

Nothing.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by brkay54** [comment]
Thank you for the work @satoshi-ota -san, I tried the PR on the master, the avoidance module runs as we want. LGTM!

**Comment by satoshi-ota** [comment]
@brkay54 I'm happy to hear that. This PR will be reviewed by TIER IV internal member.

**Review by shmpwk — APPROVED** [review]
LGTM

**Review by danielsanchezaran — APPROVED** [review]
LGTM

**Pull request merged**
