### PR TITLE
feat(simple_planning_simulator): add actuation command simulator

### PR DESCRIPTION
**Pull request by kosuke55**
## Description
Add new simulator model `ACTUATION_CMD` which subscribes `ActuationCommandStamped` topics for its motion. When selecting this mode, launch also `raw_vehicle_cmd_converter` to publish actuation command.

[trajectory_follower] -- `ACKERMANN` --> [raw_vehicle_cmd_converter] -- `Actuation` --> [simple_planning_simulator]  

```
/**:
  ros__parameters:
    simulated_frame_id: "base_link"
    origin_frame_id: "map"
    vehicle_model_type: "ACTUATION_CMD"
    initialize_source: "INITIAL_POSE_TOPIC"
    timer_sampling_time_ms: 25
    add_measurement_noise: False
    enable_road_slope_simulation: True
    vel_lim: 50.0
    vel_rate_lim: 7.0
    steer_lim: 1.0
    steer_rate_lim: 5.0
    acc_time_delay: 0.1
    acc_time_constant: 0.1
    steer_time_delay: 0.24
    steer_time_constant: 0.27
    steer_dead_band: 0.0012
    x_stddev: 0.0001 # x standard deviation for dummy covariance in map coordinate
    y_stddev: 0.0001 # y standard deviation for dummy covariance in map coordinate

    accel_time_delay: 0.1
    accel_time_constant: 0.1
    brake_time_delay: 0.1
    brake_time_constant: 0.1
    accel_map_path: $(find-pkg-share simple_planning_simulator)/data/actuation_cmd_map/accel_map.csv
    brake_map_path: $(find-pkg-share simple_planning_simulator)/data/actuation_cmd_map/brake_map.csv
    steer_map_path: $(find-pkg-share simple_planning_simulator)/data/actuation_cmd_map/steer_map.csv
    convert_accel_cmd: true
    convert_brake_cmd: true
    convert_steer_cmd: false
```

https://github.com/user-attachments/assets/753758bf-1e06-4b8c-9374-ece3954f3b68

Note:
if setting `convert_steer_cmd: true` in simulator and raw_vehicle_cmd_converter, the control command is converted like steer_rate -> steer_cmd -> steer_rate, but currently steer_rate does not seem to be published correctly. steer_rate from control is very large like 0.8. this seems bug but it is not related to this PR. 

https://github.com/user-attachments/assets/c189b7ee-d30d-4dd7-b3e1-ce3b5deaa542

## Related links

**Parent Issue:**

- Link

## How was this PR tested?
psim

2024/07/18 https://evaluation.tier4.jp/evaluation/reports/7e7c48e9-71bd-55c1-b27b-0587b131b679/?project_id=prd_jt

unit test

```

....
1:  vehicle model = ACTUATION_CMD
1:
1: [       OK ] TestForEachVehicleModel/TestSimplePlanningSimulator.TestIdealSteerVel/7 (13469 ms)
1: [----------] 8 tests from TestForEachVehicleModel/TestSimplePlanningSimulator (108048 ms total)

100% tests passed, 0 tests failed out of 5
```
## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@kosuke55 Thank you for the PR. Would you add a test case for the new model here?
https://github.com/tier4/autoware.universe/blob/92568927758742806b02ad2252fcf0b9ee3bec31/simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp#L271-L275

We have to add some codes to publish the actuation cmd.

**Comment by kosuke55** [comment]
@TakaHoribe 
Thank for the suggestion. I added in
https://github.com/autowarefoundation/autoware.universe/pull/8065/commits/9602b5d943945ed209af1567e94a52815c14ab60

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
@TakaHoribe thanks for cleaning up the test!!!

**Comment by yuki-takagi-66** [comment]
@kosuke55 
please write launch side PR if it is necessary.

**Pull request merged**
