### PR TITLE
refactor(autoware_point_types): prefix namespace with autoware::point_types

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by knzo25 — APPROVED** [review]
LGTM !

**Comment by YamatoAndo** [comment]
Once the maintainer of autoware_point_types approves, I'll also approve the localization module.

**Comment by knzo25** [comment]
@drwnz @mojomex  :pray:

**Review by drwnz — APPROVED** [review]
LGTM!

**Review by YamatoAndo — APPROVED** [review]

**Comment by esteve** [comment]
@xmfcx thanks!

**Pull request merged**
