### PR TITLE
chore(autoware_imu_corrector): refactored the imu corrector into the autoware namespace

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Part of the autoware namespace series of PRs

Needs to be merged with: 
 - https://github.com/tier4/aip_launcher/pull/273
 - https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/16 
 - https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/99
 - https://github.com/autowarefoundation/autoware-documentation/pull/598
 - https://github.com/autowarefoundation/autoware_tools/pull/94
 - https://github.com/autowarefoundation/awsim_labs_sensor_kit_launch/pull/5

## Related links

**Parent Issue:**

- Link

## How was this PR tested?
Tested that the nodes were correctly launched
## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by YamatoAndo** [comment]
@knzo25 Hello. Thank you for the PR. I have a question.
Why did you move the .hpp files to the include/autoware directory?
If they are not intended for external export, they should be placed in the src directory.
https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#include-and-src

**Comment by TaikiYamada4** [comment]
@knzo25 
Thank you for the PR!
I found that `sample_sensor_kit_launch` also needs modification too, so could you modify `sample_sensor_kit_launch` too as same as aip_launcher?
https://github.com/autowarefoundation/sample_sensor_kit_launch/blob/main/sample_sensor_kit_launch/launch/imu.launch.xml

**Comment by knzo25** [comment]
@YamatoAndo  @TaikiYamada4 
Thanks for the catches.

With regards to the launchers, also awsim was missing, which was addressed in 
https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/16
https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/99

There is also awsim_labs, but that should sync itself to the upstream

**Comment by knzo25** [comment]
@YamatoAndo @TaikiYamada4 
anything blocking this PR?

**Comment by YamatoAndo** [comment]
@knzo25 Sorry for the confusion. I was waiting, thinking that you would submit a fix PR for other repositories as well.
Could you please also fix the following? 

https://github.com/autowarefoundation/autoware_tools/blob/a53a926d1b300a35f948dfe02eece51ace42a24b/localization/deviation_estimation_tools/deviation_evaluator/launch/deviation_evaluator.launch.xml#L54

https://github.com/autowarefoundation/autoware-documentation/blob/f93e489120c1df0f7d4ccb3ebf09a4530be4a56c/docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/index.md?plain=1#L998

Additionally, could you check if there are any other items that need to be fixed?

**Comment by knzo25** [comment]
@YamatoAndo 
Apologies, I missed the documentation one, and completely forgot the existence of the tools repository.

I sent the respective PRs, and used
```bash
GHUSER=tier4; curl "https://api.github.com/users/$GHUSER/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone
GHORG=autowarefoundation; curl "https://api.github.com/orgs/$GHORG/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone
```
to check for occurrences in all autowarefoundation and tier4 repositories

**Comment by knzo25** [comment]
@YamatoAndo @TaikiYamada4 
friendly ping

**Review by TaikiYamada4 — APPROVED** [review]
I confirmed that imu_corrector and gyro_bias_estimator works with this PR and relevant PRs via the sample rosbag replay tutorial.
LGTM and do not forget to merge the relavant PRs at once as possible.

**Pull request merged**
