### PR TITLE
fix: invalid parameter query between nodes

### LINKED ISSUE #1272: Invalid parameter query in scenario_selector node
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

According to the design, scenario mode should change to lane_driving mode after parking task is completed and stops in lane but it didn't.

image

image

### Expected behavior

After parking task is completed and the car stops in lane in parking mode, the scenario should changed to lane_driving mode.

### Actual behavior

After parking task is completed and the car stops in lane in parking mode, the scenario still keeps in parking mode.

### Steps to reproduce

1. Start autoware planning simulator using default
2. Set pose estimate in parking spot and goal pose in lane
3. Engage the car and echo "/planning/scenario_planning/scenario" topic

### Versions

- OS: Ubuntu 20.04
- ROS2: Galactic
- Autoware: Autoware.universe:main

### Possible causes

Parking state information is not correctly transferred to scenario_selector node. Scenario_selector can not [get](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp#L158) the paramter [set](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp#L383) in freespace_planner. 
The parameter name remapping does not work. I think even though they are successfully remapped to the same name it still can not work well because they belong to different nodes.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NorahXiong**
Signed-off-by: NorahXiong <norah.xiong@autocore.ai>

## Description

fix #1272

## Related links

#1272

## Tests performed

Tested in planning simulator.

Before:
image
After
image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
The parking and lane driving works fine for me too.

**Comment by NorahXiong** [comment]
> The parking and lane driving works fine for me too.

Could review this PR for me?

**Comment by shmpwk** [comment]
Your code looks great but I'm not sure it is really ok.
So I asked a senior engineer to review it.

**Comment by shmpwk** [comment]
@taikitanaka3

**Review by kenji-miyake — APPROVED** [review]
I think it's okay if it works as expected!
Thank you for fixing this. It is a technical debt from prototyping in the early stage development.

**Review by shmpwk — APPROVED** [review]

**Pull request merged**
