### PR TITLE
refactor(tensorrt_yolox): rework parameters

### PR DESCRIPTION
**Pull request by tby-udel**
## Description
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the `tensorrt_yolox` package.

 * Partially re-wrote the part of parameter declaration in the source code to ensure all parameter values are passed from the parameter files.
 * Use types that match the ones returned from declare_parameter() in order to prevent confusion and potential coding errors.
 * Move the default parameter file to a standardized location. Use the JSON Schema for that.
 * Updated readme file.

## Tests performed
Package built and launched locally.

## Notes for reviewers
 Nothing inside the src code part was changed, only taking the parameters out.

## Interface changes
Parameter values are now required to be passed to the node when launched.

## Effects on system behavior
None

## Pre-review checklist for the PR author
The PR author **must** check the checkboxes below when creating the PR.

 * [x]  I've confirmed the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
 * [x]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

 ## In-review checklist for the PR reviewers
 The PR reviewers **must** check the checkboxes below before approval.

 * [ ]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
 * [ ]  The PR has been properly tested.
 * [ ]  The PR has been reviewed by the code owners.
 
 ## Post-review checklist for the PR author
 The PR author **must** check the checkboxes below before merging.
 
 * [ ]  There are no open discussions or they are tracked via tickets.
 * [ ]  The PR is ready for merge.
 
 After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by mitsudome-r** [comment]
@tby-udel Thanks for the PR. 

However, the PR seems to be failing in the CI for DCO check. When you push commits, could you push with signed-off commits?

For example by running the following command:
`git rebase -i --signoff origin/main`

**Comment by tby-udel** [comment]
Thank you for the reminding, I have pushed the signed off commit.

**Comment by kminoda** [comment]
@tby-udel Would you fix the conflict?

**Comment by tby-udel** [comment]
> @tby-udel Would you fix the conflict?

Conflict solved.

**Review by manato — COMMENTED** [review]
@tby-udel 
Thank you for your contribution. Since I missed to submit my review comments after writing, I'm sorry for the delay in getting back to you. I added comments to some points, so I'd appreciate it if you could check them.

**Comment by tby-udel** [comment]
Thank you for your comments, all the required changes have been made.

**Comment by mitsudome-r** [comment]
@manato Could you re-review this PR?

**Review by manato — APPROVED** [review]
@tby-udel @mitsudome-r 
Thank you very much for updating and reminding me. LGTM! Again, I appreciate your contribution.

**Comment by tby-udel** [comment]
@manato Hi Manato, my pleasure working with you. I don't have the write access to this repo and I cannot do the merge by myself, it would be much appreciated if you can help me merge it.

**Comment by manato** [comment]
@tby-udel 
Merged! Thanks!

**Pull request merged**
