### PR TITLE
feat(default_ad_api): add operation mode api

### PR DESCRIPTION
**Pull request by isamu-takagi**
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>

## Description

This is an implementation of [operation mode API](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/list/api/operation_mode/). For details, see [the discussion page](https://github.com/autowarefoundation/autoware/discussions/2464#discussioncomment-4107546).

## Related links

https://github.com/autowarefoundation/autoware.universe/pull/1535
https://github.com/autowarefoundation/autoware.universe/pull/1586
https://github.com/tier4/tier4_autoware_msgs/pull/46

## Tests performed

1. Launch the planning_simulator.launch.xml, initialize pose and set route.
2. Call `change_to_autonomous` service, and check if the vehicle starts.
3. Call `change_to_stop` service, and check if the vehicle stops.
4. Call `change_to_local` and `change_to_remote` services, and check if gate_mode and selector_mode are changed (AutowareStatePanel is useful).

## Notes for reviewers

Commands
`ros2 service call /api/operation_mode/change_to_stop autoware_adapi_v1_msgs/srv/ChangeOperationMode`
`ros2 service call /api/operation_mode/change_to_autonomous autoware_adapi_v1_msgs/srv/ChangeOperationMode`
`ros2 service call /api/operation_mode/change_to_local autoware_adapi_v1_msgs/srv/ChangeOperationMode`
`ros2 service call /api/operation_mode/change_to_remote autoware_adapi_v1_msgs/srv/ChangeOperationMode`

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkhmy** [comment]
Here is several commend for this PR
1. I think the `/api/operation_mode/state` should be change to publish in 10Hz, as now it only publish when it receive mode change. This might cause the data loss if the connection is not stable, so I think is better to publish it in a constant  frequency.
2. The tools will required to base on the mode and choose the mode change, but currently I cannot get the mode in the initial, so the tools cannot know is the vehicle in and cannot call the correct service.
3. is_autonomous_mode_available is always false, cannot change to auto mode

**Comment by isamu-takagi** [comment]
@tkhmy Thank you for the comments. 

1. AD API avoid periodically publishing topics because it increases the amount of communication. The data loss should be guaranteed by DDS QoS.
2. Since the initial state depends on the vehicle interface, the application need to wait until the first state
3. Will it be true if I set initial pose and route?

**Comment by tkhmy** [comment]
> @tkhmy Thank you for the comments.
> 
> 1. AD API avoid periodically publishing topics because it increases the amount of communication. The data loss should be guaranteed by DDS QoS.
> 2. Since the initial state depends on the vehicle interface, the application need to wait until the first state
> 3. Will it be true if you set initial pose and route?

1. I think if AD API do not plan to periodically publish topic, it should be change to services instead of topic, because the app will not able to get the data is the change occur before the app launch.
2. Which part will trigger the first state? As some of the application will need to use the api to trigger the mode change, currently in psim, we will not able to get any info.
3. It still false even I set the initial pose and route

**Comment by isamu-takagi** [comment]
> I think if AD API do not plan to periodically publish topic, it should be change to services instead of topic, because the app will not able to get the data is the change occur before the app launch.

QoS of this topic is reliable/transient_local, so the application can read the message even if it is started later.

> 2. Which part will trigger the first state? As some of the application will need to use the api to trigger the mode change, currently in psim, we will not able to get any info.

The state needed to set the initial pose.

> 3. It still false even I set the initial pose and route

https://github.com/tier4/autoware_launch/pull/561

**Review by tkhmy — APPROVED** [review]
LGTM
Tested the new api

**Review by yabuta — APPROVED** [review]
LGTM

**Pull request merged**
