### PR TITLE
feat(map_projection_loader): componentize MapProjectionLoader

### PR DESCRIPTION
**Pull request by a-maumau**
## Description

Componentize the node in map/map_projection_loader.
(Add glog feature to map/map_projection_loader)

Also, log output is changed from "screen" to "both".

## Tests performed

confirmed that killing the map_projection_loader process will output logs to terminal and log file.
```Text
1716518405.4245486 [component_container_mt-57] [INFO] [1716518405.423379779] [control.trajectory_follower.lane_departure_checker_node]: waiting for route msg...
1716518409.0239754 [map_projection_loader_node-28] [INFO] [1716518409.023433474] [rclcpp]: signal_handler(signum=15)
1716518409.0241122 [map_projection_loader_node-28] *** Aborted at 1716518409 (unix time) try "date -d @1716518409" if you are using GNU date ***
1716518409.0254688 [map_projection_loader_node-28] PC: @                0x0 (unknown)
1716518409.0261354 [map_projection_loader_node-28] *** SIGTERM (@0x3e8001c1f43) received by PID 2658533 (TID 0x7f5664a35680) from PID 1843011; stack trace: ***
1716518409.0267746 [map_projection_loader_node-28]     @     0x7f5664f454d6 google::(anonymous namespace)::FailureSignalHandler()
1716518409.0273538 [map_projection_loader_node-28]     @     0x7f5664e19ded rclcpp::SignalHandler::signal_handler()
1716518409.0279086 [map_projection_loader_node-28]     @     0x7f5664442520 (unknown)
1716518409.0279868 [map_projection_loader_node-28]     @     0x7f5664491117 (unknown)
1716518409.0284991 [map_projection_loader_node-28]     @     0x7f5664493a41 pthread_cond_wait
1716518409.0285807 [map_projection_loader_node-28]     @     0x7f5664316a8d ddsrt_cond_wait
1716518409.0286429 [map_projection_loader_node-28]     @     0x7f5664316b55 ddsrt_cond_waituntil
1716518409.0291827 [map_projection_loader_node-28]     @     0x7f56642fd45d (unknown)
1716518409.0293431 [map_projection_loader_node-28]     @     0x7f56643b974f rmw_wait
1716518409.0299428 [map_projection_loader_node-28]     @     0x7f5664b85848 rcl_wait
1716518409.0304940 [map_projection_loader_node-28]     @     0x7f5664d611b6 rclcpp::Executor::wait_for_work()
1716518409.0311561 [map_projection_loader_node-28]     @     0x7f5664d616d3 rclcpp::Executor::get_next_executable()
1716518409.0319254 [map_projection_loader_node-28]     @     0x7f5664d65c81 rclcpp::executors::SingleThreadedExecutor::spin()
1716518409.0320199 [map_projection_loader_node-28]     @     0x560295d91486 main
1716518409.0325541 [map_projection_loader_node-28]     @     0x7f5664429d90 (unknown)
1716518409.0330262 [map_projection_loader_node-28]     @     0x7f5664429e40 __libc_start_main
1716518409.0331109 [map_projection_loader_node-28]     @     0x560295d91e35 _start
1716518409.0351989 [ERROR] [map_projection_loader_node-28]: process has died
```

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by KYabuuchi — DISMISSED** [review]
Thank you for making PR
I have confirmed that the glog outputs the log when the process is killed. :+1:

**Comment by KYabuuchi** [comment]
@a-maumau  Please modify the python files under `map_projection_loader/test/`.
 Those files are trying to execute `map_projection_loader` instead of `map_projection_loader_node`. :pray:

https://github.com/autowarefoundation/autoware.universe/blob/9d71cceeedac4797b54433d617f86265580c171f/map/map_projection_loader/test/test_node_load_local_cartesian_utm_from_yaml.test.py#L47
 
You can also test map_projection_loader in the following way
`colcon test --event-handlers console_cohesion+ summary+ --packages-select map_projection_loader `

**Comment by a-maumau** [comment]
@KYabuuchi Thank you for the mention. I fix the executable args in the test files in https://github.com/autowarefoundation/autoware.universe/pull/7108/commits/d966f7dd10cd51829b7cd2d35523be56f4184bea .

In my local environment, the test passed.

**Review by KYabuuchi — APPROVED** [review]
CI has passed, so there is no problem.
Thank you!

**Pull request merged**
