### PR TITLE
chore(traffic_light): change external input topic of traffic light arbiter

### PR DESCRIPTION
**Pull request by TomohitoAndo**
## Description

Changed external input topic of traffic_light_arbtier.

Related issue
- https://github.com/autowarefoundation/autoware.universe/issues/2567

## Tests performed

None

## Effects on system behavior

This has no effects on system behavior because This topic isn't used currently.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — APPROVED** [review]
Thanks! 
LGTM

**Review by yukkysaito — CHANGES_REQUESTED** [review]
I think the current topic name is better for the component interface.

**Comment by yukkysaito** [comment]
Can you wait a bit Marge?

**Comment by TomohitoAndo** [comment]
We will continue to use the current topic name for a while, so this PR will be closed for now.

**Pull request closed without merging**
