### PR TITLE
refactor(signal_processing): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]

**Review by SakodaShintaro — APPROVED** [review]
Thank you for the pull request.
As for localization changes, it looks good to me.

Unfortunately, an error occurred during rosdep install.

```
vcs import src < tools.repos
```

and 

```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
driving_environment_analyzer: Cannot locate rosdep definition for [signal_processing]
```

Because there is a package that uses this signal_processing package in autoware_tools, please make the necessary changes.

**Comment by esteve** [comment]
@SakodaShintaro I've submitted https://github.com/autowarefoundation/autoware_tools/pull/110, it should be merged after this PR is merged.

**Comment by SakodaShintaro** [comment]
@esteve 
Thank you for creating a pull request for autoware_tools.
Could you resolve the conflict in this pull request?

**Comment by xmfcx** [comment]
I'll rebase to main to test it with the latest autoware.

**Review by xmfcx — APPROVED** [review]
I was able to compile and run planning simulator with this PR.

**Pull request merged**
