### PR TITLE
fix(avoidance): use previous module output

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

use previous module output in new manager

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
NOTE: This PR use util function that is added in https://github.com/autowarefoundation/autoware.universe/pull/3042, so there are two commits to removed before merge.

- https://github.com/autowarefoundation/autoware.universe/pull/3043/commits/99f90c0f057bba918f6eb22a65eb96e38121003b
- https://github.com/autowarefoundation/autoware.universe/pull/3043/commits/bd3381165c1b72a1b5f205bd8cacc56c58fbfdea

**Comment by zulfaqar-azmi-t4** [comment]
Seems to be no issue.

https://user-images.githubusercontent.com/93502286/224611421-4208f007-fdc2-4608-843c-5a68d8118e16.mp4

**Review by zulfaqar-azmi-t4 — APPROVED** [review]
LGTM

**Comment by satoshi-ota** [comment]
[[TIER IV INTERNAL LINK]](https://evaluation.tier4.jp/evaluation/reports/b6bebd19-09b7-5000-965f-c80ab3e8de9a?project_id=prd_jt)

NOTE: following scenarios are out of scope.

- [UC-A-04-00103_001_case01_new](https://evaluation.tier4.jp/evaluation/scenarios/1b2346be-570c-4379-8774-8897c52398d5?project_id=prd_jt)
- [UC-A-04-00306_001_case01_new](https://evaluation.tier4.jp/evaluation/scenarios/4c49e387-d751-41e7-8b7d-3f2583435de6?project_id=prd_jt)
- [UC-A-04-00306_002_case01_new](https://evaluation.tier4.jp/evaluation/scenarios/69f099ee-3901-4be3-90ce-122a225f285a?project_id=prd_jt)
- [UC-A-04-00307_001_case01_new](https://evaluation.tier4.jp/evaluation/scenarios/01a2fef0-205f-4fae-92d7-8ceb4e8589b7?project_id=prd_jt)

**Pull request merged**
