### PR TITLE
chore(ground_segmentation_launch): change max_z of cropbox filter to vehicle_height

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

- Change to use `vehicle_height` for `max_z` parameter of `/perception/obstacle_segmentation/xx_crop_box_filter' nodes
- Need merge together with https://github.com/autowarefoundation/autoware_launch/pull/906

## Related_link

[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1709688432469209?thread_ts=1709652542.797929&cid=C03S84LDJGG)

## Tests performed
- Confirmed by `logging_simulator` that the correct `max_z` and `min_z` were parsed to `obstacle_segmentation/crop_box_filter' node as desired.
image

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@badai-nguyen 
image
I ran the tutorial and checked the polygon in the crop box and it looks like the polygon height is zero.

**Comment by yukkysaito** [comment]
@badai-nguyen here is parameter dump result :pray: 
image

**Comment by badai-nguyen** [comment]
@yukkysaito I'm so sorry for typo mistake :bow: . I fixed https://github.com/autowarefoundation/autoware.universe/pull/6549/commits
image

**Comment by yukkysaito** [comment]
image
I change the vehicle height to `10.5`, it is properly reflected

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
