### PR TITLE
fix(behavior_path_planner): pull_over far goal bug

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

Solved a problem where setting a goal after a loop pull_over did not work well. Because current_lanes does not contain goal, goal_arc_length cannot be calculated correctly (it becomes 0) and pull_oevr module is invoked. In addition, arc_length could not be calculated properly in the module processing, this caused bug.
In this PR, when a goal is far away and current_lanes does not contain the goal, the module will not be launched.

## Tests performed

psim

https://user-images.githubusercontent.com/39142679/184055846-bd4fff7a-8248-4a3a-8e83-aa540dfef8e3.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
Failed for me......
[Uploading Screencast from 2022年08月12日 11時05分04秒.webm…]()

**Comment by kosuke55** [comment]
@shmpwk 
thanks for checking.
In your case, the goal is placed on the shoulder of the same lane as ego, so it fails.
Even in the case of normal lane following, if the goal behind the same lane is set, it will fail.

**Review by shmpwk — COMMENTED** [review]
Thank you, I understand!
Could you apply clang-tidy to this file?

**Comment by kosuke55** [comment]
@shmpwk 
I will update pull_over moudle in
https://github.com/autowarefoundation/autoware.universe/pull/1534, so apply clang-tidy witi ti.

**Review by shmpwk — APPROVED** [review]
LGTM!

**Pull request merged**
