### PR TITLE
feat(time_synchronizer): organize twist input

### PR DESCRIPTION
**Pull request by kminoda**
## Description

Organize twist input of time_synchronizer as well as concatenate_filter

## Tests performed

Not applicable

## Effects on system behavior

The node will subscribe to /sensing/vehicle_velocity_converter/twist_with_covariance from now on. But we see no practical effects on the system behavior given that the node is not used yet in the system as far as we know.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
What is the node that uses this synchronizer?

**Comment by kminoda** [comment]
@miursh Would you answer the above question?

**Comment by miursh** [comment]
@yukkysaito This node is currently not used I think. 
Since the current concatenate node has two function ("time synchronization" and "pointcloud concatenation") in it, we (mainly @YoshiRi ) are planning to separate those to another nodes. 
https://github.com/autowarefoundation/autoware.universe/blob/main/sensing/pointcloud_preprocessor/docs/concatenate-data.md#node-separation-options-for-future

**Comment by yukkysaito** [comment]
@kminoda @miursh Thanks :+1: 
Note that the sensing component is a pre-processing step of the localization component, so it is better to avoid using localization output.

**Comment by kminoda** [comment]
@yukkysaito Understood. The reason why the proposed implementation both supports twist (for sensing) and odom (for localization) is that the node can be use in both sensing and perception module.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
