### PR TITLE
chore(map_loader): rework parameters of map_loader

### PR DESCRIPTION
**Pull request by anhnv3991**
## Description

In the map_loader module

- Added lanelet2_map_loader.schema.json and pointcloud_map_loader.schema.json that describe parameters of map_loader in the json format
- Moved the parameter lanelet2_map_path from lanelet2_map_loader.launch.xml to lanelet2_map_loader.param.yaml
- Moved the parameters pcd_paths_or_directory and pcd_metadata_path from pointcloud_map_loader.launch.xml to pointcloud_map_loader.param.yaml
- Modified README.md to refer to json schema files in the Parameters sections

## Tests performed

Parameters of pointcloud map loader 
screenshot_pointcloud_map_loader_param
Parameters of lanelet2 map loader
screenshot_lanelet2_map_loader_param

## Effects on system behavior

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by SakodaShintaro — CHANGES_REQUESTED** [review]
Thank you for the pull request.
Please wait a little longer while we decide what to do with parameters such as `pcd_paths_or_directory` and `pcd_metadata_path`.

**Comment by SakodaShintaro** [comment]
For arguments like file paths, we decided to use the following notation to maintain the previous behavior.
It should be given from the argument.
https://github.com/autowarefoundation/autoware-github-actions/issues/232#issuecomment-1867305456

**Comment by YamatoAndo** [comment]
@anhnv3991 Could you please submit [this commit](https://github.com/autowarefoundation/autoware.universe/pull/6199/commits/ea945e147094610dc2b9cb877ba215f0bf2987c5) as a separate pull request?

**Comment by anhnv3991** [comment]
@YamatoAndo If I does not add [that commit](https://github.com/autowarefoundation/autoware.universe/pull/6199/commits/ea945e147094610dc2b9cb877ba215f0bf2987c5) , one of the CLI checks will fail.

**Comment by SakodaShintaro** [comment]
@anhnv3991 
Since we need to change the `autoware_launch` parameter at the same time, could you please create a pull request for that repository as well?

`autoware_launch/config/map/lanelet2_map_loader.param.yaml` and `autoware_launch/config/map/pointcloud_map_loader.param.yaml` must be changed.

https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/map/lanelet2_map_loader.param.yaml
https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/map/pointcloud_map_loader.param.yaml

**Comment by YamatoAndo** [comment]
> @YamatoAndo If I does not add [that commit](https://github.com/autowarefoundation/autoware.universe/pull/6199/commits/ea945e147094610dc2b9cb877ba215f0bf2987c5) , one of the CLI checks will fail.

@anhnv3991  The title of this PR is "chore(map_loader): rework parameters of map_loader", and [this commit](https://github.com/autowarefoundation/autoware.universe/pull/6199/commits/ea945e147094610dc2b9cb877ba215f0bf2987c5) is not related to that, so please submit it as a separate PR.

The failed CI is not a required CI, so you don't need to worry about it.

**Comment by anhnv3991** [comment]
> @anhnv3991 Since we need to change the `autoware_launch` parameter at the same time, could you please create a pull request for that repository as well?
> 
> `autoware_launch/config/map/lanelet2_map_loader.param.yaml` and `autoware_launch/config/map/pointcloud_map_loader.param.yaml` must be changed.
> 
> https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/map/lanelet2_map_loader.param.yaml https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/map/pointcloud_map_loader.param.yaml

@SakodaShintaro How can I test those files after I made changes?

**Comment by SakodaShintaro** [comment]
@anhnv3991 

* set autoware.universe to this branch (anhnv3991:chore/rework_param_map_loader)
* set autoware_launch to a branch where you changed

Then, run autoware to check if it works properly. ([logging_simulator in sample rosbag](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) is often used)

If you submit a pull request to autoware_launch and paste the URL (draft is ok), I will check it. :smiley:

**Comment by SakodaShintaro** [comment]
@anhnv3991 
I apologize for pointing this out in detail, but we have now decided to stop setting default values in `declare_parameter`. (This is because it becomes difficult to understand where the value is set.)

https://github.com/autowarefoundation/autoware.universe/blob/e2a5f4aed880b746b76c4c5d51927fb441ce4b3e/map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
I would appreciate it if you could fix this.

from
```cpp
  declare_parameter("lanelet2_map_path", "");
  declare_parameter("center_line_resolution", 5.0);
```

to
```cpp
  declare_parameter<std::string>("lanelet2_map_path");
  declare_parameter<double>("center_line_resolution");
```

And there is a parameter in `lanelet2_map_visualization_node`.

https://github.com/autowarefoundation/autoware.universe/blob/e2a5f4aed880b746b76c4c5d51927fb441ce4b3e/map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp#L74


However, it is not a good idea to add a new param file and json file for this one parameter, so why not try writing true directly instead of using this value as a parameter?

from
```cpp
  viz_lanelets_centerline_ = this->declare_parameter("viz_lanelets_centerline", true);
```

to
```cpp
  viz_lanelets_centerline_ = true;
```

@YamatoAndo 
What about the above changes? Is it better to create config and json properly?

**Comment by YamatoAndo** [comment]
> However, it is not a good idea to add a new param file and json file for this one parameter, so why not try writing true directly instead of using this value as a parameter?
> 
> from
> 
>   viz_lanelets_centerline_ = this->declare_parameter("viz_lanelets_centerline", true);
> to
> 
>   viz_lanelets_centerline_ = true;

I agree with this proposal!

**Review by SakodaShintaro — APPROVED** [review]
Thank you for the correction.
It has been confirmed that the `logging_simulator` runs with the same accuracy as before on AWSIM data with GT.
Looks Good To Me

When merging, please press the merge button at the same time as below
https://github.com/autowarefoundation/autoware_launch/pull/843
(Strictly speaking, there is no problem even if PR at autoware_launch is merged first, so I think it would be a good idea to press the merge button of the PR at autoware_launch first.)

**Comment by SakodaShintaro** [comment]
@anhnv3991 
Sorry, I forgot to check the map_loader test.

build-and-test-differential is failed. <https://github.com/autowarefoundation/autoware.universe/actions/runs/7809902259/job/21302469469?pr=6199>

I think it is good to fix a test code.

https://github.com/autowarefoundation/autoware.universe/blob/main/map/map_loader/test/lanelet2_map_loader_launch.test.py#L37

from
```python
        parameters=[{"lanelet2_map_path": lanelet2_map_path}],
```

to

```python
        parameters=[{
            "lanelet2_map_path": lanelet2_map_path,
            "center_line_resolution": 5.0,
        }],
```

The test can be confirmed by following commands. 


```bash
cd ~/autoware
colcon build --symlink-install \
  --cmake-args \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=ON \
    -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' \
    -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage' \
  --packages-select map_loader
colcon test --return-code-on-test-failure --packages-select map_loader
colcon test-result --all --verbose | grep map_loader
```

**Pull request merged**
