### PR TITLE
chore(typo): fix typos in comment

### PR DESCRIPTION
**Pull request by HansRobo**
## Description

Fix typos in source code comments

This pull request is a part of #2841 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Review by soblin — APPROVED** [review]

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by HansRobo** [comment]
Thank you for your reviews!
All changes were approved by code owners, but I cannot merge because I don't have write access.

**Could you merge this pull request?**

**Comment by HansRobo** [comment]
@soblin Thanks!!

**Comment by takayuki5168** [comment]
@HansRobo Is this PR ready to merge?

**Pull request merged**
