### PR TITLE
feat: use vehicle_stop_checker for  judging vehicle stop vehicle_cmd_gate

### PR DESCRIPTION
**Pull request by tkimura4**
## Description
For vehicles that cannot acquire the vehicle speed in the low speed range, it may be incorrectly judged to be stopped 
 in the vehicle_cmd_gate node.
To prevent this, we use ```vehicle_stop-checker``` for stop judgment

## Related links
https://github.com/autowarefoundation/autoware_launch/pull/417

## Tests performed
TODO 

## Interface changes
none

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
If we use stop_duration common to ADAPI, I'll close this PR since we can use ```adapi_pause_->is_paused()``` instead of vehicle_stop_checker.

**Review by mkuri — APPROVED** [review]
LGTM

**Comment by mkuri** [comment]
Before
Shock occurs due to a stop misjudgment before stop.

Screenshot from 2023-06-23 17-38-50


After
Screenshot from 2023-06-23 17-38-26

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Pull request merged**
