### PR TITLE
fix(obstacle_stop_planner): fix virtual wall posiiton

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

- visualize actual stop posiion by virtual wall

## Related link

- https://github.com/autowarefoundation/autoware.universe/pull/1434

### obstacle_stop_planner

- `hold_stop_margin_distance`: 2.0 [m]

https://user-images.githubusercontent.com/44889564/184602983-987d3775-3379-4f59-8458-9682fda777a0.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by h-ohta** [comment]
I think it is not natural behavior for stopline, detection area and vtl.

**Comment by satoshi-ota** [comment]
> I think it is not natural behavior for stopline, detection area and vtl.

Separate PR into two parts, `obstacle_stop_planner` and the others.

**Comment by h-ohta** [comment]
@satoshi-ota Could you fix PR tile?

**Review by yukkysaito — COMMENTED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
