### PR TITLE
feat: add lidar point filter when debug

### PR DESCRIPTION
**Pull request by storrrrrrrrm**
Signed-off-by: suchang <chang.su@autocore.ai>

## Description

when debug roi_cluster_fusion,In the case of many obstacles, it is difficult to distinguish which box corresponds to which target.  so i add a fuction: filter point out of user-defined scope to make it easier to debug.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kenji-miyake — COMMENTED** [review]
I'm sorry, I'm not familiar with this node.
@yukkysaito @aohsato @miursh Could you assign someone appropriate? :pray:

**Comment by yukkysaito** [comment]
Sorry for the late reply. In Japan, people are on vacation.
Please wait for a few days :pray:

**Comment by storrrrrrrrm** [comment]
> @storrrrrrrrm could you resolve some conflicts? pray

conflicts resolved

**Comment by yukke42** [comment]
LGTM!

**Review by yukke42 — APPROVED** [review]

**Comment by storrrrrrrrm** [comment]
> LGTM Can you share the debug picture?

before:
image

after:
change configuration to filter objects out of your intrested scope
```
  <arg name="filter_scope_miny" default="-1"/>
  <arg name="filter_scope_maxy" default="2"/>
```
image

**Comment by yukke42** [comment]
@storrrrrrrrm Can you merge if there is no problem?

**Review by Sharrrrk — COMMENTED** [review]
LGTM

**Pull request merged**
