### PR TITLE
fix(pcl_ros): fix build fail by pcl_ros

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Related Issue(required)

#424 

## Description(required)
~since this won't be a good way to fix. dont merge this~

```
roi_cluster_fusion_nodelet.cpp:23:10: fatal error: pcl/point_types.h: そのようなファイルやディレクトリはありません
   23 | #include <pcl/point_types.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/roi_cluster_fusion_nodelet.dir/build.make:63: CMakeFiles/roi_cluster_fusion_nodelet.dir/src/roi_cluster_fusion_nodelet.cpp.o] エラー 1
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/roi_cluster_fusion_nodelet.dir/all] エラー 2
make: *** [Makefile:141: all] エラー 2
```

```
   54 | #include <pcl_ros/transforms.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointcloud_preprocessor_filter.dir/build.make:76: CMakeFiles/pointcloud_preprocessor_filter.dir/src/concatenate_data/concatenate_data_nodelet.cpp.o] エラー 1
make[2]: *** 未完了のジョブを待っています....
/home/taniyama/workspace/occlusion.proj/src/autoware/universe/sensing/pointcloud_preprocessor/src/filter.cpp:54:10: fatal error: pcl_ros/transforms.hpp: そのようなファイルやディレクトリはありません
   54 | #include <pcl_ros/transforms.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointcloud_preprocessor_filter.dir/build.make:63: CMakeFiles/pointcloud_preprocessor_filter.dir/src/filter.cpp.o] エラー 1
make[1]: *** [CMakeFiles/Makefile2:241: CMakeFiles/pointcloud_preprocessor_filter.dir/all] エラー 2
make: *** [Makefile:141: all] エラー 2
---
Failed   <<< pointcloud_preprocessor [49.2s, exited with code 2]
Summary: 253 packages finished [55.5s]
  10 packages failed: costmap_generator extrinsic_map_based_calibrator laserscan_to_occupancy_grid_map lidar_centerpoint obstacle_collision_checker obstacle_stop_planner point_cloud_accumulator pointcloud_preprocessor roi_cluster_fusion velodyne_pointcloud
  11 packages had stderr output: camera_calibration costmap_generator extrinsic_map_based_calibrator laserscan_to_occupancy_grid_map lidar_centerpoint obstacle_collision_checker obstacle_stop_planner point_cloud_accumulator pointcloud_preprocessor roi_cluster_fusion velodyne_pointcloud
  20 packages not processed
```

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by tkimura4** [comment]
[b730a5a](https://github.com/autowarefoundation/autoware.universe/pull/425/commits/b730a5a06efd94f587206bb1789633d87fad4dbc)
: Fix following error

```
[component_container_mt-15] /opt/ros/galactic/lib/rclcpp_components/component_container_mt: symbol lookup error: universe.proj/install/obstacle_stop_planner/lib/libobstacle_stop_planner.so: undefined symbol: _ZN7pcl_ros19transformPointCloudERKN5Eigen6MatrixIfLi4ELi4ELi0ELi4ELi4EEERKN11sensor_msgs3msg12PointCloud2_ISaIvEEERS9_
[ERROR] [component_container_mt-15]: process has died [pid 385604, exit code 127, cmd '/opt/ros/galactic/lib/rclcpp_components/component_container_mt --ros-args -r __node:=motion_planning_container -r __ns:=/planning/scenario_planning/lane_driving/motion_planning --params-file /tmp/launch_params_ho0y8vy7'].
```

**Comment by kenji-miyake** [comment]
@taikitanaka3 Please do not write TIER IV's Slack links because they aren't visible to everyone.

**Review by kenji-miyake — CHANGES_REQUESTED** [review]
Could you explain why `ament_cmake_auto` can't resolve this dependency?

**Comment by kenji-miyake** [comment]
If you merge this, I believe we should create a follow-up issue for that (`ament_cmake_auto`).

**Comment by taikitanaka3** [comment]
@kenji-miyake 
I actually don't know why this happened. But this bug is mentioned in many place in slack. And you said this maybe because of galatic sync.

**Comment by kenji-miyake** [comment]
@taikitanaka3 I guess this problem is different from what I mentioned before.

**Comment by wep21** [comment]
@taikitanaka3 Have you already solved this issue? If so, could you close this PR?

**Comment by taikitanaka3** [comment]
@wep21 
yes maybe rosdep update was necessary for this.

**Pull request closed without merging**
