### PR TITLE
refactor(obstacle_avoidance_planner): clean up the code

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

Refactored obstacle_avoidance_planner

**NOTE**
- The default trajectory length for optimization (MPT and EB) is 1.0m * 100points = 100m.
- Curvature calculated from the input path is not used in MPT since the optimization result will be unstable for some reason.

**Scenario Test**
https://evaluation.tier4.jp/evaluation/reports/badb956d-c52a-5966-b68b-2f4ca4822259?project_id=prd_jt

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by purewater0901 — APPROVED** [review]
Lgtm

**Comment by takayuki5168** [comment]
pre-commit.ci run

**Comment by takayuki5168** [comment]
pre-commit.ci run

**Review by kosuke55 — APPROVED** [review]

**Comment by takayuki5168** [comment]
@mehmetdogru @beyzanurkaya 
Sorry to share this with you late, but the following PRs' modification, which was recently merged, was removed with this large refactoring PR.
I will try to import the modification soon.

- https://github.com/autowarefoundation/autoware.universe/commit/ee9875496ff2636be8bf4a9ef1a861e984519489
- https://github.com/autowarefoundation/autoware.universe/commit/d6afa1bb7e8401586c97d9850f1caa06ac094ebd
- https://github.com/autowarefoundation/autoware.universe/commit/2d98ee84c9b422529a543922732e6f12046c0e20

**Comment by mehmetdogru** [comment]
@takayuki5168 I guess we will import the missing functionalities if you don't mind?

**Comment by takayuki5168** [comment]
@mehmetdogru
Ah, I'm so sorry to forget them.
Of course, it's fine for me that you will import them.
(FYI: If you want me to do it, I can start importing from July.)

**Pull request merged**
