### PR TITLE
refactor(kalman_filter): make getter functions explicitly return values

### PR DESCRIPTION
**Pull request by IshitaTakeshi**
## Description

Getter functions should explicitly return values. 
Doing this allows the return values to be constants, and the readability improves.  

## Tests performed

No tests have been performed yet. The time-delay kalman filter has a large state so how to validate the internal state will be an open question.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kminoda — APPROVED** [review]
LGTM

**Comment by kminoda** [comment]
@IshitaTakeshi Just a reminder, but I think you need to get a review from the code owners of `kalman_filter` (currently only @.yukkysaito, but maybe we should consider adding other people as a new maintainer, too)

**Comment by IshitaTakeshi** [comment]
@YamatoAndo is also added as a code owner. How about?

**Comment by kminoda** [comment]
@IshitaTakeshi I don't think so (at least from [here](https://github.com/autowarefoundation/autoware.universe/blob/main/common/kalman_filter/package.xml))

```
  <description>The kalman filter package</description>
  <maintainer email="yukihiro.saito@tier4.jp">Yukihiro Saito</maintainer>
  <license>Apache License 2.0</license>
```

**Comment by IshitaTakeshi** [comment]
@kminoda I also could see the message "Waiting on code owner review from yukkysaito." on GitHub

**Comment by IshitaTakeshi** [comment]
@yukkysaito Could you review this?

**Comment by kminoda** [comment]
It still requires a review from @.yukkysaito even after merging https://github.com/autowarefoundation/autoware.universe/commit/87f8142efba0c3120f686792afc96932312ad8ad ... :thinking:

**Comment by kenji-miyake** [comment]
> It still requires a review from @.yukkysaito even after merging 87f8142 ... thinking

@kminoda Please merge https://github.com/autowarefoundation/autoware.universe/pull/1983.

**Pull request merged**
