### PR TITLE
feat(image_projection_based_fusion): update pointpainting

### PR DESCRIPTION
**Pull request by yukke42**
## Description

1. fix projection between points and roi
2. update pointpainting model

## Tests performed

sample data is available on <https://github.com/autowarefoundation/autoware.universe/pull/4314>.

By [the commit](https://github.com/autowarefoundation/autoware.universe/commit/84d2917245adbe356dca48c2bdc1de23487ba2c3) for the first item.

The average delay is reduced from 0.270 sec to 0.220 sec on the same environment.

[before]

image

image

[after]

image

image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### Summary by CodeRabbit

Release Notes:
- New Feature: The `score_threshold` parameter in the `pointpainting` node has been lowered from 0.45 to 0.35, allowing for more accurate point painting.
- Refactor: The `PointPaintingFusionNode` class has undergone significant changes, including the addition of a helper function, improved transformation methods, and the introduction of a new parameter for specifying classes to be painted.
- Bug fix: The timeout duration in the `getTransformStamped` function has been reduced from 0.5 seconds to 0.01 seconds, improving performance.

> "With lower thresholds and transformed points,
> Our fusion now paints with greater accuracy.
> Transformed by Eigen, pcl_ros takes the lead,
> As we refactor and improve our code's efficiency."

### CODE REVIEW

**Comment by yukke42** [comment]
image

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by miursh — APPROVED** [review]
LGTM
@yukke42 Could you also update the param in https://github.com/autowarefoundation/autoware_launch/tree/main/autoware_launch/config/perception/object_recognition/detection/lidar_model

**Comment by yukke42** [comment]
@miursh Cloud you check <https://github.com/autowarefoundation/autoware_launch/pull/506>?

**Pull request merged**
