### PR TITLE
feat(shift_decider): put the gear in park when vehicle reaches the goal

### LINKED ISSUE #1813: Change shift to park when vehicle stops
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

In autoware.universe, shift does not change when vehicle stopped. After initialized vehicle, vehicle's shift is parking until goal_position set. However, when vehicle arrived to goal, autoware keeps shift in drive.

[Related discussion](https://github.com/autowarefoundation/autoware/discussions/2778)

### Purpose

Change shift to `GearCommand::PARK` when vehicle stops.

### Possible approaches

Subscribe to ` /autoware/state` in `shift_decider` node and change the shift to `GearCommand::PARK` when vehicle arrives to the goal position.

### Definition of done

- [ ] Subscribe to `/autoware/state` in `shift_decider.cpp`
- [ ] Change the shift to `GearCommand::PARK`  in  `shift_decider.cpp` when `AutowareState::ARRIVED_GOAL` is received

### PR DESCRIPTION
**Pull request by lilyildiz**
Signed-off-by: lilyildiz <y.yzk61@gmail.com>

## Description

Closes  #1813 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by lilyildiz** [comment]
I added the `autoware_state_`  check to the beginning of the `onTimer` function and tested it with the sample vehicle and map. 

https://user-images.githubusercontent.com/70379994/189301643-efbbf3c6-225e-4e99-beb7-c9df73549c62.mp4

**Comment by takayuki5168** [comment]
LGTM

@yukkysaito @TakaHoribe could you check please

**Review by yukkysaito — APPROVED** [review]
Thank you for PR
LGTM

**Comment by yukkysaito** [comment]
@TakaHoribe @brkay54 Can I merge this?

**Review by brkay54 — APPROVED** [review]
Thank you for PR. Works well!

**Review by TakaHoribe — COMMENTED** [review]
@lilyildiz Thank you for your nice work. Would you add a flag to enable/disable this feature? This feature is not suitable for some vehicles which, for example, have a long time for the gear transition. Default should be true.

**Comment by lilyildiz** [comment]
> @lilyildiz Thank you for your nice work. Would you add a flag to enable/disable this feature? This feature is not suitable for some vehicles which, for example, have a long time for the gear transition. Default should be true (use this feature).

@TakaHoribe I defined the new flag in `control.launch.py` since the node did not have any param files loaded ( 67c32c31d1eec35bf730a12d054de4dcfc1569d6 ). Should I create a new param file for the `shift_decider` package or is it okay to leave it like this?

**Review by TakaHoribe — APPROVED** [review]
@lilyildiz Thank you! I don't think the param file is needed for now. Will be created when it is required.

**Comment by takayuki5168** [comment]
@lilyildiz Sorry to be late to request a change.

In the near future, parameters will be managed by yaml file in another repository since autoware.universe is not supposed to be forked to change parameters.
So could you add yaml file in shift_decider and tier4_control_launch packages and remove definition of `park_on_goal` in control.launch.py?

**Pull request merged**
