### PR TITLE
fix(object_merger): preserve unknown objects close to known objects

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

- This PR aims to separate GIoU thresholds for each class when determining whether unknown objects are overlapped with known objects or how far unknown objects are from known objects to enable merging.
- This also could solve issue #4425 

## Related link
[TIER IV INTERNAL LINK  ](https://tier4.atlassian.net/browse/RT1-3051)

## Tests performed

Some traffic cones detection near by truck was confirmed by internal rosbag.
image

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by miursh** [comment]
@badai-nguyen Could you also modify this config https://github.com/autowarefoundation/autoware.universe/blob/main/perception/object_merger/config/overlapped_judge.param.yaml ?

**Comment by badai-nguyen** [comment]
@miursh I have updated overlapped_judge config here https://github.com/autowarefoundation/autoware.universe/pull/4499/commits/ad121ab0facf468bc6bbab7cd526acbc870069ff

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
