### PR TITLE
docs(autoware_auto_geometry): fix link

### PR DESCRIPTION
**Pull request by esteve**
## Description

Fix link to article

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kenji-miyake — DISMISSED** [review]

**Comment by esteve** [comment]
CI is currently failing because of a broken link, fixed in #743

**Comment by kenji-miyake** [comment]
@esteve Thank you for fixing this!

Regarding `pre-commit-optional`, you don't have to pass it because it's not required.
But I really appreciate that you fixed invalid links. :pray: 

And DCO also fails. You might be familiar with this, but I'll explain it just in case.

When you edit files from the Web browser, it will be failed.
image

In that case, you can manually pass it by clicking `Details` -> `Set DCO to pass`. (If you believe there is no DCO issue.)
image

**Comment by kenji-miyake** [comment]
Or of course, you can `git commit amend -s` and `git push -f`.

**Comment by esteve** [comment]
@kenji-miyake thanks, I've updated the commits to include the DCO :slightly_smiling_face:

**Review by kenji-miyake — APPROVED** [review]

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
