### PR TITLE
perf(common_ground_filter): performance tuning

### PR DESCRIPTION
**Pull request by taisa1**
## Description

This PR makes scan_ground_filter (common_ground_filter) faster without changing the logical output.
The tail latency of the scan_ground_filter gets about x1.7 faster with this PR merged.

The main changes are as follows:
- Minimized the use of trigonometric functions such as `std::atan2`,
- Processed the input point cloud without converting it to `pcl::PointCloud`.

In addition, some small changes are made to improve performance.

### Measurement Condition
・Ubuntu22.04 + ROS2 Humble + Autoware Universe rosbag simulation
・Core Isolated
・Core Frequency Fixed (2.3GHz)
・L3 Cache: 24MB

## Related links

- [Implementation details, performance analysis of previous implementation](https://tier4.atlassian.net/wiki/spaces/~6422e65c57f0c028e2f72804/pages/2890237067/) (TIER IV internal link): 
- [Detailed explanation of this change](https://tier4.atlassian.net/wiki/spaces/~6422e65c57f0c028e2f72804/pages/2945910575/) (TIER IV internal link)

## Tests performed

It has been verified that the content of output topics with the same timestamp is identical before and after the PR.

### To reproduce
Download files from https://drive.google.com/drive/folders/1703DlE8MT0rksiQfZGR8A53wwrvMRSEc?usp=drive_link and run `python3 validator.py default.csv after.csv` for comparing results.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by atsushi421 — CHANGES_REQUESTED** [review]
It would be great if this PR was modified to pass CodeScene.

**Review by atsushi421 — APPROVED** [review]
LGTM!

**Comment by atsushi421** [comment]
@taisa1
The unit test is failed due to changes in `filter()`. It is recommended that the unit tests also use `faster_filter()`.
https://github.com/autowarefoundation/autoware.universe/actions/runs/7342510285/job/19991834839?pr=5861

**Comment by miursh** [comment]
This is the result of TIER IV CI test. https://evaluation.tier4.jp/evaluation/reports/f87c3c5b-89b0-5904-acb8-afae5ff2fdfc?project_id=prd_jt
image
After running our CI tests, we've observed a significant increase in the number of failure. The number of passing test cases, dropping from 148 to 68. While we haven't confirmed the details yet, it seems that some errors may be occurring.

**Comment by miursh** [comment]
Thanks!
I can see some changes, but there are still many failures.
https://evaluation.tier4.jp/evaluation/reports/d9fcb22f-095a-5b13-89a2-82b72be71201?project_id=prd_jt
image

**Comment by atsushi421** [comment]
@miursh 
Sorry for the late response. :bow: 
I found a variable uninitialized and have fixed it, could you review this again?

**Comment by atsushi421** [comment]
@badai-nguyen 
Thank you for the other day.
I used the [tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) to observe the state of the point cloud before and after PR and found no particular difference, as shown in the images below. (Used autoware.universe commit ID: ebb4172992ef0a3d989a57af227d2545d404b63c)
It seems to be working correctly in my environment, could you please review again?

| Before | After |
| -- | -- |
| |  |

**Review by badai-nguyen — APPROVED** [review]
@taisa1  @atsushi421 I deeply appreciate your improvement. 
 
I confirmed by `logging_simulator` that the `obstacle_segmentation/pointcloud` as before and the processing time of `/perception/obstacle_segmentation/common_ground_filter` node is improved.
| Before | After | 
| --- | ---|
| image  | image| 
| image| Screenshot from 2024-03-08 00-40-56 | 

[CI tested result](https://evaluation.tier4.jp/evaluation/reports/6f46b598-b02f-5b69-8489-29bd5c680260?project_id=prd_jt) also shows the acceptable pass rate.

LGTM!

**Pull request merged**
