### PR TITLE
refactor(mission_planner): merge set route service

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

From this comment: https://github.com/autowarefoundation/autoware.universe/pull/3396#issuecomment-1506993820. When we were using HADMapRoute, there was a type conversion problem, but now it is unified with LaneletRoute. So remove unnecessary services.

## Tests performed

Check if the route can be set in the simple planning simulator.

## Effects on system behavior

None.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]
thanks, good.
check built passed with https://github.com/autowarefoundation/autoware.universe/pull/3396/commits/b9b6a83ab35433cdd82745462f5b425082055841 in https://github.com/autowarefoundation/autoware.universe/pull/3396

**Comment by kosuke55** [comment]
@yukkysaito @kenji-miyake @tkhmy @yabuta 
Could you please check this PR as a code? :pray:

**Comment by kenji-miyake** [comment]
@kosuke55 The code looks good, but interfaces are managed by Saito-san. So I'll leave it to him.

**Review by yukkysaito — APPROVED** [review]
LGTM
As I discussed with @mitsudome-r and @isamu-takagi , there may be a need for more discussion in api_v2 regarding the mission planner interface.

**Review by tkhmy — APPROVED** [review]
LGTM

**Pull request merged**
