### PR TITLE
revert: "feat(pointcloud_preprocessor): use point_cloud_msg_wrapper"

### PR DESCRIPTION
**Pull request by miursh**
Reverts autowarefoundation/autoware.universe#1276

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by xmfcx** [comment]
What is the reason for reverting this change?

**Comment by xmfcx** [comment]
I see it's for https://github.com/autowarefoundation/autoware.universe/issues/2306

**Comment by xmfcx** [comment]
I think it's ok, it's better to add point_cloud_msg_wrapper feature once we finalize the point types architecture in [here](https://github.com/autowarefoundation/autoware-documentation/pull/180) and allow different point types too.

**Pull request merged**
