### PR TITLE
feat(tier4_autoware_utils): add expandPolygon function

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

move `expandPolygon` used in the behavior_path_planner package to `common/`.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
No need to write some tests?

**Comment by takayuki5168** [comment]
I should :sweat_smile:, I will.

**Comment by takayuki5168** [comment]
@kenji-miyake I added a simple test.

**Comment by takayuki5168** [comment]
@purewater0901 Could you review the PR?
I just moved `expandPolygon` to tier4_autoware_utils and added a test.

**Review by purewater0901 — APPROVED** [review]
LGTM

**Pull request merged**
