### PR TITLE
docs(autoware_pyplot): add missing readme and move the package to common

### PR DESCRIPTION
**Pull request by soblin**
## Description

add missing README of autoware_pyplot package.

@esteve Hi, is it OK for us to use this package from `common` and `planning` components ? The major motivation for this package is to create the illustrative descriptions of utility functions of `common`/`planning` components as documentation for better development experience. If it is unintended to use `visualization` package from `common` and `planning`, can you move this back to `common` ?

## Related links

**Parent Issue:**

- Link

## How was this PR tested?

 document PR

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by yhisaki — APPROVED** [review]

**Comment by xmfcx** [comment]
This reverts:
- https://github.com/autowarefoundation/autoware.universe/pull/9489

**Comment by xmfcx** [comment]
@soblin can you rebase this to latest main?

**Comment by xmfcx** [comment]
@esteve do you have any objection is on this?

This is a cpp library that provides python bindings to visualize graphs. Will be used and be depended by a lot of packages including the packages from common. That's why it might be a better idea to keep it in common.

**Comment by esteve** [comment]
@xmfcx if it's gonna be used by other packages, sure, no problem. My concern was that it seemed it wasn't being used by any other package other than those in `visualization`, but it's being used by packages that are in other folders, it makes sense to move it back.

I wonder if it might be better to rename `common` to `base`, IMHO it better describes its purpose.

**Comment by xmfcx** [comment]
@soblin You may merge this since we agreed on moving it back to `common` 👍

**Pull request merged**
