### PR TITLE
feat(map_loader): make some functions static

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

In order to make a static path planner with optimization as follows,
https://github.com/autowarefoundation/autoware.universe/issues/1942
I made some functions of map_loader required in the static planner static.

The usage in the static planner is like this
https://github.com/autowarefoundation/autoware.universe/blob/7296a427c03b82f24de90bc53d65285ac2f3710f/planning/static_centerline_optimizer/src/functions.cpp#L78-L87

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@TakaHoribe Could you review this PR.

**Comment by TakaHoribe** [comment]
@takayuki5168 How about having two functions with different arguments? (It seems a little odd to me that all methods are static.)


```
HADMapBin create_map_bin_msg(
  const lanelet::LaneletMapPtr map, const std::string & lanelet2_filename) {
  return create_map_bin_msg(map, lanelet2_filename, now());
}

static HADMapBin create_map_bin_msg(
  const lanelet::LaneletMapPtr map, const std::string & lanelet2_filename,
  const rclcpp::Time & now);
```

**Comment by takayuki5168** [comment]
@TakaHoribe 
To me, your idea looks redundant since there is no reason to define two types of functions.

@kenji-miyake What do you think.


> (It seems a little odd to me that all methods are static.)

I made the functions only required in the static path planner static. (If I do my best, I can split the static and non-static part more specifically)

**Comment by kenji-miyake** [comment]
> To me, your idea looks redundant since there is no reason to define two types of functions.
> @kenji-miyake What do you think.

I also think it's redundant in this case.

But since it seems class-independent, I feel it might be better to make these functions normal functions (like libraries), not class functions.
Are there any reasons to define these in the class?

**Comment by takayuki5168** [comment]
> Are there any reasons to define these in the class?

Not a big reason, but I just wanted to apply the minimum changes to map_loader and there are only two small functions which I feel exaggerated to make them a library.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
