### PR TITLE
ci: fix the way to check labels before running unsafe workflows

### PR DESCRIPTION
**Pull request by kenji-miyake**

### CODE REVIEW

**Review by KeisukeShima — APPROVED** [review]
LGTM

**Comment by kenji-miyake** [comment]
Actually, I found some points to be improved, I'll fix them later.
Also, will consider to make this a composite action.

**Comment by kenji-miyake** [comment]
I added a workflow in https://github.com/autowarefoundation/autoware-github-actions/pull/19.

**Comment by kenji-miyake** [comment]
I'll merge this and check the behavior.

**Pull request merged**
