### PR TITLE
feat(simulator_compatibility_test): creating test codes to check simulator compatibility with autoware

### PR DESCRIPTION
**Pull request by Soohyeok-Park**
## Description
- Purpose : To check whether a certain simulator is compatible with Autoware

## Related links
[issue link](https://github.com/autowarefoundation/autoware.universe/issues/1105)

## Tests performed
- Run the simulator compatibility test codes with MORAI SIM: Drive.

### Example usage
1. Build **simulator_compatibility_test** package
`$ cd {your_auware_workspace_directory}`
`$ source ./install/setup.bash`
`$ colcon build --packages-select simulator_compatibility_test`
2. Launch a simulator that is going to be tested
3. go to the test codes directory.
the test codes are located in _src/universe/autoware.universe/tools/simulator_test/simulator_compatibility_test/test_another_sim/_
`$ cd src/universe/autoware.universe/tools/simulator_test/simulator_compatibility_test/test_another_sim`
4. run test codes
   1. To test all cases automatically
    `$ pytest`
   2. To test a specific case
   `python -m pytest test_0{number}_{test_item}.py`

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by hakuturu583 — COMMENTED** [review]
simulator directory is [here.](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator)

Why do you create tools/simulator_test directory?

**Comment by Soohyeok-Park** [comment]
@hakuturu583 
> simulator directory is [here.](https://github.com/autowarefoundation/autoware.universe/tree/main/simulator)
> 
> Why do you create tools/simulator_test directory?

The simulation working group discussed where to put this code because the code is a test module rather than a simulator (in some point of view, it is related to a simulator as well.). 
there was an opinion that makes a folder named "tools" and put the test code for checking simulator compatibility. but I want to ask others for any suggestions. shall I move this to "autoware.universe/simulator/" ?

**Comment by mitsudome-r** [comment]
Is morai_msgs package copied from somewhere else, or is it made solely for this feature?
It if makes sense to be maintained within MORAI's github, then we can also add it in the repos file rather than copying it as autoware universe code. https://github.com/autowarefoundation/autoware/blob/main/autoware.repos

Also, could you add README to simulator_compatibility_test package to explain how it is used to test simulator compatibility?

**Comment by WJaworskiRobotec** [comment]
@Soohyeok-Park I have one question before I will go deeper into the code : Why do we need MORAI-specific messages/package with tests ?

I thought that those scripts will "mock" Autoware, sending the same messages that Autoware does, and analyzing the responses on the topics that Autoware subscribes to. I believe this package should be totally independent of tested simulator. If new simulation tool provider wants to integrate with Autoware, they should be able to just start simulator, run tests and get the result, which parts work and which don't.

Please let me know if I'm missing something, and then I will check in more detailed way the tests itself and also test it with TierIV SIM :)

**Comment by WJaworskiRobotec** [comment]
@Soohyeok-Park I've just tested the tests with TierIV Sim. Initialiy i had some problems and the commands send from the test scripts were not affecting the Simulator at all. 

I've found out that it was caused by the QoS : commands sent from Autoware have RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL, and without applying this change of durability to QoS used by publishers in your code it was not working.

After making this change I have 13/15 passed tested for TierIV Sim - looks pretty good to me, 2 tests that failed I will discuss directly with TierIV and later we can discuss it on the SimWG meeting.

Would you mind applying the change mentioned above to this PR ? (I can do that, or if you prefer you can do it on your own)

**Comment by Soohyeok-Park** [comment]
> I've found out that it was caused by the QoS : commands sent from Autoware have RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL, and without applying this change of durability to QoS used by publishers in your code it was not working.
> 
> After making this change I have 13/15 passed tested for TierIV Sim - looks pretty good to me, 2 tests that failed I will discuss directly with TierIV and later we can discuss it on the SimWG meeting.
> 
> Would you mind applying the change mentioned above to this PR ? (I can do that, or if you prefer you can do it on your own)

@WJaworskiRobotec  Thanks for your detailed review. I don't mind changing the code but for your convenience I did it. As far as I understood, the QoS durability setting about publishers matters (not subscribers) so I applied the RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL to the publishers only.

**Review by WJaworskiRobotec — APPROVED** [review]
Thanks for applying changes to QoS. now works fine and in general looks OK. approved

**Comment by WJaworskiRobotec** [comment]
@mitsudome-r I see that my review is not enough, review from someone with write access is required

**Review by mitsudome-r — APPROVED** [review]

**Comment by Soohyeok-Park** [comment]
I handled an error caused by this simulator_compatibility_test package to pass _build-and-test-differential_ but there are some failures due to other packages.

**Pull request merged**
