### PR TITLE
feat: isolate gtests in all packages

### LINKED ISSUE #684: Isolate gtests in all packages
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Change the way gtests are run in all packages to ensure they are isolated from each other.

### Purpose

The change will prevent tests running in parallel and publishing topics to interfere with each other.
For example, a test A subscribes to the `/tf` topic while a test B publishes transforms to the `/tf` topic.
The purpose of this task is to ensure test A and B cannot interfere with each other.

### Possible approaches

Replace the CMake commands `ament_add_gtest` with `ament_add_ros_isolated_gtest` similarly to what was done in https://github.com/autowarefoundation/autoware.universe/pull/661

### Definition of done

All packages run gtests in isolation.

### PR DESCRIPTION
**Pull request by maxime-clem**
## Description

Change the way gtests are run in all packages to ensure they are isolated from each other.
Closes #684 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by maxime-clem** [comment]
`uncrustify` is failing for package `autoware_auto_common`. If I fix it then `clang-format` fails during the pre-commit checks...

**Comment by esteve** [comment]
@maxime-clem you can prevent `uncrustify` to run on a block by surrounding it with `*INDENT-OFF*` and `*INDENT-ON*`, like this:

```c++
/* *INDENT-OFF* */
int x = 123;
/* *INDENT-ON* */
```

I'd favor `clang-format` over `uncrustify`

**Comment by maxime-clem** [comment]
The issue with formatting is fixed. The wrong lint dependency was used in the `package.xml` of `autoware_auto_common` which was causing the issue.

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Review by esteve — APPROVED** [review]

**Pull request merged**
