### PR TITLE
fix(ntp_monitor): move chronyc command execution to a timer

### PR DESCRIPTION
**Pull request by ito-san**
## Description
The diagnostic topic of `ntp_monitor` sometimes may not be sent periodically, every 1 second.
The root cause is that the execution of the `chronyc tracking` command gets stuck when the network connection is poor.

So the execution of the `chronyc` will be separated from the main thread using a separate thread along with a timer.
In addition, a feature will be added to monitor timeouts in `chronyc` and to send a WARNING notification when a timeout occurs.
The timeout duration is set to 5 seconds by default.

## Related links

[TIER IV INTERNAL LINK TO JIRA](https://tier4.atlassian.net/browse/AEAP-668)

## Tests performed

1. Run Autoware.
2. Run rqt_runtime_monitor.
    ```console
    ros2 run rqt_runtime_monitor rqt_runtime_monitor
    ```
3. Verify OK is reported during normal operation.
image

4. Verify Warning is reported when `chronyc tracking` gets stuck.
image

## Notes for reviewers

None

## Interface changes

None

## Effects on system behavior

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by h-ohta** [comment]
Could you add parameter to param.yaml with detail comments?
https://github.com/autowarefoundation/autoware.universe/blob/4c33a4a3011a2ac840922ead44d5dce5f14fcf99/system/system_monitor/config/ntp_monitor.param.yaml

**Comment by ito-san** [comment]
> Could you add parameter to param.yaml with detail comments? https://github.com/autowarefoundation/autoware.universe/blob/4c33a4a3011a2ac840922ead44d5dce5f14fcf99/system/system_monitor/config/ntp_monitor.param.yaml

You mean  the newly added parameter `timeout`?

**Comment by ito-san** [comment]
> @h-ohta
> You mean the newly added parameter `timeout`?

@h-ohta
Would you please answer the question?

**Comment by h-ohta** [comment]
@ito-san Yes

**Comment by ito-san** [comment]
> @ito-san Yes

@h-ohta Fixed in [94d4e90](https://github.com/autowarefoundation/autoware.universe/pull/4634/commits/94d4e90c5f0196643099d961321d4cfd49b1a673)

**Comment by h-ohta** [comment]
I checked this PR with following procedures.

1. Run system_monitor with ros2 launch 

``` bash
$ ros2 launch system_monitor system_monitor.launch.xml # for working in multi process
```

1. Run rqt_runtime_monitor.

``` bash
$ ros2 run rqt_runtime_monitor rqt_runtime_monitor
```

1. Confirm during normal operation

image



1. Confirm during abnormal operation, that is command stucking

I changed the command `chronyc tracking` to `sleep 10`.
      https://github.com/autowarefoundation/autoware.universe/blob/93ca42309e947c469b6e86b2e0d742206984fc63/system/system_monitor/src/ntp_monitor/ntp_monitor.cpp#L188

And I found out that ntp_monitor turned to warning state. 

image

**Review by h-ohta — APPROVED** [review]

**Comment by ito-san** [comment]
@asana17 Could you review this PR as the code owner?

**Review by asana17 — APPROVED** [review]
LGTM.

**Pull request merged**
