### PR TITLE
fix(autoware_ndt_scan_matcher): remove unsed functions

### PR DESCRIPTION
**Pull request by veqcc**
## Description

Fixed cppcheck `unusedFunction` warnings
```
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:177:0: style: The function 'getCov' is never used. [unusedFunction]
    const Eigen::Matrix3d & getCov() const { return (cov_); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:197:0: style: The function 'getPointCount' is never used. [unusedFunction]
    int getPointCount() const { return (nr_points_); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:355:0: style: The function 'apply_filter_thread' is never used. [unusedFunction]
  inline bool apply_filter_thread(int tid, GridNodeType & node)
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:135:0: style: The function 'setNumThreads' is never used. [unusedFunction]
  void setNumThreads(int n)
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:142:0: style: The function 'getNumThreads' is never used. [unusedFunction]
  inline int getNumThreads() const { return params_.num_threads; }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:184:0: style: The function 'setResolution' is never used. [unusedFunction]
  inline void setResolution(float resolution)
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:196:0: style: The function 'getResolution' is never used. [unusedFunction]
  inline float getResolution() const { return (params_.resolution); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:201:0: style: The function 'getStepSize' is never used. [unusedFunction]
  inline double getStepSize() const { return (params_.step_size); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:206:0: style: The function 'setStepSize' is never used. [unusedFunction]
  inline void setStepSize(double step_size) { params_.step_size = step_size; }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:211:0: style: The function 'getOutlierRatio' is never used. [unusedFunction]
  inline double getOutlierRatio() const { return (outlier_ratio_); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:216:0: style: The function 'setOutlierRatio' is never used. [unusedFunction]
  inline void setOutlierRatio(double outlier_ratio) { outlier_ratio_ = outlier_ratio; }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:274:0: style: The function 'setRegularizationScaleFactor' is never used. [unusedFunction]
  inline void setRegularizationScaleFactor(float regularization_scale_factor)
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:307:0: style: The function 'setTransformationEpsilon' is never used. [unusedFunction]
  inline void setTransformationEpsilon(double epsilon) { params_.trans_epsilon = epsilon; }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:312:0: style: The function 'getTransformationEpsilon' is never used. [unusedFunction]
  inline double getTransformationEpsilon() { return (params_.trans_epsilon); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:314:0: style: The function 'setMaximumIterations' is never used. [unusedFunction]
  inline void setMaximumIterations(int max_iterations)
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h:320:0: style: The function 'getMaxIterations' is never used. [unusedFunction]
  inline int getMaxIterations() const { return params_.max_iterations; }
^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by SakodaShintaro** [comment]
A similar issue has been discussed on ndt_omp (https://github.com/tier4/ndt_omp/pull/42#discussion_r1537266103)

@anhnv3991 
Do you have any thoughts on this?

**Comment by anhnv3991** [comment]
@SakodaShintaro My thought is still the same. Those functions are for setting/getting private members of ndt_omp. They should remain the same.

**Comment by veqcc** [comment]
@SakodaShintaro @anhnv3991 
Now Autoware has almost 0 `unusedFunction` warning from the point of software quality view.

There are several disadvantages of remaining functions as unused:
 - maintainability
 - compile time
 - binary size

Are there any big advantage over these disadvantages?

**Comment by SakodaShintaro** [comment]
@veqcc  @anhnv3991 

I would also like to remove.
If there are people who want to use `ndt_omp` as a good library, I think they should fork the `ndt_omp` repository and customize their own version of it.

If Anh-san agrees with this, I approve this PR.

**Comment by anhnv3991** [comment]
@SakodaShintaro @veqcc I see. In ndt_omp I aimed to develop a complete standalone library, so those functions are needed. But if your objective is to keep Autoware as compact as possible then I agree those unused functions should be deleted.

**Review by anhnv3991 — APPROVED** [review]

**Pull request merged**
