### PR TITLE
feat: add autoware auto msgs depends

### PR DESCRIPTION
**Pull request by taikitanaka3**
# Related Issue
#1

# Related Link
This PR depends on
- #4 
# Description
Add autoware auto msgs from https://github.com/tier4/autoware_auto_msgs.iv

# How to review
Check the following item

- Readme
- Launch file

### CODE REVIEW

**Review by kenji-miyake — APPROVED** [review]
I think you can add this in the PR that needs this dependency but anyway, I'll approve.

**Comment by kenji-miyake** [comment]
@taikitanaka3 Ah, but if possible, you should fix commits and try to pass DCO.

**Comment by taikitanaka3** [comment]
@kenji-miyake 
is it  possible to continue PR using force push? currently it seem pr is closed automatically when using force push

**Comment by taikitanaka3** [comment]
@kenji-miyake 
I opened this PR
https://github.com/autowarefoundation/autoware.universe/pull/63

**Pull request closed without merging**
