### PR TITLE
chore: replace legacy timer

### LINKED ISSUE #120: Fix legacy timer creation
https://github.com/tier4/autoware.iv/pull/2302

image

### PR DESCRIPTION
**Pull request by wep21**
## Related Issue(required)

Closes #120

## Description(required)

replace legacy timer description.

## Review Procedure(required)

confirm both planning simulation and rosbag simulation work.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@wep21 I've tested this with the simulator, but it seems Trajectory is not published. Does it work in your environment?

**Comment by wep21** [comment]
@kenji-miyake I found the description below causes the problem at runtime. (but I have no idea why this causes the problem...)
```
auto on_timer = std::bind(...);
timer_ = rclcpp::create_timer(..., on_timer) 
```
I fixed and rebased them, so could you try it again?

**Comment by wep21** [comment]
@Mergifyio rebase

**Review by kenji-miyake — APPROVED** [review]
I've checked the basic behavior with the simulator.

**Pull request merged**
