### PR TITLE
fix(behavior_velocity_planner): avoid duplicates in intersection module

### PR DESCRIPTION
**Pull request by maxime-clem**
Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>

## Description

The `intersection` module of the `behavior_velocity_planner` outputs very large debug message when crossing multiple intersections. Moreover, the CPU load also greatly increases in that case.

This PR solves this issue by simplifying the `detection_area_lanelets` calculated by function `getObjectiveLanelets()`.
This variable is used to (1) calculate the lanelet IDs to use for collision detection and (2) calculate the debug polygons to highlight in rviz. Originally, the `detection_area_lanelets` was a vector of sequences of lanelets where the sequences could overlap, sharing many common lanelets. This would result in many duplicated IDs (1) and many overlapping polygons (2).
In this PR, the `detection_area_lanelets` is changed to be a vector of lanelets without any duplicate, which simplifies both (1) and (2) without changing the behavior of the module.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@maxime-clem Thank you! I asked @taikitanaka3 to review this PR.

**Comment by taikitanaka3** [comment]
I tested with
image

**Review by taikitanaka3 — APPROVED** [review]
LGTM
I checked with lanelets with loop
image
I checked with right of way
image

**Review by soblin — APPROVED** [review]
using `set` for checking duplicate lanelet looks good !

**Pull request merged**
