### PR TITLE
fix: use transient_local qos for route

### LINKED ISSUE #119: Fix subscriber qos for route
https://github.com/tier4/autoware.iv/pull/2388

image

### PR DESCRIPTION
**Pull request by 1222-takeshi**
## Related Issue(required)
Resolves #119 
## Description(required)
fix subscriber qos for route
## Review Procedure(required)
Make sure that the qos of all route subscribers is set to transient_local.

``` sh
ag "create_subscription<autoware_auto_planning_msgs::msg::HADMapRoute>\(" ./ -A 3
```
## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by 1222-takeshi** [comment]
@wep21 
If there are any omissions, please let me know. :bow:

**Comment by wep21** [comment]
@mitsudome-r This modification has not been merged into upstream, but can I proceed to merge? Or, I have to wait to merge until porting has been done?

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Comment by taikitanaka3** [comment]
@mitsudome-r cc: @1222-takeshi 
I think porting is finished so can I merge now?

**Comment by kenji-miyake** [comment]
@taikitanaka3 I asked mitsudome-san and he said we can start to merge remaining PRs.

**Pull request merged**
