### PR TITLE
fix(autoware_behavior_path_lane_change_module): fix clang-diagnostic-unused-variable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on clang-tidy `clang-diagnostic-unused-variable` error.

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp:952:16: error: unused variable 'route_handler' [clang-diagnostic-unused-variable]
  const auto & route_handler = getRouteHandler();
               ^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp:1065:16: error: unused variable 'route_handler' [clang-diagnostic-unused-variable]
  const auto & route_handler = getRouteHandler();
               ^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp:1224:16: error: unused variable 'route_handler' [clang-diagnostic-unused-variable]
  const auto & route_handler = getRouteHandler();
               ^
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by veqcc** [comment]
@mkquda @rej55 @kosuke55 @maxime-clem @satoshi-ota @shmpwk @TomohitoAndo @tkimura4 @zulfaqar-azmi-t4
Hi

**Review by kosuke55 — APPROVED** [review]
I am not main maintainer but seems ok

**Comment by veqcc** [comment]
@mkquda @rej55 @maxime-clem @satoshi-ota @shmpwk @TomohitoAndo @tkimura4 @zulfaqar-azmi-t4
Hi

**Review by zulfaqar-azmi-t4 — APPROVED** [review]

**Comment by veqcc** [comment]
@zulfaqar-azmi-t4 
Somehow `json-schema-check` didn't run. Do you know why it doesn't run? :pray:

**Pull request merged**
