### PR TITLE
fix(obstacle_stop_planner): use common ego nearest search

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

use the new nearest index search algorithm in obstacle stop planner to deal with edge cases shown in the issue.

## Related links
issue
https://github.com/autowarefoundation/autoware.universe/issues/1581

depends on
https://github.com/autowarefoundation/autoware.universe/pull/1582
https://github.com/tier4/autoware_launch/pull/437

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
No need to modify tier4_planning_launch and planning_launch since the removed parameter is not contained in these laucher's yaml files.

**Review by satoshi-ota — APPROVED** [review]
LGTM

**Comment by satoshi-ota** [comment]
@takayuki5168 Should we merge this PR with https://github.com/tier4/autoware_launch/pull/437 ?

**Comment by takayuki5168** [comment]
@satoshi-ota Yes.
Give me LGTM in these PRs.
https://github.com/tier4/autoware_launch/pull/437
https://github.com/autowarefoundation/autoware.universe/pull/1582

**Comment by takayuki5168** [comment]
I confirmed this PR worked well with tier4's and awf's meta repository.

**Pull request merged**
