### PR TITLE
refactor(object_merger)!: fix namespace and directory structure

### PR DESCRIPTION
**Pull request by technolojin**
## Description

This PR puts headers in the `autoware` namespace.
Part of: https://github.com/autowarefoundation/autoware/issues/4569

Additional works
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468) [list](https://github.com/autowarefoundation/autoware.universe/pull/3606)

## Tests performed
Not applicable.

## Effects on system behavior
Not applicable.

## Interface changes
Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by esteve — CHANGES_REQUESTED** [review]
@technolojin thanks for submitting this PR. Header files must be in `autoware_object_merger`, not `autoware/object_merger`. Also, if they are not needed by downstream packages, they should be moved to `src` to keep them private.

**Comment by technolojin** [comment]
> @technolojin thanks for submitting this PR. Header files must be in `autoware_object_merger`, not `autoware/object_merger`. Also, if they are not needed by downstream packages, they should be moved to `src` to keep them private.

Thank you. Those were my open points during this work. I will implement in that way.

**Comment by technolojin** [comment]
@esteve resolved in https://github.com/autowarefoundation/autoware.universe/pull/7642/commits/0c0139f859f80469e412c52584a43bbd6560de72

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by technolojin** [comment]
@esteve 
1. DCO Issue is resolved.e no
2. header file for the node is moved into `src` https://github.com/autowarefoundation/autoware.universe/pull/7642/commits/35f84fdd9b451bf7f5f10ce08328b1f3cf59a38d

**Comment by technolojin** [comment]
@esteve 
I am waiting your response.

**Review by esteve — APPROVED** [review]
@technolojin I meant moving all the headers, it doesn't seem that there are any downstream packages that depend on these headers, so it's safe to keep them private. But it's optional, so up to you if you want to move them. Thanks for addressing my feedback.

**Pull request merged**
