### PR TITLE
revert(perf_ring_outlier_filter): temporal revert for further investigation

### PR DESCRIPTION
**Pull request by tzhong518**
## Description

This reverts commit e45c1ce8df336aef408650532b0477dd174ae27d.
It reduces computation time of ring_outlier_filter, but also results in missing points for pointpainting.

Part of the concatenated/pointcloud is lost when pointpainting module [filtering the points out of the range](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp#L239-L241), while they actually lie within the range. This leads to the misdetection of the bus, because only half of its pointcloud is input to the network.
- blue points: /sensing/lidar/concatenated/pointcloud
- red points: /perception/object_recognition/detection/pointpainting/output
- blue bounding boxes: /perception/object_recognition/detection/objects
image

After reverting, the pointcloud is correctly accessed and filtered. As a result, the bus is correctly detected.
image

Therefore, it will be reverted for the release of v0.44.0.0, and revisited afterwards.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
cc @VRichardJP @mojomex

**Comment by kminoda** [comment]
@VRichardJP @mojomex Hi, we would like to revert https://github.com/autowarefoundation/autoware.universe/commit/e45c1ce8df336aef408650532b0477dd174ae27d that you've worked on. Although we strongly agree with the motivation behind this commit, unfortunately it turned out that the commit causes a severe degradation in some cases, a mis-perception of a bus being a smaller car for instance. Since the investigation in depth may take some time due to our lack of resources, we see that reverting the commit for now is the best option to minimize the risk on Autoware users. Thus, an investigation on the issue is out of scope of this PR. 

Fixed version of the above PR is appreciated. Thank you for your understanding and your continuous contribution :bow:

**Review by kminoda — APPROVED** [review]
LGTM

**Review by miursh — APPROVED** [review]

**Review by xmfcx — APPROVED** [review]

**Comment by miursh** [comment]
I'm going to share the data to reproduce this issue to ensure the bug fix of the ring outlier filter works fine in the future.

**Comment by miursh** [comment]
This is the test data 
https://drive.google.com/file/d/1vd59I0BmVM1_HCTkb3JmrZbeMCji-X3w/view?usp=sharing

**Pull request merged**
