### PR TITLE
fix(velodyne_monitor): add 20 to temp_hot_*** 

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

- add 20 to temp_hot_***
- update README

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by tkimura4 — APPROVED** [review]
LGTM

**Review by ito-san — APPROVED** [review]
LGTM

**Comment by yn-mrse** [comment]
Can you please provide the background of the 20 degree higher setting in the description section of this PR?
It is preferable to include this information in the README if possible, but at a minimum, the description in the PR will ensure traceability.

**Comment by h-ohta** [comment]
@yn-mrse I fixed PR comment to explain the reason.

**Pull request merged**
