### PR TITLE
refactor(traffic_light_recognition_marker_publisher): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with `autoware`

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by xmfcx — CHANGES_REQUESTED** [review]
https://github.com/autowarefoundation/autoware.universe/blob/7a19e8aa360f7849f871f15d9d971a4aff68739a/common/traffic_light_recognition_marker_publisher/launch/traffic_light_recognition_marker_publisher.launch.xml#L2

This launch file needs to be updated too.

**Comment by esteve** [comment]
@xmfcx I used `chore` because `refactor` is not a valid label, my PRs always failed the `pr-label` check because of that. I've reverted your change.

**Comment by xmfcx** [comment]
Interesting, let me try that again, I'd like to see how it fails.

I've added information on why we should use refactor [here](https://github.com/autowarefoundation/autoware.universe/pull/9302#issuecomment-2488380000).

**Comment by xmfcx** [comment]
It did not fail here:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/11932871094/job/33258732808?pr=9305

Until it fails again, can we go with `refactor`?

**Comment by esteve** [comment]
@xmfcx sure, no problem

**Review by xmfcx — APPROVED** [review]
The tests pass and I see the references are updated correctly. Thanks @esteve .

@tkimura4 @1222-takeshi @shmpwk please review.

Since it's been more than a week since the review was requested, I will merge it tomorrow.

Reference: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/code-owners/#unreviewed-pull-requests

**Review by shmpwk — APPROVED** [review]
LGTM

**Pull request merged**
