### PR TITLE
refactor(cuda_utils): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by knzo25** [comment]
@esteve 
Is there a change in `.github/labeler.yaml` not needed? :pray:

**Comment by knzo25** [comment]
Would `perception/autoware_lidar_apollo_instance_segmentation/CMakeLists.txt` not need a change as well?

**Comment by esteve** [comment]
@knzo25 fixed in e2df6f2f599673aa22be938db6847f78d742c907, thanks. I couldn't find any other package that needed update, is there anywhere else that needs an update? Thanks.

**Comment by esteve** [comment]
@knzo25 could you review this PR again? I've addressed your feedback. Thanks.

**Review by knzo25 — APPROVED** [review]
LGTM

**Comment by esteve** [comment]
@knzo25 thanks

@xmfcx should we wait for @manato and @YoshiRi 's review or do you think this could be merged as is?

**Comment by xmfcx** [comment]
The CI is passing, the main package owner has approved it, I think we can merge as is. Thanks @esteve and @knzo25

**Pull request merged**
