### PR TITLE
fix(tensorrt): update tensorrt code of traffic_light_classifier

### PR DESCRIPTION
**Pull request by xmfcx**
Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>

## Description

Part of: https://github.com/autowarefoundation/autoware.universe/issues/2330

Updating the code to compile with https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ TensorRT version.

We can remove the deprecated code when we update the ansible installation to use native 22.04 cuda.

Updated TensorRT version is `tensorrt-dev_8.5.1.7-1+cuda11.8` for now.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Currently compiles on my machine with`tensorrt-dev_8.5.1.7-1+cuda11.8` from https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/

**Comment by kenji-miyake** [comment]
@xmfcx Thank you for updating the interfaces!
How about labeling these PRs and create an issue for tracking?

**Comment by xmfcx** [comment]
Screenshot from 2022-12-20 00-55-39

I've changed the code to support old and new versions.

Tested for the new TensorRT 8.5.2 version and it works.

Should work for the old version too, the changes are very minimal for this.

**Comment by xmfcx** [comment]
@yukkysaito could you review please? The changes are fairly small.

**Comment by yukkysaito** [comment]
@xmfcx Thank you :+1: 
LGTM
@Mingyu1991 @miursh may i ask you double-check?

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
