### PR TITLE
feat(simple_object_tracker): add_simple_object_tracker

### PR DESCRIPTION
**Pull request by purewater0901**
## Description

This PR includes a simple object tracking module, which just transforms a detected object into a tracked object. This package will be useful when people want to get the non-delayed object in simulation. 

## Notes for reviewers
Check the module to run the scenario simulator by changing the tracking.launch.xml.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
It seems the id required by tracking is not included.

**Comment by yukkysaito** [comment]
I think the role of the tracking component is not being fulfilled.
Does this need to be merged into perception?

**Review by yukkysaito — CHANGES_REQUESTED** [review]
Need to discuss, including whether to merge or not.

**Comment by purewater0901** [comment]
@yukkysaito Let's talk about this package later.

**Comment by purewater0901** [comment]
We decided not to include the simple object tracker, so I'm going to close this PR.

**Pull request closed without merging**
