### PR TITLE
fix(behavior_velocity_planenr): add header on debug path msgs

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

Without header, we can't visualize the debug paths on Rviz.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@TakaHoribe 
Thank you for PR can you also set this param to false by default? I commited without reverting this debug testing
https://github.com/autowarefoundation/autoware.universe/blob/7b94ead19dcb6359d155059ccac8c7e0a32363ac/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml#L19

**Comment by TakaHoribe** [comment]
@taikitanaka3 I'll make another PR.

**Comment by TakaHoribe** [comment]
@taikitanaka3 FYI. https://github.com/autowarefoundation/autoware.universe/pull/1680

**Review by taikitanaka3 — APPROVED** [review]

**Comment by taikitanaka3** [comment]
@TakaHoribe 
I added these two PRs to release note

**Pull request merged**
