### PR TITLE
refactor: update TRT build log

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

This PR updates to use throttle logging while building TRT engine from onnx every 5 seconds.

The target packages are as follows.

- lidar_centerpoint( & pointpainting)
- lidar_apollo_instance_segmentation
- tensorrt_yolo
- tensorrt_yolox
- traffic_light_classifier
- traffic_light_fine_detector
- traffic_light_ssd_fine_detector

Sample usage

```c++
#include <tensorrt_common/logger.hpp>

{
  tensorrt_common::Logger logger;

  // throttle logging every 1 sec
  auto log_thread = logger.log_throttle(nvinfer1::ILogger::Severity::kINFO, "SOME MESSAGE", 1);
  /* SOME OPERATION */
  logger.stop_throttle(log_thread);
}
```

## Tests performed

https://github.com/autowarefoundation/autoware.universe/assets/60615504/0c60e80a-76ed-49c5-8b3e-2ad809ce72ba

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by manato** [comment]
@ktro2828 
Thank you very much for the improvement. The modification to notify users that tensorrt-related operations are in progress looks user-friendly. 
One quick question: It looks you have replaced some `RCLCPP_ERROR` into `tensorrt_common::LOG_ERROR` (like [this](https://github.com/autowarefoundation/autoware.universe/pull/6117/files#diff-8da161af6f87a529a07497080a06b2b26d698da35c323537a23fca7e89d7f33bR68)). Do you have intention regarding this replacement?

**Comment by ktro2828** [comment]
@manato 

> One quick question: It looks you have replaced some RCLCPP_ERROR into tensorrt_common::LOG_ERROR (like [this](https://github.com/autowarefoundation/autoware.universe/pull/6117/files#diff-8da161af6f87a529a07497080a06b2b26d698da35c323537a23fca7e89d7f33bR68)). Do you have intention regarding this replacement?

Thanks your comment. 
Because the classes containing these replacements are not ROS nodes but just TensorRT library classes I think it is better to use TensorRT logging operation.

**Comment by manato** [comment]
@ktro2828 
Thank you for the prompt response.
> 
> > One quick question: It looks you have replaced some RCLCPP_ERROR into tensorrt_common::LOG_ERROR (like [this](https://github.com/autowarefoundation/autoware.universe/pull/6117/files#diff-8da161af6f87a529a07497080a06b2b26d698da35c323537a23fca7e89d7f33bR68)). Do you have intention regarding this replacement?
> 
> Thanks your comment. Because the classes containing these replacements are not ROS nodes but just TensorRT library classes I think it is better to use TensorRT logging operation.

I completely agree with your opinion. Thanks for clarifying.
Besides, I've tested the behavior by `ros2 launch tensorrt_yolox yolox.launch.xml` and confirmed the PR looks working as expected.

**Comment by miursh** [comment]
@ktro2828 
I could not find the message in traffic_light_fine_detector. 
Could you take a look at this?

centerpoint
image

pointpainting
image

apollo
image

yolo
image

yolox
image

traffic_light_classifier
image

traffic_light_fine_detector
image

traffic_light_ssd_fine_detector
image

**Comment by ktro2828** [comment]
@miursh Thanks for your review.

I found missing to update the log output setting in launcher. I added `output="screen"` in https://github.com/autowarefoundation/autoware.universe/pull/6117/commits/a9e7b2d5c9cd81090722d39e38134f3ecdc883bc

- before

Screenshot from 2024-01-25 11-50-14

- after

Screenshot from 2024-01-25 11-44-58

**Review by miursh — APPROVED** [review]
Thanks!
LGTM

**Pull request merged**
