### PR TITLE
feat(simple_planning_simulator): add delay model of velocity and steering

### PR DESCRIPTION
**Pull request by kyoichi-sugahara**
## Related Issue(required)
https://github.com/autowarefoundation/autoware.universe/issues/236

## Description(required)

Added delay model of velocity and steer wchich is used in simple planning simulator

## Review Procedure(required)

change the param to `DELAY_STEER_VEL` in the file below
https://github.com/tier4/lexus_description.iv/blob/tier4/universe/config/simulator_model.param.yaml#L5

and excute command below
`ros2 launch autoware_launch planning_simulator.launch.xml map_path:=path_to_map vehicle_model:=lexus sensor_model:=aip_xx1`

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by takayuki5168** [comment]
Is this work in progress?

**Comment by kyoichi-sugahara** [comment]
forgot to open... thanks!

**Comment by takayuki5168** [comment]
For proj.eva to sync with this PR, we have to update [this param](https://github.com/tier4/ymc_golfcart_proto2_description.iv/blob/81e749bdd6b6b2b97b237d31492e332bfaa53142/config/simulator_model.param.yaml#L27), but .iv and .universe use the same branch (`main`) of ymc_golfcart_proto2_description.iv.
Now I'm wondering if creating branch of ymc_golfcart_proto2_description.iv for universe is good or not :thinking:

**Comment by takayuki5168** [comment]
[This](https://github.com/tier4/gsm8_description/pull/8/files) is a universe porting of gsm8_description (only for simple planning simulator).
Like this, we have to update not only vehicle model type but also some other params. So now I'm sure it's better to make a universe branch for ymc_golfcart_proto2_description.iv.

**Comment by takayuki5168** [comment]
@kyoichi-sugahara What do you think? If you agree, could you make a PR of ymc_golfcart_proto2_description.iv and proj.eva as well so that this PR's simple planning simulator will work with proj.eva:tier4/universe.

**Comment by taikitanaka3** [comment]
@takayuki5168 
I think it would be better to update model like taxi type vehicle description. 
note the closed production name shouldn't be on this public PR I think.

**Comment by kyoichi-sugahara** [comment]
@takayuki5168 
your idea is coming from `main` branch of ymc_golfcart_proto2_description.iv will be used from `main` of proj.eva?
I agree with your opinion so i will
- [ ] make new branch and update param in ymc_golfcart_proto2_description.iv
- [ ] make PR in proj.eva:tier4/universe so that simple planning simulator will work with delay model

**Comment by takayuki5168** [comment]
@kyoichi-sugahara Great.

> note the closed production name shouldn't be on this public PR I think.(It's inconvenient though)
(Let's remove this PR's comments that are related to Tanaka-san's comment, when this PR will be merged)

**Comment by taikitanaka3** [comment]
working nicely

DELAY_STEER_VEL
image
IDEAL_STEER_VEL
image

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Pull request merged**
