### PR TITLE
fix(system_error_monitor): fix shadowVariable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck shadowVariable warnings
```
system/system_error_monitor/src/system_error_monitor_core.cpp:291:18: style: Local variable 'param_key' shadows outer variable [shadowVariable]
    const auto & param_key = split_names.at(1);
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
I thought about using "param_key" all the time, but I changed the variable name because I thought it would be better not to use it all the time semantically.

**Comment by veqcc** [comment]
> I thought about using "param_key" all the time, but I changed the variable name because I thought it would be better not to use it all the time semantically.

Then, how about changing the first `param_key` from
```
  const auto param_key = std::string("required_modules.") + key;
  const uint64_t depth = 3;
  const auto param_names = this->list_parameters({param_key}, depth).names;
  if (param_names.empty()) {
    throw std::runtime_error(fmt::format("no parameter found: {}", param_key));
  }
```
to
```
  const uint64_t depth = 3;
  const auto param_names = this->list_parameters({std::string(required_modules.) + "key"}, depth).names;
  if (param_names.empty()) {
    throw std::runtime_error(fmt::format("no parameter found: required_modules.{}", key));
  }
```

**Comment by kobayu858** [comment]
I have corrected the above advice as advised above.

**Review by veqcc — APPROVED** [review]

**Review by ito-san — APPROVED** [review]
LGTM

**Pull request merged**
