### PR TITLE
fix(ar_tag_based_localizer): added small changes

### PR DESCRIPTION
**Pull request by SakodaShintaro**
## Description

Multiple small changes added.

* Changed Qos for the input image topic from `reliable` to `best_effort`.
* Changed to dynamically scale covariance according to recognition distance.
* Changed `camera_frame_` to be taken from the received image topic instead of keeping it as a member variable
* Added the sample simulation data from AWSIM.

### for deault Autoware (i.e. `pose_source:=ndt`)
- [x] logging_simulator (sample rosbag)
- [x] driving_log_replayer (sample rosbag)
- [x] AWSIM

### for ar_tag_based_localizer (`pose_source:=artag`)
- [x] logging_simulator (sample data 1 / Real world data)
- [x] logging_simulator (sample data 2 / AWSIM)

## Evaluation Result

|Method|Mean Error[m]|
|:--------:|:------------------:|
|Odometry Only|2.766|
|Odometry + AR-Tag|0.627|
|Odometry + NDT(Default Autoware)|0.053|

## Effects on system behavior

If AR tag-based self-location estimation is used, the behavior changes slightly. Otherwise, there is no change.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by KYabuuchi** [comment]
Thank you for creating the PR!  I have tried your new rosbag. 
The position is corrected each time an AR marker is detected, so I think it is functioning as intended.

https://github.com/autowarefoundation/autoware.universe/assets/24854875/b9b04a18-f6ba-4001-9f18-582bba6c2384

**Comment by SakodaShintaro** [comment]
@KYabuuchi 
Thanks for your review!
The upper limit was revised to 13 m. https://github.com/autowarefoundation/autoware.universe/pull/4885/commits/0d83680a41552c868a899b6a3b43a1e936da1fef
With this change, there is now less lateral shift except for the last tag.

In fact, it would be better if the AR tag placement could be improved to observe within 10 m. In AWSIM, the vehicle is a full-size car, so the AR tag is placed about 12~13 m away from the car.

In the use case assumed by AR tag-based self-localization, such as a small car, it would be possible to place it with such constraints.

**Review by KYabuuchi — APPROVED** [review]
LGTM :ok_hand: 

Also, I have confirmed that excessive position correction has been improved due to changes in the detection limit.

**Review by Motsu-san — APPROVED** [review]
LGTM

**Pull request merged**
