### PR TITLE
feat(obstacle_stop_planner): add hold stop margin distance

### PR DESCRIPTION
**Pull request by satoshi-ota**
Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>

## Description

Now, this ego always try to stop at the stop position by re-starting (re-approach) even if the ego is stopped near the planned stop position in the module. On the other hand, if the stopping performance of the vehicle is poor (e.g. it cannot stop for one meter) and once it starts traveling, there is a possibility that the vehicle may over the stop position, in which case there may be a issue for the vehicle to continue stopping on the spot, if the distance between the ego and stop position is closer than threshold.

So, in this PR, I fixed following points.

add new param hold_stop_margin_distance (default: 0.0 [m])
if the following condisions are satisfied, the ego keep stopping at current position.
condition 1. the ego has stopped
condition 2. the distance between the ego and stop point is shorter than hold_stop_margin_distance

test perform (hold_stop_margin_distance = 2.0 [m])

https://user-images.githubusercontent.com/44889564/180969741-03a23d9e-ad62-47c2-896c-4d7b771b3d08.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by h-ohta** [comment]
@satoshi-ota How Can I check the distance between ego and obstacle? Is some information published?

**Comment by satoshi-ota** [comment]
> @satoshi-ota How Can I check the distance between ego and obstacle? Is some information published?

@h-ohta Sorry for late reply. I checked the distance by using rviz measure or tempolary embedded debug code.

Unfortunatly, there is no infomation about the distance between the ego and collision obstacle now. But this module has and outputs debug values array, so I can add the distance infomation and output as debug message.

**Comment by satoshi-ota** [comment]
@h-ohta I added the infomation about the distance between the ego and obstacle as a debug message. Please check that in plotjuggler.

- topic name: /planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop/debug_values
- data: data.4 is the infomation about the distance between the ego and collision obstacle

Screenshot from 2022-07-29 08-55-05

**Comment by satoshi-ota** [comment]
@TakaHoribe I confirmed that there is no critical degradation in this PR by evaluator.

https://evaluation.tier4.jp/evaluation/reports/49ea6a0f-b177-50c8-95ed-1ba2a72ef8a5?project_id=prd_jt

**Comment by satoshi-ota** [comment]
@TakaHoribe @h-ohta I fixed some bugs and re-run test. Test result is similar to baseline.

This PR: https://evaluation.tier4.jp/evaluation/reports/d9b53322-3336-5f2a-8e91-428cc2d14e59?project_id=prd_jt (702/768)
Baseline: https://evaluation.tier4.jp/evaluation/reports/ddd34bcc-0fb6-5ea8-8844-0a4961745f5f?project_id=prd_jt (700/768)

**Review by TakaHoribe — APPROVED** [review]
LGTM
image

**Pull request merged**
