### PR TITLE
fix: add_ros_test to add_launch_test

### PR DESCRIPTION
**Pull request by kminoda**
## Description

add_ros_test did NOT work on GitHub Actions while add_launch_test does.

For example, see this CI result in the previous PR, where the launch test does not appear: https://github.com/autowarefoundation/autoware.universe/actions/runs/6655105668/job/18084616669?pr=5421

## Tests performed

The launch test in the CI is properly executed.

## Effects on system behavior

Not applicable

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
@Motsu-san Hi, would you review this PR?

**Comment by YamatoAndo** [comment]
@kminoda Please fix [ndt_scan_matcher](https://github.com/autowarefoundation/autoware.universe/blob/main/localization/ndt_scan_matcher/CMakeLists.txt#L40) as well

**Comment by kminoda** [comment]
@YamatoAndo Thank you, done.

**Review by YamatoAndo — APPROVED** [review]

**Comment by kminoda** [comment]
@Motsu-san @RyuYamamoto @mitsudome-r Hi, would you review this PR?

**Review by RyuYamamoto — APPROVED** [review]

**Pull request merged**
