### PR TITLE
fix(autoware_ground_segmentation): fix unreadVariable

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck unreadVariable warnings.

```
perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp:470:27: style: Variable 'points_distance' is assigned a value that is never used. [unreadVariable]
    float points_distance = 0.0f;
                          ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by badai-nguyen** [comment]
@kobayu858 Thank you for your PR. 
Q: Did you mean `points_distance` is unread variable? I think it is used at  [here](https://github.com/autowarefoundation/autoware.universe/blob/9a7f8862e2aa3c2918372a627286147154dfdf09/perception/ground_segmentation/src/scan_ground_filter/node.cpp#L491-L502)?

**Comment by kobayu858** [comment]
@badai-nguyen 

Thank you for your question.

It is a variable scope issue. The original code is declaring variables outside of the second for loop and not read within the scope of the first for loop, which is why the warning is occurring.

Therefore, I put the variable declaration inside the second for loop.
By doing this, the cppcheck warning was eliminated.

**Comment by badai-nguyen** [comment]
> @badai-nguyen
> 
> Thank you for your question.
> 
> It is a variable scope issue. The original code is declaring variables outside of the second for loop and not read within the scope of the first for loop, which is why the warning is occurring.
> 
> Therefore, I put the variable declaration inside the second for loop. By doing this, the cppcheck warning was eliminated.

@kobayu858 Thank you for your explanition and fixing.

**Review by badai-nguyen — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
