### PR TITLE
fix(diagnostic_graph_utils): fix clang-diagnostic-delete-abstract-non-virtual-dtor

### PR DESCRIPTION
**Pull request by veqcc**
## Description

This fixes clang-tidy error
```
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95:2: error: delete called on non-final 'diagnostic_graph_utils::DiagLeaf' that has virtual functions but non-virtual destructor [clang-diagnostic-delete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:396:4: note: in instantiation of member function 'std::default_delete<diagnostic_graph_utils::DiagLeaf>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
/home/veqcc/work/autoware/src/universe/autoware.universe/system/diagnostic_graph_utils/src/lib/graph.cpp:48:56: note: in instantiation of member function 'std::unique_ptr<diagnostic_graph_utils::DiagLeaf>::~unique_ptr' requested here
  for (const auto & diag : msg.diags) diags_.push_back(std::make_unique<DiagLeaf>(diag));
                                                       ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95:2: error: delete called on non-final 'diagnostic_graph_utils::DiagNode' that has virtual functions but non-virtual destructor [clang-diagnostic-delete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:396:4: note: in instantiation of member function 'std::default_delete<diagnostic_graph_utils::DiagNode>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
/home/veqcc/work/autoware/src/universe/autoware.universe/system/diagnostic_graph_utils/src/lib/graph.cpp:47:56: note: in instantiation of member function 'std::unique_ptr<diagnostic_graph_utils::DiagNode>::~unique_ptr' requested here
  for (const auto & node : msg.nodes) nodes_.push_back(std::make_unique<DiagNode>(node));
                                                       ^
2 errors generated.
```

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by veqcc** [comment]
@isamu-takagi 
Hi

**Review by isamu-takagi — COMMENTED** [review]
@veqcc Could you please add a virtual destructor to the base class `DiagUnit`, instead?

**Comment by veqcc** [comment]
@isamu-takagi 
> @veqcc Could you please add a virtual destructor to the base class DiagUnit, instead?

OK, completed in https://github.com/autowarefoundation/autoware.universe/pull/9431/commits/1f9170681367dcdb9a5a491794ff75698f4511fc

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
