### PR TITLE
fix(euclidean_cluster): keep pointcloud resolution in long-range for Euclidean cluster

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

This PR to reflect a suggestion for #2754 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@badai-nguyen May I ask a little more background on the PR?
What kind of problems did you encounter?

**Comment by badai-nguyen** [comment]
> @badai-nguyen May I ask a little more background on the PR? What kind of problems did you encounter?

@yukkysaito I am sorry for forgetting open discussion for this beforehand. 
[Here is background](https://github.com/autowarefoundation/autoware.universe/issues/2754) why I made this PR. Could you give me your opinion about that ?

**Comment by yukkysaito** [comment]
@badai-nguyen Thank you. LGTM 👍 
In the future, it may be possible to create an outlier filter in polar coordinates.

Also, can you update this figure?
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/node-diagram/

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
