### PR TITLE
chore(ground_segmentation): rename topic and node

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

- Rename to more reasonable topic name of ground_segmentation pipeline.

## Related Link

[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1709522148776059?thread_ts=1709520926.605739&cid=C03S84LDJGG)

## Tests performed

-  I confirmed by `loggging-simulator`:
- The node and topic name have been updated:  
image

- Ground_segmentation worked and output result as before. 
image

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kminoda — COMMENTED** [review]
Thank you for your PR. Could you also fix synchronized_grid_map_fusion.md as well?

image

**Comment by badai-nguyen** [comment]
@kminoda I fied at https://github.com/autowarefoundation/autoware.universe/pull/6536/commits/3a0848fe55e0fbb4afa1004a4eda91059f610425

**Review by miursh — APPROVED** [review]
LGTM
but https://github.com/tier4/aip_launcher/blob/tier4/universe/aip_x1_launch/launch/topic_state_monitor.launch.py#L158 and https://github.com/tier4/aip_launcher/blob/tier4/universe/aip_x1_launch/launch/topic_state_monitor.launch.xml#L79 need to be modified as well

**Comment by badai-nguyen** [comment]
> LGTM but https://github.com/tier4/aip_launcher/blob/tier4/universe/aip_x1_launch/launch/topic_state_monitor.launch.py#L158 and https://github.com/tier4/aip_launcher/blob/tier4/universe/aip_x1_launch/launch/topic_state_monitor.launch.xml#L79 need to be modified as well

@miursh 
thank you for your comment. 
I create PR for that here: https://github.com/tier4/aip_launcher/pull/214

**Comment by badai-nguyen** [comment]
@YoshiRi @yukkysaito Could you approve this PR as code owner of `probabilistic_occupancy_grid_map` package :bow:

**Review by YoshiRi — APPROVED** [review]
LGTM

**Pull request merged**
