### PR TITLE
refactor(pose_initializer)!: prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by a-maumau**
## Description
This PR will add an `autoware_` prefix to `pose_initializer` package.

Also directory structure is changed to fit https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#include-and-src

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Checked that it works with the Autoware's sample ROS bag.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by SakodaShintaro** [comment]
@a-maumau 
One of the CI checks failed: 'pre-commit-optional'.
Can you please take a look?

**Comment by a-maumau** [comment]
@SakodaShintaro I fixed link error in the `README.md`.

**Review by SakodaShintaro — APPROVED** [review]
I have confirmed that

* logging_simulator
* AWSIM (multi time initialpose estimation)
* planning_simulator

and I checked

- **Directory Name**
  - [x] Add `autoware_` as a prefix to the directory name.

- **packages.xml**
  - [x] Add `autoware_` to the `name` element.

- **CMakeLists.txt**
  - [x] Change the `project` name to `autoware_***`.
  - [x] Add `autoware::` to `PLUGIN`.

- **Header Files (.hpp)**
  - [x] Add `autoware::` to `namespace`.

- **Source Files (.cpp)**
  - [x] Add `autoware::` inside `RCLCPP_COMPONENTS_REGISTER_NODE`.

- **Launch Files**
  - [x] Add `autoware_` before `find-pkg-share`.
  - [x] Change `node pkg="<pkgname>"` to `autoware_<pkgname>`.

- **Verification Points**
  - [x] Search `find-pkg-share` in autoware
  - [x] Check README file (especially json schema)
  - [x] Pay attention to complex cases like `sensor_launch` as seen in `gnss_poser`

LGTM

**Comment by SakodaShintaro** [comment]
@KeisukeShima @taikitanaka3 @TakaHoribe @takayuki5168 @tkimura4 
Can anyone review this pull request about "simulator.launch.xml"? The operation of logging_simulator, AWSIM and planning_simulator has been confirmed.

**Review by takayuki5168 — APPROVED** [review]
LGTM for simulator.launch.xml

**Pull request merged**
