### PR TITLE
fix(autoware_object_velocity_splitter): fix funcArgNamesDifferent

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on cppcheck funcArgNamesDifferent warnings

```
perception/object_velocity_splitter/src/object_velocity_splitter_node.cpp:68:82: style: inconclusive: Function 'onObjects' argument 1 names different: declaration 'msg' definition 'objects_data_'. [funcArgNamesDifferent]
void ObjectVelocitySplitterNode::onObjects(const DetectedObjects::ConstSharedPtr objects_data_)
                                                                                 ^
```
## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by veqcc** [comment]
@kokosabu @scepter914 @miursh @YoshiRi 
Using `objects_data_` as a parameter, not as a global variable, seems not ideal.

And the variable declared in header seems not be used
```
  // Data Buffer
  DetectedObjects::ConstSharedPtr objects_data_{};
```

Is it correct?

**Comment by kobayu858** [comment]
@scepter914 @miursh @YoshiRi 

Please confirm the PR. Thank you very much.

**Comment by yukkysaito** [comment]
It appears that objects_data_ is not used in this change. objects_data_ is likely a typo. It would be better to align the code with msg instead of objects_data_.

**Comment by veqcc** [comment]
> It appears that objects_data_ is not used in this change. objects_data_ is likely a typo. It would be better to align the code with msg instead of objects_data_.

@scepter914  @miursh @YoshiRi
Please check whether `objects_data_` is really a typo. Thank you.

@kobayu858 
If it is a typo, then change the parameter/argument name and delete `objects_data_` declaration from hpp
If not, please follow the maintainer's instructions.

**Comment by scepter914** [comment]
> It appears that objects_data_ is not used in this change. objects_data_ is likely a typo. It would be better to align the code with msg instead of objects_data_.

It seems typo, so would you align to msg?

**Comment by kobayu858** [comment]
Thanks for the discussion.

I removed objects_data_ and unified it with msg.

**Review by veqcc — APPROVED** [review]

**Review by YoshiRi — APPROVED** [review]
LGTM

**Pull request merged**
