### PR TITLE
refactor(traffic_light_*)!: add package name prefix of autoware_

### PR DESCRIPTION
**Pull request by technolojin**
## Description
This PR adds the autoware_ prefix to the package name.

- traffic_light_fine_detector
- traffic_light_multi_camera_fusion
- traffic_light_occlusion_predictor
- traffic_light_classifier
- traffic_light_map_based_detector
- traffic_light_visualization

Changes are as following.
1. Folder name (appears as file renaming)
2. Package names in `CMakeLists.txt`, `package.xml`
3. `README.md`
4. Launch files `$(find-pkg-share ...)`
5. `.github/CODEOWNERS`

This PR do not contains any logic change.

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

### Related PRs
- webauto-ci https://github.com/tier4/pilot-auto/pull/868
- jetson_launcher (TIER IV INTERNAL) - in a branch
https://github.com/tier4/jetson_launcher/tree/refactor/autoware-prefix
- autoware_launcher, aip_laucher... : no changes (abstracted in tier4_perception_launch)

## How was this PR tested?
Tested in a local recompute environment and the [TIER IV Cloud](https://evaluation.tier4.jp/evaluation/reports/c84ff928-c989-55b3-8f1b-0c7478d6b3c5?project_id=prd_jt) environment.

## Notes for reviewers
None.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by YoshiRi — APPROVED** [review]
Thanks! Could you fix conflict?

**Comment by miursh** [comment]
@technolojin 
Could you please add links to the related links section for PRs to launchers (i.e. jetson_launch, autoware_launch, etc) using these packages

**Comment by technolojin** [comment]
@miursh 

aip_launcher 
https://github.com/tier4/aip_launcher/pull/267

jetson_launcher (TIER IV INTERNAL) - in a branch
https://github.com/tier4/jetson_launcher/tree/refactor/autoware-prefix

autoware_launcher : no changes

**Review by miursh — APPROVED** [review]

**Pull request merged**
