### PR TITLE
refactor(run_out): remove unused parameter

### PR DESCRIPTION
**Pull request by TomohitoAndo**
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>

## Description

Removed unused parameter.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by 0x126 — APPROVED** [review]
LGTM

**Comment by TomohitoAndo** [comment]
@taikitanaka3 
could you review this PR? 
I can't merge without code owner review. :pleading_face:

**Comment by taikitanaka3** [comment]
@TomohitoAndo 
I didn't follow conversation but you don't use assumption of pedestrian velocity anymore?

**Comment by TomohitoAndo** [comment]
@taikitanaka3 
Parameters for that assumption are moved to here, so parameters removed in this PR are no longer needed.
https://github.com/autowarefoundation/autoware.universe/blob/ccdb1121d987ecc1dbf252ba5424c203417b1f5a/launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/run_out.param.yaml#L20-L21

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Comment by TomohitoAndo** [comment]
ah, it seems review from @TakaHoribe is necessary...? :thinking: 
image

**Review by TakaHoribe — APPROVED** [review]
GMT

**Pull request merged**
