### PR TITLE
fix(lidar_centerpoint): fixed the lidar_centerpoint related packages for their use without installing symlinks

### PR DESCRIPTION
**Pull request by knzo25**
## Description
When compiling this package without the symlink option, the cuda library is not installed.

Before this PR:
```
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to lidar_centerpoint


find . -name 'libcenterpoint_cuda_lib.so'
>>> ./build/lidar_centerpoint/libcenterpoint_cuda_lib.so


ldd ./install/lidar_centerpoint/lib/libcenterpoint_lib.so | grep 'libcenterpoint_cuda_lib.so'
	libcenterpoint_cuda_lib.so => not found
```

After this PR:
```
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to lidar_centerpoint

 find . -name 'libcenterpoint_cuda_lib.so'
./build/lidar_centerpoint/libcenterpoint_cuda_lib.so
./install/lidar_centerpoint/lib/libcenterpoint_cuda_lib.so

ldd ./install/lidar_centerpoint/lib/libcenterpoint_lib.so | grep 'libcenterpoint_cuda_lib.so'
	libcenterpoint_cuda_lib.so => /***/install/lidar_centerpoint/lib/libcenterpoint_cuda_lib.so (0x00007fe81d9d0000)
```

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@yukke42 Can you check this PR?

**Comment by yukke42** [comment]
Related Issue: <https://github.com/autowarefoundation/autoware.universe/issues/1256>

**Comment by yukke42** [comment]
I clean the install/build/log directory and ccache files, but cuda library cannot be linked yet ..., it may be the problem of my environment ...

```
~/ghq/github.com/tier4/pilot-auto.xx1.pr tier4/universe 1m 40s
❯ find . -name 'libcenterpoint_cuda_lib.so'
./install/lidar_centerpoint/lib/libcenterpoint_cuda_lib.so
./build/lidar_centerpoint/libcenterpoint_cuda_lib.so

~/ghq/github.com/tier4/pilot-auto.xx1.pr tier4/universe
❯ ldd ./install/lidar_centerpoint/lib/libcenterpoint_lib.so | grep 'libcenterpoint_cuda_lib.so'
	libcenterpoint_cuda_lib.so => not found
```

**Comment by knzo25** [comment]
I forgot to add it into the description but we need to source , or otherwise the library path is not added

bu default cmake is stripping the rpath and we rely on the ldd library path

**Comment by yukke42** [comment]
> I forgot to add it into the description but we need to source , or otherwise the library path is not added
> 
> bu default cmake is stripping the rpath and we rely on the ldd library path

ha ha ha... what a simple mistake.

```
❯ ldd ./install/lidar_centerpoint/lib/libcenterpoint_lib.so | grep 'libcenterpoint_cuda_lib.so'
	libcenterpoint_cuda_lib.so => /home/yusuke/ghq/github.com/tier4/pilot-auto.xx1.pr/install/lidar_centerpoint/lib/libcenterpoint_cuda_lib.so (0x00007f205f8cf000)

```

**Review by yukke42 — APPROVED** [review]

**Comment by knzo25** [comment]
I actually forgot it too and did not understand why there were so many ldd errors :laughing:

**Comment by twbabyduck** [comment]
Dear @knzo25 @yukke42,
I can confirm there was an issue found when users attempted to test CenterPoint inside a docker container, which has been fixed in this PR.

Below attached the test result.
screenshoot

**Pull request merged**
