### PR TITLE
refactor(autoware_pointcloud_preprocessor): rework lanelet2 map filter parameters

### PR DESCRIPTION
**Pull request by vividf**
## Description
This PR includes the following changes
1. Remove the default parameters for the lanelet2 map filter node. 
2. Add parameter, launch file, and parameters schema for the node. 
3. Change the name `nodelet` to `node`.
## Related links

**Parent Issue:**

- Link

## How was this PR tested?
`ros2 launch autoware_pointcloud_preprocessor lanelet2_map_filter_node.launch.xml`
## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by knzo25 — APPROVED** [review]
LGTM

**Review by amadeuszsz — CHANGES_REQUESTED** [review]
Please consider boundaries for numeric / integer parameters. This comment apply for rest of pointcloud preprocessor PRs as well

**Comment by vividf** [comment]
@amadeuszsz Thanks, add in https://github.com/autowarefoundation/autoware.universe/pull/8491/commits/8b57823d0f06d8ecbdf6657893ab6ed3ed310958

**Review by amadeuszsz — APPROVED** [review]
LGTM

**Pull request merged**
