### PR TITLE
feat(system_error_monitor): add heartbeat timeout for subscribed data

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

The system_error_monitor can't decide emergency when any of required topics are not be able to subscribed due to process death.
For example...
1. autoware_state is `WAITING_FOR_ROUTE` and current_gate_mode is `AUTO`
2. isInNoFaultCondition() is true, so some error diags are ignored
3. Now, kill ad_service_state_monitor and autoware_state msg is no longer updated
4. item 2 is stil true...

To avoid such a situation, I'll add heartbeat timeout to required topics.
Timeout parameter is set to 1 second as default and we can change from launch.xml.

## Tests performed

- Launch planning simulator and set start and goal
- kill required topics publisher with the command `ps -aux | grep ad_service_state_monitor | awk '{print $2}' | xargs kill`
- publish `/system/emergency/hazard_status` as timeout like below

```
---
stamp:
  sec: 1659433471
  nanosec: 185921844
status:
  level: 3
  emergency: true
  emergency_holding: false
  diag_no_fault: []
  diag_safe_fault: []
  diag_latent_fault: []
  diag_single_point_fault:
  - level: "\x02"
    name: system_error_monitor/input_data_timeout
    message: ''
    hardware_id: system_error_monitor
    values: []
```

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by tkimura4 — APPROVED** [review]
I confirmed that the error occured in the `/system/emergency/hazard_status` properly when the ad_state_service_monitor process was died after merging this PR. 
image

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by yukkysaito** [comment]
Can you update readme?

**Comment by h-ohta** [comment]
@yukkysaito This way? Could you tell me what kind of contents should I write in README?

**Comment by yukkysaito** [comment]
@h-ohta [here](https://github.com/autowarefoundation/autoware.universe/blob/25f822b49a6d78597475963b5f72790a4b6a9901/system/system_error_monitor/README.md) :pray: 
pls update UML if necessary

**Comment by h-ohta** [comment]
@yukkysaito updated
https://github.com/autowarefoundation/autoware.universe/pull/1501/commits/4e90ffcb24d5a2943b0fb99e579e6c42bede6673

**Comment by yukkysaito** [comment]
@h-ohta No need to update UML?

**Comment by h-ohta** [comment]
@yukkysaito yes. Do you have any ideas?

**Comment by yukkysaito** [comment]
@h-ohta ok. you certainly don't need an update.

**Comment by h-ohta** [comment]
@yukkysaito Can I merge this PR?

**Comment by yukkysaito** [comment]
@yn-mrse @0x126 pls check for product :pray:

**Review by 0x126 — APPROVED** [review]
LGTM

**Comment by yn-mrse** [comment]
@h-ohta cc. @yukkysaito 
Wouldn't it be possible to avoid using HeartbeatChecker and put monitoring function equivalent to the HeatbeatChecker implementation in each callback of this node?

HeartbeatChecker is useful especially if the usage is limited to monitoring of external topics that are not used inside the node.

However, if you use HeartbeatChecker to monitor the input topic used inside the node like this usage, a problem will occur.
There will be two subscribers per topic, and there is a risk that it will not be possible to detect that one of the subscribers has stopped.

**Comment by h-ohta** [comment]
@yn-mrse Thank you. I think so too. I'll fix by keeping only timestamp.

**Comment by h-ohta** [comment]
@yn-mrse @tkimura4 @0x126 @yukkysaito 
I change some implementation. Could you re-review? Thank you.

**Comment by yukkysaito** [comment]
Wouldn't it be better to use the time received rather than the timestamp in the header?
When looking at the timestamp in the header, I feel that data is coming at regular intervals, but if there is a large processing delay, an error will occur.

If there is a large delay, I think some kind of error detection is necessary. but I don't think it is necessary to look at the delay because the heartbeat is a function to check if the node is still alive or not.

**Comment by h-ohta** [comment]
@yukkysaito Thank you for your comment. Actullay all we have to do is to check the heartbeat of each topics. I'll fix it.

**Review by tkimura4 — APPROVED** [review]
The code changes of the PR look fine and it seems to work well.

(After the commands `ps -aux | grep ad_service_state_monitor | awk '{print $2}' | xargs kill
`)
image

**Comment by h-ohta** [comment]
@0x126 @yn-mrse @yukkysaito ping

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by yn-mrse — APPROVED** [review]
LGTM!

**Pull request merged**
