### PR TITLE
fix(behavior_velocity_planner): fix misc concurrency issues

### LINKED ISSUE #2706: Misc concurrency issues in `behavior_velocity_planner`
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Similar to https://github.com/autowarefoundation/autoware.universe/issues/2495, I have found several concurrency issues in [src/universe/autoware.universe/planning/behavior_velocity_planner/src/node.cpp](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/src/node.cpp):
- `BehaviorVelocityPlannerNode::onParam`: missing mutex lock for `planner_data_`
- `BehaviorVelocityPlannerNode::onExternalVelocityLimit`: missing mutex lock for `planner_data_`
- `BehaviorVelocityPlannerNode::onTrigger`: could make use of `std::lock_guard` instead of manually locking/unlocking the mutex. Also, it suffers from the same issue described in https://github.com/autowarefoundation/autoware.universe/issues/2495: making a shallow copy of `planner_data_` does not solve concurrency problems: when we copy `planner_data_`, we duplicate the member pointers, not pointed data. As a consequence, the "copied" `planner_data` actually points to the same data than `planner_data_`, and concurrent read/write may occur.

### Expected behavior

No concurrent access of protected data.

### Actual behavior

Concurrent access of protected data.

### Steps to reproduce

N/A

### Versions

_No response_

### Possible causes

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by VRichardJP**
Signed-off-by: Vincent Richard <richard-v@macnica.co.jp>

## Description

Fix #2706

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by soblin** [comment]
@VRichardJP Thanks for your PR and sorry for my late response :)
For the most part I agree with this change:

Now behavior_velocity_planner assigns different callback groups to each topic, each spinner thread (of type MutuallyExclusive) run in parallel so we have to lock/unlock the `planner_data_` in each callback if it has access to `planner_data_` as you pointed out. Using RAII style locking in `onTrajectory` is also a good for avoiding careless mistake.

I think the lock in `onParam` is unnecessary because actually this function is not a callback but is just used in the constructor only once. I'm sure this additional lock does not have any side effects like dead locking, so can you replace it with some comment ?

**Comment by VRichardJP** [comment]
@soblin I overlooked the `onParam`. Indeed the mutex lock is not necessary, but I added a memo as you suggested in case someone would make it a callback.

**Comment by soblin** [comment]
@VRichardJP thanks, I'll approve this.

**Review by soblin — APPROVED** [review]
LGTM

**Pull request merged**
