### PR TITLE
feat(mission_planner): add reroute interface for api

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Add reroute interface for api.
https://github.com/autowarefoundation/autoware/issues/3406

## Tests performed

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]

**Review by takayuki5168 — APPROVED** [review]

**Comment by kosuke55** [comment]
@kenji-miyake @yabuta @tkhmy 
Could you please check this as a code owner of `component_interface_specs`?

**Comment by kenji-miyake** [comment]
@kosuke55 Saito-san will review it. I'll update the codeowner of component_interface_specs.

**Comment by kosuke55** [comment]
@yukkysaito  please check this PR:pray:

**Comment by yukkysaito** [comment]
@kosuke55 @isamu-takagi Could you please resolve conflicts?

**Comment by kosuke55** [comment]
@yukkysaito sorry, I fixed conficts.

**Comment by yukkysaito** [comment]
@mitsudome-r We need a little more discussion on the API side, don't we?

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
