### PR TITLE
feat(dummy_perception_publisher): publish object with acc

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

publish dummy object with designated acceleration

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

https://user-images.githubusercontent.com/20228327/189957137-1ab25ab8-08e0-4b00-a2db-d44f3e8e5afe.mp4

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@takayuki5168 can you add min-max range for velocity?

**Comment by takayuki5168** [comment]
@yukkysaito DONE

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
cc @soblin @kyoichi-sugahara

**Pull request merged**
