### PR TITLE
refactor(lidar_transfusion)!: fix namespace and directory structure

### PR DESCRIPTION
**Pull request by MasatoSaeki**
## Description
This PR puts headers in the `autoware` namespace.

Additional works
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468)   [LIST](https://github.com/autowarefoundation/autoware.universe/pull/3606)

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Tested in a local recompute environment.
And also tested `colcon test`. results is below.
<details>
<code>
<pre>

$ colcon test --merge-install --packages-select autoware_lidar_transfusion --event-handlers console_cohesion+
Starting >>> autoware_lidar_transfusion
--- output: autoware_lidar_transfusion
UpdateCTestConfiguration  from :/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/CTestConfiguration.ini
Parse Config file:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/CTestConfiguration.ini
   Site: dpc2403005
   Build name: (empty)
 Add coverage exclude regular expressions.
Create new tag: 20240712-1112 - Experimental
UpdateCTestConfiguration  from :/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/CTestConfiguration.ini
Parse Config file:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/CTestConfiguration.ini
Test project /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: test_detection_class_remapper

1: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_detection_class_remapper.gtest.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_cmake_gtest/test_detection_class_remapper.txt" "--command" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_detection_class_remapper" "--gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_detection_class_remapper.gtest.xml"
1: Test timeout computed to be: 60
1: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion':
1:  - /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_detection_class_remapper --gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_detection_class_remapper.gtest.xml
1: [==========] Running 1 test from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 1 test from DetectionClassRemapperTest
1: [ RUN      ] DetectionClassRemapperTest.MapClasses
1: [       OK ] DetectionClassRemapperTest.MapClasses (0 ms)
1: [----------] 1 test from DetectionClassRemapperTest (0 ms total)
1:
1: [----------] Global test environment tear-down
1: [==========] 1 test from 1 test suite ran. (0 ms total)
1: [  PASSED  ] 1 test.
1: -- run_test.py: return code 0
1: -- run_test.py: inject classname prefix into gtest result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_detection_class_remapper.gtest.xml'
1: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_detection_class_remapper.gtest.xml'
1/7 Test #1: test_detection_class_remapper ....   Passed    0.08 sec
test 2
    Start 2: test_ros_utils

2: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_ros_utils.gtest.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_cmake_gtest/test_ros_utils.txt" "--command" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_ros_utils" "--gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_ros_utils.gtest.xml"
2: Test timeout computed to be: 60
2: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion':
2:  - /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_ros_utils --gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_ros_utils.gtest.xml
2: [==========] Running 2 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 2 tests from TestSuite
2: [ RUN      ] TestSuite.box3DToDetectedObject
2: [WARN] [1720782725.912863644] [lidar_transfusion]: Unexpected label: UNKNOWN is set.
2: [       OK ] TestSuite.box3DToDetectedObject (0 ms)
2: [ RUN      ] TestSuite.getSemanticType
2: [       OK ] TestSuite.getSemanticType (0 ms)
2: [----------] 2 tests from TestSuite (0 ms total)
2:
2: [----------] Global test environment tear-down
2: [==========] 2 tests from 1 test suite ran. (0 ms total)
2: [  PASSED  ] 2 tests.
2: -- run_test.py: return code 0
2: -- run_test.py: inject classname prefix into gtest result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_ros_utils.gtest.xml'
2: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_ros_utils.gtest.xml'
2/7 Test #2: test_ros_utils ...................   Passed    0.07 sec
test 3
    Start 3: test_nms

3: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_nms.gtest.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_cmake_gtest/test_nms.txt" "--command" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_nms" "--gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_nms.gtest.xml"
3: Test timeout computed to be: 60
3: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion':
3:  - /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_nms --gtest_output=xml:/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_nms.gtest.xml
3: [==========] Running 1 test from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 1 test from NonMaximumSuppressionTest
3: [ RUN      ] NonMaximumSuppressionTest.Apply
3: [       OK ] NonMaximumSuppressionTest.Apply (1 ms)
3: [----------] 1 test from NonMaximumSuppressionTest (1 ms total)
3:
3: [----------] Global test environment tear-down
3: [==========] 1 test from 1 test suite ran. (1 ms total)
3: [  PASSED  ] 1 test.
3: -- run_test.py: return code 0
3: -- run_test.py: inject classname prefix into gtest result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_nms.gtest.xml'
3: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/test_nms.gtest.xml'
3/7 Test #3: test_nms .........................   Passed    0.07 sec
test 4
    Start 4: copyright

4: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/copyright.xunit.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_copyright/copyright.txt" "--command" "/opt/ros/humble/bin/ament_copyright" "--xunit-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/copyright.xunit.xml"
4: Test timeout computed to be: 200
4: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion':
4:  - /opt/ros/humble/bin/ament_copyright --xunit-file /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/copyright.xunit.xml
4: No problems found, checked 32 files
4: -- run_test.py: return code 0
4: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/copyright.xunit.xml'
4/7 Test #4: copyright ........................   Passed    0.57 sec
test 5
    Start 5: cppcheck

5: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/cppcheck.xunit.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_cppcheck/cppcheck.txt" "--command" "/opt/ros/humble/bin/ament_cppcheck" "--xunit-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/cppcheck.xunit.xml" "--include_dirs" "/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion/include" "/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion/include"
5: Test timeout computed to be: 300
5: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion':
5:  - /opt/ros/humble/bin/ament_cppcheck --xunit-file /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/cppcheck.xunit.xml --include_dirs /home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion/include /home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion/include
5: cppcheck 2.7 has known performance issues and therefore will not be used, set the AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS environment variable to override this.
5: -- run_test.py: return code 0
5: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/cppcheck.xunit.xml'
5/7 Test #5: cppcheck .........................   Passed    0.08 sec
test 6
    Start 6: lint_cmake

6: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/lint_cmake.xunit.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_lint_cmake/lint_cmake.txt" "--command" "/opt/ros/humble/bin/ament_lint_cmake" "--xunit-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/lint_cmake.xunit.xml"
6: Test timeout computed to be: 60
6: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion':
6:  - /opt/ros/humble/bin/ament_lint_cmake --xunit-file /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/lint_cmake.xunit.xml
6:
6: No problems found
6: -- run_test.py: return code 0
6: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/lint_cmake.xunit.xml'
6/7 Test #6: lint_cmake .......................   Passed    0.07 sec
test 7
    Start 7: xmllint

7: Test command: /usr/bin/python3.10 "-u" "/home/masatosaeki/t4/pilot-auto_transfusion/src/install/share/ament_cmake_test/cmake/run_test.py" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/xmllint.xunit.xml" "--package-name" "autoware_lidar_transfusion" "--output-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/ament_xmllint/xmllint.txt" "--command" "/opt/ros/humble/bin/ament_xmllint" "--xunit-file" "/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/xmllint.xunit.xml"
7: Test timeout computed to be: 60
7: -- run_test.py: invoking following command in '/home/masatosaeki/t4/pilot-auto_transfusion/src/autoware/universe/perception/autoware_lidar_transfusion':
7:  - /opt/ros/humble/bin/ament_xmllint --xunit-file /home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/xmllint.xunit.xml
7: File 'package.xml' is valid
7:
7: File 'launch/lidar_transfusion.launch.xml' is valid
7:
7: No problems found
7: -- run_test.py: return code 0
7: -- run_test.py: verify result file '/home/masatosaeki/t4/pilot-auto_transfusion/src/build/autoware_lidar_transfusion/test_results/autoware_lidar_transfusion/xmllint.xunit.xml'
7/7 Test #7: xmllint ..........................   Passed    0.98 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
copyright     =   0.57 sec*proc (1 test)
cppcheck      =   0.08 sec*proc (1 test)
gtest         =   0.21 sec*proc (3 tests)
lint_cmake    =   0.07 sec*proc (1 test)
linter        =   1.70 sec*proc (4 tests)
xmllint       =   0.98 sec*proc (1 test)

Total Test time (real) =   1.91 sec
---
Finished <<< autoware_lidar_transfusion [1.97s]

Summary: 1 package finished [2.61s]
</pre>
</code>
</details>

## Notes for reviewers
I integrate `lidar_transfusion`  and `transfusion`  as `{PROJECT_NAME}` in CMakeLists.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by knzo25** [comment]
@amadeuszsz 
I don't think the CODEOWNERS file should be changed manually
(https://github.com/autowarefoundation/autoware-github-actions/tree/main/update-codeowners-from-packages)

**Comment by MasatoSaeki** [comment]
@knzo25 
I think you are right, but I changed manually because CODEOWNER is also changed at the same time in other PRs. (For consistency) How about this?

**Review by amadeuszsz — APPROVED** [review]
LGTM.
Also tested by logging simulator demo without any issue.

**Pull request merged**
