### PR TITLE
feat(metrics_calculation): add kinematic and localization evaluators with metrics

### PR DESCRIPTION
**Pull request by djargot**
## Description
This PR extends planning evaluator with other evaluators and various metrics calculation.

- [x] Create frameworks for different types of metrics:
- [ ] Extract overlapping code to generic evaluator that other evaluators can inherit from
- [x] Add example metrics
- [ ] Add all tests
- [ ] Add README

## Related links
https://github.com/autowarefoundation/autoware-projects/issues/11 

## Notes for reviewers
Work in progress.

## Pre-review checklist for the PR author
- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
@WJaworskiRobotec @Soohyeok-Park 
Could you please add one of tier4 members as reviewer when you add a huge commit?
 @mitsudome-r @yukkysaito @TakaHoribe

**Comment by mitsudome-r** [comment]
@taikitanaka3 
This is not a pull request to TIER IV owned code, and I don't see the reason why there needs a review from TIER IV. Please be aware that TIER IV is not an owner of Autoware.Universe. The PR was there for over a month until it was merged, and if you have any concerns, you should've assigned yourself as a reviewer to the PR.

**Comment by WJaworskiRobotec** [comment]
@taikitanaka3 this commit is about adding entirely new component according to the task from the Simulation WG - not used by Autoware stack by default, only for simulation based testing. We will create further PRs for perception-related evaluators, @mitsudome-r should we add someone else as reviewers (@djargot is working on the task so I can review it if it's not a problem)?

**Comment by taikitanaka3** [comment]
@WJaworskiRobotec 
Thank you for contribution.
My suggestion is to add architects as a reviewer to discuss with code base.

**Comment by WJaworskiRobotec** [comment]
@taikitanaka3 sure, we might discuss the structure a bit later - we had plan to also merge existing evaluators into one package. Then we might need discussion with the architects where to put our proposal of evaluators.

**Pull request merged**
