### PR TITLE
refactor(image_projection_based_fusion): rework param

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

- Rearrange params for `image_projection_based_fusion`
- Should merge after https://github.com/autowarefoundation/autoware_launch/pull/845

## Related Link

[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1706745602992849) 

## Tests performed

- Confirmed each Nodes executable after moving params

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by Shin-kyoto — CHANGES_REQUESTED** [review]
@badai-nguyen 

Please add these params to https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/config/pointpainting.param.yaml, too

```yaml
    # fusion interface common params
    debug_mode: false
    image_buffer_size: 15
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0
```

That is because pointpainting uses roi_sync_param in https://github.com/autowarefoundation/autoware.universe/blob/1ed6fac11a9851c12ede1ec34409204d799d9863/perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml#L26

[I checked this PR with evaluator](https://evaluation.tier4.jp/evaluation/oidc/auth/cb/?code=ory_ac_dqcTUSmpfothS_fxY_KIWKER1eENYQQQS6s4LFWsY1g.-gFuMYY_u9fyfAujaRKZ8HeNbnAFTbwmwuIWgs3e5Gk&scope=openid+profile+email+offline_access&state=f9b871c576544626afba41d79798dde7), and I got the error below.

```bash
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'pointpainting' of type 'image_projection_based_fusion::PointPaintingFusionNode' in container 'pointcloud_container': Component constructor threw an exception: Statically typed parameter 'filter_scope_min_x' must be initialized.
```

And please run the evaluator on the condition that "perception_mode" is "camera_lidar_fusion" and "lidar_detection_model" is "pointpainting", and paste the link to the result of evaluator.
[This example](https://github.com/tier4/auto-evaluator/tree/feat/review-rework-projection-param) will be helpful for you.

**Comment by kminoda** [comment]
@badai-nguyen In addition to above, please make sure to update the parameter file in Evaluator: https://evaluation.tier4.jp/evaluation/mlpackages/5b56c824-de65-406e-b12f-d7271589cc70?project_id=zWhWRzei , communicate with System Integration team to make sure that the ML model to be deployed accordingly.

**Comment by badai-nguyen** [comment]
Since the policy of pointpainting/centerpoint param management is under reviewing so I will change to draft this PR and update and re-open it after the new policy is reflected.
cc @Shin-kyoto

**Review by Shin-kyoto — APPROVED** [review]
LGTM
I did NOT run autoware with this PR. I checked the code only. Please check this PR runs correctly.

**Comment by miursh** [comment]
@badai-nguyen 
Don't we need to change https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/schema/roi_sync.schema.json ?

**Comment by badai-nguyen** [comment]
> @badai-nguyen Don't we also need to change the schema file at https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/schema/roi_sync.schema.json ?

@miursh Thank you for your comment. I fixed https://github.com/autowarefoundation/autoware.universe/pull/6289/commits/a728e117c86ed1ef27ec49600970ddfc8c120f6d

**Comment by miursh** [comment]
@badai-nguyen 
How about this [line](https://github.com/autowarefoundation/autoware.universe/blob/a728e117c86ed1ef27ec49600970ddfc8c120f6d/perception/image_projection_based_fusion/schema/fusion_common.schema.json#L6C6-L6C14) ?

**Comment by badai-nguyen** [comment]
> @badai-nguyen How about this [line](https://github.com/autowarefoundation/autoware.universe/blob/a728e117c86ed1ef27ec49600970ddfc8c120f6d/perception/image_projection_based_fusion/schema/fusion_common.schema.json#L6C6-L6C14) ?

@miursh I'm sorry, I missed that one. I fixed at https://github.com/autowarefoundation/autoware.universe/pull/6289/commits/928a216f4bcb5d31738d3bbc7c58418942f383cd

**Review by miursh — APPROVED** [review]
Thanks!

**Pull request merged**
