### PR TITLE
fix: Modifications for changing the behaviour of detection area visi…

### PR DESCRIPTION
**Pull request by sujithvemi**
This PR is related to the detection area highlighting requirement for RViz where the required specification is as follows:

**Expected behavior**

I can decide whether obstacles are not detected, module is unregistered or ego vehicle goes over the dead line from debug markers.

My proposal is

- module is registered but not detected: detection area marker is green
- detected: detection area marker is red
- go over the dead line: detection area marker is grey
- unregistered: delete

It is for issue 1121, the link is given below:
https://github.com/autowarefoundation/autoware.universe/issues/1121

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@sujithvemi I totally agree with your motivation/proposal. This PR contains undesired commits. Please clean up them.

**Comment by sujithvemi** [comment]
> @sujithvemi Thank you for this update. I totally agree with your motivation/proposal. This PR contains undesired commits. Please clean up them.

Okay, will do and comment

**Comment by sujithvemi** [comment]
@TakaHoribe Hi, can you please expand on what are the undersired commits here? Pipeline is running well for the most part except for some linter issues, I wanted to understand properly what you meant by undersired commits before I fix them and make any more commits. Do you mean the commits where I modified files that are not in the original commit of mine (related to the issue I am fixing) but ones that I got when I did a pull?

**Comment by xmfcx** [comment]
@sujithvemi Currently 24 files are modified in this PR and many seem to be unrelated.

Thanks for working on this issue:sparkles:. If you'd like to improve autoware with those changes, please open up new issues or PRs to suggest them.

Examples:
- Why are there modifications in [control/trajectory_follower/include/trajectory_follower/mpc.hpp](https://github.com/autowarefoundation/autoware.universe/pull/2237/files#diff-e210592d543094a1ada4c8e115fb2e42ce598f6654a185db102e959e2835b823L21)
- Why are there modifications in any of these control, localization topics etc.
Screenshot from 2022-11-15 17-03-56

We can review it once the changes are reduced to minimum to reflect the purpose of this PR like @TakaHoribe suggested.

**Comment by sujithvemi** [comment]
I got those issues when I pulled to update my codebase, so I modified them. Now it will be a little difficult to undo these changes and recommit, so can I delete this PR and raise a new one with only the required files changed? Please let me know if that is allowed, otherwise I will get this one itself to work by reverting commits and making only needed changes.

**Comment by mitsudome-r** [comment]
@sujithvemi Please go ahead and create new PR with clean commit if that is easier for you. Make sure to put the link in this thread so that everyone will be aware of the new PR.

**Comment by sujithvemi** [comment]
Have raised a new updated pull request that resolves the issues with the current pull request. It is PR #2401

**Pull request closed without merging**
