### PR TITLE
feat: add visualization node of traffic light recognition result

### PR DESCRIPTION
**Pull request by tkimura4**
## Description
Add visualization node of traffic light recognition result
image
image

## Tests performed
I checked on logging simulator

## Notes for reviewers
none

## Interface changes
none

## Effects on system behavior
no effects on system behavior.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
TODO: fix readme

**Comment by tkimura4** [comment]
finish to update Readme.

**Review by shmpwk — APPROVED** [review]
LGTM

**Comment by miursh** [comment]
@tkimura4 Just FYI, after merging https://github.com/autowarefoundation/autoware.universe/pull/4084, we, perception team, are gonna change output I/F of traffic light module to [autoware_perception_msgs/msg/TrafficLightArray.msg](https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_perception_msgs/msg/TrafficLightArray.msg)

**Pull request merged**
