### PR TITLE
feat(safety_check): add option to use polygon along path in safety check

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

:warning: Please approve following PR first.
https://github.com/autowarefoundation/autoware_launch/pull/865

Current `safety_checker` assumes that steering angle is fixed during braking and creates rectangle polygon to check safety based on each predicted poses. However, basically it is able to change steering angle anytime. Additionally, previous logic sometimes caused false positive and modules judged unsafe excessively because the detection polygon covered not only adjacent lane but also the area where the ego wouldn't go through.

In this PR, I added option to switch steering policy during breaking from `fixed` or `free`.

### steering policy: `fixed`

In this policy, the safety checker creates rectangle polygon based on each predicted poses. (original method)

image

### steering policy: `free`

In this policy, the safety checker creates polygon along path. Polygon's longitudinal length is calculated by rss parameter.

image

## Tests performed

- [x] TEST WITH XX1
- [x] [PASS TIER IV INTERNAL SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/eeccd553-6264-59f5-a753-6a3c5d94a81c?project_id=prd_jt)

## Effects on system behavior

Improve avoidance behavior.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by zulfaqar-azmi-t4** [comment]
It seems that the behavior is a little of sometime.
For example in the video at time after 5s (I also attach image of the polygon at the time), the polygon seems to be straight, then it follows back the curvature of the path.
Is behavior is expected?

https://github.com/autowarefoundation/autoware.universe/assets/93502286/bc2bc88d-c5c2-4c1b-912d-1b32e65b7587

image

**Comment by zulfaqar-azmi-t4** [comment]
`steering` as parameter name seems to be odd.
I would suggest either
1. `steering_policy`, or
2. `extended_polygon_policy` but the name might be too long.
I would say `steering` feels odd because it technically not related to steering.

**Comment by satoshi-ota** [comment]
> Thank you @satoshi-ota for the great PR!
> 
> Just checking It seems that the behavior is a little of sometimes. For example in the video at time after 5s (I also attach image of the polygon at the time), the polygon seems to be straight, then it follows back the curvature of the path. Is behavior is expected?
> 
>  cap-.2024-02-15-22-35-24.mp4 
> image

Hmm... No. Something wrong. I'll take a look. Thanks for your review! @zulfaqar-azmi-t4

**Comment by satoshi-ota** [comment]
> `steering` as parameter name seems to be odd. I would suggest either
> 
> 1. `steering_policy`, or
> 2. `extended_polygon_policy` but the name might be too long.
>    I would say `steering` feels odd because it technically not related to steering.

`extended_polygon_policy` seems to be nice! 

This is my image.

- `extended_polygon_policy`
  - `along_path`
  - `rectangle`

**Comment by satoshi-ota** [comment]
@zulfaqar-azmi-t4 I fixed wierd polygon shape in https://github.com/autowarefoundation/autoware.universe/pull/6336/commits/c42fa54e3c589386de37a9b499849206c19e7484.
And, update param name. Could you see again?

image

**Comment by satoshi-ota** [comment]
[NO REGRESSION.](https://evaluation.tier4.jp/evaluation/reports/21f566d6-95c8-510a-8208-c50bff2263d8?project_id=prd_jt)

**Review by zulfaqar-azmi-t4 — APPROVED** [review]
LGTM

https://github.com/autowarefoundation/autoware.universe/assets/93502286/007dc4d5-ae13-47b0-8eb7-a9fbecbb82a7

**Pull request merged**
