### PR TITLE
feat: visualize lane boundaries

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

- visualize lane boundaries with namespace "lane_start_bound"

Before
Before

After
After

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@maxime-clem What do you think is the appropriate name for the red part? Is `lane_bound` okay for you?
image

**Comment by kenji-miyake** [comment]
Since `left_bound` and `right_bound` represent the blue parts (in my understanding), I feel it's good to name the red line differently.
image

**Comment by maxime-clem** [comment]
> @maxime-clem What do you think is the appropriate name for the red part? Is lane_bound okay for you?

How about `start_bound` (and `end_bound` if we add the segment between the last points of the left and right bounds) ?

**Comment by h-ohta** [comment]
@maxime-clem @kenji-miyake Thank you. I'll use `start_bound`. And Can I change namespace to `start_lane_bound`?

**Comment by kenji-miyake** [comment]
@maxime-clem Thank you! Seeing this part, `start_bound` seems good to me. :smile: 
image

@h-ohta I'm not confident, but I feel `lane_start_bound` is better. Or `front_lane_bound`? :thinking: 
I'll leave the decision to @maxime-clem -san... :pray:

**Comment by maxime-clem** [comment]
> @h-ohta I'm not confident, but I feel `lane_start_bound` is better. Or `front_lane_bound`? I'll leave the decision to @maxime-clem -san...

I like `lane_start_bound` :smiley:

**Comment by h-ohta** [comment]
@kenji-miyake @maxime-clem I fixed. Could you review again?

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
