### PR TITLE
fix(tier4_planning_launch): fix tier4_planning_launch package

### PR DESCRIPTION
**Pull request by k-obitsu**
Signed-off-by: k-obitsu <koichi.obitsu@tier4.jp>

## Description

- Fixed the path of 'stop_line.param.yaml' in 'behavior_planning.launch.py'
- Related to the above, added param.yaml files.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
https://github.com/tier4/autoware_launch/pull/271#discussion_r845958718
LGTM except for the above comment.

**Comment by yukkysaito** [comment]
LGTM

**Review by takayuki5168 — DISMISSED** [review]
LGTM

**Comment by yukkysaito** [comment]
>I'm not sure how tier4_*_launch is used. Should we verify that simple planning simulator works with a meta repository? If so, could you give us the meta repository. (maybe autoware?)

yes. We need to make sure the tutorial works.
https://github.com/autowarefoundation/autoware
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/

**Comment by takayuki5168** [comment]
@k-obitsu 
Could you verify that this PR works with the meta repository `autoware`.
https://github.com/autowarefoundation/autoware

There is a tutorial of simple planning simulator in the following. (You don't have to use the sample map.)
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/

If this doesn't make sense to you, I'll do verification.

**Comment by k-obitsu** [comment]
@takayuki5168 
I updated this PR  for the following files, because I synced my local repository upstream.
  - blind_soprt.param.yaml
  - occlusion_sport.param.yaml
  - behavior_planning.launch.py

And I verified that this PR works with the meta repository `autoware`.
https://github.com/autowarefoundation/autoware

**Comment by takayuki5168** [comment]
Thank you for your verification.

> I updated this PR for the following files, because I synced my local repository upstream.

I don't understand well. Do you mean you did an additional modification to the three files?

Also please don't always force-push since I don't know what you've modified after I put LGTM.

(force-pushをせずにcommit履歴を残していただければ、上記の「3つファイルを変更しました」に関してのみの変更を見ることができます。ということをcommit履歴に残せるので、なるべくforce-pushは避けていただけると :pray: )

**Comment by k-obitsu** [comment]
@takayuki5168 

> I don't understand well. Do you mean you did an additional modification to the three files? If so, could you give me a bit more explanation about the modification.
> 
> Also please don't always force-push since I don't know what you've modified after I put LGTM.
I'm sorry, but it was caused by my misunderstanding.
I would like to revert to before the change.(In this case, I'll use force-push again...)

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Comment by taikitanaka3** [comment]
LGTM

**Pull request merged**
