### PR TITLE
fix(autoware_occupancy_grid_map_outlier_filter): fix bugprone-incorrect-roundings

### PR DESCRIPTION
**Pull request by kobayu858**
## Description
This is a fix based on clang-tidy `bugprone-incorrect-roundings` error.

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:143:16: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
      std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
               ^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:143:33: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
      std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
                                ^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:203:16: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
      std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
               ^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:203:33: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
      std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
```
## Related links

**Parent Issue:**

- Link

## How was this PR tested?
Confirm that the value does not change by actually operating the system.

```
#include <iostream>
#include <cmath>
#include <algorithm>

int calculateMinPointsThreshold(double min_points_and_distance_ratio_, double distance, int min_points_, int max_points_) {
    return std::min(
        std::max(static_cast<int>(std::lround(min_points_and_distance_ratio_ / distance)), min_points_),
        max_points_
    );
}

int calculateMinPointsThreshold_old(double min_points_and_distance_ratio_, double distance, int min_points_, int max_points_) {
    return std::min(
      std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
      max_points_);
}

int main() {
    double min_points_and_distance_ratio = 30;
    double distance = 3.9;
    int min_points = 5;
    int max_points = 15;

    int min_points_threshold = calculateMinPointsThreshold(min_points_and_distance_ratio, distance, min_points, max_points);
    int min_points_threshold_old = calculateMinPointsThreshold_old(min_points_and_distance_ratio, distance, min_points, max_points);

    std::cout << "Calculated min_points_threshold: " << min_points_threshold << std::endl;
    std::cout << "Calculated min_points_threshold_old: " << min_points_threshold_old << std::endl;

    return 0;
}
```

> emb4@emb4-E5-165:~/autoware_cppcheck/autoware.universe$ ./test
> Calculated min_points_threshold: 8
> Calculated min_points_threshold_old: 8

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by kobayu858** [comment]
@amc-nu @YoshiRi @yukkysaito 
Please confirm the PR. Thank you very much.

**Comment by kobayu858** [comment]
@amc-nu @YoshiRi @yukkysaito 
Please confirm the PR. Thank you very much.

**Comment by yukkysaito** [comment]
@kobayu858 Thank you. I believe std::lround might increase the computational cost, so could you measure the latency before and after implementing it?

**Comment by kobayu858** [comment]
@yukkysaito 
```
double min_points_and_distance_ratio = 400.0;
int min_points = 4;
int max_points = 70;
```
This is the average latency of 1,000,000 calculations with varying DISTANCE using this parameter.
New is the modified implementation and Old is the existing implementation.
Depending on the value of distance, the maximum increase will be about 4ns.

distance [0.1, 10.0]
```
calculateMinPointsThreshold (New) - Average: 20.2532 ns
calculateMinPointsThreshold_old (Old) - Average: 16.7661 ns
```
distance [10.0, 100.0]
```
calculateMinPointsThreshold (New) - Average: 17.2914 ns
calculateMinPointsThreshold_old (Old) - Average: 16.9614 ns
```
distance [100.0, 1000.0]
```
calculateMinPointsThreshold (New) - Average: 17.7293 ns
calculateMinPointsThreshold_old (Old) - Average: 17.2558 ns
```

**Comment by kobayu858** [comment]
Restored because it was closed by mistake

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
