### PR TITLE
feat(behavior_path_planner): param to skip some linestring types when expanding the drivable area

### PR DESCRIPTION
**Pull request by maxime-clem**
## Description

Add parameters to specify, for each module of the `behavior_path_planner`, types of linestrings (as defined in the lanelet map) that cannot be used for drivable area expansion.

## Related links

Issue raised here: https://github.com/autowarefoundation/autoware.universe/issues/2182#issuecomment-1313743496

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by mehmetdogru — DISMISSED** [review]
@maxime-clem 

Thank you for creating this PR.

I tried the PR with different types for `avoidance` and `lane_following` modules. It works as intended. Since the feature implementation in the PR is the same for every module there should not be a problem.

**Comment by xmfcx** [comment]
@maxime-clem can you rebase&resolve conflicts please?

**Comment by mehmetdogru** [comment]
@maxime-clem 

If you don't mind could you rebase this PR and resolve the conflicts? 😊

**Comment by mitsudome-r** [comment]
@maxime-clem This needs to be merged by this week so that LeoDrive can test this feature.
If you need help, @mehmetdogru can take over the PR.

**Comment by maxime-clem** [comment]
@xmfcx @mehmetdogru 
I updated the branch. This should now work again with the latest autoware universe. Let me know if you encounter some issue.
The default configuration was moved so you also need to use this branch for ` autoware_launch`: https://github.com/autowarefoundation/autoware_launch/tree/behavior_path_planner-add_drivable_area_exp_skip_types

**Comment by mehmetdogru** [comment]
Hi @maxime-clem. Thank you for solving the conflicts :smiley: 

I would like to share as a difference from previous implementation of the PR (using grid map), current implementation extends only wrt to current linestrings. What I mean is that if there is a `road_border` linestring, inside the expansion area, current implementation ignores that so it causes MPT to plan outside of drivable area.

pr-2288-outer-linestring-issue_1

pr-2288-outer-linestring-issue_2

_I believe how it should be:_

pr-2288-outer-linestring-issue_3

**Comment by maxime-clem** [comment]
> I would like to share as a difference from previous implementation of the PR (using grid map), current implementation extends only wrt to current linestrings.

For this PR, this was also the case before the change from grid map to left/right bounds.
The feature to not grow the drivable area beyond some specific linestrings is in another PR: https://github.com/autowarefoundation/autoware.universe/pull/2434

**Comment by mehmetdogru** [comment]
@maxime-clem 
sorry to bother you but there are conflicts again while rebasing. After fixing those maybe we could ask for a code owners review so we can merge this PR?

**Comment by maxime-clem** [comment]
> @maxime-clem sorry to bother you but there are conflicts again while rebasing. After fixing those maybe we could ask for a code owners review so we can merge this PR?

I fixed the conflict. Because of the holidays I don't think the PR will be reviewed soon. Sorry about that.

**Comment by mehmetdogru** [comment]
@maxime-clem 

Thank you for merging the PR.

Could you please create a PR for [the branch](https://github.com/autowarefoundation/autoware_launch/tree/behavior_path_planner-add_drivable_area_exp_skip_types) which includes the necessary additions to config file in autoware_launch? Unless that branch is merged bpp would not work.

**Pull request merged**
