### PR TITLE
refactor(lidar_centerpoint_tvm): rework parameters

### PR DESCRIPTION
**Pull request by tby-udel**
## Description
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the `lidar_centerpoint_tvm` package.

 * Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
 * Use types that match the ones returned from declare_parameter() in order to prevent confusion and potential coding errors.
 * Move the default parameter file to a standardized location. Use the JSON Schema for that.
 * Updated readme file.

## Tests performed
Package built and launched locally.

## Notes for reviewers
 Nothing inside the src code part was changed, only taking the parameters out.

## Interface changes
Parameter values are now required to be passed to the node when launched.

## Effects on system behavior
None

## Pre-review checklist for the PR author
The PR author **must** check the checkboxes below when creating the PR.

 * [x]  I've confirmed the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
 * [x]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

 ## In-review checklist for the PR reviewers
 The PR reviewers **must** check the checkboxes below before approval.

 * [ ]  The PR follows the [pull request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
 * [ ]  The PR has been properly tested.
 * [ ]  The PR has been reviewed by the code owners.
 
 ## Post-review checklist for the PR author
 The PR author **must** check the checkboxes below before merging.
 
 * [ ]  There are no open discussions or they are tracked via tickets.
 * [ ]  The PR is ready for merge.
 
 After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Review by angry-crab — APPROVED** [review]
LGTM

**Comment by tby-udel** [comment]
The signed off commit has been pushed.

**Comment by knzo25** [comment]
@tby-udel 
We do no longer have maintainers for this package, so it will probably be deprecated
https://github.com/orgs/autowarefoundation/discussions/4883

**Comment by kminoda** [comment]
The package no longer exists

**Pull request closed without merging**
