### PR TITLE
feat(behavior_velocity_planner): use common calcSignedArcLength

### PR DESCRIPTION
**Pull request by kosuke55**
## Related Issue(required)

https://github.com/autowarefoundation/autoware.universe/issues/361
## Description(required)

https://github.com/autowarefoundation/autoware.universe/pull/322#discussion_r797173244
Since multiple calcSignedArcLengths are defined in each module, use the common one.

detection_area test
https://user-images.githubusercontent.com/39142679/152911319-539510c2-47a3-4e9f-921c-734638544e80.mp4

traffic_light test
https://user-images.githubusercontent.com/39142679/152908576-4d4aa3e3-55f8-48f0-b16c-4aedc49db8c2.mp4

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [x] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kosuke55** [comment]
@k-obitsu 
Is it the same as what you fixed for in https://github.com/autowarefoundation/autoware.universe/pull/322?

If we set ego at a position beyond the goal, the stop line disappears. (detection_area video 00:10)
image

**Comment by taikitanaka3** [comment]
LooksGood
cc : @yukkysaito

**Review by taikitanaka3 — APPROVED** [review]

**Comment by yukkysaito** [comment]
@kosuke55 pls merge

**Comment by kosuke55** [comment]
@k-obitsu 
This PR has already been merged, but please check this comment.
https://github.com/autowarefoundation/autoware.universe/pull/362#issuecomment-1032178467

**Comment by kosuke55** [comment]
@k-obitsu 
hmm, Is it the correct behavior to disappear?

**Comment by k-obitsu** [comment]
@kosuke55
I think it is correct. 
but I don't know why the stop line is disappeared by v1.8.3.

**Pull request merged**
