### PR TITLE
fix(velodyne monitor): fix warning and error threshold of hot temperature

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

- add config file for each model
- use VLP-16.param.yaml as default argument
- update README about config file and operational temperature of each model

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by tkimura4** [comment]
@h-ohta 
Can you give me links to the documentations you used to determine these values?
(There is no problem even if it is Japanese documents)

**Comment by h-ohta** [comment]
@tkimura4 There are some documents, but some of them are not in official...

VLP-16: https://www.mapix.com/wp-content/uploads/2018/07/63-9229_Rev-H_Puck-_Datasheet_Web-1.pdf
VLP-32C: https://velodynelidar.com/wp-content/uploads/2019/12/63-9378_Rev-F_Ultra-Puck_Datasheet_Web.pdf
VLS-128: https://www.mapix.com/wp-content/uploads/2019/11/VelodyneLidar_AlphaPrime_Datasheet.pdf
M1600: https://www.gpsolution.com/uploads/files/2021/1124/48kOVJmPqTiBmRCxTI0qO0hBpoMiQ9XLKfOK0LWC.pdf
HLD-32E: https://www.mapix.com/wp-content/uploads/2018/07/97-0038_Rev-M_-HDL-32E_Datasheet_Web.pdf

**Review by tkimura4 — APPROVED** [review]
LGTM

**Comment by tkimura4** [comment]
There is no problem with the change, but the file name below is incorrect, so please correct it.
[HDL-32E.param..yaml](https://github.com/autowarefoundation/autoware.universe/pull/1623/files#diff-af094792d61b7a78c2622984ab3ab4760e48e8b2a459121746e72f38527a4813)

**Comment by h-ohta** [comment]
Thanks. I'll fix it.

**Pull request merged**
