### PR TITLE
feat(start_planner): visualize backward driving path

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

visualize backward drving path as greee arrows

image

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM!

**Comment by kyoichi-sugahara** [comment]
@kosuke55 
It doesn't seem like all the points of the backward path are visualized when looking at the image, but are the small arrows the points of the backward path?

**Comment by kosuke55** [comment]
@kyoichi-sugahara 
sorry for the confusing.

the backward driving path.
The image may be confusing because it includes the backward path (=5m) of the sift path.
Additionally, the backward driving path is buggy and output short.
The bug is being fixed in https://tier4.atlassian.net/browse/RT1-3916

**Comment by kosuke55** [comment]
@kyoichi-sugahara 
> but are the small arrows the points of the backward path?

yes, but the visualization is no problem

**Pull request merged**
