### PR TITLE
refactor(obstacle_stop_planner): clean up code

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

- use alias
- create additional header file for utils functions
- no logic modifications

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@satoshi-ota This PR contains the fix for behavior_path_planner. Is it expected?

**Comment by satoshi-ota** [comment]
> @satoshi-ota This PR contains the fix for behavior_path_planner. Is it expected?

Yes. drop the commit https://github.com/autowarefoundation/autoware.universe/pull/1818 for Evaluator tests.

I'll run the evaluator once more because the bug is fixed.

**Comment by satoshi-ota** [comment]
@TakaHoribe 
This PR: [786/823](https://evaluation.tier4.jp/evaluation/reports/d8add238-1327-5541-aa9d-bd6e88f9d352?project_id=prd_jt)
Baseline: [777/823](https://evaluation.tier4.jp/evaluation/reports/712d87b2-3cb8-51a5-af29-b8b45b2fb620?project_id=prd_jt)

**Review by TakaHoribe — APPROVED** [review]
Great work!

**Pull request merged**
