### PR TITLE
docs(behaivor_path_planner): fixed default value for document in goal_planner

### PR DESCRIPTION
**Pull request by asa-naki**
## Description
I have corrected the default value in the goal_planner documentation for behaivor_planner

I checked for different values based on the yaml.file below
https://github.com/autowarefoundation/autoware_launch/tree/main/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/goal_planner

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
@asa-naki 
Could you modify the title following the document ? 
https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/#rationale_2

The conventional commit this time is "docs".

**Comment by shmpwk** [comment]
`docs(behaivor_path_planner):Fixed default value for document in goal_planner` should be `docs(behaivor_path_planner): Fixed default value for document in goal_planner`

**Comment by shmpwk** [comment]
Could you make pass DCO following the "Details" link?

**Review by kosuke55 — APPROVED** [review]

**Comment by asa-naki** [comment]
It doesn't seem like this PR is the cause of spell-check-differential / spell-check-differential (pull_request) failed.

**Review by shmpwk — APPROVED** [review]
Thank you ! You can merge this whenever after the requird CI is passed.

**Pull request merged**
