### PR TITLE
fix(behavior_path_planner): add function to check the shift points in avoidance module

### PR DESCRIPTION
**Pull request by shulanbushangshu**
## Description

To solve #706

We can add function to detect points with offset distance to make sure they are within the drivable zone.
We can determine whether the offset points  are all in the driveable lane in the generateAvoidancePath of avoidance module(Consider the width of the vehicle when detecting),otherwise we use reference_path as the obstacle avoidance path(No obstacle avoidance behavior)

## Related links
Wrong path planned by avoidance module in a special case https://github.com/autowarefoundation/autoware.universe/issues/706

## Tests performed
Case1:
1.Run planning_simulator.
2.place ego position and goal
3. Set a obstacle near discontinuous adjacent lanes 
4. result -- ego vehicle stops

Case2:
1.Run planning_simulator.
2.place ego position and goal
3. Set a obstacle in continuous adjacent lanes 
4. result-- ego vehicle bypasses obstacle

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
@takayuki5168 @rej55 Can you review this PR?

**Comment by zulfaqar-azmi-t4** [comment]
Sorry for the many comments.
Some additional comments include you need to pass DCO.
if you want to fix DOC
`git rebase <branch> --signoff`

**Comment by takayuki5168** [comment]
> git rebase <branch> --signoff

Or we just push "Set DCO to pass" button here.
image

**Comment by shulanbushangshu** [comment]
Thank you.I will  fix the DCO

**Comment by zulfaqar-azmi-t4** [comment]
@shulanbushangshu 
I deeply apologize for the delay.
I've checked your solution using
1. single obstacle
2. dual obstacles

For single obstacle case, the solution works.
But when dual obstacle situation, the solution might be off.
Please refer to the following videos for example. (sorry again due to some technical issue, the video doesn't show full frame, but i think it should be sufficient)

https://user-images.githubusercontent.com/93502286/170184933-0ef57c32-7ab9-4f19-97bd-8902cb8e4670.mp4

Let me illustrate the acceptable result first, as 1m36s: if furthest obstacle was ignored (path not shifted) but if we place an obstacle ahead, the path will still remain shifted if the condition is acceptable.

Then in your proposed solution, when the furthest obstacle near the discontinued path was ignore, when we place the obstacle ahead (0m24s), the new obstacle is also ignored.

**Comment by shulanbushangshu** [comment]
I close this pr and will test this issue in the newest code.
If this issue occurs in the newest code,I will work on another pr.

**Pull request closed without merging**
