### PR TITLE
build: fix opencv dependency

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR adds `opencv-dev` as a depdency in `package.xml`

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@mitsudome-r @xmfcx this change fixes the Debian builds for `behavior_path_planner`, it'd nice to get it merged before the `2023.07` release.

**Review by xmfcx — APPROVED** [review]

**Comment by esteve** [comment]
@xmfcx thanks for the quick review

**Comment by esteve** [comment]
@xmfcx I've enabled auto-merge for this PR, I don't know why it hasn't merged itself after you approved it. Do you know why?

**Review by xmfcx — APPROVED** [review]

**Comment by xmfcx** [comment]
I needed to add myself to global code owners team and re-approve, merge, remove myself from the team.

**Pull request merged**
