### PR TITLE
fix: suppress spell check failure to ignore LOBF, bcnn, CTRV and DLCPU

### PR DESCRIPTION
**Pull request by h-ohta**
## Description

I fix spell check failures to ignore LOBF, bcnn, CTRV and DLCPU.
I followed ↓.
https://github.com/autowarefoundation/autoware.universe/blob/6b1a459a138bb04f1fcf5f8c9c160718032ce65d/common/tvm_utility/data/models/abs_model_aarch64/inference_engine_tvm_config.hpp#L40
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by YoshiRi — APPROVED** [review]
Thanks, LGTM

**Comment by ambroise-arm** [comment]
How is it decided when to add a word to the dictionary and when to ignore it in the codebase?

**Comment by h-ohta** [comment]
@ambroise-arm 
These words are not common because they are not in the dictionary and only used in specific nodes.
So I decided them to ignore by codebase.

**Review by ambroise-arm — APPROVED** [review]

**Comment by h-ohta** [comment]
@soblin @yukkysaito @angry-crab Could you review this PR?

**Review by soblin — APPROVED** [review]

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by h-ohta** [comment]
For some reason, `json-schema-check` action is not working...
I closed this PR and recreate it.

**Comment by h-ohta** [comment]
@xmfcx This PR is blocked by json-schema-check.
Because it is specified as required action.
Could you check and fix it ?

**Comment by HansRobo** [comment]
I made a pull-request for this problem.
https://github.com/autowarefoundation/autoware.universe/pull/6524

**Comment by h-ohta** [comment]
@angry-crab I appreciate it if you review this PR.

**Review by angry-crab — APPROVED** [review]
LGTM

**Comment by angry-crab** [comment]
Appologies for late response

**Pull request merged**
