### PR TITLE
docs(vehicle_info): add docs for versioning

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

update vehicle info docs based on https://github.com/orgs/autowarefoundation/discussions/4050

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by taikitanaka3 — APPROVED** [review]

**Review by mehmetdogru — APPROVED** [review]
LGTM, thank you.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
@mitsudome-r @xmfcx 
If this looks good for you, I'll merge it.

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
@xmfcx 
I'll merge this. If you have any concerns, let me know :pray:

**Pull request merged**
