### PR TITLE
fix(pointcloud_preprocessor): fix preprocessorErrorDirective

### PR DESCRIPTION
**Pull request by veqcc**
## Description

This is a fix based on cppcheck `preprocessorErrorDirective` warning

```
sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:132:2: error: #error Unsupported bitness [preprocessorErrorDirective]
#error Unsupported bitness
 ^
```

The `ROBIN_HOOD_PRIVATE_DEFINITION_BITNESS` macro is not used, right?

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

This `preprocessorErrorDirective` has prevented the cppcheck for analysing `robin_hood.h` file, so now it has a lot of cppcheck warnings, which is not acceptable in current CI workflow. See cppcheck-differential workflow for more detail.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by knzo25** [comment]
For this one, I think only @yukkysaito can properly give an answer (since it is related to the `pickup_based_voxel_grid_downsample_filter`)

**Review by yukkysaito — APPROVED** [review]
We are using the [external file](https://github.com/autowarefoundation/autoware.universe/blob/2b885aebfe332811a9382c4b6953080fcee00031/sensing/pointcloud_preprocessor/docs/downsample-filter.md#assumptions--known-limits). Accepting this change would not be an issue, but reducing the differences might improve maintainability. However, since the upstream repository is publicly archived and the likelihood of future changes is very low, I think it's fine to accept this PR.

**Comment by veqcc** [comment]
@yukkysaito 
Thank you for approving this PR!!

Since `cppcheck-differential` workflow is failing due to bugporone warings, we have to fix them before merging it.
May I add several commits before merging?
Or, do you prefer suppressing these warnings by inline cppcheck suppression?
 
See for detailed warnings: https://github.com/autowarefoundation/autoware.universe/actions/runs/9758833824/job/26934249776?pr=7786 
```
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:425:3: warning: Member variable 'BulkPoolAllocator::mHead' is not assigned a value in 'BulkPoolAllocator::operator='. [operatorEqVarError]
  operator=(const BulkPoolAllocator & ROBIN_HOOD_UNUSED(o) /*unused*/) noexcept
  ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:425:3: warning: Member variable 'BulkPoolAllocator::mListForFree' is not assigned a value in 'BulkPoolAllocator::operator='. [operatorEqVarError]
  operator=(const BulkPoolAllocator & ROBIN_HOOD_UNUSED(o) /*unused*/) noexcept
  ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:586:8: warning: The struct 'NodeAllocator' defines member function with name 'addOrFree' also defined in its parent class 'BulkPoolAllocator'. [duplInheritedMember]
  void addOrFree(void * ptr, size_t ROBIN_HOOD_UNUSED(numBytes) /*unused*/) noexcept
       ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:4[7](https://github.com/autowarefoundation/autoware.universe/actions/runs/9758833824/job/26934249776?pr=7786#step:11:8)2:8: note: Parent function 'BulkPoolAllocator::addOrFree'
  void addOrFree(void * ptr, const size_t numBytes) noexcept
       ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:5[8](https://github.com/autowarefoundation/autoware.universe/actions/runs/9758833824/job/26934249776?pr=7786#step:11:9)6:8: note: Derived function 'NodeAllocator::addOrFree'
  void addOrFree(void * ptr, size_t ROBIN_HOOD_UNUSED(numBytes) /*unused*/) noexcept
       ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2033:[10](https://github.com/autowarefoundation/autoware.universe/actions/runs/9758833824/job/26934249776?pr=7786#step:11:11): style: Variable 'kv' can be declared as pointer to const [constVariablePointer]
    auto kv = mKeyVals + findIdx(key);
         ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2045:10: style: Variable 'kv' can be declared as pointer to const [constVariablePointer]
    auto kv = mKeyVals + findIdx(key);
         ^
/home/runner/work/autoware.universe/autoware.universe/sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:[13](https://github.com/autowarefoundation/autoware.universe/actions/runs/9758833824/job/26934249776?pr=7786#step:11:14)76:7: performance: Prefer prefix ++/-- operators for non-primitive types. [postfixOperator]
      mKeyVals++;
      ^
```

**Comment by yukkysaito** [comment]
@veqcc Thank you. Since the upstream repository is publicly archived, we will need to maintain this file ourselves in the future. Considering this, I believe it would be better to fundamentally address the cppcheck issues rather than suppress them with inline cppcheck suppression.

**Comment by yukkysaito** [comment]
If there are a few additional commits, can I change it to draft until it is review ready?

**Comment by veqcc** [comment]
> If there are a few additional commits, can I change it to draft until it is review ready?
Of cource yes :+1: 

I will work on fixing blocking warnings later.

**Comment by veqcc** [comment]
@vividf 
HI, could you check the pointclouds are the same as before/after this PR?
I have fixed all the cppcheck warnigs.

**Comment by vividf** [comment]
@veqcc Sure, I will test it

**Comment by vividf** [comment]
I tested the changes, and the pointcloud after this PR is the same as before. 
LGTM!

**Review by vividf — APPROVED** [review]
I tested the changes, and the pointcloud after this PR is the same as before.
LGTM!

**Pull request merged**
