### PR TITLE
fix(autoware_pointcloud_preprocessor): fix image display in distortion corrector

### PR DESCRIPTION
**Pull request by vividf**
## Description
Images were displayed in the HTML table instead of the markdown table.
Which causes the images to fail to display on the Autoware documentation page.

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by knzo25** [comment]
@vividf 
Seen from github, the only difference is that this PR shows the figure centered and in bold letters.
Seen from the documentation https://autowarefoundation.github.io/autoware.universe/main/sensing/autoware_pointcloud_preprocessor/docs/distortion-corrector/
The images are broken. Will this PR fix that?

**Comment by vividf** [comment]
@knzo25 
Yes, this PR aims to fix the broken images.

**Review by knzo25 — APPROVED** [review]
LGTM

**Comment by knzo25** [comment]
@vividf 
It seems it did not work?
https://autowarefoundation.github.io/autoware.universe/main/sensing/autoware_pointcloud_preprocessor/docs/distortion-corrector/

**Comment by vividf** [comment]
Not sure whether the main docs update it immediately, probably it takes time (?)
https://autowarefoundation.github.io/autoware.universe/pr-9761/sensing/autoware_pointcloud_preprocessor/docs/distortion-corrector/

**Comment by vividf** [comment]
@knzo25 main is updated

**Pull request merged**
