### PR TITLE
feat(map_based_prediction): add time_keeper

### PR DESCRIPTION
**Pull request by soblin**
## Description

image

## Related links

**Parent Issue:**

- https://tier4.atlassian.net/browse/RT0-32279

## How was this PR tested?

see the pic

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by xmfcx** [comment]
Sorry, testing for:
- https://github.com/autowarefoundation/autoware.universe/pull/8177
to see if it will add annoying labels to the PR.

**Comment by xmfcx** [comment]
@soblin -san, you can use or ignore the suggestions, I hope they were useful.

My test is finished.

You can check https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/ai-pr-review/#how-to-use if you find it useful.

**Review by takayuki5168 — APPROVED** [review]

**Pull request merged**
