### PR TITLE
refactor(global_parameter_loader): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with `autoware`

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by esteve** [comment]
@mitsudome-r could you review (and merge) this PR when you have time? Thanks.

**Comment by xmfcx** [comment]
Searching the `global_parameter_loader` within the autoware directory, there are repositories that contain references to this package that needs to be updated:

| Repository                                       | Reference to `global_parameter_loader`                                         |
|--------------------------------------------------|-------------------------------------------------------------------------------|
| [autowarefoundation/autoware_tools](https://github.com/autowarefoundation/autoware_tools) | [Search Results](https://github.com/search?q=repo%3Aautowarefoundation%2Fautoware_tools%20global_parameter_loader&type=code) |
| [autowarefoundation/autoware_launch](https://github.com/autowarefoundation/autoware_launch) | [Search Results](https://github.com/search?q=repo%3Aautowarefoundation%2Fautoware_launch%20global_parameter_loader&type=code) |
| [tier4/pacmod_interface](https://github.com/tier4/pacmod_interface) | [Search Results](https://github.com/search?q=repo%3Atier4%2Fpacmod_interface%20global_parameter_loader&type=code) |

**Comment by esteve** [comment]
@xmfcx thanks for the review, I'm moving this back to draft to address your feedback.

**Comment by esteve** [comment]
@xmfcx I've submitted these PR to update other repositories:

https://github.com/tier4/pacmod_interface/pull/87
https://github.com/autowarefoundation/autoware_tools/pull/159
https://github.com/autowarefoundation/autoware_launch/pull/1246

**Comment by esteve** [comment]
@mitsudome-r @xmfcx the other three PRs have been approved, should all four PRs be merged now? Thanks.

**Review by mitsudome-r — APPROVED** [review]

**Comment by mitsudome-r** [comment]
I will check locally with planning-simulator if this modification doesn't cause any issue and will merge the PR.

**Comment by xmfcx** [comment]
image

I was able to drive autonomously with AWSIM-Labs with the latest autoware nightly repos, with all the sub-PRs rebased and checked out to main. ✅

Thanks for your efforts!

**Comment by xmfcx** [comment]
Also manually checked the usage of `global_parameter_loader` throughout the repository and checking them visually, they all seemed to have been prefixed correctly ✅

**Review by xmfcx — APPROVED** [review]

**Comment by esteve** [comment]
@xmfcx whenever you think it's ok, we can merge this and the other PRs. Thanks for taking the time to review all these changes, much appreciated :pray:

**Comment by xmfcx** [comment]
Thank you a lot as well @esteve 💫

I'm now waiting for the CI in here to be finished. Then I will merge:
- https://github.com/autowarefoundation/autoware_tools/pull/159#event-15526554240

**Pull request merged**
