### PR TITLE
fix(behavior_path_planner): fix turn signal endless loop

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

fix turn signal endless loop
https://github.com/autowarefoundation/autoware.universe/issues/5440

## Tests performed

https://evaluation.tier4.jp/evaluation/reports/c40eba8d-7d8e-5aa6-9c33-071b5b7841ac?project_id=prd_jt
1665/1667

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kyoichi-sugahara** [comment]
@danielsanchezaran 
First of all, thank you so much for the report!!!!! That's super helpful.
Could you review this PR and approve after your all comments are resolved?
And could you close the issue after merging this PR?
I will approve this PR because maintainer's approve is necessary and you are not the maintainer for now. But mergeing will be handled by @.kosuke55 san! 

When close the issue, we really appreciate it if you upload the video that problem is solved.
(Just uploading the same video you shared internally

**Review by kyoichi-sugahara — APPROVED** [review]
LGTM!
(don't merge before @.danielsanchezaran san's approval :bow:

**Comment by danielsanchezaran** [comment]
@kosuke55 CC @kyoichi-sugahara 
LGTM. Thanks for your quick response. With this fix the issue has been solved!

**Review by danielsanchezaran — APPROVED** [review]
LGTM

**Pull request merged**
