### PR TITLE
refactor(vehicle_constants_manager)!:  remove package

### PR DESCRIPTION
**Pull request by takayuki5168**
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description

Since we have vehicle_info_util widely used in autwoare.universe, the almost same package (vehicle_constants_manager) is not needed.
https://github.com/autowarefoundation/autoware.universe/tree/main/vehicle/vehicle_info_util/

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@xmfcx Can I remove this package?

**Comment by xmfcx** [comment]
Sure, I've created this package in Autoware.Auto as a mirror of `vehicle_info_util` anyways, since it's not used in any package here, we can remove it.

**Comment by xmfcx** [comment]
Oh it was just the space character before the colon :open_mouth:

**Comment by takayuki5168** [comment]
@xmfcx Thank you.

Regarding failed job, there is unnecessary space since we cannot put "!" with `git commit` without space.
https://stackoverflow.com/questions/5131948/use-of-an-exclamation-mark-in-a-git-commit-message-via-the-command-line

**Pull request merged**
