### PR TITLE
docs: comply with mkdocs style

### PR DESCRIPTION
**Pull request by ambroise-arm**
## Description

Change from the Autoware.Auto style of package documentation to one that gets parsed better by the current way of generating the documentation.

## Tests performed

Built the documentation locally

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by angry-crab — APPROVED** [review]
LGTM

**Comment by ambroise-arm** [comment]
@angry-crab How does the approval work? I see you as a code owner in the "reviewers" at the top right, but it still says "Code owner review required".

**Comment by angry-crab** [comment]
> @angry-crab How does the approval work? I see you as a code owner in the "reviewers" at the top right, but it still says "Code owner review required".

Well, I think AWF has decided that approval from global code owners is also required for each PR. 

@mitsudome-r @xmfcx Would you be able to approve this PR? Thanks.

**Comment by angry-crab** [comment]
@kenji-miyake 
I have added myself to the maintainer of the packages involved in the pr. But it doesn't seem to resolve the issue. Is there anything else I need to do?

**Comment by ambroise-arm** [comment]
Could it be the code owners are computed only when the PR is created? Closing and reopening didn't change anything.

**Comment by xmfcx** [comment]
Now it has created https://github.com/autowarefoundation/autoware.universe/pull/3443/files, it should solve the problem.

**Pull request merged**
