### PR TITLE
fix(freespace_planner, mission_planner): null checking

### PR DESCRIPTION
**Pull request by shmpwk**
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>

## Description

Resolve https://github.com/autowarefoundation/autoware.universe/issues/1251.

This PR reverts some commits in [this PR](https://github.com/autowarefoundation/autoware.universe/pull/1155/files).

As for `freespace_planner`, I remove unnecessary nullptr checking.
As for `mission_planner`, it waits until `route_handler` is ready.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
https://github.com/autowarefoundation/autoware.universe/blob/86101edd278bd572124995866d7fecf534830d21/planning/mission_planner/lib/mission_planner_base.cpp#L137

It's called here so

**Comment by shmpwk** [comment]
@taikitanaka3 Right, thank you and I fixed it.

**Review by NorahXiong — APPROVED** [review]
I tested parking mode and lane_driving mode and everything is alright.

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Pull request merged**
