### PR TITLE
fix(detected_object_validation): consider shoulder lanelet in object lanelet filter

### PR DESCRIPTION
**Pull request by shmpwk**
## Description

Current object lanelet filter only considers the "road" lanelet. 
This PR takes into account the "shoulder" lanelet where objects are filtered.
This idea is based on the current shoulder lane parking design, which considers objects in or accross the shoulder lanes.

## Related links

This PR can address the [Internal ticket](https://tier4.atlassian.net/browse/RT1-4092).

### Before

The objects in or across the shoulder lanelet **are filtered** after object_lanelet_filter node.
The unknown objects in the picture shows `/perception/object_recognition/detection/objects`

image

[Filtered in or across the shoulder lanelet movie](https://github.com/autowarefoundation/autoware.universe/assets/42209144/2e6adfc6-270f-44fe-8bc3-622da0db1a30)

### After

The objects in or across the shoulder lanelet **are not filtered** after object_lanelet_filter node.

image

[Not filtered in or across the shoulder lanelet movie](https://github.com/autowarefoundation/autoware.universe/assets/42209144/711758a5-08a3-4234-92c2-1867c10cf269)

## Notes for reviewers

No 

## Interface changes

No

## Effects on system behavior

This PR enables objects on the shoulder lanelet will be intentionally filtered.
If this is the case, **the latent unknown objects will appear on the road shoulder** which bother the road shoulder parking.
This suggests that we might need to seperate the road filter and shoulder filter in the future.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]
thanks! LGTM!

**Comment by shmpwk** [comment]
@yukkysaito @miursh 
Could you approve this as a code owner?

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by shmpwk** [comment]
@yukkysaito 
Thank you. Could you also run these CI? 
image

**Pull request merged**
