### PR TITLE
fix(obstacle_stop_planner): change polygon creating method

### PR DESCRIPTION
**Pull request by brkay54**
## Description

If the use_predicted_objects true there was a bug. If the obstacle left of the trajectory, stop planner founds an intersection and send stop. To fix this, I changed polygon creating method, and also it removes the opencv lib dependency.

Screenshot from 2023-04-20 01-58-17

In the picture, as you can see that although obstacle is outside of the trajectory, obstacle_stop_planner assumes there is an obstacle on the path. While using predicted_objects, node checks there is intersection between vehicle footprint and obstacle polygon. Before this PR, while creating polygon, checking polygon direction is unobserved. Because the direction is not determined, bg::intersects returns false positive while obstacle is left of the trajectory. 

## Tests performed

https://user-images.githubusercontent.com/45468306/234491580-463cc71e-4e9b-4cce-ac39-94737125b07c.mp4

Not applicable.

## Effects on system behavior

It fixes bug, there is no change in system behavior.

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@brkay54 Thanks you. I'll review this. 

Are you eady for review?

**Comment by brkay54** [comment]
@satoshi-ota Yes, it is ready for review.

**Comment by satoshi-ota** [comment]
@brkay54 This PR loogs good. And, I'm going to test by TIER IV internal senarios.

By the way, I was hoping you could explain briefly where the bug code is :pray:
And, I think it is better to update PR title `fix(obstacle_stop_planner): ~` if this is a bug fix PR.

**Comment by brkay54** [comment]
@satoshi-ota Thank you for reply. There are a lot of bugs for using predicted object option and I am currently working on this. I am going to open another PR for fixing other bugs and some improvements. This PR just fixes the problem that occurred while creating polygons. I gonna add brief explanation for bug and change the name of PR.

**Comment by satoshi-ota** [comment]
@brkay54 I confirmed this PR doesn't cause any regression. I'll aprove.

And, could you fill `Tests performed` (just paste movie is OK) and `Effects on system behavior` in PR description?

**Pull request merged**
