### PR TITLE
feat(shift_decider): send current gear if the autoware state is not driving

### PR DESCRIPTION
**Pull request by brkay54**
## Description
Closes: https://github.com/autowarefoundation/autoware.universe/issues/3526
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/3683

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by maxime-clem — APPROVED** [review]
Tested together with https://github.com/autowarefoundation/autoware.universe/pull/3683 and it works well.

**Comment by brkay54** [comment]
@maxime-clem Thank you for your review! 🙏🏼 
Friendly ping to  @TakaHoribe . If it is okay for you too, can you approve?

**Review by tkimura4 — APPROVED** [review]

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Review by TakaHoribe — APPROVED** [review]
LGTM

**Pull request merged**
