### PR TITLE
fix(behavior_path_planner): revert road shoulder margin to zero

### PR DESCRIPTION
**Pull request by zulfaqar-azmi-t4**
Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>

## Description

To reduce the number of parameters to be tune, it is decided to revert the road_shoulder_safety_margin to zero. The reason is that the parameter is dependent on the lanelet/ODD, therefore it might be different depending on the area.

Related links: 
road_shoulder_safety_margin: https://github.com/tier4/autoware_launch/pull/357
threshold_distance_object_is_on_center: https://github.com/tier4/autoware_launch/pull/397

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
image

@zulfaqar-azmi-t4 
can you also reconsider this value?
```
      threshold_distance_object_is_on_center: 1.0 # [m]
```

**Comment by zulfaqar-azmi-t4** [comment]
@taikitanaka3 CC: @TakaHoribe 
May I know what value you would suggest?

As far as I know as of know it shouldn't the be `0.0`, since, the value itself is to differentiate between parked object and vehicles at traffic light.

**Comment by taikitanaka3** [comment]
@zulfaqar-azmi-t4 
0.5m
image
0.3m
image
I think 0.3m is ok for this value

**Comment by zulfaqar-azmi-t4** [comment]
@taikitanaka3 
Based on the discussion during morning briefing, I've changed the parameter to `threshold_distance_object_is_on_center: 0.5`

**Comment by taikitanaka3** [comment]
@zulfaqar-azmi-t4 
discussion with horibe-san
for awf they don't use FOA so parameter can be strict like 1.0m

**Review by taikitanaka3 — APPROVED** [review]
LGTM

**Pull request merged**
