### PR TITLE
refactor(elevation_map_loader): add package name prefix `autoware_`, fix namespace and directory structure

### PR DESCRIPTION
**Pull request by technolojin**
## Description
This PR puts headers in the `autoware` namespace.
It also adds the autoware_ prefix to the package name.

1. Folder name (appears as file renaming)
2. Package names in `CMakeLists.txt`, `package.xml`
3. `README.md`
4. Launch files `$(find-pkg-share ...)`
5. `.github/CODEOWNERS`

Rework of https://github.com/autowarefoundation/autoware.universe/pull/7807

Additional works
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468)   [LIST](https://github.com/autowarefoundation/autoware.universe/pull/3606)

This PR do not contains any logic change.

## Related links
Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?
Tested in a local recompute environment with the following options settings.

* options
1. autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml
`use_single_frame_filter: True`
2. universe/launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
`"use_inpaint": True,`
`"use_elevation_map_cloud_publisher": True,`

* visualization
Elevation map (GridMap) /perception/obstacle_segmentation/elevation_map/map
Screenshot from 2024-07-18 18-00-48

## Notes for reviewers
None.

## Interface changes
None.

## Effects on system behavior
None.

### CODE REVIEW

**Review by badai-nguyen — APPROVED** [review]
LGTM

**Review by yukkysaito — APPROVED** [review]

**Review by Shin-kyoto — COMMENTED** [review]
@technolojin 

Did `elevation_map_loader_node` run in the TIER IV Cloud environment?

**Comment by technolojin** [comment]
> @technolojin
> 
> Did `elevation_map_loader_node` run in the TIER IV Cloud environment?

I realize the node is not tested.
I could not confirm the node is working properly before this PR changes.

@Shin-kyoto 
Can you confirm if the main branch works with the node enabled?

**Comment by technolojin** [comment]
@Shin-kyoto I could visualize the grid map, in the PR changes. see https://github.com/autowarefoundation/autoware.universe/pull/7988#issue-2404384169.

**Review by Shin-kyoto — COMMENTED** [review]
@technolojin 
I want to review this PR by running autoware. However, there are many breaking changes and conflicts with main, so it is difficult to build an environment to check its operation. 
Could you please share the autoware.repos of the environment you check this PR?

**Review by Shin-kyoto — APPROVED** [review]
LGTM

- I confirmed that this PR works well with [this autoware.repos](https://star4.slack.com/archives/C03S84LDJGG/p1721880702926189?thread_ts=1721876589.671279&cid=C03S84LDJGG) and [this launch command](https://star4.slack.com/archives/C03S84LDJGG/p1721898939027419?thread_ts=1721876589.671279&cid=C03S84LDJGG)
- I confirmed that this PR works well by checking log, `ros2 topic echo` and rviz.


Result:

- log

```bash
[component_container_mt-1] [INFO 1721893359.854956929] [perception.obstacle_segmentation.elevation_map.elevation_map_loader]: Saving elevation map successful: true
```

- `ros2 topic echo`

```bash
autoware:~/autoware$ ros2 topic echo /perception/obstacle_segmentation/elevation_map/map --no-arr
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: map
info:
  resolution: 0.3
  length_x: 1455.6
  length_y: 1772.1
  pose:
    position:
      x: 89272.140625
      y: 42713.98046875
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
layers: '<sequence type: string, length: 1>'
basic_layers: '<sequence type: string, length: 0>'
data: '<sequence type: std_msgs/msg/Float32MultiArray, length: 1>'
outer_start_index: 0
inner_start_index: 0
```

- rviz

image

**Review by takayuki5168 — APPROVED** [review]

**Pull request merged**
