### PR TITLE
refactor(component_interface_utils): prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by esteve**
## Description

prefix package and namespace with autoware

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5077
- https://github.com/autowarefoundation/autoware/issues/4569

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by esteve** [comment]
Depends on https://github.com/tier4/tier4_ad_api_adaptor/pull/127

**Review by isamu-takagi — APPROVED** [review]
I've confirmed that it's just adding a namespace, so if it builds then it should be OK.

**Comment by esteve** [comment]
@isamu-takagi thanks for the review.

@xmfcx can you merge https://github.com/tier4/tier4_ad_api_adaptor/pull/127  and then this?  https://github.com/tier4/tier4_ad_api_adaptor/pull/127 is failing because CI can't find the new name for the `component_interface_utils` package, but it should be fine. Thanks.

**Comment by xmfcx** [comment]
@esteve Unfortunately I don't have access to https://github.com/tier4 organization.

@mitsudome-r @isamu-takagi could you prioritize this and help @esteve on this?

**Comment by isamu-takagi** [comment]
@esteve @xmfcx I approve https://github.com/tier4/tier4_ad_api_adaptor/pull/127 and enable auto-merge.

**Comment by esteve** [comment]
@isamu-takagi @xmfcx thanks 🙏

**Pull request merged**
