### PR TITLE
feat(pointcloud_preprocessor): test loaned message API

### PR DESCRIPTION
**Pull request by esteve**
## Description

This PR is not meant to be merged as is, but to start a discussion on how to migrate to the loaned message API for zero copy

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by esteve** [comment]
@mitsudome-r I'm not sure who should be part of this discussion, so please feel free to ping other people. The changes in this PR could be merged as they are, but I want to have feedback from other people before moving forward onto other packages. I picked `pointcloud_preprocessor` because it handles point clouds, which among other types that contain a lot of data (like images), I think would benefit a lot from zero copy.

**Comment by mitsudome-r** [comment]
From the last ASWG, we have decided that we can start replacing the publishers in pointcloud_preprocessor package to use loaned API.

**Comment by mitsudome-r** [comment]
@esteve Could you make sure that you can still run rosbag replay simulation with this change?
https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/

**Comment by esteve** [comment]
@mitsudome-r the demo is not working after rebasing these changes on top of main, I'm working on a fix.

**Comment by esteve** [comment]
@mitsudome-r additionally, I can convert other nodes that don't use intraprocess to use the loaned messages API

**Comment by yukkysaito** [comment]
@esteve If this PR is not merged, can we change it to a draft?

We plan to review this PR carefully because of the issue [here](https://github.com/autowarefoundation/autoware.universe/issues/2306).
@badai-nguyen @miursh Can you review?

**Comment by miursh** [comment]
@mitsudome-r @esteve 
Do we still have the motivation to use this `loaned message API`? I remember trying it, but it didn't seem to work well.
If not, would it be acceptable to close this PR for now?

**Comment by esteve** [comment]
@miursh I'm not currently working on this PR, but I'd like to know what issues you had with the loaned messages API so that I can take them into account when we revive this PR. Thanks.

**Comment by esteve** [comment]
Closing this PR, not planning to work on this soon

**Pull request closed without merging**
