### PR TITLE
refactor(perception-traffic-light-classifier): rework parameters

### PR DESCRIPTION
**Pull request by karishma1911**
## Description

Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the traffic-light-classifier

1. Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.

2.create schema

## Tests performed

Not applicable.

## Effects on system behavior

More reliable and faster parameter configuration file creation.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by idorobotics** [comment]
@miursh @yukkysaito please urgently review.

**Review by yukkysaito — APPROVED** [review]
Sorry for late.
LGTM

**Comment by idorobotics** [comment]
@karishma1911 could you rebase this to the latest main? To fix the CI.

**Comment by karishma1911** [comment]
> @karishma1911 could you rebase this to the latest main? To fix the CI.

Done!

**Comment by idorobotics** [comment]
@karishma1911 DCO checks are failing. Please rebase to main.

**Comment by xmfcx** [comment]
Also please for PRs in Autoware, check this checkbox:

image

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

So we can do it when necessary.

**Comment by mitsudome-r** [comment]
@karishma1911 Could you make the change as @xmfcx requested?
There is something wrong with the commit log, and I would like to clean them up before merging.

**Pull request closed without merging**
