### PR TITLE
feat: update msg to publish pcd hash #1

### PR DESCRIPTION
**Pull request by tkimura4**
## Related Issue(required)
https://github.com/autowarefoundation/autoware.universe/issues/1

## Description(required)
add pcd variable to publish pointcloud map hash.

## Review Procedure(required)
-

## Related PR(optional)
https://github.com/tier4/AutowareArchitectureProposal_api_msgs/pull/1

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by 1222-takeshi** [comment]
Could you fix DCO error ?

**Review by 1222-takeshi — APPROVED** [review]
LGTM

**Comment by tkimura4** [comment]
We cannot solve DCO error, but it is not necessary for merging PR.

**Comment by 1222-takeshi** [comment]
Can't you solve this problem locally with the following command ?
[check here](https://github.com/autowarefoundation/autoware.universe/pull/140/checks?check_run_id=4451474597)
- git commit --amend --no-edit --signoff
- git push --force-with-lease origin 1-update-autoware_external_api_msgs

It is not required, but it is better to solve it if possible.

**Comment by tkimura4** [comment]
@1222-takeshi 
Thanks! I try it.

**Comment by tkimura4** [comment]
@1222-takeshi 

> git commit --amend --no-edit --signoff
git push --force-with-lease origin 1-update-autoware_external_api_msgs

I cannot resolve DCO error with this commands.
Do you now any other solutions?

**Comment by 1222-takeshi** [comment]
@tkimura4 
To resolve the DCO error, each commit needs to have "Signed-off-by:~".
For example 
image

But your commit doesn't seem to reflect that.
So, could you retry `git commit --amend --no-edit --signoff` ?
image

**Comment by tkimura4** [comment]
`git commit --amend --no-edit --signoff` seems to sign off only previous commit.
Then, I resolved DCO erro with following process.

git reset --hard 64062c14bbe6a827c28d0c468c8aa550d7ce214b
git commit --amend --no-edit --signoff # sign off the commit 64062c1
(Then, rebase on tier4/proposal)

**Pull request merged**
