### PR TITLE
feat(pointpainting): add a pointpainting package for the perception

### PR DESCRIPTION
**Pull request by tzhong518**
## Description

We would like to add a pointpainting package for the perception.
At present, we plan to develop it as an independent package for convenience. In the camera_lidar_fusion_based_detection.lauch, choosing 'pointpainting' as 'lidar_detection_model' would call the pointpainting.launch.
But since part of the code will be duplicate with lidar_centerpoint and roi_cluster_fusion package, there might be better solutions.
Please give us your advice. Thank you very much.

## Pre-review checklist for the PR author

PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has the write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by miursh** [comment]
@yukkysaito @yukke42 
As described in PR comment, we'are planning to implement Pointpainting package with launchers created in this PR. 
At this time, pointpaintig package is separated from centerpoint, roi_cluster_fusion since centerpoint and roi fusion have also being changed. If you have any suggestions, please make a comment.

**Comment by yukkysaito** [comment]
Thank you
Since roi_cluster_fusion, roi_object_fusion and pointpaing are almost the same code, pls integrate them into a package called image_projection_based_fusion. @yukke42  is currently working on it, so please share your work with each other.

**Comment by yukke42** [comment]
@tzhong518 
An image_projection_based_fusion package is implementing and the first prototype will be shared tomorrow or the start of the next week (The fusion algorithm don't change). On the other hand, lidar_centerpoint has already implemented ([here](https://github.com/autowarefoundation/autoware.universe/pull/480)), so please implement the core fusion method of pointpainting by reference to roi_cluster_fusion and above pr, and integrate it after both packages are merged. I will help to integrate pointpainting to image_projection_based_fusion.

**Comment by yukke42** [comment]
@miursh 
I create a new package `image_projection_based_fusion` and plan that `poinpainting` is in this package and uses `lidar_centerpoint` as a shared library. But, both packages aren't merged yet, so it's better to implement it by reference to roi_cluster_fusion and [here](https://github.com/autowarefoundation/autoware.universe/pull/480) and integrate after both packages are merged.

**Comment by yukke42** [comment]
@tzhong518 cc. @miursh 
I created a new package `image_projection_based_fusion` and please take a plan to add `pointpainting` to this package. https://github.com/autowarefoundation/autoware.universe/pull/548

**Comment by miursh** [comment]
Close this PR since it get old and the new PR is created

**Pull request closed without merging**
