### PR TITLE
fix(tier4_state_rviz_plugin): resolves #3121

### LINKED ISSUE #3121: autoware_state_panel cannot present NEUTRAL
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

autoware_state_panel cannot present `NEUTRAL` gear

### Expected behavior

when the vehicle shift to `NEUTRAL`, we can see `NEUTRAL` in AutowareStatePanel in RViz

### Actual behavior

when the vehicle shift to `NEUTRAL`, it could not show `NEUTRAL` in the red box below
image

### Steps to reproduce

1. turn on Autoware.core/universe
2. switch vehicle to the gear of `NEUTRAL` 

### Versions

- OS: Ubuntu 22.04
- Autoware.universe: [4267add](https://github.com/autowarefoundation/autoware.universe/commit/4267add3ec861b333c8ccf8d1fe692d5dfb70d58)

### Possible causes

https://github.com/autowarefoundation/autoware.universe/blob/main/common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp#L517
there is no `NEUTRAL` handle command in `AutowareStatePanel::onShift` function
```c++
void AutowareStatePanel::onShift(
  const autoware_auto_vehicle_msgs::msg::GearReport::ConstSharedPtr msg)
{
  switch (msg->report) {
    case autoware_auto_vehicle_msgs::msg::GearReport::PARK:
      gear_label_ptr_->setText("PARKING");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::REVERSE:
      gear_label_ptr_->setText("REVERSE");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::DRIVE:
      gear_label_ptr_->setText("DRIVE");
      break;
    case autoware_auto_vehicle_msgs::msg::GearReport::LOW:
      gear_label_ptr_->setText("LOW");
      break;
  }
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ahuazuipiaoliang**
…dation/autoware.universe/issues/3121

## Description
resolves #3121

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Comment by h-ohta** [comment]
@ahuazuipiaoliang Thank you for your PR. Could you fix PR description like `resolves #3121`and title?

**Comment by ahuazuipiaoliang** [comment]
@h-ohta If there is no any problem, please approval the PR.

**Review by h-ohta — APPROVED** [review]

**Comment by h-ohta** [comment]
@ahuazuipiaoliang Could you update main branch on pixmoving-moveit/autoware.universe  and update this branch ?
I'm sorry for inconvenience.

**Comment by ahuazuipiaoliang** [comment]
@h-ohta Thanks, I've updated.

**Comment by ahuazuipiaoliang** [comment]
@h-ohta I have no idea why the `autoware-global-codeowners is still` pending.

**Comment by h-ohta** [comment]
@ahuazuipiaoliang 
If a package has no code owners, we have to get approve from global code owners.
But, this package has code owners, as below.
https://github.com/autowarefoundation/autoware.universe/blob/1ec2a516c78a5cd2a040aa764a370c774921b1c1/.github/CODEOWNERS#L45

So, We do not need to get approve from global code owners.

**Pull request merged**
