### PR TITLE
test(autoware_detected_object_feature_remover): add unit testing for the node

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

Add unit testing for `DetectedObjectFeatureRemover`.

## Related links

**Parent Issue:**

- Link

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by YoshiRi — APPROVED** [review]
LGTM. Tested within my local environment.

**Comment by YoshiRi** [comment]
@tkimura4 Could you approve this? Nobody except you has right access.

**Review by tkimura4 — APPROVED** [review]
LGTM

@YoshiRi 
Can you add a maintainer on the Perception team?

**Comment by YoshiRi** [comment]
@tkimura4 
I created PR to add uetake-san and me to maintain this package. Please check it.
https://github.com/autowarefoundation/autoware.universe/pull/8962

**Pull request merged**
