### PR TITLE
feat(static centerline optimizer): new package

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

This PR depends on
- https://github.com/autowarefoundation/autoware.universe/pull/2014
- https://github.com/autowarefoundation/autoware.universe/pull/2015
- https://github.com/autowarefoundation/autoware.universe/pull/2259

**TODO**
- Sometimes path planning failed.
    - Actually, the path planning function is not so much tested. At least, simple case (path planning with a few left, right turn) has been tested.
- Elastic band is disabled
- successive path optimization

**Example command to plan path with kashiwanoha map**
ros2 launch static_centerline_optimizer static_centerline_optimizer.launch.xml run_background:=false lanelet2_input_file_path:="/home/takayukimurooka/AutonomousDrivingScenarios/map/kashiwanoha/lanelet2_map.osm" start_lanelet_id:=125 end_lanelet_id:=132 vehicle_model:=lexus

## Related links
https://github.com/autowarefoundation/autoware.universe/issues/1942

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
mission_planner's change is the same as https://github.com/autowarefoundation/autoware.universe/pull/2259
After https://github.com/autowarefoundation/autoware.universe/pull/2259 is merged, remove mission_planner's change from this PR, and merge this PR.

**Comment by TakaHoribe** [comment]
It worked perfectly. Please let me know after CI issue is fixed.
image

**Comment by takayuki5168** [comment]
@TakaHoribe 
Thanks to the massive help from @kenji-miyake-san, all the required CI passed finally.
Give me LGTM!

**Review by TakaHoribe — APPROVED** [review]
LGTM. Great work!

**Pull request merged**
