### PR TITLE
refactor(obstacle_stop_planner): rework parameters

### PR DESCRIPTION
**Pull request by Ariiees**
## Description
Implement the ROS Node configuration layout for the obstacle_stop_planner package.

## Test performed
1. Build ```colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to obstacle_cruise_planner```
2. Launch ```ros2 launch obstacle_stop_planner obstacle_stop_planner.launch.xml```

## Notes for reviewers
None

## Interface Changes
1. Create 3 schema.json files
2. Update README.md

## Effects on system behavior
None

## Pre-review checklist for the PR author
The PR author must check the checkboxes below when creating the PR.
- [x] I've confirmed  the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/)
- [x] The PR follows the [pull request guidelines](https://github.com/autowarefoundation/autoware.universe/pull/7204) 

## In-review checklist for the PR reviewers
The PR reviewers must check the checkboxes below before approval.
- [ ] The PR follows the [pull request guidelines](https://github.com/autowarefoundation/autoware.universe/pull/7204)
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author
The PR author must check the checkboxes below before merging.
- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.
After all checkboxes are checked, anyone who has write access can merge the PR.

### CODE REVIEW

**Comment by mitsudome-r** [comment]
@Ariiees Thanks for the PR. 

However, the PR seems to be failing in the CI for DCO check. When you push commits, could you push with signed-off commits?

For example by running the following command:
`git rebase -i --signoff origin/main`

**Comment by Ariiees** [comment]
> @Ariiees Thanks for the PR.
> 
> However, the PR seems to be failing in the CI for DCO check. When you push commits, could you push with signed-off commits?
> 
> For example by running the following command: `git rebase -i --signoff origin/main`

Sure! Thank you for your suggestion. I've really rebase and sign it on the latest branch

**Comment by mitsudome-r** [comment]
@Ariiees Could you tell me why you closed this PR?

**Comment by mitsudome-r** [comment]
Never mind, I noticed that you recreated the PR: https://github.com/autowarefoundation/autoware.universe/pull/7795

**Pull request closed without merging**
