### PR TITLE
feat(behavior_velocity_planner): add instrument type and id to virtua…

### PR DESCRIPTION
**Pull request by kosuke55**
## Related Issue(required)

https://github.com/autowarefoundation/autoware.universe/issues/244

## Description(required)
Related to https://github.com/autowarefoundation/autoware.universe/pull/306#discussion_r794243955, I added  `instrument_type` and `instrument_id` to the logger.
In the original PR, I added them to all `RCLCPP_DEBUG`, but in this PR, I added them to the logger.

without this PR
```
[component_container_mt-13] [DEBUG 1643694653.855303949] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module]: before start_line
[component_container_mt-13] [DEBUG 1643694653.855405680] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module]: no message received
```

with this PR
```
[component_container_mt-13] [DEBUG 1643692913.909882010] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module.intersection_coordination_585]: no message received
[component_container_mt-13] [DEBUG 1643692913.909964927] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module.intersection_coordination_605]: before start_line
```

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
> example of output

@kosuke55 Could you show me the current output to compare to this PR?

**Comment by kosuke55** [comment]
@kenji-miyake 
Do you mean the current is autoware.universe tier4/proposal or autwoware.iv with https://github.com/tier4/autoware.iv/pull/2413?

**Comment by kenji-miyake** [comment]
It's `autoware.universe@tier4/proposal`.

**Comment by kosuke55** [comment]
@kenji-miyake 
OK, the current output is like bellow
```
[component_container_mt-13] [DEBUG 1643694653.855303949] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module]: before start_line
[component_container_mt-13] [DEBUG 1643694653.855405680] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module]: no message received
```

**Review by kenji-miyake — APPROVED** [review]
Cool!

**Pull request merged**
