### PR TITLE
feat(behavior_velocity_planner): changeable maximum stop distance

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

Now, this ego always try to stop at the stop position by re-starting (re-approach) even if the ego is stopped near the planned stop position in the module. On the other hand, if the stopping performance of the vehicle is poor (e.g. it cannot stop for one meter) and once it starts traveling, there is a possibility that the vehicle may over the stop position, in which case there may be a issue for the vehicle to continue stopping on the spot, if the distance between the ego and stop position is closer than threshold.

So, in this PR, I fixed following points.

- add new param `hold_stop_margin_distance` (default: 0.0 [m])
- if the following condisions are satisfied, the ego keep stopping at current position.

condition 1. the ego has stopped
condition 2. the distance between  the ego and stop point is shorter than `hold_stop_margin_distance`

test perform (`hold_stop_margin_distance` = 1.0 [m])

1. the ego has been stopped by obstacle on lane
2. there is another obstacle in detection area
3. remove obstacle on lane
4. check whether the ego don't move to approach detection area virtual wall

https://user-images.githubusercontent.com/44889564/179914995-270f6509-9aa9-403c-b889-2d2b083fee54.mp4

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by taikitanaka3** [comment]
[Q]
I think stop line position can be controlled by stop_margin what cases do you want to add max stop distance too?

**Comment by satoshi-ota** [comment]
> [Q] I think stop line position can be controlled by stop_margin what cases do you want to add max stop distance too?

@taikitanaka3 `max_stop_distance` is **NOT** parameter for distance of stop point such as `stop_margin` but parameter for torelance of stop position. If the ego stops within `max_stop_distance`, the ego keep stopping at current position. This is what I want to do.

**Comment by satoshi-ota** [comment]
@TakaHoribe I confirmed that there is no critical degradation in this PR by evaluator.

This PR: https://evaluation.tier4.jp/evaluation/reports/4da698d3-83e4-577a-b8ad-d902669cf139?project_id=prd_jt
Baseline: https://evaluation.tier4.jp/evaluation/reports/822bf00c-c113-57ea-b82a-aef251801a4d?project_id=prd_jt

**Comment by TakaHoribe** [comment]
LGTM
image

**Review by TakaHoribe — APPROVED** [review]

**Comment by satoshi-ota** [comment]
@satoshi-ota TODO: update README in another PR

**Comment by satoshi-ota** [comment]
double check
image

**Pull request merged**
