### PR TITLE
chore(tier4_perception_launch): fix typo

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

fix typo of tier4_perception_launch

## Tests performed

spell check

## Effects on system behavior

Nothing

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/4429
It overlaps with this one.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by knzo25** [comment]
@takayuki5168 
Sorry, did not see this PR
:bow:

**Comment by takayuki5168** [comment]
@knzo25 Sorry about that. Then I will merge mine.

**Pull request merged**
