### PR TITLE
fix(pointcloud_preprocessor): separate targets for base class

### LINKED ISSUE #1009: Sometimes the sensing module doesn't publish concatenated pointcloud
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

sometimes the sensing module cannot launch concatenated and cropbox filter with the following error
```
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'concatenate_data' of type 'pointcloud_preprocessor::PointCloudConcatenateDataSynchronizerComponent' in container 'pointcloud_container': Failed to find class with the requested plugin name.
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'crop_box_filter' of type 'pointcloud_preprocessor::CropBoxFilterComponent' in container 'pointcloud_container': Failed to find class with the requested plugin name.
```

### Expected behavior

launch concatenated and cropbox filter without error

### Actual behavior

launch concatenated and cropbox filter without error

### Steps to reproduce

play rosbag replay simulator in tutorials

### Versions

_No response_

### Possible causes

_No response_

### Additional context

_No response_

### Temporary fix

- [ ] #1797

### PR DESCRIPTION
**Pull request by wep21**
## Description

closes #1009 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by wep21** [comment]
@lchojnack Could you try this PR for #1009? I can also reproduce the error with following commands.
```
ros2 run rclcpp_components component_container_mt
ros2 component load /ComponentManager compare_map_segmentation compare_map_segmentation::CompareElevationMapFilterComponent
ros2 component load /ComponentManager pointcloud_preprocessor pointcloud_preprocessor::VoxelGridOutlierFilterComponent
```

**Comment by lhakim85** [comment]
> @lchojnack Could you try this PR for #1009? I can also reproduce the error with following commands.

I try this PR but get this error
image
 
Any idea @wep21

**Comment by lhakim85** [comment]
@mitsudome-r here the detail
Setup A                                               
Ubuntu 20.04.5                              
gcc 9.4.0
Intel i7-8700
GPU RTX 3060
Source installation
Amd64

Setup B
Ubuntu 20.04.5                              
gcc 9.4.0
Intel i9-10900k
GPU RTX 2070
Source installation
Amd64

Both setup fail to compile with same error

**Review by shmpwk — APPROVED** [review]
It works for me.

Ubuntu20.04
11th Gen Intel® Core™ i7-11800H
GPU RTX 2520
gcc 9.4.0

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
