### PR TITLE
feat(tensorrt_yolo): remove package

### PR DESCRIPTION
**Pull request by kminoda**
## Description

Part of:
- https://github.com/autowarefoundation/autoware/issues/4165

See:
- https://github.com/orgs/autowarefoundation/discussions/4136

- https://github.com/autowarefoundation/autoware/pull/4160
should be merged after this PR

## Tests performed

Not applicable

## Effects on system behavior

Not applicable

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — COMMENTED** [review]
Could you update https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml#L40 as well?

**Comment by kminoda** [comment]
@miursh I see. How about this? https://github.com/autowarefoundation/autoware.universe/pull/6361/commits/364ca275c77ae53325552589f99866db64d118bf

Also removed the arguments for the launch file since it seemed outdated. Let me know if it's better to leave it as it is.

**Comment by miursh** [comment]
@kminoda I changed as https://github.com/autowarefoundation/autoware.universe/pull/6361/commits/e977f13b22f14343f74b6deadd19ab47f83cc5cd. Is this ok?

**Comment by kminoda** [comment]
@miursh Yes, thanks.

**Pull request merged**
