### PR TITLE
feat: use `pose_source` and `twist_source` for selecting localization methods

### PR DESCRIPTION
**Pull request by kminoda**
THIS PR SHOULD BE MERGED AFTER A CERTAIN DISCUSSION IN https://github.com/orgs/autowarefoundation/discussions/3659 

## Description
Change localization_launch architecture so that we can select localization methods with 
- `pose_source`: `ndt`, `yabloc`, or `eagleye`
- `twist_source`: `gyro_odom`, or `eagleye`

You can specify these now like as follow:
```bash
$ ros2 launch autoware_launch autoware.launch.xml ... pose_source:=yabloc twist_source:=gyro_odom ...
```

NOTE: This PR does NOT (and must not) change the performance of any localization mode. 

## Related links
- https://github.com/autowarefoundation/autoware_launch/pull/442
- https://github.com/autowarefoundation/autoware-documentation/pull/418

INTERNAL LINK: https://star4.slack.com/archives/CEL0DR2S2/p1688988460478459
## Tests performed

- For logging simulator:
  - Run with default launch command to verify that it works
  - Run with `pose_source:=yabloc` with yabloc sample rosbag
  - Run with `pose_source:=ndt_scan_matcher twist_source:=eagleye` to confirm that eagleye with twist_estimator mode works
  - Run with `pose_source:=eagleye twist_source:=eagleye` to confirm that eagleye with pose_twist_estimator mode works
- For planning simulator:
  - Run simple planning simulator and confirmed that it engages and starts driving
  - Run scenario based planning simulation based on [a tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/scenario-simulation/planning-simulation/scenario-test-simulation/) and confirmed that the vehicle engages and starts driving

## Notes for reviewers

Some large modifications have been made in this PR, including:

- localization_launch directory structure
  - `pose_estimator` and `twist_estimator` has been merged into `pose_twist_estimator`
  - `map4_localization_launch` has been removed
- YabLoc
  - Namespace has been modified (`/localization/yabloc/...` to `/localization/pose_estimator/...`)

For testing this PR, please use the following dataset:
- NDT: any data with LiDAR is OK (e.g. sample-map-rosbag)
- YabLoc: please find the YabLoc sample dataset [in this link](https://github.com/autowarefoundation/autoware.universe/pull/3946)
- Eagleye: Sample data is NOT sufficient, so please use some arbitrary longer data, e.g. from JPN TAXI (eagleye takes a lot of time for initialization)

## Interface changes
- Some of the YabLoc internal topic names are modified, but should not have any effect to other packages (No influence when using other pose estimator such as `ndt_scan_matcher`)

## Effects on system behavior
None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by KYabuuchi** [comment]
For other reviewers, you can find the YabLoc sample dataset [in this link](https://github.com/autowarefoundation/autoware.universe/pull/3946#:~:text=autowarefoundation/discussions/3484-,Tests%20performed,-I%20confirmed%20that) :camera_flash:

**Comment by KYabuuchi** [comment]
I have tested all combinations using logging_simulator.launch.xml.
I found some problems.
( I just checked the behavior and have not seen the code yet. I will let you know if I find those causes. :runner: )

|  twist\pose  |  ndt  | yabloc | eagleye | INVALID ARG|
| ---- | ---- | ---- | ---- | ---- |
|  **gyro_odom**  |  :ok:  | :ok:  | :warning:    | *1|
|  **eagleye**  |  :ok:  | :ok:  | :warning:  | *1 |
| **INVALID ARG** | *2 | *2 | *2 | *3|

*1, *2 and *3 indicates that `pose_estimator`, `twist_estimator`, and both of them are not launched, respectively. It looks good to me.

## Issue 1
When `pose_source:=eagleye`, Perhaps the GNSS topic that `pose_initializer` is subscribe to has not been properly modified.  Therefore, the localization state is transitioning to INITIALIZED before eagleye is initialized.

## Issue 2
When `pose_source:=eagleye twist_source:=gyro_odom`, multiple twist_estimator publishes `/localization/twist_estimator/twist_with_covariance`. Is this expected behavior?

**Comment by kminoda** [comment]
@KYabuuchi Thank you for the comprehensive evaluation! Both points are now fixed: in https://github.com/autowarefoundation/autoware.universe/pull/4257/commits/d289f039c2143dfeba653539fcadec9834a92ce3 and https://github.com/autowarefoundation/autoware.universe/pull/4257/commits/b0da34a0e4783cb060c9f27e47e8ec60cc55154c.

**Comment by KYabuuchi** [comment]
I have confirmed that all estimator combinations work correctly in my environment too. :tada:

Next, I will review the code in more detail. Please wait a bit more.

**Review by KYabuuchi — CHANGES_REQUESTED** [review]
Please update  `launch/tier4_localization_launch/README.md`, too

**Comment by KYabuuchi** [comment]
Please add the following packages, which were written in `map4_localization_launch`, to the `package.xml` in `tier4_localization_launch`.   :pray:
```
  <exec_depend>eagleye_fix2pose</exec_depend>
  <exec_depend>eagleye_gnss_converter</exec_depend>
  <exec_depend>eagleye_rt</exec_depend>
 ```

**Review by KYabuuchi — APPROVED** [review]
LGTM

**Review by KYabuuchi — COMMENTED** [review]
Sorry, I noticed after LGTM. :bow:
The instructions on *how to launch yabloc* in the [`/localization/yabloc/README.md`](https://github.com/autowarefoundation/autoware.universe/blob/dc29d01f0e1320e65d93af9d91d76b2b6fa8c36b/localization/yabloc/README.md) is outdated. Could you update it?

**Comment by kminoda** [comment]
@KYabuuchi Thank you! Fixed (and confirmed that `localization_mode` does not exist in Autoware workspace)

**Review by isamu-takagi — APPROVED** [review]
LGTM for pose_initializer

**Pull request merged**
