### PR TITLE
feat(lidar_centerpoint): remove files those are no longer supported nor used

### PR DESCRIPTION
**Pull request by kminoda**
## Description
Remove unused files that are no longer supported
https://github.com/autowarefoundation/autoware/issues/4165

## Tests performed

Confirmed that build for the package succeeds and Autoware logging_simulator works fine with successful perception output.

## Effects on system behavior
None

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
@knzo25 Ping

**Comment by knzo25** [comment]
@kminoda 
I think 
https://github.com/autowarefoundation/autoware.universe/blob/main/perception/lidar_centerpoint/include/lidar_centerpoint/single_inference_node.hpp
is missing

**Review by knzo25 — CHANGES_REQUESTED** [review]
Thanks for handling the issue.
There was only a header file I think should also be deleted.

By the way, the guys that did the TVM implementation copied the inference node and the visualization script. Is that in the scope of things that should be deleted?
https://github.com/autowarefoundation/autoware.universe/tree/main/perception/lidar_centerpoint_tvm

(I can send the PR later)

**Comment by kminoda** [comment]
@knzo25 Thanks. Fixed: https://github.com/autowarefoundation/autoware.universe/pull/6497/commits/e856ec230b9f2155d63ccc515ead9d3a64d09dd6

For lidar_centerpoint_tvm, I don't think we need to deal with it at this moment, given that we as TIER IV don't have motivation to do so.

**Review by knzo25 — APPROVED** [review]
LGTM

**Pull request merged**
