### PR TITLE
chore(ci): add a workflow for DCO check to avoid DCO bot system failure

### PR DESCRIPTION
**Pull request by HansRobo**
Signed-off-by: Kotaro Yoshimoto pythagora.yoshimoto@gmail.com

## Description

DCO check is not working now.
image

https://github.com/dcoapp/app/issues/211

Alternatively, I added this workflow as proposed in the issue.

## Tests performed

Well done!
https://github.com/autowarefoundation/autoware.universe/actions/runs/9377200258/job/25818372246

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by HansRobo** [comment]
Additional TODOs for maintainers
- Remove conventional DCO check from required CIs
- Add new workflow to required CIs

**Review by xmfcx — APPROVED** [review]
Thanks Robo-san, I will add it 👍

**Comment by xmfcx** [comment]
image
@HansRobo ✅

**Comment by xmfcx** [comment]
Had to make it "dco"
image

Now it works.

**Pull request merged**
