### PR TITLE
refactor(tensorrt_yolox)!: fix namespace and directory structure

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

This PR puts headers in the `autoware` namespace.

Additional works:
1. Align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables)
2. [Clean unused dependencies](https://github.com/autowarefoundation/autoware/issues/3468)   [LIST](https://github.com/autowarefoundation/autoware.universe/pull/3606)

## Related links

**Parent Issue:**

- Part of: https://github.com/autowarefoundation/autoware/issues/4569

## How was this PR tested?

I tested with the following launchers:

1. `ros2 launch autoware_tensorrt_yolox yolox.launch.xml`
2. `ros2 launch autoware_tensorrt_yolox yolox_tiny.launch.xml`

## Notes for reviewers

This PR effects to the other repositories as follows:

- https://github.com/tier4/jetson_launcher/pull/39
- https://github.com/tier4/edge_auto_jetson_launch/pull/13

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by ktro2828** [comment]
@badai-nguyen I updated `yolox_tiny.param.yaml` by https://github.com/autowarefoundation/autoware.universe/pull/7992/commits/f07dad9725cd63048c63020c2d382d37945a2b8d because it raises error when I launched `yolox_tiny.launch.xml`. Could you check this whether it is OK?

**Comment by badai-nguyen** [comment]
> @badai-nguyen I updated `yolox_tiny.param.yaml` by [f07dad9](https://github.com/autowarefoundation/autoware.universe/commit/f07dad9725cd63048c63020c2d382d37945a2b8d) because it raises error when I launched `yolox_tiny.launch.xml`. Could you check this whether it is OK?

@ktro2828 Thank you for your fixing. 
I confirmed this update fixed the issue and yolox_tiny is successfull to execute
```
autoware@npc2201009-ubuntu22:~/autoware$ ros2 launch tensorrt_yolox yolox_tiny.launch.xml 
[INFO] [launch]: All log files can be found below /home/autoware/.ros/log/2024-07-22-20-07-01-530387-npc2201009-ubuntu22-92237
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tensorrt_yolox_node_exe-1]: process started with pid [92239]
[tensorrt_yolox_node_exe-1] failed to open 
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init CUDA: CPU +563, GPU +0, now: CPU 591, GPU 264 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 610, GPU 264 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +434, GPU +102, now: CPU 1044, GPU 366 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] ----------------------------------------------------------------
[tensorrt_yolox_node_exe-1] [I] [TRT] Input filename:   /home/autoware/autoware_data/tensorrt_yolox/yolox-tiny.onnx
[tensorrt_yolox_node_exe-1] [I] [TRT] ONNX IR version:  0.0.8
[tensorrt_yolox_node_exe-1] [I] [TRT] Opset version:    11
[tensorrt_yolox_node_exe-1] [I] [TRT] Producer name:    pytorch
[tensorrt_yolox_node_exe-1] [I] [TRT] Producer version: 1.12.0
[tensorrt_yolox_node_exe-1] [I] [TRT] Domain:           
[tensorrt_yolox_node_exe-1] [I] [TRT] Model version:    0
[tensorrt_yolox_node_exe-1] [I] [TRT] Doc string:       
[tensorrt_yolox_node_exe-1] [I] [TRT] ----------------------------------------------------------------
[tensorrt_yolox_node_exe-1] [W] [TRT] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[tensorrt_yolox_node_exe-1] [W] [TRT] onnx2trt_utils.cpp:395: One or more weights outside the range of INT32 was clamped
[tensorrt_yolox_node_exe-1] [I] [TRT] No importer registered for op: EfficientNMS_TRT. Attempting to import as plugin.
[tensorrt_yolox_node_exe-1] [I] [TRT] Searching for plugin: EfficientNMS_TRT, plugin_version: 1, plugin_namespace: 
[tensorrt_yolox_node_exe-1] [I] [TRT] Successfully created plugin: EfficientNMS_TRT
[tensorrt_yolox_node_exe-1] L9 [conv 3x3 (1) /1] 480x304x12 -> 480x304x24 weights:2592 GFLOPs:0.756449
[tensorrt_yolox_node_exe-1] L12 [conv 3x3 (1) /2] 480x304x24 -> 240x152x48 weights:10368 GFLOPs:0.756449
[tensorrt_yolox_node_exe-1] L15 [conv 1x1 (1) /1] 240x152x48 -> 240x152x24 weights:1152 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L16 [conv 1x1 (1) /1] 240x152x48 -> 240x152x24 weights:1152 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L21 [conv 1x1 (1) /1] 240x152x24 -> 240x152x24 weights:576 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L24 [conv 3x3 (1) /1] 240x152x24 -> 240x152x24 weights:5184 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L29 [conv 1x1 (1) /1] 240x152x48 -> 240x152x48 weights:2304 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L32 [conv 3x3 (1) /2] 240x152x48 -> 120x76x96 weights:41472 GFLOPs:0.756449
[tensorrt_yolox_node_exe-1] L35 [conv 1x1 (1) /1] 120x76x96 -> 120x76x48 weights:4608 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L36 [conv 1x1 (1) /1] 120x76x96 -> 120x76x48 weights:4608 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L41 [conv 1x1 (1) /1] 120x76x48 -> 120x76x48 weights:2304 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L44 [conv 3x3 (1) /1] 120x76x48 -> 120x76x48 weights:20736 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L48 [conv 1x1 (1) /1] 120x76x48 -> 120x76x48 weights:2304 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L51 [conv 3x3 (1) /1] 120x76x48 -> 120x76x48 weights:20736 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L55 [conv 1x1 (1) /1] 120x76x48 -> 120x76x48 weights:2304 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L58 [conv 3x3 (1) /1] 120x76x48 -> 120x76x48 weights:20736 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L63 [conv 1x1 (1) /1] 120x76x96 -> 120x76x96 weights:9216 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L66 [conv 3x3 (1) /2] 120x76x96 -> 60x38x192 weights:165888 GFLOPs:0.756449
[tensorrt_yolox_node_exe-1] L69 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L70 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L75 [conv 1x1 (1) /1] 60x38x96 -> 60x38x96 weights:9216 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L78 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L82 [conv 1x1 (1) /1] 60x38x96 -> 60x38x96 weights:9216 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L85 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L89 [conv 1x1 (1) /1] 60x38x96 -> 60x38x96 weights:9216 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L92 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L97 [conv 1x1 (1) /1] 60x38x192 -> 60x38x192 weights:36864 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L100 [conv 3x3 (1) /2] 60x38x192 -> 30x19x384 weights:663552 GFLOPs:0.756449
[tensorrt_yolox_node_exe-1] L103 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L106 [max pool 5x5] GFLOPs:0.002736
[tensorrt_yolox_node_exe-1] L107 [max pool 9x9] GFLOPs:0.00886464
[tensorrt_yolox_node_exe-1] L108 [max pool 13x13] GFLOPs:0.0184954
[tensorrt_yolox_node_exe-1] L110 [conv 1x1 (1) /1] 30x19x768 -> 30x19x384 weights:294912 GFLOPs:0.3362
[tensorrt_yolox_node_exe-1] L113 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L114 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L119 [conv 1x1 (1) /1] 30x19x192 -> 30x19x192 weights:36864 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L122 [conv 3x3 (1) /1] 30x19x192 -> 30x19x192 weights:331776 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L126 [conv 1x1 (1) /1] 30x19x384 -> 30x19x384 weights:147456 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L129 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L132 [resize]
[tensorrt_yolox_node_exe-1] L134 [conv 1x1 (1) /1] 60x38x384 -> 60x38x96 weights:36864 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L135 [conv 1x1 (1) /1] 60x38x384 -> 60x38x96 weights:36864 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L140 [conv 1x1 (1) /1] 60x38x96 -> 60x38x96 weights:9216 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L143 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L147 [conv 1x1 (1) /1] 60x38x192 -> 60x38x192 weights:36864 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L150 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L153 [resize]
[tensorrt_yolox_node_exe-1] L155 [conv 1x1 (1) /1] 120x76x192 -> 120x76x48 weights:9216 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L156 [conv 1x1 (1) /1] 120x76x192 -> 120x76x48 weights:9216 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L161 [conv 1x1 (1) /1] 120x76x48 -> 120x76x48 weights:2304 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L164 [conv 3x3 (1) /1] 120x76x48 -> 120x76x48 weights:20736 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L168 [conv 1x1 (1) /1] 120x76x96 -> 120x76x96 weights:9216 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L171 [conv 3x3 (1) /2] 120x76x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L172 [conv 1x1 (1) /1] 120x76x96 -> 120x76x96 weights:9216 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L178 [conv 3x3 (1) /1] 120x76x96 -> 120x76x96 weights:82944 GFLOPs:1.5129
[tensorrt_yolox_node_exe-1] L179 [conv 3x3 (1) /1] 120x76x96 -> 120x76x96 weights:82944 GFLOPs:1.5129
[tensorrt_yolox_node_exe-1] L180 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L181 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L190 [conv 3x3 (1) /1] 120x76x96 -> 120x76x96 weights:82944 GFLOPs:1.5129
[tensorrt_yolox_node_exe-1] L191 [conv 3x3 (1) /1] 120x76x96 -> 120x76x96 weights:82944 GFLOPs:1.5129
[tensorrt_yolox_node_exe-1] L192 [conv 1x1 (1) /1] 60x38x96 -> 60x38x96 weights:9216 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L199 [conv 1x1 (1) /1] 120x76x96 -> 120x76x8 weights:768 GFLOPs:0.0140083
[tensorrt_yolox_node_exe-1] L200 [conv 1x1 (1) /1] 120x76x96 -> 120x76x4 weights:384 GFLOPs:0.00700416
[tensorrt_yolox_node_exe-1] L201 [conv 1x1 (1) /1] 120x76x96 -> 120x76x1 weights:96 GFLOPs:0.00175104
[tensorrt_yolox_node_exe-1] L202 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L210 [conv 1x1 (1) /1] 60x38x192 -> 60x38x192 weights:36864 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L213 [conv 3x3 (1) /2] 60x38x192 -> 30x19x192 weights:331776 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L214 [conv 1x1 (1) /1] 60x38x192 -> 60x38x96 weights:18432 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L220 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L221 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L222 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L223 [conv 1x1 (1) /1] 30x19x384 -> 30x19x192 weights:73728 GFLOPs:0.0840499
[tensorrt_yolox_node_exe-1] L232 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L233 [conv 3x3 (1) /1] 60x38x96 -> 60x38x96 weights:82944 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L234 [conv 1x1 (1) /1] 30x19x192 -> 30x19x192 weights:36864 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L241 [conv 1x1 (1) /1] 60x38x96 -> 60x38x8 weights:768 GFLOPs:0.00350208
[tensorrt_yolox_node_exe-1] L242 [conv 1x1 (1) /1] 60x38x96 -> 60x38x4 weights:384 GFLOPs:0.00175104
[tensorrt_yolox_node_exe-1] L243 [conv 1x1 (1) /1] 60x38x96 -> 60x38x1 weights:96 GFLOPs:0.00043776
[tensorrt_yolox_node_exe-1] L244 [conv 3x3 (1) /1] 30x19x192 -> 30x19x192 weights:331776 GFLOPs:0.378225
[tensorrt_yolox_node_exe-1] L252 [conv 1x1 (1) /1] 30x19x384 -> 30x19x384 weights:147456 GFLOPs:0.1681
[tensorrt_yolox_node_exe-1] L255 [conv 1x1 (1) /1] 30x19x384 -> 30x19x96 weights:36864 GFLOPs:0.042025
[tensorrt_yolox_node_exe-1] L258 [conv 3x3 (1) /1] 30x19x96 -> 30x19x96 weights:82944 GFLOPs:0.0945562
[tensorrt_yolox_node_exe-1] L259 [conv 3x3 (1) /1] 30x19x96 -> 30x19x96 weights:82944 GFLOPs:0.0945562
[tensorrt_yolox_node_exe-1] L264 [conv 3x3 (1) /1] 30x19x96 -> 30x19x96 weights:82944 GFLOPs:0.0945562
[tensorrt_yolox_node_exe-1] L265 [conv 3x3 (1) /1] 30x19x96 -> 30x19x96 weights:82944 GFLOPs:0.0945562
[tensorrt_yolox_node_exe-1] L270 [conv 1x1 (1) /1] 30x19x96 -> 30x19x8 weights:768 GFLOPs:0.00087552
[tensorrt_yolox_node_exe-1] L271 [conv 1x1 (1) /1] 30x19x96 -> 30x19x4 weights:384 GFLOPs:0.00043776
[tensorrt_yolox_node_exe-1] L272 [conv 1x1 (1) /1] 30x19x96 -> 30x19x1 weights:96 GFLOPs:0.00010944
[tensorrt_yolox_node_exe-1] Total 21.4927 GFLOPs
[tensorrt_yolox_node_exe-1] Total 5.01754 M params
[tensorrt_yolox_node_exe-1] Loading... "/home/autoware/autoware_data/tensorrt_yolox/yolox-tiny.fp16-batch1.engine"
[tensorrt_yolox_node_exe-1] [I] [TRT] Loaded engine size: 12 MiB
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1325, GPU +346, now: CPU 1980, GPU 622 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +258, GPU +60, now: CPU 2238, GPU 682 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +10, now: CPU 0, GPU 10 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 2210, GPU 674 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 2210, GPU 682 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +17, now: CPU 0, GPU 27 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 2211, GPU 698 (MiB)
[tensorrt_yolox_node_exe-1] [I] [TRT] The profiling verbosity was set to ProfilingVerbosity::kLAYER_NAMES_ONLY when the engine was built, so only the layer names will be returned. Rebuild the engine with ProfilingVerbosity::kDETAILED to get more verbose layer information.

```

**Review by MasatoSaeki — APPROVED** [review]
I ran object detection and traffic light recognition to make sure the output is correct in local env.

**Review by manato — APPROVED** [review]
@ktro2828 @badai-nguyen @MasatoSaeki 
I highly appreciate your help with this fixing. LGTM!

**Comment by ktro2828** [comment]
@Shin-kyoto @miursh @tzhong518 Could you review this? (I need at least 1 approve from the maintainer of `autoware_traffic_light_fine_detector`.)

**Review by miursh — APPROVED** [review]

**Pull request merged**
