### PR TITLE
feat(ndt_scan_matcher): add nearest voxel transfromation probability

### PR DESCRIPTION
**Pull request by YamatoAndo**
**Please merge ~https://github.com/tier4/ndt_omp/pull/10~ (merged) and https://github.com/tier4/ndt_omp/pull/13 before this PR. Otherwise, the build and test will not pass.**

## Description(required)
Add new score to determine convergence "nearest voxel transformation probability".
（If converged_param_type is set to 0, we can use "transfomation probability" as before.）

### Background
In ndt_scan_matcher, the success or failure of convergence is determined by the Transformation Probability (TP).
However, there are some factors that cause the TP to fluctuate regardless of the convergence result, as shown in the following example, which often leads to misjudgment.
- The TP depends on the completeness of the map point cloud. The TP will be low when the map point cloud is inadequate, for example, buildings that should exist are not in the map point cloud.
- The TP depends on the distance of the sensor point cloud. When the distance is increased, the influence on the completeness of the map point cloud becomes stronger, and the TP tends to become low.

Therefore, I propose a new score that has less of this dependency.

### Evaluation results
Graphing each score when offset from the correct position using rosbag in urban areas.

#### Transformation Probability
Screenshot from 2022-03-09 16-49-08

#### Nearest Voxel Transformation Probability
Screenshot from 2022-03-09 16-53-44

#### Consideration
The TP is highly variable, so it is not appropriate to use it to determine convergence.
The NVTP has a more stable value than TP, so we should use the NVTP instead of the TP.

## Review Procedure(required)
Build with https://github.com/tier4/autoware_launch/pull/198, ~https://github.com/tier4/ndt_omp/pull/10~ and https://github.com/tier4/ndt_omp/pull/13.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the [guidelines][clang-tidy-guidelines].
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]

**Review by RyuYamamoto — APPROVED** [review]
LGTM

**Comment by wep21** [comment]
@YamatoAndo Could you check the ci failure? https://github.com/autowarefoundation/autoware.universe/runs/5616843445?check_suite_focus=true

**Comment by YamatoAndo** [comment]
@wep21 
Yes. As mentioned at the beginning of the PR, the ci test cannot pass without this PR (https://github.com/tier4/ndt_omp/pull/10).

**Comment by wep21** [comment]
@YamatoAndo I'm sorry, I missed it. I merged https://github.com/tier4/ndt_omp/pull/10 and rerun the ci.

**Comment by YamatoAndo** [comment]
@RyuYamamoto please review again with https://github.com/tier4/ndt_omp/pull/13 and https://github.com/tier4/autoware_launch/pull/198.

**Review by RyuYamamoto — APPROVED** [review]
LGTM

**Pull request merged**
