### PR TITLE
feat(shift_decider): add config file

### PR DESCRIPTION
**Pull request by lilyildiz**
## Description

Solves the issue in @takayuki5168 's comment on https://github.com/autowarefoundation/autoware.universe/pull/1818 (https://github.com/autowarefoundation/autoware.universe/pull/1818#issuecomment-1245218790)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@lilyildiz Great. I really appreciate your PR.

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
@TakaHoribe Please check the PR.

**Review by TakaHoribe — APPROVED** [review]
@lilyildiz thank you!

**Pull request merged**
