### PR TITLE
chore(glog): add initialization check

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

Add `IsGoogleLoggingInitialized()` check before glog initialization as the multiple initializations terminate the process.

## Related links

Must be merged after
- https://github.com/autowarefoundation/autoware/pull/4614
- https://github.com/autowarefoundation/autoware.universe/pull/6952

## Tests performed

- Build 
- Run psim
- Confirm the glog works correctly as before
    - `kill -15 <pid>` should show the stack trace for the glog-installed process, e.g. `map_based_prediction`
image

## Notes for reviewers

None

## Interface changes

None

## Effects on system behavior

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
@TakaHoribe we used https://github.com/bombela/backward-cpp before for similar purposes and it was really good at printing the causes of segfaults.

Maybe you can try it too.

**Comment by xmfcx** [comment]
Also you need to add
```
  universe/external/glog:  # TODO(Horibe): to use isGoogleInitialized() API in v0.6.0. Remove when the rosdep glog version is updated to v0.6.0 (already updated in Ubuntu 24.04)
    type: git
    url: https://github.com/tier4/glog.git
    version: v0.6.0_t4-ros
```

to
- https://github.com/autowarefoundation/autoware.universe/blob/main/build_depends.repos

**Comment by xmfcx** [comment]
It seems they made a ROS 2 package for it too: https://github.com/pal-robotics/backward_ros

**Comment by xmfcx** [comment]
I will test backward-cpp and open up a separate PR.

**Review by KYabuuchi — APPROVED** [review]
LGTM for the localization packages :smiley:  
* `pose_estimator_arbiter`
* `yabloc_common`
* `yabloc_particle_filter`
* `ndt_scan_matcher`

**Comment by TakaHoribe** [comment]
@xmfcx Thank you for the investigation of backward-cpp. Let me merge this PR first. The backward-cpp looks much better than glog, but it still has an issue with ros-component. If the issue is loved, I want to replace all glog with backward-cpp.

**Review by xmfcx — APPROVED** [review]
Of course, I agree.

**Comment by xmfcx** [comment]
@TakaHoribe could you rebase to latest main? The CI is failing.

**Comment by xmfcx** [comment]
From above: https://github.com/autowarefoundation/autoware.universe/pull/6792#issuecomment-2049937168

> Also you need to add
> 
> ```
>   universe/external/glog:  # TODO(Horibe): to use isGoogleInitialized() API in v0.6.0. Remove when the rosdep glog version is updated to v0.6.0 (already updated in Ubuntu 24.04)
>     type: git
>     url: https://github.com/tier4/glog.git
>     version: v0.6.0_t4-ros
> ```
> 
> to
> 
> * https://github.com/autowarefoundation/autoware.universe/blob/main/build_depends.repos

Or CI won't pass. I thought we added this before but it was here.

**Comment by xmfcx** [comment]
I could add it too but you should [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on the PR.

**Comment by TakaHoribe** [comment]
@xmfcx Thank you! I submitted it in a different PR: https://github.com/autowarefoundation/autoware.universe/pull/6952

**Comment by xmfcx** [comment]
Now needs to be rebased again 🙏

**Pull request merged**
