### PR TITLE
feat: change planning factor behavior constants

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Changed the velocity/steering factor type to string for extensibility of the module. Since it is an unreleased API, I don't think it will have a big impact, but the default_ad_api package converts it to the previous type to maintain compatibility.

## Related links

https://github.com/autowarefoundation/autoware_adapi_msgs/pull/45

## Tests performed

- Checkout https://github.com/autowarefoundation/autoware_adapi_msgs/pull/45
- Launch planning simulator
- Add VelocitySteeringFactorsPanel on rviz
- Set initialpose and goal
- Check if VelocitySteeringFactorsPanel works well

## Notes for reviewers

None

## Interface changes

https://github.com/autowarefoundation/autoware_adapi_msgs/pull/45.

## Effects on system behavior

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by satoshi-ota — APPROVED** [review]

**Review by takayuki5168 — APPROVED** [review]

**Review by maxime-clem — APPROVED** [review]

**Review by rej55 — APPROVED** [review]

**Review by kyoichi-sugahara — APPROVED** [review]

**Review by soblin — APPROVED** [review]

**Review by tkhmy — APPROVED** [review]
LGTM

**Review by yabuta — APPROVED** [review]
LGTM

**Review by shmpwk — APPROVED** [review]

**Comment by h-ohta** [comment]
After merging this PR, following line would be no longer used.
https://github.com/autowarefoundation/autoware_adapi_msgs/blob/main/autoware_adapi_v1_msgs/planning/msg/VelocityFactor.msg#L39
@isamu-takagi Do you make another PR to fix it?

**Review by taikitanaka3 — APPROVED** [review]

**Comment by h-ohta** [comment]
https://github.com/autowarefoundation/autoware.universe/assets/9547070/a1988533-945c-42fe-94d3-730ee32e5069

Confirmed:
- Velocity Factors
  - Intersection
  - Route Obstacle
  - Crosswalk 
- Steering Factors
  - Intersection

**Pull request merged**
