### PR TITLE
fix(lidar_centerpoint): updated the config file for the centerpoint tiny v2

### PR DESCRIPTION
**Pull request by knzo25**
## Description
When I uploaded the centerpoint tiny v2 I missed uploading the updated config file, which caused errors and an unnecessary bad performance.

The new file was tested in the environments in which the error arose

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by shmpwk — APPROVED** [review]
I tested this more than 3 times in logging simulator and AWSIM simulator.
Without this PR, my centerpoint tiny v2 died.
With this PR, I confirmed everything works fine!

**Comment by taikitanaka3** [comment]
@yukke42 
can you review this PR?

**Review by yukke42 — APPROVED** [review]
LGTM

**Comment by yukke42** [comment]
@shmpwk Thank you for cheking it to work.

**Comment by lexavtanke** [comment]
Hello, 
Sorry to mention, but It seem to me that there is a issue with this configuration with demo bag data in logging simulator. When I use it lidar_centerpoint can't produce bounding boxes and gives this warning:
```
[lidar_centerpoint_node-41] [WARN] [1679402682.492713175] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402682.707407694] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402682.898299740] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402683.322440747] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402683.513103993] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402683.734927234] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402683.937108600] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402684.148641184] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402684.347404019] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402684.544896785] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402684.767671966] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402684.976230420] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402685.401099385] [lidar_centerpoint]: No detected boxes.
[lidar_centerpoint_node-41] [WARN] [1679402685.630374434] [lidar_centerpoint]: No detected boxes.
```
Screenshot from 2023-03-21 21-06-05


 I've started autoware loggin simulator with:
 ```os2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-rosbag vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit planning:=false```
 
 And with this command I've started playing ros2 bag:
```ros2 bag play ~/autoware_map/sample-rosbag/sample.db3 -s sqlite3  -r 0.5 --loop```
 
 It happens on the main branch of autoware.universe. Here is the [video](https://user-images.githubusercontent.com/37497658/226616028-534703bb-119b-4dde-b4eb-56fb429a1955.webm). If I change  the config file to its previous stage it works fine and produce bounding boxes. Here is  the [video](https://user-images.githubusercontent.com/37497658/226619673-07160a14-256a-4639-bc70-80ad4609a70e.webm).

Actually centerpoint still throws this warning as you can see in the end of the video but not so frequently.

**Comment by yukke42** [comment]
@lexavtanke Thank you for the feedback. Cloud you try again after removing `install/lidar_centerpoint` and re-build?

**Comment by lexavtanke** [comment]
@yukke42 Yes, sure. It works strange, very unstable. Here is the video. 

https://user-images.githubusercontent.com/37497658/227120669-87511382-8c2e-4fcb-8ade-0bb94a31d629.mp4

**Comment by lexavtanke** [comment]
here is the video with old config file without rebuilding package.

https://user-images.githubusercontent.com/37497658/227124981-be194c34-2819-4624-9e08-80d94187f857.mp4

**Comment by yukke42** [comment]
@lexavtanke I have checked only lidar_centerpoint node and there is no issue in my environment.
Cloud you let me know your PC spec? it look like that obejcts are detected but the outputs are so delayed.
image

**Comment by yukke42** [comment]
Or it might be an issue in another package. Please give me more time to check the behavior.

**Comment by lexavtanke** [comment]
My PC spec 
image

**Comment by knzo25** [comment]
@lexavtanke 
Sorry, I was supposed to attend to this problem but have been doing some other tasks.
The model was trained used the ranges I pushed so the fact that it works better for other ranges should be a coincidence.
I will try in another environment with a clean install and get back to you

**Comment by knzo25** [comment]
@lexavtanke 
I installed autoware in a clean environment closer to yours

image

It works without any issues here.
Could you try the following command with [this](https://drive.google.com/drive/folders/1tLhkB9MkTpQQ_wrR3w94mptsRK6Ahw_b?usp=share_link) data? (the ply file is the result in my environment)

```ros2 launch lidar_centerpoint single_inference_lidar_centerpoint.launch.xml pcd_path:=test_pointcloud.pcd detections_path:=test_detections.ply```

**Pull request merged**
