### PR TITLE
feat(evalautor): rename evaluator diag topics

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

/diagnostic/* topic name is confusing because theare are /diagnostics/* topics.
and in the future, we plan to separate metrics (just calculate value) and diagnostics (compare with threshould).

 
image

## Related links

**Parent Issue:**

- Link

**Private Links:**

- https://star4.slack.com/archives/C03QW0GU6P7/p1720616595278849
- https://star4.slack.com/archives/C03QW0GU6P7/p1721702345525949?thread_ts=1721700599.221729&cid=C03QW0GU6P7

## How was this PR tested?

2024/07/23 https://evaluation.tier4.jp/evaluation/reports/fda048c3-d0c1-549c-91e6-9a7444741bb8/?project_id=prd_jt

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]
Thank you

**Comment by kosuke55** [comment]
@kyoichi-sugahara @maxime-clem 
please check as a code owner.

**Review by maxime-clem — APPROVED** [review]

**Comment by kyoichi-sugahara** [comment]
@kosuke55 
This PR's change looks good to me, but the other implementation which refers to this topic like [here](https://github.com/autowarefoundation/autoware_tools/blob/0cd9722fd3a639a0d043ca6f25473db6654a797e/evaluation/tier4_metrics_rviz_plugin/include/metrics_visualize_panel.hpp#L211-L212) also should be changed together?

And `/diagnostic/perception_online_evaluator/*` will be kept as it is? Or this is out of to topic for now?

**Review by xtk8532704 — APPROVED** [review]

**Comment by kosuke55** [comment]
@kyoichi-sugahara 
thanks! 
fixed in 
https://github.com/autowarefoundation/autoware_tools/pull/82

**Pull request merged**
