### PR TITLE
refactor(obstacle_stop_planner): update params name for readability

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Description

- update params name for readability

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by satoshi-ota** [comment]
TODO: create PR for autoware_launch

**Comment by satoshi-ota** [comment]
> TODO: create PR for autoware_launch

https://github.com/tier4/autoware_launch/pull/458

**Comment by h-ohta** [comment]
@satoshi-ota Could you fix below?
https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

**Comment by satoshi-ota** [comment]
> @satoshi-ota Could you fix below? https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/obstacle_stop_planner.param.yaml

@h-ohta Fix in https://github.com/autowarefoundation/autoware.universe/pull/1720/commits/4013048469d09f99d428083a6db3dc2f1bdab50c.

**Comment by satoshi-ota** [comment]
@h-ohta Evaluator test results:

Try 1: [782/823](https://evaluation.tier4.jp/evaluation/reports/5a7c8f31-2c53-5b1d-8b8b-87893bc0c524?project_id=prd_jt)
Try 2: [783/823](https://evaluation.tier4.jp/evaluation/reports/5f11e3ca-e025-5700-bad0-d903353cf03d?project_id=prd_jt)
Baseline 1: [785/823](https://evaluation.tier4.jp/evaluation/reports/35457d26-9a52-5398-a35f-df6b64418c3a?project_id=prd_jt)
Baseline 2: [788/823](https://evaluation.tier4.jp/evaluation/reports/a8ac1802-ec84-58f4-a536-bbfdaf2b8e9e?project_id=prd_jt)

I think there is no critical degration.

**Comment by h-ohta** [comment]
@satoshi-ota 
The `velocity_threshold_decel_complete` are `acceleration_threshold_decel_complete` are not defined in param.yaml and Is this OK?

**Comment by satoshi-ota** [comment]
> @satoshi-ota The `velocity_threshold_decel_complete` are `acceleration_threshold_decel_complete` are not defined in param.yaml. Is this OK?

@h-ohta I don't think it is necessary to add these params to the config file since they are parameters that are not frequently changed. (Additionaly, products using these parameters no longer exist.)

**Comment by h-ohta** [comment]
It is wasteful to define parameters which is rarely changed.
On the other hand, I guess all parameters should be defined in the param.yaml.
It is up to you.

LGTM to others.

**Comment by satoshi-ota** [comment]
> It is wasteful to define parameters which is rarely changed. On the other hand, I guess all parameters should be defined in the param.yaml. It is up to you.
> 
> LGTM to others.

@h-ohta OK. I'll fix and add these params.

**Comment by satoshi-ota** [comment]
@h-ohta add all params in config file.

**Comment by h-ohta** [comment]
I confimed.
https://github.com/autowarefoundation/autoware.universe/pull/1720/files#diff-cf194f76c0faede5c49f2b015508b61f6c5760233a0476e337292d8194d43590R48-R49
https://github.com/autowarefoundation/autoware.universe/pull/1720/files#diff-8644b541cf341399153ecba1cbb50a31899e02ae40f0acdf86cd07a331e402deR48-R49

**Review by h-ohta — APPROVED** [review]

**Pull request merged**
