### PR TITLE
fix(system_monitor): prevent nethogs from monitoring all networks due to high CPU load

### PR DESCRIPTION
**Pull request by ito-san**
Signed-off-by: ito-san <fumihito.ito@tier4.jp>

## Description

As reported from shuttle bus project of TIER IV, the `nethogs`, which monitors network traffic usage per process, has a bug to cause high CPU usage when there are many network connections. 
image

Currently, the main ECU which runs Autoware and `nethogs` uses all network ports(7 ports) to communicate with local network and internet, and `nethogs` monitors all network ports, so the high CPU load bug is coming up.

To workaround this, a network port to be monitored by `nethogs` should be configured because `nethogs` is used to monitor only network traffic on internet in `net_monitor` originally.

## Changes
1. Run `nethogs` with any network interface instead of all network interfaces.
1. Code refactoring to clean up complex codes.
1. Add diagnostics topic named `Network Connection` to make it easy to understand network diagnostic information.
1. The `nethogs` outputs process name but it's not enough. A command line is needed to monitor more properly, so I'm adding to get command line of process from `/proc/pid/cmdline`.
    Only process name, it's difficult to understand
    ```console
    /usr/bin/python3.7/37031/919	1.60508	6.72676
    ```
    Actually this process is run by `greengrass` v2.
    ```console
    /usr/bin/python3.7 -u /greengrass/v2/.../python/lambda_runtime.py --handler=entrypoint.lambda_handler -d/3673/919	1.54316	5.00352
   ```
## Related links

[TIER IV INTERNAL LINK TO SLACK](https://star4.slack.com/archives/CRUE57C30/p1669768994335239)

### Verify `net_monitor: Network CRC Error` reports `OK` in normal operation.
1. Run Autoware.
1. Run rqt_runtime_monitor.
    ```console
    ros2 run rqt_runtime_monitor rqt_runtime_monitor
    ```
1. Verify net_monitor: every information reports `OK`.
   1. **Network Connection**
image

   1. **Network Usage**
image

   1. **Network CRC Error**
image

   1. **IP Packet Reassembles Failed**
image

   1. **Network Traffic**
image

### Verify no warning and error messages in a normal run.

image

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.
- [x] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by ito-san** [comment]
@asana17 Sorry but many changes were made. Verified `net_monitor` works correctly with the computer used in the shuttle bus project.

**Comment by asana17** [comment]
`net_monitor` functions look to be working correctly in the tests performed. Are there any references to this change's improvement of the high CPU load problem?

**Comment by ito-san** [comment]
> @ito-san `net_monitor` functions look to be working correctly in the tests performed. Are there any references to this change's improvement of the high CPU load problem?

@asana17 
Thank you for reviewing this!
Yes, multiple connections cause high CPU usage.
Please refer to https://github.com/raboof/nethogs/issues/166 and https://github.com/raboof/nethogs/pull/223
This issue seems to be fixed in v0.8.7 release but Ubuntu 22.04 uses the older version of nethogs. [nethogs (0.8.6-3) [universe]](https://packages.ubuntu.com/jammy/nethogs).

**Review by asana17 — COMMENTED** [review]
LGTM

**Comment by ito-san** [comment]
> LGTM

Sorry, please approve this PR.

**Comment by ito-san** [comment]
> LGTM

@asana17 sorry, please approve this PR.

**Review by asana17 — APPROVED** [review]

**Pull request merged**
